[[ext:a]]
=== ext:a[] Extension for Atomic Instructions

The ext:a[] extension comprises the extlink:zalrsc[] and extlink:zaamo[] extensions,
which are defined in the following sections.

[NOTE]
====
The instructions in the ext:a[] extension can be used to provide sequentially
consistent loads and stores, but this constrains hardware reordering of memory
accesses more than necessary.

A {cpp} sequentially consistent load can be implemented as an insn:lr[] with
_aq_ set. However, the insn:lr[]/insn:sc[] eventual success guarantee may slow
down concurrent loads from the same effective address.

A sequentially consistent store can be implemented as an insn:amoswap[] that
writes the old value to `x0` and has _rl_ set. However the superfluous load may
impose ordering constraints that are unnecessary for this use case.

Specific compilation conventions may require both the _aq_ and _rl_ bits to be
set in either or both the insn:lr[] and insn:amoswap[] instructions.

The extlink:zalasr[] extension provides load-acquire and store-release
instructions without the aforementioned drawbacks.
====
