[[ext:q]]
=== ext:q[] Extension for Quad-Precision Floating-Point

This chapter describes the ext:q[] standard extension for _quad-precision_
floating-point, which adds computational instructions compliant with the IEEE
754-2008 arithmetic standard's binary128 format and operations. The ext:q[] extension
depends on the ext:d[] extension.

[#norm:Q_flen_128]#The floating-point registers are now extended to hold
either a single, double, or quad-precision floating-point value, i.e., FLEN=128.#
The NaN-boxing scheme described in <<nanboxing>> is now extended recursively to
allow a single-precision value to be NaN-boxed inside a double-precision value
which is itself NaN-boxed inside a quad-precision value.

[[norm:Q_canonical_NaN]]
(((NaN, canonical, quad-precision)))
For quad-precision floating-point, the canonical NaN corresponds to the pattern
`0x7fff8000000000000000000000000000`.

==== Quad-Precision Load and Store Instructions

[[norm:fsq_flq_op]]
New 128-bit variants of LOAD-FP and STORE-FP instructions are added,
encoded with a new value for the funct3 width field.

include::images/wavedrom/quad-ls.edn[]
[[quad-ls]]
//.Quad-precision load and store

[[norm:fsq_flq_atomic_align]]
insnlink:flq[] and insnlink:fsq[] are only guaranteed to execute atomically if the effective
address is naturally aligned and XLEN=128.

[[norm:fsq_flq_bits_maintained]]
insnlink:flq[] and insnlink:fsq[] do not modify the bits being transferred; in particular, the
payloads of non-canonical NaNs are preserved.

==== Quad-Precision Computational Instructions

The _fmt_ field of instructions in the ext:q[] extension is set to _Q_ (11),
as defined in <<tab:fpfmt>>.

[[norm:Q_computational_instrs]]
The quad-precision floating-point computational instructions are defined
analogously to their double-precision counterparts, but operate on
quad-precision operands and produce quad-precision results.

include::images/wavedrom/quad-compute.edn[]
[[quad-compute]]
//.Quad-precision computational

==== Quad-Precision Convert and Move Instructions

New floating-point-to-integer and integer-to-floating-point conversion
instructions are added. These instructions are defined analogously to
the double-precision-to-integer and integer-to-double-precision
conversion instructions.
[#norm:fcvt-w-q_fcvt-l-q_op]#insnlink:fcvt.w.q[] or insnlink:fcvt.l.q[] converts a quad-precision floating-point number to a signed 32-bit or 64-bit integer, respectively#.
[#norm:fcvt-q-w_fcvt-q-l_op]#insnlink:fcvt.q.w[] or insnlink:fcvt.q.l[] converts a 32-bit or 64-bit signed integer, respectively, into a quad-precision floating-point number#.
[#norm:fcvt-wu-q_fcvt-lu-q_fcvt-q-wu_fcvt-q-lu_op]#insnlink:fcvt.wu.q[], insnlink:fcvt.lu.q[], insnlink:fcvt.q.wu[], and insnlink:fcvt.q.lu[] variants convert to or from unsigned integer values#.
[#norm:fcvt_long_quad_rv64_only]#insnlink:fcvt.l.q[], insnlink:fcvt.lu.q[], insnlink:fcvt.q.l[], and insnlink:fcvt.q.lu[] are RV64-only instructions#.
[#norm:fcvt_int_quad_valid_input]#The range of valid inputs for insnlink:fcvt.w.q[], insnlink:fcvt.wu.q[], insnlink:fcvt.l.q[], and insnlink:fcvt.lu.q[] and the behavior for invalid inputs are the same as for insnlink:fcvt.w.s[], insnlink:fcvt.wu.s[], insnlink:fcvt.l.s[], and insnlink:fcvt.lu.s[]#.
Note insnlink:fcvt.q.l[] and insnlink:fcvt.q.lu[] always produce an exact result and are unaffected by rounding mode.

include::images/wavedrom/quad-cnvrt-mv.edn[]
[[quad-cnvrt-mv]]
//.Quad-precision convert and move

New floating-point-to-floating-point conversion instructions are added.
These instructions are defined analogously to the double-precision
floating-point-to-floating-point conversion instructions. [#norm:fcvt-s-q_fcvt-q-s_op]#insnlink:fcvt.s.q[] or
insnlink:fcvt.q.s[] converts a quad-precision floating-point number to a
single-precision floating-point number, or vice-versa, respectively#.
[#norm:fcvt-d-q_fcvt-q-d_op]#insnlink:fcvt.d.q[] or insnlink:fcvt.q.d[] converts a quad-precision floating-point number to
a double-precision floating-point number, or vice-versa, respectively#.

include::images/wavedrom/quad-cnvt-interchange.edn[]
[[quad-convert-interchange]]
//.Quad-precision convert and move interchangeably

[[norm:fsgnj-q_fsgnjn-q_fsgnjx-q_op]]
Floating-point to floating-point sign-injection instructions, insnlink:fsgnj.q[],
insnlink:fsgnjn.q[], and insnlink:fsgnjx.q[], are defined analogously to the double-precision
sign-injection instruction.

include::images/wavedrom/quad-cnvrt-intch-xqqx.edn[]
[[quad-cnvrt-intch-xqqx]]
//.Quad-precision convert and move interchangeably XQ-QX

insn:fmv.x.q[] and insn:fmv.q.x[] instructions are not provided in RV32 or RV64, so
quad-precision bit patterns must be moved to the integer registers via
memory.

==== Quad-Precision Floating-Point Compare Instructions

[[norm:Q_compare_instrs]]
The quad-precision floating-point compare instructions are defined
analogously to their double-precision counterparts, but operate on
quad-precision operands.

include::images/wavedrom/quad-float-compare.edn[]
[[quad-float-compare]]
//.Quad-precision floatinf-point compare

==== Quad-Precision Floating-Point Classify Instruction

[[norm:fclass-q_op]]
The quad-precision floating-point classify instruction, insnlink:fclass.q[], is
defined analogously to its double-precision counterpart, but operates on
quad-precision operands.

include::images/wavedrom/quad-float-clssfy.edn[]
[[quad-float-clssfy]]
//.Quad-precision floating point classify
