[[ext:q]]
=== ext:q[] Extension for Quad-Precision Floating-Point

This chapter describes the ext:q[] standard extension for _quad-precision_
floating-point, which adds computational instructions compliant with the IEEE
754-2008 arithmetic standard's binary128 format and operations. The ext:q[] extension
depends on the ext:d[] extension.

[#norm:Q_flen_128]#The floating-point registers are now extended to hold
either a single, double, or quad-precision floating-point value (FLEN=128).#
The NaN-boxing scheme described in <<nanboxing>> is now extended recursively to
allow a single-precision value to be NaN-boxed inside a double-precision value
which is itself NaN-boxed inside a quad-precision value.

==== Quad-Precision Load and Store Instructions

[[norm:fsq_flq_op]]
New 128-bit variants of LOAD-FP and STORE-FP instructions are added,
encoded with a new value for the funct3 width field.

include::images/wavedrom/quad-ls.edn[]
[[quad-ls]]
//.Quad-precision load and store

[[norm:fsq_flq_atomic_align]]
insn:flq[] and insn:fsq[] are only guaranteed to execute atomically if the effective
address is naturally aligned and XLEN=128.

[[norm:fsq_flq_bits_maintained]]
insn:flq[] and insn:fsq[] do not modify the bits being transferred; in particular, the
payloads of non-canonical NaNs are preserved.

==== Quad-Precision Computational Instructions

A new supported format is added to the format field of most
instructions, as shown in <<fpextfmt>>

[[fpextfmt]]
.Format field encoding.
[%autowidth,float="center",align="center",cols="^,^,<",options="header",]
|===
|_fmt_ field |Mnemonic |Meaning
|00 |S |32-bit single-precision
|01 |D |64-bit double-precision
|10 |H |16-bit half-precision
|11 |Q |128-bit quad-precision
|===

[[norm:Q_computational_instrs]]
The quad-precision floating-point computational instructions are defined
analogously to their double-precision counterparts, but operate on
quad-precision operands and produce quad-precision results.

include::images/wavedrom/quad-compute.edn[]
[[quad-compute]]
//.Quad-precision computational

==== Quad-Precision Convert and Move Instructions

New floating-point-to-integer and integer-to-floating-point conversion
instructions are added. These instructions are defined analogously to
the double-precision-to-integer and integer-to-double-precision
conversion instructions. [#norm:fcvt-w-q_fcvt-l-q_op]#insn:fcvt.w.q[] or insn:fcvt.l.q[] converts a quad-precision
floating-point number to a signed 32-bit or 64-bit integer,
respectively#. [#norm:fcvt-q-w_fcvt-q-l_op]#insn:fcvt.q.w[] or insn:fcvt.q.l[] converts a 32-bit or 64-bit signed
integer, respectively, into a quad-precision floating-point number#.
[#norm:fcvt-wu-q_fcvt-lu-q_fcvt-q-wu_fcvt-q-lu_op]#insn:fcvt.wu.q[], insn:fcvt.lu.q[], insn:fcvt.q.wu[] and insn:fcvt.q.lu[] variants convert to or
from unsigned integer values#. [#norm:fcvt_long_quad_rv64_only]#insn:fcvt.l.q[], insn:fcvt.lu.q[], insn:fcvt.q.l[] and insn:fcvt.q.lu[] are RV64-only
instructions#. Note insn:fcvt.q.l[] and insn:fcvt.q.lu[] always produce an exact result and is unaffected by rounding mode.

include::images/wavedrom/quad-cnvrt-mv.edn[]
[[quad-cnvrt-mv]]
//.Quad-precision convert and move

New floating-point-to-floating-point conversion instructions are added.
These instructions are defined analogously to the double-precision
floating-point-to-floating-point conversion instructions. [#norm:fcvt-s-q_fcvt-q-s_op]#insn:fcvt.s.q[] or
insn:fcvt.q.s[] converts a quad-precision floating-point number to a
single-precision floating-point number, or vice-versa, respectively#.
[#norm:fcvt-d-q_fcvt-q-d_op]#insn:fcvt.d.q[] or insn:fcvt.q.d[] converts a quad-precision floating-point number to
a double-precision floating-point number, or vice-versa, respectively#.

include::images/wavedrom/quad-cnvt-interchange.edn[]
[[quad-convert-interchange]]
//.Quad-precision convert and move interchangeably

[[norm:fsgnj-q_fsgnjn-q_fsgnjx-q_op]]
Floating-point to floating-point sign-injection instructions, insn:fsgnj.q[],
insn:fsgnjn.q[], and insn:fsgnjx.q[] are defined analogously to the double-precision
sign-injection instruction.

include::images/wavedrom/quad-cnvrt-intch-xqqx.edn[]
[[quad-cnvrt-intch-xqqx]]
//.Quad-precision convert and move interchangeably XQ-QX

insn:fmv.x.q[] and insn:fmv.q.x[] instructions are not provided in RV32 or RV64, so
quad-precision bit patterns must be moved to the integer registers via
memory.

==== Quad-Precision Floating-Point Compare Instructions

[[norm:Q_compare_instrs]]
The quad-precision floating-point compare instructions are defined
analogously to their double-precision counterparts, but operate on
quad-precision operands.

include::images/wavedrom/quad-float-compare.edn[]
[[quad-float-compare]]
//.Quad-precision floatinf-point compare

==== Quad-Precision Floating-Point Classify Instruction

[[norm:fclass-q_op]]
The quad-precision floating-point classify instruction, insn:fclass.q[], is
defined analogously to its double-precision counterpart, but operates on
quad-precision operands.

include::images/wavedrom/quad-float-clssfy.edn[]
[[quad-float-clssfy]]
//.Quad-precision floating point classify
