[[rvbna]]
=== RISC-V Bulk Normalization Algorithm

This section defines the RISC-V Bulk Normalization Algorithm (RVBNA), a scheme
employed by multiple RISC-V extensions for efficient computation of
floating-point dot products.

A correctly rounded dot product is costly, and many applications do not
require such a degree of accuracy.
RVBNA reduces circuit cost and delay in exchange for a slight reduction in
accuracy using _bulk normalization_, wherein all products are aligned with
respect to a common exponent, called the _maximum reference exponent_, or
`max_exp`.
Aligned products are rounded to an intermediate precision according to round-to-odd (RTO), then summed.
The sum is then rounded to the target precision according to RTO, but unlike
RTO, out-of-range values are rounded to infinity, instead of the largest
representable number.

Formally, bulk normalization is characterized by multiple parameters:

- `p_l`, `p_r`: the size of each left (resp. right) hand side factor's significand (significand product is `p_l + p_r`-bit wide, signed product is `p_l + p_r + 1`-bit wide)
- `e_l`, `e_r`: the size of each left (resp. right) hand side factor's biased exponent (the bias is 2^e_l-1^ - 1 resp. 2^e_r-1^ - 1)
- `q`: the size of the result's significand
- `f`: the size of the result's biased exponent (the bias is 2^f-1^ - 1)
- `n`: the number of products accumulated
- `o`: the number of overflow bits
- `g`: the number of guard bits

`o` is defined to accommodate any carry overflow and is defined to be `ceil(log2(n))`.

The number of guard bits, `g`, is defined to be `ceil(log2(n))`.

Note:: It is expected that `n` would be a constant defined by each operation/implementation using RVBNA.
`n` is not expected to depend on a dynamic parameter such as `vl`. Dot product operations are still allowed to use `vl` or any dynamic length parameter but are encouraged to not link this to the bulk normalization parameters (which is similar to assuming identity-value products are injected in place of inactive elements).
`n` may vary depending on the element width (e.g. be different for different values of `SEW`).

Note:: Given the recommendation made on `n`, RVBNA mandates a fixed value of `g` for a given format size.
This reduces the space of possible implementations. An implementation using RVBNA for different formats with different `n` values requires support for multiple values of `g`.
Supporting multiple values of `g` is straightforward: an implementation can build a shared accumulator datapath based on the maximum `g` value: `gmax`.
Behavior for smaller `g` values would be obtained by OR-reducing both the sticky bits defined by `gmax` and the extra `gmax - g` least significant bits of the aligned products into the least significant accumulator bit. This should not require more than a few extra gates for hardware implementations.

Note:: Initially, RVBNA was only defined for symmetric products (i.e., `e_l = e_r` and `p_l = p_r`). The current definition generalizes RVBNA to asymmetric products.
It is generally expected, but not necessary, that `e_l + p_l = e_r + p_r`.

Informally, RVBNA works as follows:

- Computing maximum exponent `max_exp`:
**** Computing each product and the addend **reference exponent** (details in <<#RVBNAReferenceExponent>>)
**** Computing `max_exp`, the maximum of the **reference exponents**
- Aligning product magnitudes on `max_exp` (2 integer bits and `p_l + p_r -2` fractional bits)
**** Each product is extended to `q-1+g` fractional bits (right padding of `(q-1+g) - (p_l + p_r -2)` zeros)
**** Each extended product is right shifted by its reference exponent subtracted from `max_exp` (discarded significand bits are OR-reduced with any trailing bits when performing RTO)
- Rounding to odd each aligned product magnitude
- Selecting an accumulator sign `S`, negating the aligned-rounded product(s) whose sign does not match `S`
- Accumulating the rounded products. If the final sum is negative, negate it and negate `S` as well
- Normalizing/Denormalizing the result and round it to odd to the output format (e.g. binary32) mantissa `M`, computing the result exponent, `E`
- Building output result from `S`, `E`, and `M`

Bulk Normalization is illustrated by Figure <<#RVBNAFig>>. 4 products are aligned.
For the two bottom products, some bits fall under the guard bit limits. For each product those bits are OR-ed into the least significant guard bit.

[#RVBNAFig]
.RISC-V Bulk Normalization Algorithm
image::rvbna.svg[width=80%]


The following is a functional description of bulk normalization:
```
// n is the static dimension of the dot product (a power of two)
// In this specification, the number of guard bits, g, and the number of
// overflow bits, o, are defined as:
// g = o = log2(n)
//
// A[i] are IEEE-encoded floating point numbers on (e_l+p_l) bits
// B[i] are IEEE-encoded floating point numbers on (e_r+p_r) bits
// MSB is sign, next e_l (resp. e_r) bits are biased exponent,
// last m_l (resp. m_r) bits are the mantissa.
// exponent bias is lhs_bias (resp. rhs_bias)
// p_l = m_l + 1
// p_r = m_r + 1
// the output is an IEEE-encoded floating-point number on (f+q) bits
// f is the output exponent width and
// q is the size of the output significand (the size of the output mantissa is q-1)
BulkNormalizedDotProduct(A[n], B[n]) {
   let maxExp = 0
   let maskExpLHS = (1 << e_l) - 1 // bitmask for left hand side exponent
   let maskExpRHS = (1 << e_r) - 1 // bitmask for right hand side exponent
   let maskMantLHS = (1 << m_l) - 1 // bitmask for left hand side mantissa
   let maskMantRHS = (1 << m_r) - 1 // bitmask for right hand side mantissa
   let prodRefExps[n] = {0} // array of product reference exponents
   let prodSigns[n] = {0} // array of product signs
   let prodSigs[n] = {0} // array of significand products

   // boundary for exponent overflow (output format)
   // this is also the output exponent for infinity and NaN
   let overflowExp = (1 << f) - 1
   let lhs_bias = (1 << (e_l - 1)) - 1
   let rhs_bias = (1 << (e_r - 1)) - 1
   let res_bias = (1 << (f - 1)) - 1
   let prodOpBias = lhs_bias + rhs_bias


   // predicate output special cases
   // expected Not a Number (NaN) result
   let nanResult = false
   // expected infinite result
   let infiniteResult = false
   // invalid operation flag
   let invalidFlag = false
   // sign of infinite result
   let infiniteSign = 0

    // determining maximum reference exponent
    for i in 0 to n - 1
        // extracting A[i] and B[i]'s encoded exponents
        // (which are also used as reference exponents for product alignment)
        let A_i_exp = (A[i] >> m_l) & maskExpLHS
        let B_i_exp = (B[i] >> m_r) & maskExpRHS
        let A_i_mant = (A[i] & maskMantLHS)
        let B_i_mant = (B[i] & maskMantRHS)
        let A_i_sign = (A[i] >> (e_l + m_l)) & 0x1
        let B_i_sign = (B[i] >> (e_r + m_r)) & 0x1

        prodSigns[i] = A_i_sign ^ B_i_sign

        let A_i_isSub = A_i_exp == 0
        let B_i_isSub = B_i_exp == 0
        let A_i_isZero = (A_i_isSub && A_i_mant == 0)
        let B_i_isZero = (B_i_isSub && B_i_mant == 0)
        let prod_isZero = A_i_isZero || B_i_isZero

        // detecting corner cases
        let A_i_isInf = (A_i_exp == maskExpLHS) && (A_i_mant == 0)
        let B_i_isInf = (B_i_exp == maskExpRHS) && (B_i_mant == 0)
        let A_i_isNaN = (A_i_exp == maskExpLHS) && (A_i_mant != 0)
        let B_i_isNaN = (B_i_exp == maskExpRHS) && (B_i_mant != 0)
        let A_i_isSNaN = A_i_isNaN && (A_i_mant & (1 << (m_l - 1))) == 0
        let B_i_isSNaN = B_i_isNaN && (B_i_mant & (1 << (m_r - 1))) == 0

        let invalidProd = (A_i_isInf && B_i_isZero) || (B_i_isInf && A_i_isZero)
        let infiniteProdLHS = (A_i_isInf && !B_i_isNaN  && !B_i_isZero)
        let infiniteProdRHS = (B_i_isInf && !A_i_isNaN  && !A_i_isZero)
        let infiniteProd = infiniteProdLHS || infiniteProdRHS
        let invalidSum = infiniteResult && infiniteProd && (infiniteSign != prodSigns[i])

        infiniteResult ||= infiniteProd
        invalidFlag ||= invalidProd || invalidSum || A_i_isSNaN || B_i_isSNaN
        infiniteSign = infiniteProd ? prodSigns[i] : infiniteSign

        nanResult ||= A_i_isNaN || B_i_isNaN || invalidProd || invalidSum

        let A_i_sig = ((!A_i_isSub) << (p_l - 1)) | A_i_mant
        let B_i_sig = ((!B_i_isSub) << (p_r - 1)) | B_i_mant

        prodSigs[i] =  A_i_sig * B_i_sig

        let A_i_ref_exp = (A_i_isSub ? 1 : A_i_exp)
        let B_i_ref_exp = (B_i_isSub ? 1 : B_i_exp)

        prodRefExps[i] = prod_isZero ? 0 : A_i_ref_exp + B_i_ref_exp

        maxExp = (prodRefExps[i] > maxExp ? prodRefExps[i] : maxExp)
    end for


    // early exit for special cases
    if (nanResult) {
        if (invalidFlag) {
            raise invalid flag
        }
        // canonical quiet NaN
        return (overflowExp << (q - 1)) | (1 << (q - 2))
    } else if (infiniteResult) {
        return (infiniteSign << (q + f - 1)) | (overflowExp << (q - 1))
    }

    let alignedProducts[n] = {0}
    // aligning products
    for i in 0 to n - 1
        let alignShift = maxExp - prodRefExps[i]

        // aligning i-th product
        let padRight = q + 1 + g - (p_l + p_r)
        alignedProducts[i] = (prodSigs[i] << padRight) >> alignShift

        // evaluating values of discarded bits
        // a mask is built to extract the discarded bits
        // - mask=0 if alignShift is <= q+1+g-(p_l + p_r)
        // - mask=(1 << (p_l + p_r)) - 1 if alignShift=q+1+g
        let discardedMask = ((1 << (p_l + p_r)) - 1) >> (q + 1 + g - alignShift)
        let discardedBits = prodSigs[i] & discardedMask
        let jam = (alignShift >= (q+1+g) ? prodSigs[i] : discardedBits) != 0

        alignedProducts[i] |= (jam ? 1 : 0) // rounding to odd aligned product
    end for

    // accumulating products
    let accumulator = 0
    for i in 0 to n - 1
        accumulator += prodSigns[i] ? -alignedProducts[i] : alignedProducts[i]
    end for

    // computing accumulator absolute value and normalizing it
    let accSign = accumulator < 0
    let accAbs = accSign ? -accumulator : accumulator;
    let lzc = LZC(accAbs) // leading zero count assuming g + q + 1 + o width

    let resExp = accumulator == 0 ? 0 : ((maxExp + o + 1 - lzc) - prodOpBias + res_bias)
    let unroundedSig = (accAbs << lzc) >> (g + o + 1)
    let rawJamMask = (1 << (g + o + 1)) - 1
    let jamMask = (rawJamMask >> (lzc > (g + o + 1) ? 0 : (g + o + 1 - lzc)))

    let jamSig = ((accAbs << lzc) & jamMask) != 0
    let roundedSig = unroundedSig | (jamSig ? 1 : 0)

    if (accAbs == 0) {
        // a zero result is always +0
        return 0
    } else if (resExp >= overflowExp) {
        // overflow
        raise overflow flag
        return (accSign << (q + f - 1)) | overflowExp << (q - 1)
    } else if (resExp >= 1) {
        // normal output
        let roundedMant = roundedSig & ((1 << (q - 1)) - 1)
        return (accSign << (q + f - 1)) | (resExp << (q - 1)) | roundedMant
    } else {
        if (resExp < -(q - 1)) {
            return (accSign << (q + f - 1)) | (accAbs != 0 ? 1 : 0)
        } else {
            // denormalization and final round-to-odd
            // (of bits discarded during denormalization)
            let denormalizedSig = accAbs >> (q - 1 + resExp)
            let discardedMask = ((1 << (q - 1)) - 1) >> (q - 1 + resExp)
            let discardedBits = accAbs & discardedMask
            let forceLSB =  (discardedBits != 0 ? 1 : 0)
            return (accSign << (q + f - 1)) | denormalizedSig | forceLSB
        }
    }
}
```

Note:: In the current specification the most significant bit of the max product has a weight of `max_exp + 1`, which means that there are `q-2+g` fractional bits in the max product. `g` could be increased to `ceil(log2(n)) + 1` to ensure the number of fractional bits is at least `q-1` (identical to the output format). Numerical impacts of the value of `g` have not been evaluated.

Note:: Any one of the `p_l + p_r` bits of the max product can be its leading bit due to leading zeros in subnormal inputs. It is also possible for the maximum product to have more leading zeros than the other products (including when product alignment is taken into account). This is discussed in more detail in the next section <<#RVBNAReferenceExponent>>.

Note:: The RVBNA pseudocode assumes that operands are represented in the IEEE 754-2008 binary encoding, but this is not actually a requirement of RVBNA.
The pseudocode can easily be generalized to other floating-point encodings (e.g. Open Compute OFP formats).
The actual requirement is to used biased exponent to compute the reference exponent and not real exponent (in particular because we want to avoid normalizing subnormal operands before computing the reference exponent).
The significand also need to be materialized correctly for the product (including possible implicit digit(s)).

[#RVBNAReferenceExponent]
==== Reference Exponent

The **reference exponent** is a proxy to the product exponent used to determine the largest product and to align the smaller products with respect to it.


The **reference exponent** of a product is evaluated as the sum of the factors' biased exponents.
If a non-zero factor is subnormal then biased `emin_normal` (`=1`) is used as its biased exponent, for purposes of computing the **reference exponent**. Note that in that case, the value is independent from the format. More generally, unbiasing is not needed to compute the reference exponent.

Note:: the minimal reference exponent for a non-zero product is `2` (`emin_normal + emin_normal`).

If a product operand is zero then the product exponent is set to a value which ensures that every non-zero product is considered greater than every zero product when determining the maximum product. A zero product should not force any loss of accuracy on non-zero products. This can be obtained by setting the product reference exponent to zero for any zero product.

Note:: for a dot product where the left hand side vector and the right hand side vector have different formats then the bias used for the exponent may differ.
This bias has no impact on the difference between the **reference exponents**.

Note:: The **reference exponent** may differ from the product exponent (with the latter being defined as the exponent of the leading non-zero digit of the product). For example it does not take into account the actual number of leading zeros of the product (which can be large if at least one of the operand is subnormal). This simplification implies that the `max_exp` used to align products may not actually be that close to the real exponent of the maximum product and the maximum product could even be different from the one that set `max_exp`. Using the reference exponent rather the real exponent simplifies the product exponent evaluation and comparison logic.





==== Rounding modes

For floating-point dot product operations, RVBNA only supports rounding-to-odd (RTO) with some specifics (see <<#RVBNARTO>>).

For floating-point multiply operations, RVBNA supports all the rounding modes mandated by the **F** extension.

For integer operations, no rounding is required.

[#RVBNARTO]
==== Rounding to Odd behavior in dot product mode

Rounding to odd (RTO) is not part of the IEEE 754 standard (at least not until and including revision 2019).

The version used for the dot product operation admits two divergences with the generally accepted definition:

- When overflowing, an infinity result is returned (rather than the largest magnitude normal number) see <<#RVBNAOverflow>>
- A zero result is always positive (+0) whatever the sign of the actual zero term(s) of the dot product sum


==== Support for subnormal numbers

RVBNA supports subnormal values for both inputs and outputs:

- the subnormal inputs are not normalized before or after the product
- the biased subnormal input exponent is fixed to `emin_normal` for each subnormal operand when computing the product reference exponent (used to evaluate `max_exp` and shift amounts)
- the result is denormalized before the final round-to-odd is applied.

==== Behavior on floating-point zeros

If the result of a dot product operation is zero, then `+0` is returned, even if `-0` would have been returned under IEEE 754 arithmetic.

==== IEEE 754 exception flags

Under RVBNA, only the invalid operation and overflow exceptions can be raised.


Note:: The underflow and inexact flags are not raised, for two different reasons.
+
Detecting underflow accurately would add significant implementation complexity for little practical benefit. Furthermore, in some RVBNA configurations (e.g. product of OFP8 numbers into an FP32 accumulator), underflow cannot actually occur, because the product range is narrower than the range in which underflow could be triggered during accumulation.
+
Inexact is suppressed because, given the compound nature of RVBNA, the flag would carry no meaningful numerical information: nearly every result would either always raise it or never raise it at all.

===== Invalid operation

The invalid operation flag must be raised if at least one of the following conditions is met:

- Any of the operands is a signaling NaN
- At least one of the following conditions:
**** there are at least two products that are infinites with opposite sign.
**** there is at least one product between a zero and an infinity.

// comment to force next notes to be left aligned
Note:: A product is said to be infinite when it is the product between an infinity and a non-zero finite number.

Note:: The invalid exception flag can be raised even if one of the operands is a quiet NaN (for example with `inf - inf + qNaN`, or `inf * 0 + qNaN`)


[#RVBNAOverflow]
===== Overflow

The overflow flag is raised according to the IEEE 754-2008 definition:

> The overflow exception shall be signaled if and only if the destination format’s largest finite number is exceeded in magnitude by what would have been the rounded floating-point result were the exponent range unbounded.

The result returned in case of an overflow is infinity with the sign of the result with unbounded exponent. This diverges from a generally accepted definition of RTO (which rounds values exceeding the largest finite value to that extremum).

Note:: In rounding-to-odd (RTO), it is equivalent to detect overflow before or after rounding as RTO rounding cannot make the significand overflow and force a late exponent change. This applies whatever the choice for the result returned in case of overflow.
