[[memorymodel]]
=== RVWMO Memory Consistency Model

This section defines the base RISC-V memory consistency model. A memory
consistency model is a set of rules specifying the values that can be
returned by loads of memory. RISC-V uses a memory model called RISC-V
Weak Memory Ordering (RVWMO) which is designed to provide flexibility
for architects to build high-performance scalable designs while
simultaneously supporting a tractable programming model.
(((design, high performance)))
(((design, scalable)))

[#norm:rvwmo_single_hart_op]#Under RVWMO, code running on a single hart appears to execute in order
from the perspective of other memory instructions in the same hart, but
memory instructions from another hart may observe the memory
instructions from the first hart being executed in a different order.#
Therefore, multithreaded code may require explicit synchronization to
guarantee ordering between memory instructions from different harts. The
base RISC-V ISA provides a insn:fence[] instruction for this purpose, described
in <<fence>>, while the ext:zalrsc[] and ext:zaamo[] extensions additionally
define load-reserved/store-conditional and atomic read-modify-write instructions.
(((atomics, misaligned)))

The standard ISA extension for total store ordering extlink:ztso[] augments
RVWMO with additional rules specific to those extensions.

The appendices to this specification provide both axiomatic and
operational formalizations of the memory consistency model as well as
additional explanatory material.
(((FENCE)))
(((SFENCE)))

[NOTE]
====
[#norm:rvwmo_only_mainmem]#This chapter defines the memory model for regular main memory
operations. The interaction of the memory model with I/O memory,
instruction fetches (extlink:ziccif[]), insn:fence.i[], page-table walks, and insn:sfence.vma[] is not
(yet) formalized.# Some or all of the above may be formalized in a future
revision of this specification.

[#norm:rvwmo_excludes_overlap_widths]#Memory consistency models supporting overlapping
memory accesses of different widths simultaneously remain an active area of academic
research and are not yet fully understood. The specifics of how memory
accesses of different sizes interact under RVWMO are specified to the
best of our current abilities#, but they are subject to revision should
new issues be uncovered.
====

[[rvwmo]]
==== Definition of the RVWMO Memory Model

The RVWMO memory model is defined in terms of the _global memory order_,
a total ordering of the memory operations produced by all harts. In
general, a multithreaded program has many different possible executions,
with each execution having its own corresponding global memory order.
(((RVWMO)))

The global memory order is defined over the primitive load and store
operations generated by memory instructions. It is then subject to the
constraints defined in the rest of this chapter.
Any execution satisfying all of the memory model
constraints is a legal execution (as far as the memory model is concerned).

[[rvwmo-primitives]]
===== Memory Model Primitives

The _program order_ over memory operations reflects the order in which
the instructions that generate each load and store are logically laid
out in that hart's dynamic instruction stream; i.e., the order in which
a simple in-order processor would execute the instructions of that hart.

Memory-accessing instructions give rise to _memory operations_. A memory
operation can be either a _load operation_, a _store operation_, or both
simultaneously.
[#norm:rvwmo_single_copy_atomic]#All memory operations are single-copy atomic:
they can never be observed in a partially complete state.#
(((operations, memory)))

[#norm:rvwmo_aligned_memop]#Each aligned memory instruction that accesses XLEN or
fewer bits gives rise to exactly one memory operation, unless specified otherwise.#
[#norm:rvwmo_aligned_amo_memop]#An aligned AMO gives rise to a single memory operation that
is both a load operation and a store operation simultaneously.#

[NOTE]
====
Among instructions in RV32GC and RV64GC, the following are exceptions to the
rule that an aligned memory instruction gives rise to exactly one memory
operation:

* [#norm:rvwmo_sc_fail_no_memop]#An unsuccessful SC instruction does not give rise to any memory operations.#
* Floating-point load and store instructions that access more than XLEN bits
  (e.g., insn:fld[]/insn:fsd[] in RV32) may each give rise to multiple memory operations.

[#norm:rvwmo_v_p_multi_memops]#ISA extensions such as the ext:v[] extension may
give rise to multiple memory operations.#
However, the memory model for these extensions has not yet been formalized.
====

[#norm:rvwmo_misaligned_ldst_memops]#A misaligned load or store instruction may be decomposed
into a set of component memory operations of any granularity.#
[#norm:rvwmo_fp_gt_xlen_memops]#A floating-point load or store of more than XLEN bits may
also be decomposed into a set of component memory operations of any granularity.#
[#norm:rvwmo_order_multi_memops]#The memory operations generated by such instructions
are not ordered with respect to each other in program order, but they are ordered normally with
respect to the memory operations generated by preceding and subsequent
instructions in program order.#
The ext:zaamo[] extension does not require execution environments to support
misaligned atomic instructions at all.
However, [#norm:rvwmo_misaligned_in_atomic_pma]#if misaligned atomics are supported via the
misaligned atomicity granule PMA, then AMOs within an atomicity granule are not decomposed, nor are
loads and stores defined in the base ISAs, nor are loads and stores of no more
than XLEN bits defined in the ext:f[], ext:d[], and ext:q[] extensions.#
(((decomposition)))

[NOTE]
====
The decomposition of misaligned memory operations down to byte
granularity facilitates emulation on implementations that do not
natively support misaligned accesses. Such implementations might, for
example, simply iterate over the bytes of a misaligned access one by
one.
====

An insn:lr[] instruction and an insn:sc[] instruction are said to be _paired_ if the
insn:lr[] precedes the insn:sc[] in program order and if there are no other insn:lr[] or
insn:sc[] instructions in between; the corresponding memory operations are said to
be paired as well (except in case of a failed insn:sc[], where no store
operation is generated). The complete list of conditions determining
whether an insn:sc[] must succeed, may succeed, or must fail is defined in
extlink:zalrsc[].

Load and store operations may also carry one or more ordering
annotations from the following set: _acquire-RCpc_, _acquire-RCsc_,
_release-RCpc_, and _release-RCsc_. An AMO or insn:lr[] instruction with
_aq_ set has an acquire-RCsc annotation. An AMO or insn:sc[] instruction
with _rl_ set has a release-RCsc annotation. An AMO, insn:lr[], or
insn:sc[] instruction with both _aq_ and _rl_ set has both acquire-RCsc and
release-RCsc annotations.

For convenience, we use the term _acquire annotation_ to refer to an
acquire-RCpc annotation or an acquire-RCsc annotation. Likewise, a
_release annotation_ refers to a release-RCpc annotation or a
release-RCsc annotation. An _RCpc annotation_ refers to an
acquire-RCpc annotation or a release-RCpc annotation. An _RCsc
annotation_ refers to an acquire-RCsc annotation or a release-RCsc
annotation.

[NOTE]
====
In the memory model literature, the term _RCpc_ stands for release
consistency with processor-consistent synchronization operations, and
the term _RCsc_ stands for release consistency with sequentially
consistent synchronization operations.

While there are many different definitions for acquire and release
annotations in the literature, in the context of RVWMO these terms are
concisely and completely defined by <<ppo, Preserved Program Order>> rules 5-7.

RCpc annotations are currently only used when implicitly assigned to every
memory access per the standard extension extlink:ztso[]. Furthermore, although
the ISA does not currently contain native RCpc load-acquire or store-release
instructions, the RVWMO model itself is designed to be forwards-compatible with
the potential addition of them into the ISA in a future extension.
====

[[mem-dependencies]]
===== Syntactic Dependencies

The definition of the RVWMO memory model depends in part on the notion
of a syntactic dependency, defined as follows.

In the context of defining dependencies, a _register_ refers either to
an entire general-purpose register, some portion of a CSR, or an entire
CSR. The granularity at which dependencies are tracked through CSRs is
specific to each CSR and is defined in
<<csr-granularity>>.

Syntactic dependencies are defined in terms of instructions' _source
registers_, instructions' _destination registers_, and the way
instructions _carry a dependency_ from their source registers to their
destination registers. This section provides a general definition of all
of these terms; however, <<source-dest-regs>> provides a
complete listing of the specifics for each instruction.

In general, a register _r_ other than `x0` is a _source
register_ for an instruction _i_ if any of the following
hold:

* In the opcode of _i_, _rs1_, _rs2_, or _rs3_ is set to
_r_
* _i_ is a CSR instruction, and in the opcode of
_i_, _csr_ is set to _r_, unless _i_
is insn:csrrw[] or insn:csrrwi[] and _rd_ is set to `x0`
* _r_ is a CSR and an implicit source register for
_i_, as defined in <<source-dest-regs>>
* _r_ is a CSR that aliases with another source register for
_i_

Memory instructions also further specify which source registers are
_address source registers_ and which are _data source registers_.

In general, a register _r_ other than `x0` is a _destination
register_ for an instruction _i_ if any of the following
hold:

* In the opcode of _i_, _rd_ is set to _r_
* _i_ is a CSR instruction, and in the opcode of
_i_, _csr_ is set to _r_, unless _i_
is insn:csrrs[] or insn:csrrc[] and _rs1_ is set to `x0` or _i_ is
insn:csrrsi[] or insn:csrrci[] and uimm[4:0] is set to zero.
* _r_ is a CSR and an implicit destination register for
_i_, as defined in <<source-dest-regs>>
* _r_ is a CSR that aliases with another destination
register for _i_

Most non-memory instructions _carry a dependency_ from each of their
source registers to each of their destination registers. However, there
are exceptions to this rule; see <<source-dest-regs>>.

Instruction _j_ has a _syntactic dependency_ on instruction
_i_ via destination register _s_ of
_i_ and source register _r_ of _j_
if either of the following hold:

* _s_ is the same as _r_, and no instruction
program-ordered between _i_ and _j_ has
_r_ as a destination register
* There is an instruction _m_ program-ordered between
_i_ and _j_ such that all of the following hold:
. _j_ has a syntactic dependency on _m_ via
destination register _q_ and source register _r_
. _m_ has a syntactic dependency on _i_ via
destination register _s_ and source register _p_
. _m_ carries a dependency from _p_ to
_q_

Finally, in the definitions that follow, let _a_ and
_b_ be two memory operations, and let _i_ and
_j_ be the instructions that generate _a_ and
_b_, respectively.

_b_ has a _syntactic address dependency_ on _a_
if _r_ is an address source register for _j_ and
_j_ has a syntactic dependency on _i_ via source
register _r_

_b_ has a _syntactic data dependency_ on _a_ if
_b_ is a store operation, _r_ is a data source
register for _j_, and _j_ has a syntactic
dependency on _i_ via source register _r_

_b_ has a _syntactic control dependency_ on _a_
if there is an instruction _m_ program-ordered between
_i_ and _j_ such that _m_ is a
branch or indirect jump and _m_ has a syntactic dependency
on _i_.

[NOTE]
====
Generally speaking, non-AMO load instructions do not have data source
registers, and unconditional non-AMO store instructions do not have
destination registers. However, a successful SC instruction is
considered to have the register specified in _rd_ as a destination
register, and hence it is possible for an instruction to have a
syntactic dependency on a successful SC instruction that precedes it in
program order.
====

===== Preserved Program Order
[[ppo]]
The global memory order for any given execution of a program respects
some but not all of each hart’s program order. The subset of program
order that must be respected by the global memory order is known as
_preserved program order_.

[[norm:rvwmo_ppo_lead-in]]
The complete definition of preserved program order is as follows (and
note that AMOs are simultaneously both loads and stores): memory
operation _a_ precedes memory operation _b_ in
preserved program order (and hence also in the global memory order) if
_a_ precedes _b_ in program order,
_a_ and _b_ both access regular main memory
(rather than I/O regions), and any of the following hold:

[[overlapping-ordering]]
* [#norm:rvwmo_ppo_overlap]#Overlapping-Address Orderings#:
. [#norm:rvwmo_ppo_overlap1]#_b_ is a store, and _a_ and _b_ access overlapping memory addresses#
. [#norm:rvwmo_ppo_overlap2]#_a_ and _b_ are loads, _x_ is a byte read by both _a_ and
_b_, there is no store to _x_ between _a_ and _b_ in program order, and _a_ and _b_ return values for _x_
written by different memory operations#
. [#norm:rvwmo_ppo_overlap3]#_a_ is generated by an AMO or SC instruction, _b_ is a load, and
_b_ returns a value written by _a_#
* [#norm:rvwmo_ppo_sync]#Explicit Synchronization#:
[start=4]
. [#norm:rvwmo_ppo_sync1]#There is a insn:fence[] instruction that orders _a_ before _b_#
. [#norm:rvwmo_ppo_sync2]#_a_ has an acquire annotation annotation#
. [#norm:rvwmo_ppo_sync3]#_b_ has a release annotation#
. [#norm:rvwmo_ppo_sync4]#_a_ and _b_ both have RCsc annotations#
. [#norm:rvwmo_ppo_sync5]#_a_ is paired with _b_#
* [#norm:rvwmo_ppo_dep]#Syntactic Dependencies#:
[start=9]
. [#norm:rvwmo_ppo_dep1]#_b_ has a syntactic address dependency on _a_#
. [#norm:rvwmo_ppo_dep2]#_b_ has a syntactic data dependency on _a_#
. [#norm:rvwmo_ppo_dep3]#_b_ is a store, and _b_ has a syntactic control dependency on _a_#
* [#norm:rvwmo_ppo_pipe]#Pipeline Dependencies#:
[start=12]
. [#norm:rvwmo_ppo_pipe1]#_b_ is a load, and there exists some store _m_ between _a_ and _b_
in program order such that _m_ has an address or data dependency on _a_,
and _b_ returns a value written by _m_#
. [#norm:rvwmo_ppo_pipe2]#_b_ is a store, and there exists some instruction _m_ between _a_
and _b_ in program order such that _m_ has an address dependency on _a_#

===== Memory Model Axioms

[[norm:rvwmo_obeyed]]
An execution of a RISC-V program obeys the RVWMO memory consistency
model only if there exists a global memory order conforming to preserved
program order and satisfying the _load value axiom_, the _atomicity
axiom_, and the _progress axiom_.

[[ax-load]]
====== Load Value Axiom

[[norm:rvwmo_ld_val_axiom_lead-in]]
Each byte of each load _i_ returns the value written to that
byte by the store that is the latest in global memory order among the
following stores:

[[norm:rvwmo_ld_val_axiom_list]]
. Stores that write that byte and that precede _i_ in the
global memory order
. Stores that write that byte and that precede _i_ in
program order

[[ax-atom]]
====== Atomicity Axiom

[[norm:rvwmo_atomicity_axiom]]
If _r_ and _w_ are paired load and store
operations generated by aligned LR and SC instructions in a hart
_h_, _s_ is a store to byte _x_, and
_r_ returns a value written by _s_, then
_s_ must precede _w_ in the global memory order,
and there can be no store from a hart other than _h_ to byte
_x_ following _s_ and preceding _w_
in the global memory order.
[NOTE]
====
The <<ax-atom, Atomicity Axiom>> theoretically supports LR/SC pairs of different widths and to
mismatched addresses, since implementations are permitted to allow SC
operations to succeed in such cases. However, in practice, we expect
such patterns to be rare, and their use is discouraged.
====

[[ax-prog]]
====== Progress Axiom

[[norm:rvwmo_progress_axiom]]
No memory operation may be preceded in the global memory order by an
infinite sequence of other memory operations.

[[csr-granularity]]
==== CSR Dependency Tracking Granularity

.Granularities at which syntactic dependencies are tracked through CSRs
[%autowidth,float="center",align="center",cols="<,<,<",options="header",]
|===
|Name |Portions Tracked as Independent Units |Aliases
|csr:fflags[] |Bits 4, 3, 2, 1, 0 |csr:fcsr[]
|csr:frm[] |entire CSR |csr:fcsr[]
|csr:fcsr[] |Bits 7-5, 4, 3, 2, 1, 0 |csr:fflags[], csr:frm[]
|===

Note: read-only CSRs are not listed, as they do not participate in the
definition of syntactic dependencies.

[[source-dest-regs]]
==== Source and Destination Register Listings

This section provides a concrete listing of the source and destination
registers for each instruction. These listings are used in the
definition of syntactic dependencies in
<<mem-dependencies>>.

// Generated by scripts/generate_rvwmo_source_dest_listings.py
include::rvwmo-source-dest-listings.adoc[]
