[[ext:v]]
=== ext:v[] Vector Extension for Application Processors

The single-letter V extension is intended for use in application
processor profiles.

[#norm:misa_v_op]#The csr:misa[v] bit is set for implementations providing csr:misa[] and
supporting V.#

[#norm:V_precise_traps]#The V vector extension has precise traps.#

[#norm:V_dependent_Zvl128b_Zve64d]#The V vector extension depends upon the Zvl128b and Zve64d extensions.#

NOTE: The value of 128 was chosen as a compromise for application
processors. Providing a larger VLEN allows strip-mining code to be
elided in some cases for short vectors, but also increases the size of
the minimum implementation.  Note that larger LMUL can be used to
avoid strip mining for longer known-size application vectors at the
cost of having fewer available vector register groups. For example, an
LMUL of 8 allows vectors of up to sixteen 64-bit elements to be
processed without strip mining using four vector register groups.

[#norm:V_supported_eew]#The V extension supports EEW of 8, 16, 32, and 64.#

[#norm:V_instr_config]#The V extension supports the vector configuration instructions
(<<sec-vector-config>>).#

[#norm:V_instr_ls_eew64_nsupported_xlen32]#The V extension supports all vector load and store instructions
(<<sec-vector-memory>>), except the V extension does not
support EEW=64 for index values when XLEN=32.#

[#norm:V_instr_int]#The V extension supports all vector integer instructions
(<<sec-vector-integer>>).#

The V extension includes the insn:vmulh[] integer multiply
variants that return the high half of the product (insn:vmulh.vv[],
insn:vmulh.vx[], insn:vmulhu.vv[], insn:vmulhu.vx[], insn:vmulhsu.vv[],
insn:vmulhsu.vx[])  with EEW=64.

[#norm:V_instr_fixedpt]#The V extension supports all vector fixed-point arithmetic
instructions (<<sec-vector-fixed-point>>).#

[#norm:V_instr_red]#The V extension supports all vector integer single-width and
widening reduction operations (<<sec-vector-integer-reduce>>,
<<sec-vector-integer-reduce-widen>>).#

[#norm:V_instr_mask]#The V extension supports all vector mask instructions
(<<sec-vector-mask>>).#

[#norm:V_instr_perm]#The V extension supports all vector permutation instructions
(<<sec-vector-integer-permute>>, <<sec-vector-float-permute>>).#

[#norm:V_dependent_F_D]#The V extension depends upon the F and D
extensions, and implements all vector floating-point instructions
(<<sec-vector-float>>) for floating-point operands with EEW=32
or EEW=64 (including widening instructions and conversions between
FP32 and FP64). Vector single-width floating-point reductions
(<<sec-vector-float-reduce>>) for EEW=32 and EEW=64 are supported as
well as widening reductions from FP32 to FP64.#

[NOTE]
====
As is the case with other RISC-V extensions, it is valid to
include overlapping extensions in the same ISA string.  For example,
RV64GCV and RV64GCV_Zve64f are both valid and equivalent ISA strings,
as is RV64GCV_Zve64f_Zve32x_Zvl128b.
====

//
