[[ext:zabha]]
=== ext:zabha[] Extension for Byte and Halfword Atomic Memory Operations

The ext:zaamo[] and ext:zacas[] extensions offer atomic memory operation (AMO) instructions for _words_,
_doublewords_, and _quadwords_ (only for insn:amocas[]). The absence of atomic
operations for subword data types necessitates emulation strategies. For bitwise
operations, this emulation can be performed via word-sized bitwise
insn:amo{asterisk}[] instructions. For non-bitwise operations, emulation is achievable using
word-sized insn:lr[]/insn:sc[] instructions.

Several limitations arise from this emulation approach:

. In systems with large-scale or Non-Uniform Memory Access (NUMA)
  configurations, emulation based on insn:lr[]/insn:sc[] introduces issues related to
  scalability and fairness, particularly under conditions of high contention.

. Emulation of narrower AMOs through wider insn:amo{asterisk}[] instructions on non-idempotent
  IO memory regions may result in unintended side effects.

. Utilizing wider insn:amo{asterisk}[] instructions for emulating narrower AMOs risks activating
  extraneous breakpoints or watchpoints.

. In the absence of native support for subword atomics, compilers often resort
  to inlining code sequences to provide the required emulation. This practice
  contributes to an increase in code size, with consequent impacts on system
  performance and memory utilization.

The ext:zabha[] extension addresses these limitations by adding support for _byte_ and
_halfword_ atomic memory operations to the RISC-V Unprivileged ISA. The ext:zabha[]
extension depends upon the ext:zaamo[] standard extension.

==== Byte and Halfword Atomic Memory Operation Instructions

ext:zabha[] extension provides the insn:amoadd.b/h[], insn:amoand.b/h[],
insn:amoor.b/h[], insn:amoxor.b/h[], insn:amoswap.b/h[], insn:amomin.b/h[],
insn:amominu.b/h[], insn:amomax.b/h[] and insn:amomaxu.b/h[] instructions.
If ext:zacas[] extension is also implemented, ext:zabha[] further provides the
insn:amocas.b/h[] instructions.

[wavedrom, zabha-ext-wavedrom-reg,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:['AMO','AMO','AMO','AMO','AMO','AMO','AMO','AMO']},
  {bits:  5, name: 'rd', attr:['dest','dest','dest','dest','dest','dest','dest','dest']},
  {bits:  3, name: 'funct3', attr:['width=0/1','width=0/1','width=0/1','width=0/1','width=0/1','width=0/1','width=0/1','width=0/1']},
  {bits:  5, name: 'rs1', attr:['addr','addr','addr','addr','addr','addr','addr','addr']},
  {bits:  5, name: 'rs2', attr:['src','src','src','src','src','src','src','src']},
  {bits:  1, name: 'rl'},
  {bits:  1, name: 'aq', attr:['ordering','ordering','ordering','ordering','ordering','ordering','ordering','ordering']},
  {bits:  5, name: 'funct5', attr:['AMOSWAP.B/H','AMOADD.B/H','AMOAND.B/H','AMOOR.B/H','AMOXOR.B/H','AMOMAX[U].B/H','AMOMIN[U].B/H','AMOCAS.B/H']},
], config:{lanes: 1, hspace:1024}}
....

[#norm:Zabha_rd_sign_extension]#Byte and halfword AMOs always sign-extend the value placed in `rd`, and ignore
the stem:[XLEN-1:2^{(width + 3)}] bits of the original value in `rs2`.# [#norm:Zabha_amocas-BH_ignore_bits]#The
insn:amocas.b/h[] instructions similarly ignore the stem:[XLEN-1:2^{(width + 3)}]
bits of the original value in `rd`.#

[#norm:Zabha_rs1_align_addr]#Similar to the AMOs specified in the ext:zaamo[] extension, the ext:zabha[] extension mandates
that the address contained in the `rs1` register must be naturally aligned to
the size of the operand.# The same exception options as specified in the
ext:zaamo[] extension are applicable in cases where the address is not naturally aligned.

Similar to the AMOs specified in the ext:zaamo[] and ext:zacas[] extensions, the AMOs in the
ext:zabha[] extension optionally provide release consistency semantics, using the `aq`
and `rl` bits, to help implement multiprocessor synchronization.

[NOTE]
====
ext:zabha[] omits _byte_ and _halfword_ support for insn:lr[] and insn:sc[] due to low utility.
====
