[[ext:zabhlrsc]]
=== ext:zabhlrsc[] Extension for Byte and Halfword Load Reserved/Store Conditional

The ext:zalrsc[] extension offers LR/SC (load reserved/store conditional) instructions
for _words_ and _doublewords_. ext:zabhlrsc[] extends this by adding _byte_ and
_halfword_ versions. The ext:zabhlrsc[] extension depends upon the ext:zalrsc[]
standard extension.

[NOTE]
====
The absence of LR/SC operations for subword data types
is problematic for CHERI software (RVY base architectures).
Non-CHERI RISC-V software can use LR/SC on larger data types than are strictly
required for the memory access to register the reservation set.
RVY base architectures check memory bounds and so it is not possible to round a subword
access up to a word or larger to gain the reservation set.
It is not always possible to emulate narrow accesses using wider accesses on a CHERI system, due to the memory bounds.
Such emulation can be problematic for other reasons as explained in the rationale for ext:zabha[].
====

==== Byte and Halfword Atomic Load Reserved/Store Conditional Instructions

The ext:zabhlrsc[] extension provides the insn:lr.b/h[] and insn:sc.b/h[] instructions.

[wavedrom, zabhlrsc-lr-ext-wavedrom-reg, svg]
....
{reg: [
  {bits: 7,  name: 'opcode',   attr: ['7', 'AMO=0101111'], type: 8},
  {bits: 5,  name: 'rd',       attr: ['5', 'rdest[4:0]'], type: 3},
  {bits: 3,  name: 'funct3',   attr: ['3', '.B=000', '.H=001'], type: 8},
  {bits: 5,  name: 'rs1',      attr: ['5', 'base'], type: 4},
  {bits: 5,  name: 'rs2',      attr: ['5', 'LR.*=00000'],  type: 4},
  {bits: 1,  name: 'rl',       attr: ['1', 'rl'],  type: 4},
  {bits: 1,  name: 'aq',       attr: ['1', 'aq'],  type: 4},
  {bits: 5,  name: 'funct5',   attr: ['5', 'op', 'LR.*=00010'], type: 3},
]}
....

[wavedrom, zabhlrsc-sc-ext-wavedrom-reg, svg]
....
{reg: [
  {bits: 7,  name: 'opcode',   attr: ['7', 'AMO=0101111'], type: 8},
  {bits: 5,  name: 'rd',       attr: ['5', 'rdest[4:0]'], type: 3},
  {bits: 3,  name: 'funct3',   attr: ['3', 'width', '.B=000','.H=001'], type: 8},
  {bits: 5,  name: 'rs1',      attr: ['5', 'base'], type: 4},
  {bits: 5,  name: 'rs2',      attr: ['5', 'src'],  type: 4},
  {bits: 1,  name: 'rl',       attr: ['1', 'rl'],  type: 4},
  {bits: 1,  name: 'aq',       attr: ['1', 'aq'],  type: 4},
  {bits: 5,  name: 'funct5',   attr: ['5', 'op', 'SC.*=00011'], type: 3},
]}
....

[#norm:Zabhlrsc_lr_analogy]#insn:lr.b/h[] behave analogously to insn:lr.w/d[].#
They sign extend the result and write it to _rd_.

[#norm:Zabhlrsc_sc_analogy]#insn:sc.b/h[] behave analogously to insn:sc.w/d[].#
