[[ext:zawrs]]
=== ext:zawrs[] Extension for Wait-on-Reservation-Set instructions

The ext:zawrs[] extension defines a pair of insn:wrs[] (wait-on-reservation-set)
instructions to be used in polling loops that allows a core to enter a low-power
state and wait on a store to a memory location. Waiting for a memory location to
be updated is a common pattern in many use cases such as:

. Contenders for a lock waiting for the lock variable to be updated.

. Consumers waiting on the tail of an empty queue for the producer to queue
  work/data. The producer may be code executing on a RISC-V hart, an accelerator
  device, an external I/O agent.

. Code waiting on a flag to be set in memory indicative of an event occurring.
  For example, software on a RISC-V hart may wait on a "done" flag to be set in
  memory by an accelerator device indicating completion of a job previously
  submitted to the device.

Such use cases involve polling on memory locations, and such busy loops can be a
wasteful expenditure of energy. To mitigate the wasteful looping in such usages,
a insn:wrs.nto[] (WRS-with-no-timeout) instruction is provided. Instead of polling
for a store to a specific memory location, software registers a reservation set
that includes all the bytes of the memory location using the insn:lr[] instruction.
[#norm:Zawrs_wrs-nto_stall_exec]#Then a subsequent insn:wrs.nto[] instruction would cause the hart to temporarily
stall execution in a low-power state until a store occurs to the reservation set
or an interrupt is observed.#

Sometimes the program waiting on a memory update may also need to carry out a
task at a future time or otherwise place an upper bound on the wait. To support
such use cases a second instruction [#norm:Zawrs_wrs-sto_stall_duration]#insn:wrs.sto[] (WRS-with-short-timeout) is
provided that works like insn:wrs.nto[] but bounds the stall duration to an
implementation-define short timeout such that the stall is terminated on the
timeout if no other conditions have occurred to terminate the stall.# The
program using this instruction may then determine if its deadline has been
reached.

[NOTE]
====
The instructions in the ext:zawrs[] extension are only useful in conjunction with the
insn:lr[] instruction, which is provided by the ext:zalrsc[] component of the ext:a[] extension.
====

==== Wait-on-Reservation-Set Instructions

The insn:wrs.nto[] and insn:wrs.sto[] instructions cause the hart to temporarily stall
execution in a low-power state as long as the reservation set is valid and no
locally enabled interrupts at any privilege level are pending,
regardless of the global interrupt enable at each privilege level.
For insn:wrs.sto[] the stall
duration is bounded by an implementation defined short timeout. These
instructions are available in all privilege modes.

[wavedrom, ,svg]
....
{reg: [
  {bits: 7, name: 'opcode', attr: ['SYSTEM(0x73)'] },
  {bits: 5, name: 'rd', attr: ['0'] },
  {bits: 3,  name: 'funct3', attr: ['0'] },
  {bits: 5,  name: 'rs1', attr: ['0'] },
  {bits: 12,  name: 'funct12', attr:['WRS.NTO(0x0d)', 'WRS.STO(0x1d)'] },
], config:{lanes: 1, hspace:1024}}
....

<<<

Hart execution may be stalled while the following conditions are all satisfied:
[loweralpha]
    . The reservation set is valid
    . If insn:wrs.sto[], a "short" duration since start of stall has not elapsed
    . No locally enabled interrupt at any privilege level is pending (see the rules below)

[#norm:Zawrs_stall_terminate]#While stalled, an implementation is permitted to occasionally terminate the
stall and complete execution for any reason.#

[#norm:Zawrs_exec_resume_rules]#insn:wrs.nto[] and insn:wrs.sto[] instructions follow the rules of the insn:wfi[] instruction
for resuming execution on a locally enabled pending interrupt.#

[#norm:Zawrs_priv_illegal_instr_excp]#When the csr::[tw] (timeout wait) bit in csr:mstatus[] is set and insn:wrs.nto[] is executed
in any privilege mode other than M-mode, and it does not complete within an
implementation-specific bounded time limit, the insn:wrs.nto[] instruction will cause
an illegal-instruction exception.#

[#norm:Zawrs_virtual_instr_excp]#When executing in VS- or VU-mode, if the csr::[vtw] bit is set in csr:hstatus[], the
csr::[tw] bit in csr:mstatus[] is clear, and the insn:wrs.nto[] does not complete within an
implementation-specific bounded time limit, the insn:wrs.nto[] instruction will cause
a virtual-instruction exception.#

[NOTE]
====
Since the insn:wrs.sto[] and insn:wrs.nto[] instructions can complete execution for
reasons other than stores to the reservation set, software will likely need
a means of looping until the required stores have occurred.

The duration of a insn:wrs.sto[] instruction's timeout may vary significantly within
and among implementations. In typical implementations this duration should be
roughly in the range of 10 to 100 times an on-chip cache miss latency or a
cacheless access to main memory.

insn:wrs.nto[], unlike insn:wfi[], is not specified to cause an illegal-instruction
exception if executed in U-mode when the governing csr::[tw] bit is 0. insn:wfi[] is
typically not expected to be used in U-mode and on many systems may promptly
cause an illegal-instruction exception if used at U-mode. Unlike insn:wfi[],
insn:wrs.nto[] is expected to be used by software in U-mode when waiting on
memory but without a deadline for that wait.
====
