[[ext:zba]]
=== ext:zba[] Extension for Address Generation

The ext:zba[] instructions can be used to accelerate the generation of addresses that index into arrays of basic types (halfword, word, doubleword) using both unsigned word-sized and XLEN-sized indices: a shifted index is added to a base address.

The shift and add instructions do a left shift of 1, 2, or 3 because these are commonly found in real-world code and because they can be implemented with a minimal amount of additional hardware beyond that of the simple adder. This avoids lengthening the critical path in implementations.

While the shift and add instructions are limited to a maximum left shift of 3, the insnlink:slli[] instruction from the base ISA can be used to perform similar shifts for indexing into arrays of wider elements. The insnlink:slli.uw[] added in this extension can be used when the index is to be interpreted as an unsigned word.

The following instructions comprise the ext:zba[] extension:

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|
|{check}
|insnlink:add.uw[rd,rs1,rs2]
|<<#insns-add_uw>>

|{check}
|{check}
|insnlink:sh1add[rd,rs1,rs2]
|<<#insns-sh1add>>

|
|{check}
|insnlink:sh1add.uw[rd,rs1,rs2]
|<<#insns-sh1add_uw>>

|{check}
|{check}
|insnlink:sh2add[rd,rs1,rs2]
|<<#insns-sh2add>>

|
|{check}
|insnlink:sh2add.uw[rd,rs1,rs2]
|<<#insns-sh2add_uw>>

|{check}
|{check}
|insnlink:sh3add[rd,rs1,rs2]
|<<#insns-sh3add>>

|
|{check}
|insnlink:sh3add.uw[rd,rs1,rs2]
|<<#insns-sh3add_uw>>

|
|{check}
|insnlink:slli.uw[rd,rs1,imm]
|<<#insns-slli_uw>>

|===
