[[compressed]]
== Compressed Instructions

This chapter describes the RISC-V compressed instruction-set
extensions, which reduce static and dynamic code size by
adding short 16-bit instruction encodings for common operations.
Typically, 50%-60% of the RISC-V instructions in a program can be replaced
with compressed instructions, resulting in a 25%-30% code-size reduction.

The ext:zca[link] extension forms the core of the compressed extensions;
it provides compressed forms of integer loads, stores, branches, and
computational instructions.
The <<sec:zcf,`Zcf`>> extension is an XLEN=32-only extension that adds
single-precision floating-point loads and stores.
The <<sec:zcd,`Zcd`>> extension adds double-precision floating-point loads and
stores.
The <<sec:c,`C`>> extension combines `Zca`, `Zcf` if XLEN=32 and the F extension
is present, and `Zcd` if the D extension is present.
Various additional `Zc*` extensions are also defined.

include::zca.adoc[]
include::zcf.adoc[]
include::zcd.adoc[]
