[[zc]]
== Compressed Instructions

This chapter describes the RISC-V compressed instruction-set
extensions, which reduce static and dynamic code size by
adding short 16-bit instruction encodings for common operations.
Typically, 50%-60% of the RISC-V instructions in a program can be replaced
with compressed instructions, resulting in a 25%-30% code-size reduction.

The extlink:zca[] extension forms the core of the compressed extensions;
it provides compressed forms of integer loads, stores, branches, and
computational instructions.
The extlink:zcf[] extension is an XLEN=32-only extension that adds
single-precision floating-point loads and stores.
The extlink:zcd[] extension adds double-precision floating-point loads and
stores.
The extlink:c[] extension combines ext:zca[], ext:zcf[] if XLEN=32 and the ext:f[] extension
is present, and ext:zcd[] if the ext:d[] extension is present.
Various additional ext:zc*[] extensions are also defined.

include::zca.adoc[]
include::zcf.adoc[]
include::zcd.adoc[]
include::c-st-ext.adoc[]
include::zcb.adoc[]
include::zcmt.adoc[]
include::zcmp.adoc[]
include::zce.adoc[]
include::zclsd.adoc[]
include::zcmop.adoc[]
