[[ext:zcb]]
=== ext:zcb[] Extension for Additional Compressed Instructions

The ext:zcb[] extension adds several compressed instructions which, like those
in the extlink:zca[] extension, expand into a single 32-bit instruction.
The ext:zcb[] extension depends on the ext:zca[] extension.

As shown on the individual instruction pages, many of the instructions in Zcb
depend upon another extension being implemented.
For example, inst:c.mul[] is only implemented if extlink:m[] or extlink:zmmul[] is
implemented, and inst:c.sext.b[] is only implemented if extlink:zbb[] is
implemented.

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|yes
|yes
|c.lbu _rd'_, uimm(_rs1'_)
|<<#insns-c_lbu>>

|yes
|yes
|c.lhu _rd'_, uimm(_rs1'_)
|<<#insns-c_lhu>>

|yes
|yes
|c.lh _rd'_, uimm(_rs1'_)
|<<#insns-c_lh>>

|yes
|yes
|c.sb _rs2'_, uimm(_rs1'_)
|<<#insns-c_sb>>

|yes
|yes
|c.sh _rs2'_, uimm(_rs1'_)
|<<#insns-c_sh>>

|yes
|yes
|c.zext.b _rsd'_
|<<#insns-c_zext_b>>

|yes
|yes
|c.sext.b _rsd'_
|<<#insns-c_sext_b>>

|yes
|yes
|c.zext.h _rsd'_
|<<#insns-c_zext_h>>

|yes
|yes
|c.sext.h _rsd'_
|<<#insns-c_sext_h>>

|
|yes
|c.zext.w _rsd'_
|<<#insns-c_zext_w>>

|yes
|yes
|c.not _rsd'_
|<<#insns-c_not>>

|yes
|yes
|c.mul _rsd'_, _rs2'_
|<<#insns-c_mul>>

|===

[#insns-c_lbu,reftext="Load unsigned byte, 16-bit encoding"]
==== c.lbu

Synopsis::

Load unsigned byte, 16-bit encoding

Mnemonic::

c.lbu _rd'_, _uimm_(_rs1'_)

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x0, attr: ['C0'] },
    { bits:  3, name: 'rd\'' },
    { bits:  2, name: 'uimm[0|1]' },
    { bits:  3, name: 'rs1\'' },
    { bits:  3, name: 0x0 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

The immediate offset is formed as follows:

[source,sail]
--
  uimm[31:2] = 0;
  uimm[1]    = encoding[5];
  uimm[0]    = encoding[6];
--

Description::

This instruction [#norm:c-lbu_op]#loads a byte from the memory address formed by adding _rs1'_ to the zero extended immediate _uimm_. The resulting byte is zero extended to XLEN bits and is written to _rd'_.#

[NOTE]
====
_rd'_ and _rs1'_ are from the standard 8-register set x8-x15.
====

Prerequisites::

None
//32-bit equivalent:
//<<insns-lbu>>

Operation::

[source,sail]
----
//This is not SAIL, it's pseudocode. The SAIL hasn't been written yet.

X(rdc) = EXTZ(mem[X(rs1c)+EXTZ(uimm)][7..0]);
----

<<<
[#insns-c_lhu,reftext="Load unsigned halfword, 16-bit encoding"]
==== c.lhu

Synopsis::

Load unsigned halfword, 16-bit encoding

Mnemonic::

c.lhu _rd'_, _uimm_(_rs1'_)

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x0, attr: ['C0'] },
    { bits:  3, name: 'rd\'' },
    { bits:  1, name: 'uimm[1]' },
    { bits:  1, name: 0x0 },
    { bits:  3, name: 'rs1\'' },
    { bits:  3, name: 0x1 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

The immediate offset is formed as follows:

[source,sail]
----
  uimm[31:2] = 0;
  uimm[1]    = encoding[5];
  uimm[0]    = 0;
----

Description::

This instruction [#norm:c-lhu_op]#loads a halfword from the memory address formed by adding _rs1'_ to the zero extended immediate _uimm_. The resulting halfword is zero extended to XLEN bits and is written to _rd'_.#

[NOTE]
====
_rd'_ and _rs1'_ are from the standard 8-register set x8-x15.
====

Prerequisites::

None
//32-bit equivalent:
//
//<<insns-lhu>>

Operation::

[source,sail]
--
//This is not SAIL, it's pseudocode. The SAIL hasn't been written yet.

X(rdc) = EXTZ(load_mem[X(rs1c)+EXTZ(uimm)][15..0]);
--

<<<
[#insns-c_lh,reftext="Load signed halfword, 16-bit encoding"]
==== c.lh

Synopsis::

Load signed halfword, 16-bit encoding

Mnemonic::

c.lh _rd'_, _uimm_(_rs1'_)

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x0, attr: ['C0'] },
    { bits:  3, name: 'rd\'' },
    { bits:  1, name: 'uimm[1]' },
    { bits:  1, name: 0x1 },
    { bits:  3, name: 'rs1\'' },
    { bits:  3, name: 0x1 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

The immediate offset is formed as follows:

[source,sail]
----
  uimm[31:2] = 0;
  uimm[1]    = encoding[5];
  uimm[0]    = 0;
----

Description::

This instruction [#norm:c-lh_op]#loads a halfword from the memory address formed by adding _rs1'_ to the zero extended immediate _uimm_. The resulting halfword is sign extended to XLEN bits and is written to _rd'_.#

[NOTE]
====
_rd'_ and _rs1'_ are from the standard 8-register set x8-x15.
====

Prerequisites::

None
//32-bit equivalent:
//
//<<insns-lh>>

Operation::

[source,sail]
----
//This is not SAIL, it's pseudocode. The SAIL hasn't been written yet.

X(rdc) = EXTS(load_mem[X(rs1c)+EXTZ(uimm)][15..0]);
----

<<<
[#insns-c_sb,reftext="Store byte, 16-bit encoding"]
==== c.sb

Synopsis::

Store byte, 16-bit encoding

Mnemonic::

c.sb _rs2'_, _uimm_(_rs1'_)

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x0, attr: ['C0'] },
    { bits:  3, name: 'rs2\'' },
    { bits:  2, name: 'uimm[0|1]' },
    { bits:  3, name: 'rs1\'' },
    { bits:  3, name: 0x2 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

The immediate offset is formed as follows:

[source,sail]
----
  uimm[31:2] = 0;
  uimm[1]    = encoding[5];
  uimm[0]    = encoding[6];
----

Description::

This instruction [#norm:c-sb_op]#stores the least significant byte of _rs2'_ to the memory address formed by adding _rs1'_ to the zero extended immediate _uimm_.#

[NOTE]
====
_rs1'_ and _rs2'_ are from the standard 8-register set x8-x15.
====

Prerequisites::

None
//
//32-bit equivalent:
//
//<<insns-sb>>

Operation::

[source,sail]
--
//This is not SAIL, it's pseudocode. The SAIL hasn't been written yet.

mem[X(rs1c)+EXTZ(uimm)][7..0] = X(rs2c)
--

<<<
[#insns-c_sh,reftext="Store halfword, 16-bit encoding"]
==== c.sh

Synopsis::

Store halfword, 16-bit encoding

Mnemonic::

c.sh _rs2'_, _uimm_(_rs1'_)

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x0, attr: ['C0'] },
    { bits:  3, name: 'rs2\'' },
    { bits:  1, name: 'uimm[1]' },
    { bits:  1, name: '0' },
    { bits:  3, name: 'rs1\'' },
    { bits:  3, name: 0x3 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

The immediate offset is formed as follows:

[source,sail]
----
  uimm[31:2] = 0;
  uimm[1]    = encoding[5];
  uimm[0]    = 0;
----

Description::

This instruction [#norm:c-sh_op]#stores the least significant halfword of _rs2'_ to the memory address formed by adding _rs1'_ to the zero extended immediate _uimm_.#

[NOTE]
====
_rs1'_ and _rs2'_ are from the standard 8-register set x8-x15.
====

Prerequisites::

None
//
//32-bit equivalent:
//
//<<insns-sh>>

Operation::
[source,sail]
----
//This is not SAIL, it's pseudocode. The SAIL hasn't been written yet.

mem[X(rs1c)+EXTZ(uimm)][15..0] = X(rs2c)
----

<<<
[#insns-c_zext_b,reftext="Zero extend byte, 16-bit encoding"]
==== c.zext.b

Synopsis::

Zero extend byte, 16-bit encoding

Mnemonic::

c.zext.b _rd'/rs1'_

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['C1'] },
    { bits:  3, name: 0x0, attr: ['C.ZEXT.B'] },
    { bits:  2, name: 0x3, attr: ['FUNCT2'] },
    { bits:  3, name: 'rd\'/rs1\'', attr: ['SRCDST'] },
    { bits:  3, name: 0x7 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

Description::

This instruction takes a single source/destination operand.
It [#norm:c-zext-b_op]#zero-extends the least-significant byte of the operand to XLEN bits by inserting zeros into all of
the bits more significant than 7.#

[NOTE]
====
_rd'/rs1'_ is from the standard 8-register set x8-x15.
====

Prerequisites::

None

32-bit equivalent:

[source,asm]
----
andi rd'/rs1', rd'/rs1', 0xff
----

[NOTE]
====
The SAIL module variable for _rd'/rs1'_ is called _rsdc_.
====

Operation::

[source,sail]
----
X(rsdc) = EXTZ(X(rsdc)[7..0]);
----

<<<
[#insns-c_sext_b,reftext="Sign extend byte, 16-bit encoding"]
==== c.sext.b

Synopsis::

Sign extend byte, 16-bit encoding

Mnemonic::

c.sext.b _rd'/rs1'_

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['C1'] },
    { bits:  3, name: 0x1, attr: ['C.SEXT.B'] },
    { bits:  2, name: 0x3, attr: ['FUNCT2'] },
    { bits:  3, name: 'rd\'/rs1\'', attr: ['SRCDST'] },
    { bits:  3, name: 0x7 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

Description::

This instruction takes a single source/destination operand.
It [#norm:c-sext-b_op]#sign-extends the least-significant byte in the operand to XLEN bits by copying the most-significant bit
in the byte (i.e., bit 7) to all of the more-significant bits.#

[NOTE]
====
_rd'/rs1'_ is from the standard 8-register set x8-x15.
====

Prerequisites::

Zbb is also required.
//
//32-bit equivalent:
//
//<<insns-sext_b>> from Zbb

[NOTE]

The SAIL module variable for _rd'/rs1'_ is called _rsdc_.

Operation::

[source,sail]
----
X(rsdc) = EXTS(X(rsdc)[7..0]);
----

<<<
[#insns-c_zext_h,reftext="Zero extend halfword, 16-bit encoding"]
==== c.zext.h

Synopsis::

Zero extend halfword, 16-bit encoding

Mnemonic::

c.zext.h _rd'/rs1'_

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['C1'] },
    { bits:  3, name: 0x2, attr: ['C.ZEXT.H'] },
    { bits:  2, name: 0x3, attr: ['FUNCT2'] },
    { bits:  3, name: 'rd\'/rs1\'', attr: ['SRCDST'] },
    { bits:  3, name: 0x7 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

Description::

This instruction takes a single source/destination operand.
It [#norm:c-zext-h_op]#zero-extends the least-significant halfword of the operand to XLEN bits by inserting zeros into all of
the bits more significant than 15.#

[NOTE]
====
_rd'/rs1'_ is from the standard 8-register set x8-x15.
====

Prerequisites::

Zbb is also required.
//
//32-bit equivalent:
//
//<<insns-zext_h>> from Zbb

[NOTE]
====
The SAIL module variable for _rd'/rs1'_ is called _rsdc_.
====

Operation::

[source,sail]
----
X(rsdc) = EXTZ(X(rsdc)[15..0]);
----

<<<
[#insns-c_sext_h,reftext="Sign extend halfword, 16-bit encoding"]
==== c.sext.h

Synopsis::

Sign extend halfword, 16-bit encoding

Mnemonic::

c.sext.h _rd'/rs1'_

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['C1'] },
    { bits:  3, name: 0x3, attr: ['C.SEXT.H'] },
    { bits:  2, name: 0x3, attr: ['FUNCT2'] },
    { bits:  3, name: 'rd\'/rs1\'', attr: ['SRCDST'] },
    { bits:  3, name: 0x7 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

Description::

This instruction takes a single source/destination operand.
It [#norm:c-sext-h_op]#sign-extends the least-significant halfword in the operand to XLEN bits by copying the most-significant bit
in the halfword (i.e., bit 15) to all of the more-significant bits.#

[NOTE]
====
_rd'/rs1'_ is from the standard 8-register set x8-x15.
====

Prerequisites::

Zbb is also required.
//
//32-bit equivalent:
//
//<<insns-sext_h>> from Zbb

[NOTE]
====
The SAIL module variable for _rd'/rs1'_ is called _rsdc_.
====

Operation::

[source,sail]
----
X(rsdc) = EXTS(X(rsdc)[15..0]);
----

<<<
[#insns-c_zext_w,reftext="Zero extend word, 16-bit encoding"]
==== c.zext.w

Synopsis::

Zero extend word, 16-bit encoding

Mnemonic::

c.zext.w _rd'/rs1'_

Encoding (RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['C1'] },
    { bits:  3, name: 0x4, attr: ['C.ZEXT.W'] },
    { bits:  2, name: 0x3, attr: ['FUNCT2'] },
    { bits:  3, name: 'rd\'/rs1\'', attr: ['SRCDST'] },
    { bits:  3, name: 0x7 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

Description::

This instruction takes a single source/destination operand.
It [#norm:c-zext-w_op]#zero-extends the least-significant word of the operand to XLEN bits by inserting zeros into all of
the bits more significant than 31.#

[NOTE]
====
_rd'/rs1'_ is from the standard 8-register set x8-x15.
====

Prerequisites::

Zba is also required.

32-bit equivalent:

[source,asm]
----
add.uw rd'/rs1', rd'/rs1', zero
----

[NOTE]
====
The SAIL module variable for _rd'/rs1'_ is called _rsdc_.
====

Operation::

[source,sail]
----
X(rsdc) = EXTZ(X(rsdc)[31..0]);
----

<<<
[#insns-c_not,reftext="Bitwise not, 16-bit encoding"]
==== c.not

Synopsis::

Bitwise not, 16-bit encoding

Mnemonic::

c.not _rd'/rs1'_

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['C1'] },
    { bits:  3, name: 0x5, attr: ['C.NOT'] },
    { bits:  2, name: 0x3, attr: ['FUNCT2'] },
    { bits:  3, name: 'rd\'/rs1\'', attr: ['SRCDST'] },
    { bits:  3, name: 0x7 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

Description::

This instruction [#norm:c-not_op]#takes the one's complement of _rd'/rs1'_ and writes the result to the same register.#

[NOTE]
====
rd'/rs1' is from the standard 8-register set x8-x15.
====

Prerequisites::

None

32-bit equivalent:

[source,asm]
----
xori rd'/rs1', rd'/rs1', -1
----

[NOTE]
====
The SAIL module variable for _rd'/rs1'_ is called _rsdc_.
====

Operation::

[source,sail]
----
X(rsdc) = X(rsdc) XOR -1;
----

<<<
[#insns-c_mul,reftext="Multiply, 16-bit encoding"]
==== c.mul

Synopsis::

Multiply, 16-bit encoding

Mnemonic::

c.mul _rsd'_, _rs2'_

Encoding (RV32, RV64):

[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x1, attr: ['C1'] },
    { bits:  3, name: 'rs2\'', attr: ['SRC2']  },
    { bits:  2, name: 0x2, attr: ['FUNCT2'] },
    { bits:  3, name: 'rd\'/rs1\'', attr: ['SRCDST'] },
    { bits:  3, name: 0x7 },
    { bits:  3, name: 0x4, attr: ['FUNCT3'] },
],config:{bits:16}}
....

Description::

This instruction [#norm:c-mul_op]#multiplies XLEN bits of the source operands from _rsd'_ and _rs2'_ and writes the lowest XLEN bits of the result to _rsd'_.#

[NOTE]
====
_rd'/rs1'_ and _rs2'_ are from the standard 8-register set x8-x15.
====

Prerequisites::

M or Zmmul must be configured.
//
//32-bit equivalent:
//
//<<insns-mul>>

[NOTE]
====
The SAIL module variable for _rd'/rs1'_ is called _rsdc_, and for _rs2'_ is called _rs2c_.
====

Operation::

[source,sail]
----
let result_wide = to_bits(2 * sizeof(xlen), signed(X(rsdc)) * signed(X(rs2c)));
X(rsdc) = result_wide[(sizeof(xlen) - 1) .. 0];
----

<<<

//
