[[ext:zcd]]
=== ext:zcd[] Double-Precision Floating-Point Compressed Instructions Extension

[NOTE]
====
Double-precision loads and stores represent a significant fraction of static
instructions in programs compiled for the ILP32D and LP64D calling conventions,
due in large part to callee-saved register spills and fills.
====

==== Stack-Pointer-Based Loads and Stores

[#norm:c-fldsp_op]#C.FLDSP is an RV32DC/RV64DC-only instruction that loads a
double-precision floating-point value from memory into floating-point
register _rd_. It computes its effective address by adding the
_zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It
expands to `fld rd, offset(x2)`.#

[#norm:c-fsdwsp_op]#C.FSDSP is an RV32DC/RV64DC-only instruction that stores a
double-precision floating-point value in floating-point register _rs2_
to memory. It computes an effective address by adding the
_zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It
expands to `fsd rs2, offset(x2)`.#

==== Register-Based Loads and Stores

These instructions encode their data source or destination as
described in <<zcf-registers>>.

[#norm:c-fld_op]#C.FLD is an RV32DC/RV64DC-only instruction that loads a double-precision
floating-point value from memory into floating-point register
`_rd′_`. It computes an effective address by adding the
_zero_-extended offset, scaled by 8, to the base address in register
`_rs1′_`. It expands to
`fld rd′, offset(rs1′)`.#

[#norm:c-fsd_op]#C.FSD is an RV32DC/RV64DC-only instruction that stores a
double-precision floating-point value in floating-point register
`_rs2′_` to memory. It computes an effective address by
adding the _zero_-extended offset, scaled by 8, to the base address in
register `_rs1′_`. It expands to
`fsd rs2′, offset(rs1′)`.#

//
