[[ext:zcd]]
=== ext:zcd[] Double-Precision Floating-Point Compressed Instructions Extension

The ext:zcd[] extension adds compressed double-precision floating-point
load and store instructions.

[NOTE]
====
Double-precision loads and stores represent a significant fraction of static
instructions in programs compiled for the ILP32D and LP64D calling conventions,
due in large part to callee-saved register spills and fills.
====

==== Stack-Pointer-Based Loads and Stores

[#norm:c-fldsp_op]#insn:c.fldsp[] is an RV32DC/RV64DC-only instruction that loads a
double-precision floating-point value from memory into floating-point
register _rd_. It computes its effective address by adding the
_zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It
expands to insn:fld[rd,offset(x2)].#

[#norm:c-fsdwsp_op]#insn:c.fsdsp[] is an RV32DC/RV64DC-only instruction that stores a
double-precision floating-point value in floating-point register _rs2_
to memory. It computes an effective address by adding the
_zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It
expands to insn:fsd[rs2,offset(x2)].#

==== Register-Based Loads and Stores

These instructions encode their data source or destination as
described in <<zcf-registers>>.

[#norm:c-fld_op]#insn:c.fld[] is an RV32DC/RV64DC-only instruction that loads a double-precision
floating-point value from memory into floating-point register
`_rd′_`. It computes an effective address by adding the
_zero_-extended offset, scaled by 8, to the base address in register
`_rs1′_`. It expands to
insn:fld[rd′,offset(rs1′)].#

[#norm:c-fsd_op]#insn:c.fsd[] is an RV32DC/RV64DC-only instruction that stores a
double-precision floating-point value in floating-point register
`_rs2′_` to memory. It computes an effective address by
adding the _zero_-extended offset, scaled by 8, to the base address in
register `_rs1′_`. It expands to
insn:fsd[rs2′,offset(rs1′)].#

//
