[[ext:zcf]]
=== ext:zcf[] Single-Precision Floating-Point Compressed Instructions Extension

The ext:zcf[] extension adds compressed single-precision floating-point
load and store instructions.
It is an XLEN=32-only extension.

[NOTE]
====
Single-precision loads and stores are not a significant source of static or
dynamic compression for programs compiled for the LP64D and ILP32D calling
conventions.
However, for microcontrollers that only provide hardware single-precision
floating-point units and whose programs use the ILP32F calling convention, the
single-precision loads and stores are used at least as frequently as
double-precision loads and stores are used in LP64D and ILP32D.
====

==== Stack-Pointer-Based Loads and Stores

[#norm:c-flwsp_op]#C.FLWSP is an RV32FC-only instruction that loads a single-precision
floating-point value from memory into floating-point register _rd_. It
computes its effective address by adding the _zero_-extended offset,
scaled by 4, to the stack pointer, `x2`. It expands to
`flw rd, offset(x2)`.
C.FLWSP uses the <<rvc-form,CI format>>.#

[#norm:c-fswsp_op]#C.FSWSP is an RV32FC-only instruction that stores a single-precision
floating-point value in floating-point register _rs2_ to memory. It
computes an effective address by adding the _zero_-extended offset,
scaled by 4, to the stack pointer, `x2`. It expands to
`fsw rs2, offset(x2)`.#

==== Register-Based Loads and Stores

[#norm:Zc_fp_regs]#Compressed register-based floating-point loads and stores use the
CL and CS formats, respectively, with the eight registers mapping to `f8` to `f15`.#

[NOTE]
====
_The standard RISC-V calling convention maps the most frequently used
floating-point registers to registers `f8` to `f15`, which allows the
same register decompression decoding as for integer register numbers._
====


These instructions encode their data source or destination as
described in the following table.

[[zcf-registers]]
.Registers specified by the three-bit _rs1_{prime}, _rs2_{prime}, and _rd_{prime} fields of the CIW, CL, CS, CA, and CB formats.
//[cols="20%,10%,10%,10%,10%,10%,10%,10%,10%"]
[float="center",align="center",cols="1a, 1a",frame="none",grid="none"]
|===
|
[%autowidth,cols="<",frame="none",grid="none",options="noheader"]
!===
!ext:zcf[] Register Number
!Floating-Point Register Number
!Floating-Point Register ABI Name
!===
|

[%autowidth,cols="^,^,^,^,^,^,^,^",options="noheader"]
!===
!`000` !`001` !`010` !`011` !`100` !`101` !`110` !`111`
!`f8` !`f9` !`f10` !`f11` !`f12` !`f13`!`f14` !`f15`
!`fs0` !`fs1` !`fa0` !`fa1` !`fa2`!`fa3` !`fa4` !`fa5`
!===
|===

[#norm:c-flw_op]#C.FLW is an RV32FC-only instruction that loads a single-precision
floating-point value from memory into floating-point register
`_rd′_`. It computes an effective address by adding the
_zero_-extended offset, scaled by 4, to the base address in register
`_rs1′_`. It expands to
`flw rd′, offset(rs1′)`.#

[#norm:c-fsw_op]#C.FSW is an RV32FC-only instruction that stores a single-precision
floating-point value in floating-point register `_rs2′_` to
memory. It computes an effective address by adding the _zero_-extended
offset, scaled by 4, to the base address in register
`_rs1′_`. It expands to
`fsw rs2′, offset(rs1′)`.#

//
