[[ext:zclsd]]
=== ext:zclsd[] Extension for Compressed Load/Store Pair Instructions

The ext:zclsd[] extension provides compressed load/store pair instructions for
RV32, reusing the existing RV64 doubleword load/store instruction encodings.

ext:zclsd[] depends on ext:zilsd[] and ext:zca[]. It has overlapping encodings with ext:zcf[] and is thus incompatible with ext:zcf[].

==== Use of `x0` as operand

[#norm:Zilsd_c-ldsp_x0]#For insn:c.ldsp[], usage of `x0` as the destination is reserved.#

If using `x0` as `src` of insn:c.sdsp[], the entire 64-bit operand is zero, i.e., register `x1` is not accessed.

insn:c.ld[] and insn:c.sd[] instructions can only use `x8`-`x15`.

==== Exception Handling

For the purposes of RVWMO and exception handling, insn:c.ld[], insn:c.ldsp[], insn:c.sd[] and insn:c.sdsp[] instructions are
considered to be misaligned loads and stores, with one additional constraint:
a insn:c.ld[], insn:c.ldsp[], insn:c.sd[] or insn:c.sdsp[] instruction whose effective address is a multiple of 4 gives rise
to two 4-byte memory operations.

ext:zclsd[] adds the following RV32-only instructions:

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|yes
|no
|insn:c.ldsp[rd,offset(sp)]
|<<#insns-cldsp>>

|yes
|no
|insn:c.sdsp[rs2,offset(sp)]
|<<#insns-csdsp>>

|yes
|no
|insn:c.ld[rd',offset(rs1')]
|<<#insns-cld>>

|yes
|no
|insn:c.sd[rs2',offset(rs1')]
|<<#insns-csd>>

|===

<<<

[#insns-cldsp,reftext="Stack-pointer based load doubleword to register pair, 16-bit encoding"]
===== insn:c.ldsp[]

Synopsis::
Stack-pointer based load doubleword to even/odd register pair, 16-bit encoding

Mnemonic::
insn:c.ldsp[rd,offset(sp)]

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x2,      type: 8, attr: ['C2']},
  {bits: 5, name: 'imm',    type: 3, attr: ['offset[4:3|8:6]']},
  {bits: 5, name: 'rd',     type: 2, attr: ['dest≠0, dest[0]=0']},
  {bits: 1, name: 'imm',    type: 3, attr: ['offset[5]']},
  {bits: 3, name: 0x3,      type: 8, attr: ['C.LDSP']},
], config: {bits: 16}}
....

Description::
[[norm:Zilsd_c-ldsp_op]]
Loads stack-pointer relative 64-bit value into registers `rd'` and `rd'+1`. It computes its effective address by adding the zero-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to insn:ld[rd,offset(x2)]. insn:c.ldsp[] is only valid when _rd_{ne}x0; the code points with _rd_=x0 are reserved.

Included in: extlink:zclsd[]

<<<

[#insns-csdsp,reftext="Stack-pointer based store doubleword from register pair, 16-bit encoding"]
===== insn:c.sdsp[]

Synopsis::
Stack-pointer based store doubleword from even/odd register pair, 16-bit encoding

Mnemonic::
insn:c.sdsp[rs2,offset(sp)]

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x2,      type: 8, attr: ['C2']},
  {bits: 5, name: 'rs2',    type: 4, attr: ['src, src[0]=0']},
  {bits: 6, name: 'imm',    type: 3, attr: ['offset[5:3|8:6]']},
  {bits: 3, name: 0x7,      type: 8, attr: ['C.SDSP']},
], config: {bits: 16}}
....

Description::
[[norm:Zilsd_c-sdsp_op]]
Stores a stack-pointer relative 64-bit value from registers `rs2'` and `rs2'+1`. It computes an effective address by adding the _zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to insn:sd[rs2,offset(x2)].

Included in: extlink:zclsd[]

<<<

[#insns-cld,reftext="Load doubleword to register pair, 16-bit encoding"]
===== c.ld

Synopsis::
Load doubleword to even/odd register pair, 16-bit encoding

Mnemonic::
insn:c.ld[rd',offset(rs1')]

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x0,       type: 8, attr: ['C0']},
  {bits: 3, name: 'rd`',     type: 2, attr: ['dest, dest[0]=0']},
  {bits: 2, name: 'imm',     type: 3, attr: ['offset[7:6]']},
  {bits: 3, name: 'rs1`',    type: 4, attr: ['base']},
  {bits: 3, name: 'imm',     type: 3, attr: ['offset[5:3]']},
  {bits: 3, name: 0x3,       type: 8, attr: ['C.LD']},
], config: {bits: 16}}
....

Description::
[[norm:Zilsd_c-ld_op]]
Loads a 64-bit value into registers `rd'` and `rd'+1`.
It computes an effective address by adding the zero-extended offset, scaled by 8, to the base address in register rs1'.

Included in: extlink:zclsd[]

<<<

[#insns-csd,reftext="Store doubleword from register pair, 16-bit encoding"]
===== insn:c.sd[]

Synopsis::
Store doubleword from even/odd register pair, 16-bit encoding

Mnemonic::
insn:c.sd[rs2',offset(rs1')]

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x0,      type: 8, attr: ['C0']},
  {bits: 3, name: 'rs2`',   type: 4, attr: ['src, src[0]=0']},
  {bits: 2, name: 'imm',    type: 3, attr: ['offset[7:6]']},
  {bits: 3, name: 'rs1`',   type: 4, attr: ['base']},
  {bits: 3, name: 'imm',    type: 3, attr: ['offset[5:3]']},
  {bits: 3, name: 0x7,      type: 8, attr: ['C.SD']},
], config: {bits: 16}}
....

Description::
[[norm:Zilsd_c-sd_op]]
Stores a 64-bit value from registers `rs2'` and `rs2'+1`.
It computes an effective address by adding the zero-extended offset, scaled by 8, to the base address in register rs1'.
It expands to insn:sd[rs2',offset(rs1')].

Included in: extlink:zclsd[]

//
