[[ext:zcmop]]
=== ext:zcmop[] Compressed May-Be-Operations Extension

[#norm:Zcmop_op]#This section defines the ext:zcmop[] extension, which defines eight 16-bit MOP
instructions named insn:c.mop.n[], where N is an odd integer between 1 and
15, inclusive.#  [#norm:Zcmop_enc]#insn:c.mop.n[] is encoded in the reserved encoding space
corresponding to insn:c.lui[xN,0], as shown in <<norm:c-mop_enc>>.#
[#norm:Zcmop_instr_write]#Unlike the MOPs defined in the extlink:zimop[] extension, the insn:c.mop.n[] instructions
are defined to _not_ write any register.#
Their encoding allows future extensions to define them to read register
`xN`.

The ext:zcmop[] extension depends upon the ext:zca[] extension.

include::images/wavedrom/c-mop.edn[]
[[c-mop]]

NOTE: Very few suitable 16-bit encoding spaces exist.  This space was chosen
because it already has unusual behavior with respect to the `rd`/`rs1`
field--it encodes insn:c.addi16sp[] when the field contains `x2`--and is
therefore of lower value for most purposes.

[[norm:c-mop_enc]]
.C.MOP.N instruction encoding.

|===
|Mnemonic | Encoding           | Redefinable to read register

|C.MOP.1  | `0110000010000001` | `x1`
|C.MOP.3  | `0110000110000001` | `x3`
|C.MOP.5  | `0110001010000001` | `x5`
|C.MOP.7  | `0110001110000001` | `x7`
|C.MOP.9  | `0110010010000001` | `x9`
|C.MOP.11 | `0110010110000001` | `x11`
|C.MOP.13 | `0110011010000001` | `x13`
|C.MOP.15 | `0110011110000001` | `x15`
|===

NOTE: The recommended assembly syntax for insn:c.mop.n[] is simply the nullary
insn:c.mop.n[].  The possibly accessed register is implicitly `xN`.

NOTE: The expectation is that each ext:zcmop[] instruction is equivalent to some
ext:zimop[] instruction, but the choice of expansion (if any) is left to the
extension that redefines the MOP.
Note, a ext:zcmop[] instruction that does not write a value can expand into a write
to `x0`.

//
