[[zf]]
== Scalar Floating-Point Extensions

NOTE: This chapter is currently being restructured.
Its contents are normative, but the presentation might appear disjoint.

This chapter describes the scalar floating-point extensions.
The `F` extension adds floating-point registers and instructions for
computation on single-precision floating-point values.
The `D` and `Q` extensions widen those registers to hold double- and
quad-precision floating-point values, respectively, and add instructions
for computation on those formats.
Several additional extensions with the `Zf` and `Zd` prefixes provide
additional computational instructions.

The `Zfinx` and `Zdinx` extensions add computational instructions analogous to
those in the `F` and `D` extensions, but they instead operate on
floating-point numbers in the `x` registers.
These extensions, intended for lower-cost systems, are incompatible with the
`F` and `D` extensions.

include::f-st-ext.adoc[]
include::d-st-ext.adoc[]
include::q-st-ext.adoc[]
include::zfh.adoc[]
include::zfa.adoc[]
include::zfbfmin.adoc[]
include::zfinx.adoc[]
