[[zf]]
== Scalar Floating-Point Extensions

NOTE: This chapter is currently being restructured.
Its contents are normative, but the presentation might appear disjoint.

This chapter describes the scalar floating-point extensions.
The <<single-float,`F`>> extension adds floating-point registers and
instructions for computation on single-precision floating-point values.
The <<chap:d,`D`>> and <<quad-float,`Q`>> extensions widen those registers to
hold double- and quad-precision floating-point values, respectively, and add
instructions for computation on those formats.
Several additional extensions with the `Zf` and `Zd` prefixes provide
additional computational instructions.

The <<sec:zfinx,`Zfinx`>> and <<sec:zdinx,`Zdinx`>> extensions add
computational instructions analogous to those in the `F` and `D` extensions,
but they instead operate on floating-point numbers in the `x` registers.
These extensions, intended for lower-cost systems, are incompatible with the
`F` and `D` extensions.

:sectnums!:
[discrete]
=== Floating-Point Formats
:sectnums:

There are several floating-point formats in this specification. Some of those
formats are specified in the <<ieee754-2008, IEEE 754-2008 arithmetic standard>>.
<<fp-format-table>> is the summary of the floating-point formats in this
specification.

[[fp-format-table]]
.Floating-point formats.
[%autowidth,float="center",align="center",cols="^,<,<,>",options="header"]
|===
|Short Name |IEEE 754-2008 Name |Synonym |Size
|FP16 |binary16 |half-precision |16 bits
|FP32 |binary32 |single-precision |32 bits
|FP64 |binary64 |double-precision |64 bits
|FP128 |binary128 |quad-precision |128 bits
|BF16 |_not applicable_ |bfloat16 |16 bits
|E4M3 |_not applicable_ | |8 bits
|E5M2 |_not applicable_ | |8 bits
|===

While the BF16 cite:[bfloat16], E4M3 and E5M2 formats are not defined in IEEE
754-2008, the structure and operations of these formats are compatible with the
standard. E4M3 and E5M2 are specified by the Open Compute Project (OCP) as the
OCP FP8 (OFP8) formats cite:[ocp-fp8].

include::f-st-ext.adoc[]
include::d-st-ext.adoc[]
include::q-st-ext.adoc[]
include::zfh.adoc[]
include::zfhmin.adoc[]
include::zfa.adoc[]
include::zfbfmin.adoc[]
include::zfinx.adoc[]
