[[zf]]
== Scalar Floating-Point Extensions

NOTE: This chapter is currently being restructured.
Its contents are normative, but the presentation might appear disjoint.

This chapter describes the scalar floating-point extensions.
The extlink:f[] extension adds floating-point registers and
instructions for computation on single-precision floating-point values.
The extlink:d[] and extlink:q[] extensions widen those registers to
hold double- and quad-precision floating-point values, respectively, and add
instructions for computation on those formats.
Several additional extensions with the ext:zf[] prefix provide
additional computational instructions.

The extlink:zfinx[] and extlink:zdinx[] extensions add computational
instructions analogous to those in the ext:f[] and ext:d[] extensions, but they
instead operate on floating-point numbers in the `x` registers. These extensions,
intended for lower-cost systems, are incompatible with the ext:f[] and ext:d[]
extensions.

:sectnums!:
[discrete]
=== Floating-Point Formats
:sectnums:

There are several floating-point formats in this specification. Some of those
formats are specified in the <<ieee754-2008, IEEE 754-2008 arithmetic standard>>.
<<fp-format-table>> is the summary of the floating-point formats in this
specification.

[[fp-format-table]]
.Floating-point formats.
[%autowidth,float="center",align="center",cols="^,<,<,>",options="header"]
|===
|Short Name |IEEE 754-2008 Name |Synonym |Size
|FP16 |binary16 |half-precision |16 bits
|FP32 |binary32 |single-precision |32 bits
|FP64 |binary64 |double-precision |64 bits
|FP128 |binary128 |quad-precision |128 bits
|BF16 |_not applicable_ |bfloat16 |16 bits
|E4M3 |_not applicable_ | |8 bits
|E5M2 |_not applicable_ | |8 bits
|===

While the BF16 cite:[bfloat16], E4M3, and E5M2 formats are not defined in IEEE
754-2008, the structure and operations of these formats are compatible with the
standard. E4M3 and E5M2 are specified by the Open Compute Project (OCP) as the
OCP FP8 (OFP8) formats cite:[ocp-fp8].

:sectnums!:
[discrete]
=== Floating-Point Register State
:sectnums:

The ext:f[], ext:d[], and ext:q[] standard extensions use 32 floating-point
registers, `f0`-`f31`, and a floating-point CSR, csr:fcsr[], that contains the
operating mode and exception status of the floating-point unit. The
floating-point register state is shown in <<fprs>>.
We use the term FLEN to describe the width of the floating-point registers. FLEN
can be 32, 64, or 128 depending on which of the ext:f[], ext:d[], and ext:q[]
extensions are supported.

[[fprs]]
.RISC-V floating-point register state.
[cols="<,^,>",options="header",width="50%",align="center",grid="rows"]
|===
| [.small]#FLEN-1#| >| [.small]#0#
3+^| [.small]#f0#
3+^| [.small]#f1#
3+^| [.small]#f2#
3+^| [.small]#f3#
3+^| [.small]#f4#
3+^| [.small]#f5#
3+^| [.small]#f6#
3+^| [.small]#f7#
3+^| [.small]#f8#
3+^| [.small]#f9#
3+^| [.small]#f10#
3+^| [.small]#f11#
3+^| [.small]#f12#
3+^| [.small]#f13#
3+^| [.small]#f14#
3+^| [.small]#f15#
3+^| [.small]#f16#
3+^| [.small]#f17#
3+^| [.small]#f18#
3+^| [.small]#f19#
3+^| [.small]#f20#
3+^| [.small]#f21#
3+^| [.small]#f22#
3+^| [.small]#f23#
3+^| [.small]#f24#
3+^| [.small]#f25#
3+^| [.small]#f26#
3+^| [.small]#f27#
3+^| [.small]#f28#
3+^| [.small]#f29#
3+^| [.small]#f30#
3+^| [.small]#f31#
3+^| [.small]#FLEN#
| [.small]#31#| >| [.small]#0#
3+^|  [.small]#fcsr#
3+^| [.small]#32#
|===

Most floating-point instructions operate on values in the floating-point
register file. Floating-point load and store instructions transfer
floating-point values between registers and memory. Instructions to transfer
floating-point values to and from the integer register file are also provided.

[NOTE]
====
For simple and low-cost implementations, the ext:zfinx[], ext:zdinx[], and
ext:zhinx[] extensions provide computational instructions analogous to those in
the ext:f[], ext:d[], and ext:zfh[] extensions that operate on the `x` registers
instead.
====

The details of csr:fcsr[] are described in <<sec:fcsr>>.

:sectnums!:
[discrete]
=== NaN Generation and Propagation
:sectnums:

[[norm:canonical_NaN]]
(((NaN, canonical))) (((NaN, generation))) (((NaN, propagation)))
Except when otherwise stated, if the result of a floating-point operation is
NaN, it is _the canonical NaN_.

[NOTE]
====
The canonical NaN as defined here is unrelated to the definition of canonical
encodings in IEEE 754-2008 for decimal interchange formats.
====
'''
[NOTE]
====
Extensions introducing floating-point formats compatible with IEEE 754 shall
define the canonical NaN for each format.
====
'''
[NOTE]
====
We considered propagating NaN payloads, as recommended by IEEE 754-2008, but
this decision would have increased hardware cost. Moreover, since this feature
is optional in IEEE 754-2008, it cannot be used in portable code.

Implementers are free to provide a NaN payload propagation scheme as a
nonstandard extension enabled by a nonstandard operating mode. However, the
canonical NaN scheme described above must always be supported and should be the
default mode.
====
'''
[NOTE]
====
We require implementations to return the standard-mandated default values in the
case of exceptional conditions, without any further intervention on the part of
user-level software (unlike the Alpha ISA floating-point trap barriers). We
believe full hardware handling of exceptional cases will become more common, and
so wish to avoid complicating the user-level ISA to optimize other approaches.
Implementations can always trap to machine-mode software handlers to provide
exceptional default values.
====

[[nanboxing]]
:sectnums!:
[discrete]
=== NaN Boxing of Narrower Values
:sectnums:

[[norm:fp_nan-boxing]]
When multiple floating-point precisions are supported, then valid values of
narrower _n_-bit types, _n_<FLEN, are represented in the lower _n_ bits of an
FLEN-bit NaN value, in a process termed _NaN-boxing_. The upper bits of a valid
NaN-boxed value must be all 1s. Valid NaN-boxed _n_-bit values therefore appear
as negative quiet NaNs (qNaNs) when viewed as any wider _m_-bit value,
_n_ < _m_ {le} FLEN. Any operation that writes a narrower result to an `f`
register must write all 1s to the uppermost FLEN-_n_ bits to yield a legal
NaN-boxed value.

[NOTE]
====
Software might not know the current type of data stored in a floating-point
register but has to be able to save and restore the register values, hence the
result of using wider operations to transfer narrower values has to be defined.
A common case is for callee-saved registers, but a standard convention is also
desirable for features including variadic functions, user-level threading
libraries, virtual machine migration, and debugging.
====

Floating-point _n_-bit transfer operations move external values held in the
IEEE 754-2008 formats into and out of the `f` registers, and comprise
floating-point loads and stores (insn:fl*[] and insn:fs*[]) and floating-point
move instructions (insn:fmv.\*.x[] and insn:fmv.x.*[]).
[#norm:FP_transfer_instrs_narrow_transfer_in]#A narrower _n_-bit transfer,
_n_<FLEN, into the `f` registers will create a valid NaN-boxed value#.
[#norm:FP_transfer_instrs_narrow_transfer_out]#A narrower _n_-bit transfer out
of the floating-point registers will transfer the lower _n_ bits of the register
ignoring the upper FLEN-_n_ bits#.

[[norm:FP_nontransfer_instrs_improper_nan-boxed_input]]
Apart from transfer operations described in the previous paragraph, all other
floating-point operations on narrower __n__-bit operations, _n_<FLEN, check if
the input operands are correctly NaN-boxed, i.e., all upper FLEN-_n_ bits are 1.
If so, the _n_ least-significant bits of the input are used as the input value,
otherwise the input value is treated as an _n_-bit canonical NaN.

The NaN-boxing scheme can be applied recursively when an implementation supports
more than two precisions. For instance, with ext:f[], ext:d[], and ext:zfh[],
a register may hold a half-precision value to be NaN-boxed inside a
single-precision value which is itself NaN-boxed inside a double-precision
value.

[NOTE]
====
Earlier versions of the specification did not define the behavior of feeding the
results of narrower or wider operands into an operation, except to require that
wider saves and restores would preserve the value of a narrower operand. The new
definition removes this implementation-specific behavior, while still
accommodating both non-recoded and recoded implementations of the floating-point
unit. The new definition also helps catch software errors by propagating NaNs if
values are used incorrectly.

Non-recoded implementations unpack and pack the operands to the IEEE 754-2008
format on the input and output of every floating-point operation. The NaN-boxing
cost to a non-recoded implementation is primarily in checking if the upper bits
of a narrower operation represent a legal NaN-boxed value, and in writing all 1s
to the upper bits of a result.

Recoded implementations use a more convenient internal format to represent
floating-point values, with an added exponent bit to allow all values to be held
normalized. The cost to the recoded implementation is primarily the extra
tagging needed to track the internal types and sign bits, but this can be done
without adding new state bits by recoding NaNs internally in the exponent field.
Small modifications are needed to the pipelines used to transfer values in and
out of the recoded format, but the datapath and latency costs are minimal. The
recoding process has to handle shifting of input subnormal values for wide
operands in any case, and extracting the NaN-boxed value is a similar process to
normalization except for skipping over leading-1 bits instead of skipping over
leading-0 bits, allowing the datapath multiplexing to be shared.
====

include::f-st-ext.adoc[]
include::d-st-ext.adoc[]
include::q-st-ext.adoc[]
include::zfh.adoc[]
include::zfhmin.adoc[]
include::zfa.adoc[]
include::zfbfmin.adoc[]
include::zfinx.adoc[]
