[[zf]]
== Scalar Floating-Point Extensions

NOTE: This chapter is currently being restructured.
Its contents are normative, but the presentation might appear disjoint.

This chapter describes the scalar floating-point extensions.
The extlink:f[] extension adds floating-point registers and
instructions for computation on single-precision floating-point values.
The extlink:d[] and extlink:q[] extensions widen those registers to
hold double- and quad-precision floating-point values, respectively, and add
instructions for computation on those formats.
Several additional extensions with the ext:zf[] prefix provide
additional computational instructions.

The extlink:zfinx[] and extlink:zdinx[] extensions add computational
instructions analogous to those in the ext:f[] and ext:d[] extensions, but they
instead operate on floating-point numbers in the `x` registers. These extensions,
intended for lower-cost systems, are incompatible with the ext:f[] and ext:d[]
extensions.

:sectnums!:
[discrete]
=== Floating-Point Formats
:sectnums:

There are several floating-point formats in this specification. Some of those
formats are specified in the <<ieee754-2008, IEEE 754-2008 arithmetic standard>>.
<<fp-format-table>> is the summary of the floating-point formats in this
specification.

[[fp-format-table]]
.Floating-point formats.
[%autowidth,float="center",align="center",cols="^,<,<,>",options="header"]
|===
|Short Name |IEEE 754-2008 Name |Synonym |Size
|FP16 |binary16 |half-precision |16 bits
|FP32 |binary32 |single-precision |32 bits
|FP64 |binary64 |double-precision |64 bits
|FP128 |binary128 |quad-precision |128 bits
|BF16 |_not applicable_ |bfloat16 |16 bits
|E4M3 |_not applicable_ | |8 bits
|E5M2 |_not applicable_ | |8 bits
|===

While the BF16 cite:[bfloat16], E4M3 and E5M2 formats are not defined in IEEE
754-2008, the structure and operations of these formats are compatible with the
standard. E4M3 and E5M2 are specified by the Open Compute Project (OCP) as the
OCP FP8 (OFP8) formats cite:[ocp-fp8].

:sectnums!:
[discrete]
=== Floating-Point Register State
:sectnums:

The ext:f[], ext:d[], and ext:q[] standard extensions use 32 floating-point
registers, `f0`-`f31`, and a floating-point CSR, csr:fcsr[], that contains the
operating mode and exception status of the floating-point unit. The
floating-point register state is shown in <<fprs>>.
We use the term FLEN to describe the width of the floating-point registers. FLEN
can be 32, 64, or 128 depending on which of the ext:f[], ext:d[], and ext:q[]
extensions are supported.

[[fprs]]
.RISC-V floating-point register state.
[cols="<,^,>",options="header",width="50%",align="center",grid="rows"]
|===
| [.small]#FLEN-1#| >| [.small]#0#
3+^| [.small]#f0#
3+^| [.small]#f1#
3+^| [.small]#f2#
3+^| [.small]#f3#
3+^| [.small]#f4#
3+^| [.small]#f5#
3+^| [.small]#f6#
3+^| [.small]#f7#
3+^| [.small]#f8#
3+^| [.small]#f9#
3+^| [.small]#f10#
3+^| [.small]#f11#
3+^| [.small]#f12#
3+^| [.small]#f13#
3+^| [.small]#f14#
3+^| [.small]#f15#
3+^| [.small]#f16#
3+^| [.small]#f17#
3+^| [.small]#f18#
3+^| [.small]#f19#
3+^| [.small]#f20#
3+^| [.small]#f21#
3+^| [.small]#f22#
3+^| [.small]#f23#
3+^| [.small]#f24#
3+^| [.small]#f25#
3+^| [.small]#f26#
3+^| [.small]#f27#
3+^| [.small]#f28#
3+^| [.small]#f29#
3+^| [.small]#f30#
3+^| [.small]#f31#
3+^| [.small]#FLEN#
| [.small]#31#| >| [.small]#0#
3+^|  [.small]#fcsr#
3+^| [.small]#32#
|===

Most floating-point instructions operate on values in the floating-point
register file. Floating-point load and store instructions transfer
floating-point values between registers and memory. Instructions to transfer
floating-point values to and from the integer register file are also provided.

[NOTE]
====
For simple and low-cost implementations, the ext:zfinx[], ext:zdinx[], and
ext:zhinx[] extensions provide computational instructions analogous to those in
the ext:f[], ext:d[], and ext:zfh[] extensions that operate on the `x` registers
instead.
====

The details of csr:fcsr[] are described in <<sec:fcsr>>.

include::f-st-ext.adoc[]
include::d-st-ext.adoc[]
include::q-st-ext.adoc[]
include::zfh.adoc[]
include::zfhmin.adoc[]
include::zfa.adoc[]
include::zfbfmin.adoc[]
include::zfinx.adoc[]
