[[ext:zfa]]
=== ext:zfa[] Extension for Additional Floating-Point Instructions

This chapter describes the ext:zfa[] standard extension, which adds
instructions for immediate loads, IEEE 754-2019 `minimum` and `maximum`
operations, round-to-integer operations, and quiet floating-point
comparisons. For RV32, if the ext:d[] extension is implemented, the ext:zfa[] extension also adds instructions to
transfer double-precision floating-point values to and from integer
registers, and for RV64, if the ext:q[] extension is implemented, it adds analogous instructions for
quad-precision floating-point values. The ext:zfa[] extension depends on the
ext:f[] extension.

==== Load-Immediate Instructions

[[norm:fli-s_op]]
The insn:fli.s[] instruction loads one of 32 single-precision floating-point
constants, encoded in the _rs1_ field, into floating-point register
_rd_. The correspondence of _rs1_ field values and single-precision
floating-point values is shown in <<tab:flis>>. insn:fli.s[] is encoded
like insn:fmv.w.x[], but with _rs2_=1.

[[tab:flis]]
.Immediate values loaded by the insn:fli.s[] instruction.
[%autowidth,float="center",align="center",cols=">,>,^,^,^",options="header",]
|===
|_rs1_ |Value |Sign |Exponent |Significand
|0 |−1.0 |`1` |`01111111` |`000...000`
|1 |_Minimum positive normal_ |`0` |`00000001` |`000...000`
|2 |1.0 × 2^−16^ |`0` |`01101111` |`000...000`
|3 |1.0 × 2^−15^ |`0` |`01110000` |`000...000`
|4 |1.0 × 2^−8^ |`0` |`01110111` |`000...000`
|5 |1.0 × 2^−7^ |`0` |`01111000` |`000...000`
|6 |0.0625 (2^−4^) |`0` |`01111011` |`000...000`
|7 |0.125 (2^−3^) |`0` |`01111100` |`000...000`
|8 |0.25 |`0` |`01111101` |`000...000`
|9 |0.3125 |`0` |`01111101` |`010...000`
|10 |0.375 |`0` |`01111101` |`100...000`
|11 |0.4375 |`0` |`01111101` |`110...000`
|12 |0.5 |`0` |`01111110` |`000...000`
|13 |0.625 |`0` |`01111110` |`010...000`
|14 |0.75 |`0` |`01111110` |`100...000`
|15 |0.875 |`0` |`01111110` |`110...000`
|16 |1.0 |`0` |`01111111` |`000...000`
|17 |1.25 |`0` |`01111111` |`010...000`
|18 |1.5 |`0` |`01111111` |`100...000`
|19 |1.75 |`0` |`01111111` |`110...000`
|20 |2.0 |`0` |`10000000` |`000...000`
|21 |2.5 |`0` |`10000000` |`010...000`
|22 |3 |`0` |`10000000` |`100...000`
|23 |4 |`0` |`10000001` |`000...000`
|24 |8 |`0` |`10000010` |`000...000`
|25 |16 |`0` |`10000011` |`000...000`
|26 |128 (2^7^) |`0` |`10000110` |`000...000`
|27 |256 (2^8^) |`0` |`10000111` |`000...000`
|28 |2^15^ |`0` |`10001110` |`000...000`
|29 |2^16^ |`0` |`10001111` |`000...000`
|30 |+{inf} |`0` |`11111111` |`000...000`
|31 |_Canonical NaN_ |`0` |`11111111` |`100...000`
|===

[NOTE]
====
The preferred assembly syntax for entries 1, 30, and 31 is `min`, `inf`,
and `nan`, respectively. For entries 0 through 29 (including entry 1),
the assembler will accept decimal constants in C-like syntax.
====
[NOTE]
====
The set of 32 constants was chosen by examining floating-point
libraries, including the C standard math library, and to optimize
fixed-point to floating-point conversion.

Entries 8-22 follow a regular encoding pattern. No entry sets mantissa
bits other than the two most significant ones.
====

[[norm:fli-d_op]]
If the ext:d[] extension is implemented, insn:fli.d[] performs the analogous
operation, but loads a double-precision value into floating-point
register _rd_. Note that entry 1 (corresponding to the minimum positive
normal value) has a numerically different value for double-precision
than for single-precision. insn:fli.d[] is encoded like insn:fli.s[], but with
_fmt_=D.

[[norm:fli-q_op]]
If the ext:q[] extension is implemented, insn:fli.q[] performs the analogous
operation, but loads a quad-precision value into floating-point register
_rd_. Note that entry 1 (corresponding to the minimum positive normal
value) has a numerically different value for quad-precision. insn:fli.q[] is
encoded like insn:fli.s[], but with _fmt_=Q.

[[norm:fli-h_op]]
If the ext:zfh[] or ext:zvfh[] extension is implemented, insn:fli.h[] performs the
analogous operation, but loads a half-precision floating-point value
into register _rd_. Note that entry 1 (corresponding to the minimum
positive normal value) has a numerically different value for
half-precision. Furthermore, since 2^16^ is not
representable in half-precision floating-point, entry 29 in the table
instead loads positive infinity—i.e., it is redundant with entry 30.
insn:fli.h[] is encoded like insn:fli.s[], but with _fmt_=H.

[NOTE]
====
Additionally, since 2^−16^ and 2^−15^ are subnormal in half-precision, entry 1
is numerically greater than entries 2 and 3 for insn:fli.h[].
====

The insn:insn:fli.[]_fmt_ instructions never set any floating-point exception flags.

==== Minimum and Maximum Instructions

[[norm:fmaxm-s_fminm-s_op]]
The insn:fminm.s[] and insn:fmaxm.s[] instructions are defined like the insn:fmin.s[] and
insn:fmax.s[] instructions, except that if either input is NaN, the result is
the canonical NaN.

[[norm:fmaxm-d_fminm-d_op]]
If the ext:d[] extension is implemented, insn:fminm.d[] and insn:fmaxm.d[] instructions are
analogously defined to operate on double-precision numbers.

[[norm:fmaxm-q_fminm-q_op]]
If the ext:q[] extension is implemented, insn:fminm.q[] and insn:fmaxm.q[] instructions are
analogously defined to operate on quad-precision numbers.

[[norm:fmaxm-h_fminm-h_op]]
If the ext:zfh[] extension is implemented, insn:fminm.h[] and insn:fmaxm.h[] instructions
are analogously defined to operate on half-precision numbers.

These instructions are encoded like their insn:fmin[] and insn:fmax[] counterparts,
but with instruction bit 13 set to 1.
[NOTE]
====
These instructions implement the IEEE 754-2019 `minimum` and `maximum`
operations.
====
==== Round-to-Integer Instructions

[#norm:fround-s_op]#The insn:fround.s[] instruction rounds the single-precision floating-point
number in floating-point register _rs1_ to an integer, according to the
rounding mode specified in the instruction's _rm_ field. It then writes
that integer, represented as a single-precision floating-point number,
to floating-point register _rd_#. [#norm:fround-s_zero_inf]#Zero and infinite inputs are copied to
_rd_ unmodified#. [#norm:fround-s_nan_nv]#Signaling NaN inputs cause the invalid operation
exception flag to be set; no other exception flags are set#. insn:fround.s[] is
encoded like insn:fcvt.s.d[], but with _rs2_=4.

[[norm:froundnx-s_op]]
The insn:froundnx.s[] instruction is defined similarly, but it also sets the
inexact exception flag if the input differs from the rounded result and
is not NaN. insn:froundnx.s[] is encoded like insn:fcvt.s.d[], but with _rs2_=5.

[[norm:fround-d_froundnx-d_op]]
If the ext:d[] extension is implemented, insn:fround.d[] and insn:froundnx.d[] instructions
are analogously defined to operate on double-precision numbers. They are
encoded like insn:fcvt.d.s[], but with _rs2_=4 and 5, respectively,

[[norm:fround-q_froundnx-q_op]]
If the ext:q[] extension is implemented, insn:fround.q[] and insn:froundnx.q[] instructions
are analogously defined to operate on quad-precision numbers. They are
encoded like insn:fcvt.q.s[], but with _rs2_=4 and 5, respectively,

[[norm:fround-h_froundnx-h_op]]
If the ext:zfh[] extension is implemented, insn:fround.h[] and insn:froundnx.h[] instructions
are analogously defined to operate on half-precision numbers. They are
encoded like insn:fcvt.h.s[], but with _rs2_=4 and 5, respectively,

[NOTE]
====
The insn:froundnx[]._fmt_ instructions implement the IEEE 754-2019
`roundToIntegralExact` operation, and the insn:fround[]._fmt_ instructions
implement the other operations in the `roundToIntegral` family.
====

==== Modular Convert-to-Integer Instruction

[[norm:fcvtmod-w-d_op]]
The insn:fcvtmod.w.d[] instruction is defined similarly to the insn:fcvt.w.d[] instruction,
with the following differences. insn:fcvtmod.w.d[] always rounds
towards zero. Bits 31:0 are taken from the rounded, unbounded two's
complement result, then sign-extended to XLEN bits and written to
integer register _rd_. ±{inf} and NaN are converted to
zero.

[[norm:fcvtmod-w-d_flags]]
Floating-point exception flags are raised the same as they would be for
insn:fcvt.w.d[] with the same input operand.

This instruction is only provided if the ext:d[] extension is implemented. [#norm:fcvtmod-w-d_rsw]#It
is encoded like insn:fcvt.w.d[], but with the rs2 field set to 8 and the _rm_
field set to 1 (RTZ). Other _rm_ values are _reserved_.#

[NOTE]
====
The assembly syntax requires the RTZ rounding mode to be explicitly
specified, i.e., insn:fcvtmod.w.d[rd,rs1,rtz].

The insn:fcvtmod.w.d[] instruction was added principally to accelerate the
processing of JavaScript Numbers. Numbers are double-precision
values, but some operators implicitly truncate them to signed integers
mod 2^32^.
====

==== Move Instructions

[[norm:fmvh-x-d_op]]
For RV32 only, if the ext:d[] extension is implemented, the insn:fmvh.x.d[] instruction
moves bits 63:32 of floating-point register _rs1_ into
integer register _rd_. It is encoded in the OP-FP major opcode with
_funct3_=0, _rs2_=1, and _funct7_=1110001.

[NOTE]
====
insn:fmvh.x.d[] is used in conjunction with the existing insn:fmv.x.w[] instruction to
move a double-precision floating-point number to a pair of x-registers.
====

[[norm:fmvp-d-x_op]]
For RV32 only, if the ext:d[] extension is implemented, the insn:fmvp.d.x[] instruction
moves a double-precision number from a pair of integer
registers into a floating-point register. Integer registers _rs1_ and
_rs2_ supply bits 31:0 and 63:32, respectively; the result is written to
floating-point register _rd_. FMVP.D.X is encoded in the OP-FP major
opcode with _funct3_=0 and _funct7_=1011001.

[[norm:fmvh-x-q_op]]
For RV64 only, if the ext:q[] extension is implemented, the insn:fmvh.x.q[] instruction
moves bits 127:64 of floating-point register _rs1_ into
integer register _rd_. It is encoded in the OP-FP major opcode with
_funct3_=0, _rs2_=1, and _funct7_=1110011.

[NOTE]
====
insn:fmvh.x.q[] is used in conjunction with the existing insn:fmv.x.d[] instruction to
move a quad-precision floating-point number to a pair of x-registers.
====

[[norm:fmvp-q-x_op]]
For RV64 only, if the ext:q[] extension is implemented, the insn:fmvp.q.x[] instruction
moves a double-precision number from a pair of integer
registers into a floating-point register. Integer registers _rs1_ and
_rs2_ supply bits 63:0 and 127:64, respectively; the result is written
to floating-point register _rd_. insn:fmvp.q.x[] is encoded in the OP-FP major
opcode with _funct3_=0 and _funct7_=1011011.

==== Comparison Instructions

[[norm:fleq-s_fltq-s_op]]
The insn:fleq.s[] and insn:fltq.s[] instructions are defined like the insn:fle.s[] and insn:flt.s[] instructions,
except that quiet NaN inputs do not cause the invalid
operation exception flag to be set.

[[norm:fleq-d_fltq-d_op]]
If the ext:d[] extension is implemented, insn:fleq.d[] and insn:fltq.d[] instructions are
analogously defined to operate on double-precision numbers.

[[norm:fleq-q_fltq-q_op]]
If the ext:q[] extension is implemented, insn:fleq.q[] and insn:fltq.q[] instructions are
analogously defined to operate on quad-precision numbers.

[[norm:fleq-h_fltq-h_op]]
If the ext:zfh[] extension is implemented, insn:fleq.h[] and insn:fltq.h[] instructions are
analogously defined to operate on half-precision numbers.

These instructions are encoded like their insn:fle[] and insn:flt[] counterparts, but
with instruction bit 14 set to 1.

[NOTE]
====
We do not expect analogous comparison instructions will be added to the
vector ISA, since they can be reasonably efficiently emulated using
masking.
====
