[[ext:zfbfmin]]
=== ext:zfbfmin[] Extension for Scalar BF16 Conversions

This extension provides the minimal set of instructions needed to enable scalar support
of the BF16 format. It enables BF16 as an interchange format as it provides conversion
between BF16 values and FP32 values.

This extension depends upon the ext:f[] extension.

This extension includes six instructions: the insn:fcvt.bf16.s[] and
insn:fcvt.s.bf16[] instructions, defined below, and the insn:flh[], insn:fsh[],
insn:fmv.x.h[], and insn:fmv.h.x[] instructions, defined in <<chap:zfh>>.

[NOTE]
====
While conversion instructions tend to include all supported formats, in these extensions we
only support conversion between BF16 and FP32 as we are targeting a special use case.
These extensions are intended to support the case where BF16 values are used as reduced
precision versions of FP32 values, where use of BF16 provides a two-fold advantage for
storage, bandwidth, and computation. In this use case, the BF16 values are typically
multiplied by each other and accumulated into FP32 sums.
These sums are typically converted to BF16
and then used as subsequent inputs. The operations on the BF16 values can be performed
on the CPU or a loosely coupled coprocessor.

Subsequent extensions might provide support for native BF16 arithmetic. Such extensions
could add additional conversion
instructions to allow all supported formats to be converted to and from BF16.
====

[NOTE]
====
BF16 addition, subtraction, multiplication, division, and square-root operations can be
faithfully emulated by converting the BF16 operands to single-precision, performing the
operation using single-precision arithmetic, and then converting back to BF16. Performing
BF16 fused multiply-addition using this method can produce results that differ by 1-ulp
on some inputs for the RNE and RMM rounding modes.


Conversions between BF16 and formats larger than FP32 can be
emulated.
Exact widening conversions from BF16 can be synthesized by first
converting to FP32 and then converting from FP32 to the target
precision.
Conversions narrowing to BF16 can be synthesized by first
converting to FP32 through a series of halving steps and then
converting from FP32 to BF16.
As with the fused multiply-addition instruction described above,
this method of converting values to BF16 can be off by 1-ulp
on some inputs for the RNE and RMM rounding modes.
====

==== BF16 Number Format

BF16 bits::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'frac'},
{bits: 8, name: 'expo'},
{bits: 1, name: 'S'},
]}
....

While BF16 is not an IEEE 754 _standard_ format, it is a valid floating-point
format as defined by IEEE 754-2008, with radix 2, number of significand digits 8,
and maximum exponent 127.

[[norm:bf16_subnorm]]
BF16 computational instructions defined in this chapter support all IEEE
754-2008 features, including all rounding modes, subnormal inputs and outputs,
overflow and underflow, and default exception handling.
Tininess is detected after rounding.

The BF16 canonical NaN is `0x7fc0`.

BF16 values are NaN-boxed when held in `f` registers, as described in <<nanboxing>>.

==== insn:fcvt.bf16.s[]

Synopsis::
Convert FP32 value to a BF16 value

Mnemonic::
insn:fcvt.bf16.s[rd,rs1]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '01000', attr: ['bf16.s']},
{bits: 2, name: '10', attr: ['h']},
{bits: 5, name: '01000', attr: 'fcvt'},
]}
....

[NOTE]
====
.Encoding
While the mnemonic of this instruction is consistent with that of the other RISC-V floating-point convert instructions,
a new encoding is used in bits 24:20.

`BF16.S` and `H` are used to signify that the source is FP32 and the destination is BF16.
====

Description::
[[norm:fcvt-bf16-s_op]]
Narrowing convert FP32 value to a BF16 value. Round according to the RM field.

This instruction is similar to other narrowing
floating-point-to-floating-point conversion instructions.

Exceptions:  Overflow, Underflow, Inexact, Invalid

==== insn:fcvt.s.bf16[]

Synopsis::
Convert BF16 value to an FP32 value

Mnemonic::
insn:fcvt.s.bf16[rd,rs1]

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '00110', attr: ['bf16']},
{bits: 2, name: '00', attr: ['s']},
{bits: 5, name: '01000', attr: 'fcvt'},
]}
....

[NOTE]
====
.Encoding
While the mnemonic of this instruction is consistent with that of the other RISC-V floating-point
convert instructions, a new encoding is
used in bits 24:20 to indicate that the source is BF16.
====

Description::
[[norm:fcvt-s-bf16_op]]
Converts a BF16 value to an FP32 value. The conversion is exact.

This instruction is similar to other widening
floating-point-to-floating-point conversion instructions.

[NOTE]
====
If the input is normal or infinity, the BF16 encoded value is shifted
to the left by 16 places and the
least significant 16 bits are written with 0s.

The result is NaN-boxed by writing the most significant `FLEN`-32 bits with 1s.
====

Exceptions: Invalid

//
