[[ext:zfh]]
=== ext:zfh[] Extension for Half-Precision Floating-Point

This chapter describes the ext:zfh[] standard extension for _half-precision_
floating-point, which adds computational instructions compliant with the IEEE
754-2008 arithmetic standard's binary16 format and operations. The ext:zfh[] extension
depends on the ext:f[] extension. The NaN-boxing scheme described in <<nanboxing>> is
extended to allow a half-precision value to be NaN-boxed inside a
single-precision value (which may be recursively NaN-boxed inside a double- or
quad-precision value when the ext:d[] or ext:q[] extension is present).

[NOTE]
====
This extension primarily provides instructions that consume
half-precision operands and produce half-precision results. However, it
is also common to compute on half-precision data using higher
intermediate precision. Although this extension provides explicit
conversion instructions that suffice to implement that pattern, future
extensions might further accelerate such computation with additional
instructions that implicitly widen their operands—e.g.,
half{times}half+single->single—or
implicitly narrow their results—e.g.,
half+single->half.
====
==== Half-Precision Load and Store Instructions

[[norm:fsh_flh_op]]
New 16-bit variants of LOAD-FP and STORE-FP instructions are added,
encoded with a new value for the funct3 width field.

include::images/wavedrom/sp-load-store.edn[]
[[sp-load-store]]
//.Half-precision load and store instructions

[[norm:fsh_flh_atomic_align]]
insn:flh[] and insn:fsh[] are only guaranteed to execute atomically if the effective
address is naturally aligned.

[[norm:fsh_flh_bits_maintained]]
insn:flh[] and insn:fsh[] do not modify the bits being transferred; in particular, the
payloads of non-canonical NaNs are preserved. insn:flh[] NaN-boxes the result
written to _rd_, whereas insn:fsh[] ignores all but the lower 16 bits in _rs2_.

==== Half-Precision Computational Instructions

The _fmt_ field of instructions in the ext:zfh[] extension is set to _H_ (10),
as defined in <<tab:fpfmt>>.

[[norm:Zfh_computational_instrs]]
The half-precision floating-point computational instructions are defined
analogously to their single-precision counterparts, but operate on
half-precision operands and produce half-precision results.

include::images/wavedrom/spfloat-zfh.edn[]

include::images/wavedrom/spfloat2-zfh.edn[]

==== Half-Precision Conversion and Move Instructions

New floating-point-to-integer and integer-to-floating-point conversion
instructions are added. These instructions are defined analogously to
the single-precision-to-integer and integer-to-single-precision
conversion instructions.
[#norm:fcvt-w-h_fcvt-l-h_op]#insn:fcvt.w.h[] or insn:fcvt.l.h[] converts a half-precision floating-point number to a signed 32-bit or 64-bit integer, respectively#.
[#norm:fcvt-h-w_fcvt-h-l_op]#insn:fcvt.h.w[] or insn:fcvt.h.l[] converts a 32-bit or 64-bit signed integer, respectively, into a half-precision floating-point number#.
[#norm:fcvt-wu-h_fcvt-lu-h_fcvt-h-wu_fcvt-h-lu_op]#insn:fcvt.wu.h[], insn:fcvt.lu.h[], insn:fcvt.h.wu[], and insn:fcvt.h.lu[] variants convert to or from unsigned integer values#.
[#norm:fcvt_long_half_rv64_only]#insn:fcvt.l.h[], insn:fcvt.lu.h[], insn:fcvt.h.l[] and insn:fcvt.h.lu[] are RV64-only instructions.#

include::images/wavedrom/half-prec-conv-and-mv.edn[]
[[half-prec-conv-and-mv]]

New floating-point-to-floating-point conversion instructions are added.
These instructions are defined analogously to the double-precision
floating-point-to-floating-point conversion instructions.
[#norm:fcvt-s-h_fcvt-h-s_op]#insn:fcvt.s.h[] or insn:fcvt.h.s[] converts a half-precision floating-point number to a single-precision floating-point number, or vice-versa, respectively#.
[#norm:fcvt-d-h_fcvt-h-d_op]#If the ext:d[] extension is present, insn:fcvt.d.h[] or insn:fcvt.h.d[] converts a half-precision floating-point number to a double-precision floating-point number, or vice-versa, respectively#.
[#norm:fcvt-q-h_fcvt-h-q_op]#If the ext:q[] extension is present, insn:fcvt.q.h[] or insn:fcvt.h.q[] converts a half-precision floating-point number to a quad-precision floating-point number, or vice-versa, respectively#.

include::images/wavedrom/half-prec-flpt-to-flpt-conv.edn[]
[[half-prec-flpt-to-flpt-conv]]

[[norm:fsgnj-h_fsgnjn-h_fsgnjx-h_op]]
Floating-point to floating-point sign-injection instructions, insn:fsgnj.h[],
insn:fsgnjn.h[], and insn:fsgnjx.h[] are defined analogously to the single-precision
sign-injection instruction.

include::images/wavedrom/flt-to-flt-sgn-inj-instr.edn[]
[[flt-to-flt-sgn-inj-instr]]

Instructions are provided to move bit patterns between the
floating-point and integer registers. [#norm:fmv-x-h_op]#insn:fmv.x.h[] moves
the half-precision value in floating-point register _rs1_ to a
representation in the IEEE 754-2008 encoding in integer register _rd_,
filling the upper XLEN-16 bits with copies of the floating-point
number's sign bit#.

[[norm:fmv-h-x_op]]
insn:fmv.h.x[] moves the half-precision value encoded in the IEEE 754-2008
encoding from the lower 16 bits of integer register _rs1_ to the
floating-point register _rd_, NaN-boxing the result.

[[norm:fmv_half_bits_preverved]]
insn:fmv.x.h[] and insn:fmv.h.x[] do not modify the bits being transferred; in
particular, the payloads of non-canonical NaNs are preserved.

include::images/wavedrom/flt-pt-to-int-move.edn[]
[[flt-pt-to-int-move]]

==== Half-Precision Floating-Point Compare Instructions

[[norm:Zfh_compare_instrs]]
The half-precision floating-point compare instructions are defined
analogously to their single-precision counterparts, but operate on
half-precision operands.

include::images/wavedrom/half-pr-flt-pt-compare.edn[]
[[half-pr-flt-pt-compare]]

==== Half-Precision Floating-Point Classify Instruction

[[norm:fclass-h_op]]
The half-precision floating-point classify instruction, insn:fclass.h[], is
defined analogously to its single-precision counterpart, but operates on
half-precision operands.

include::images/wavedrom/half-pr-flt-pt-class.edn[]
[[half-pr-flt-class]]
