[[ext:zfhmin]]
=== ext:zfhmin[] Extension for Minimal Half-Precision Floating-Point

This section describes the ext:zfhmin[] standard extension, which provides
minimal support for 16-bit half-precision binary floating-point
instructions. The ext:zfhmin[] extension is a subset of the ext:zfh[] extension,
consisting only of data transfer and conversion instructions. Like ext:zfh[],
the ext:zfhmin[] extension depends on the ext:f[] extension. The expectation is
that ext:zfhmin[] software primarily uses the half-precision format for storage,
performing most computation in higher precision.

[[norm:zfhmin]]
The ext:zfhmin[] extension includes the following instructions from the
ext:zfh[] extension: insn:flh[], insn:fsh[], insn:fmv.x.h[], insn:fmv.h.x[],
insn:fcvt.s.h[], and insn:fcvt.h.s[]. If the ext:d[] extension is present, the
insn:fcvt.d.h[] and insn:fcvt.h.d[] instructions are also included. If the
ext:q[] extension is present, the insn:fcvt.q.h[] and
insn:fcvt.h.q[] instructions are additionally included.

[NOTE]
====
ext:zfhmin[] does not include the insn:fsgnj.h[] instruction, because it suffices to
instead use the insn:fsgnj.s[] instruction to move half-precision values
between floating-point registers.

Half-precision addition, subtraction, multiplication, division, and
square-root operations can be faithfully emulated by converting the
half-precision operands to single-precision, performing the operation
using single-precision arithmetic, then converting back to
half-precision. cite:[roux:hal-01091186] Performing half-precision fused multiply-addition using
this method incurs a 1-ulp error on some inputs for the RNE and RMM
rounding modes.

Conversion from 8- or 16-bit integers to half-precision can be emulated
by first converting to single-precision, then converting to
half-precision. Conversion from 32-bit integer can be emulated by first
converting to double-precision. If the ext:d[] extension is not present and a
1-ulp error under RNE or RMM is tolerable, 32-bit integers can be first
converted to single-precision instead. The same remark applies to
conversions from 64-bit integers without the ext:q[] extension.
====
