[[ext:zfinx]]
=== ext:zfinx[], ext:zdinx[], ext:zhinx[], ext:zhinxmin[] Extensions for Floating-Point in Integer Registers

This chapter defines the ext:zfinx[] extension (pronounced "z-f-in-x")
that provides instructions similar to those in the standard
floating-point ext:f[] extension for single-precision floating-point
instructions but which operate on the `x` registers instead of the `f`
registers. This chapter also defines the ext:zdinx[], ext:zhinx[], and
ext:zhinxmin[] extensions that provide similar instructions for other
floating-point precisions.

[NOTE]
====
The ext:f[] extension uses separate `f` registers for floating-point
computation, to reduce register pressure and simplify the provision of
register-file ports for wide superscalars. However, the additional 128 bytes of
architectural state increases the minimal implementation cost. By
eliminating the `f` registers, the ext:zfinx[] extension substantially reduces
the cost of simple RISC-V implementations with floating-point
instruction-set support. ext:zfinx[] also reduces context-switch cost.

In general, software that assumes the presence of the ext:f[] extension is
incompatible with software that assumes the presence of the
ext:zfinx[] extension, and vice versa.
====

[[norm:Zfinx_F_instrs]]
The ext:zfinx[] extension adds all of the instructions that the ext:f[] extension
adds, _except_ for the transfer instructions insn:flw[], insn:fsw[],
insn:fmv.w.x[], insn:fmv.x.w[], insn:c.flw[], insn:c.flwsp[], insn:c.fsw[] and
insn:c.fswsp[].

[NOTE]
====
ext:zfinx[] software uses integer loads and stores to transfer floating-point
values from and to memory. Transfers between registers use either
integer arithmetic or floating-point sign-injection instructions.
====

[[norm:Zfinx_x_regs]]
The ext:zfinx[] variants of these ext:f[]-extension instructions have the same
semantics, except that whenever such an instruction would have accessed
an `f` register, it instead accesses the `x` register with the same
number.

The ext:zfinx[] extension depends on the ext:zicsr[] extension.

==== Processing of Narrower Values
[[norm:Zfinx_narrow_operands]]
Floating-point operands of width _w_ < XLEN bits occupy
bits _w_-1:0 of an `x` register. Floating-point operations on _w_-bit
operands ignore operand bits XLEN-1: _w_.

[[norm:Zfinx_narrow_result]]
Floating-point operations that produce _w_ < XLEN-bit
results fill bits XLEN-1: _w_ with copies of bit _w_-1 (the sign bit).

[NOTE]
====
The NaN-boxing scheme employed in the `f` registers was designed to
efficiently support recoded floating-point formats. Recoding is less
practical for ext:zfinx[], though, since the same registers hold both
floating-point and integer operands. Hence, the need for NaN boxing is
diminished.

Sign-extending 32-bit floating-point numbers when held in RV64 `x`
registers is compatible with the existing RV64 calling conventions, which leave bits 63-32 undefined when passing a 32-bit floating point value in `x` registers. To keep the architecture more regular, we extend this pattern to 16-bit floating-point numbers in both RV32 and RV64.
====

[[ext:zdinx]]
==== ext:zdinx[]

The ext:zdinx[] extension provides analogous double-precision floating-point
instructions. The ext:zdinx[] extension depends upon the ext:zfinx[] extension.

[[norm:Zdinx_D_instrs]]
The ext:zdinx[] extension adds all of the instructions that the ext:d[] extension
adds, _except_ for the transfer instructions insn:fld[], insn:fsd[],
insn:fmv.d.x[], insn:fmv.x.d[], c.fld[], c.fldsp[], c.fsd[] and c.fsdsp[].

[[norm:Zdinx_x_regs]]
The ext:zdinx[] variants of these ext:d[]-extension instructions have the same
semantics, except that whenever such an instruction would have accessed
an `f` register, it instead accesses the `x` register with the same
number.

==== Processing of Wider Values

[[norm:Zdinx_x_reg_pair]]
For RV32, double-precision operands in ext:zdinx[] are held in aligned
`x`-register pairs. In other words, register numbers must be even. Use of
misaligned (odd-numbered) registers for double-width floating-point operands is
_reserved_.

[[norm:Zdinx_endianness]]
Regardless of endianness, the lower-numbered register holds the low-order bits
of double-width floating-point operands, and the higher-numbered register holds
the high-order bits. For RV32 with ext:zdinx[], bits 31:0 of a double-precision
operand might be held in register `x14`, with bits 63:32 of that operand held in
`x15`, for instance.

[[norm:Zdinx_x0_write]]
When a double-width floating-point result is written to `x0`, the entire write
takes no effect. For RV32 with ext:zdinx[], writing a double-precision result to
`x0` does not cause `x1` to be written.

[[norm:Zdinx_x0_read]]
When `x0` is used as a double-width floating-point operand, the entire
operand is zero. In other words, `x1` is not accessed.

[NOTE]
====
The ext:zilsd[] extension defines load-pair and store-pair instructions for RV32.
When this extension is not implemented, transferring double-precision operands
in ext:zdinx[] from or to memory requires two loads or stores. Register moves
need only a single insn:fsgnj.d[] instruction, however.
====

==== ext:zhinx[]

The ext:zhinx[] extension provides analogous half-precision floating-point
instructions. The ext:zhinx[] extension depends upon the ext:zfinx[] extension.

[[norm:Zhinx_Zfh_instrs]]
The ext:zhinx[] extension adds all of the instructions that the ext:zfh[] extension
adds, _except_ for the transfer instructions insn:flh[], insn:fsh[], insn:fmv.h.x[], and
insn:fmv.x.h[].

[[norm:Zhinx_x_regs]]
The ext:zhinx[] variants of these ext:zfh[]-extension instructions have the same
semantics, except that whenever such an instruction would have accessed
an `f` register, it instead accesses the `x` register with the same
number.

==== ext:zhinxmin[]

The ext:zhinxmin[] extension provides minimal support for 16-bit
half-precision floating-point instructions that operate on the `x`
registers. The ext:zhinxmin[] extension depends upon the ext:zfinx[] extension.

[[norm:Zfhinxmin_instrs]]
The ext:zhinxmin[] extension includes the following instructions from the
ext:zhinx[] extension: insn:fcvt.s.h[] and insn:fcvt.h.s[]. If the ext:zdinx[] extension is
present, the insn:fcvt.d.h[] and insn:fcvt.h.d[] instructions are also included.

[NOTE]
====
In the future, a ext:zqinx[] quad-precision extension for RV64 could be defined
analogously to ext:zdinx[] for RV32. A ext:zqinx[] extension for RV32 could also be defined
but would require quad-register groups.
====

==== Privileged Architecture Implications

[[norm:Zfinx_mstatus_FS_zero]]
As described in <<sec:mstatus>>, the
csr:mstatus[] field csr::[fs] is hardwired to 0 if the ext:zfinx[] extension is
implemented, and csr::[fs] no longer affects the trapping behavior of
floating-point instructions or csr:fcsr[] accesses.

[[norm:Zfinx_misa_F_D_Q_zero]]
The csr:misa[] bits csr::[f], csr::[d], and csr::[q] are hardwired to 0 when the ext:zfinx[] extension
is implemented.

[NOTE]
====
A future discoverability mechanism might be used to probe the existence
of the ext:zfinx[], ext:zhinx[], and ext:zdinx[] extensions.
====
