[[ziccif]]
=== Ziccif Extension for Instruction-Fetch Atomicity

NOTE: This extension was ratified alongside the RVA20U64 profile.
This chapter supplies an operational definition for the extension
and adds expository material.

If the Ziccif extension is implemented, main memory regions with both the
cacheability and coherence PMAs must support instruction fetch, and any
instruction fetches of naturally aligned power-of-2 sizes of at most
`min(ILEN,XLEN)` bits are atomic.

An implementation with the Ziccif extension fetches instructions in a manner
equivalent to the following state machine.

. Let `M` be the smallest power of 2 such that `M` {ge} `min(ILEN,XLEN)/8`.
Let `N` be the `pc` modulo `M`.
Atomically fetch `M` - `N` bytes from memory at address `pc`.
Let `T` be the running total of bytes fetched, initially `M` - `N`.

. If the `T` bytes fetched begin with a complete instruction of length `L` {le}
`T`, then execute that instruction, discard the remaining `T` - `L` bytes
fetched, and go back to step 1, using the updated `pc`.
Otherwise, atomically fetch `M` bytes from memory at address `pc` + `T`,
increment `T` by `M`, and repeat step 2.

[NOTE]
====
The instruction-fetch atomicity rule supports concurrent code modification.
When a hart modifies instruction memory and either it or another hart executes
the modified instructions without first having executing a FENCE.I, the
modifying hart should adhere to the following rules to ensure predictable
behavior:

- Modification stores must be single-copy atomic, hence must be naturally
aligned.

- The modified instruction must not span an aligned `M`-byte boundary,
unless it is replaced with a shorter unconditional control transfer
(e.g., `c.ebreak` or `c.j`) that does not itself span an `M`-byte
boundary.

- Modification stores must alter a complete instruction or complete
instructions that do not collectively span an `M`-byte boundary,
modulo the exception above that the first part of an instruction may be
replaced with an unconditional control transfer instruction.

- Modifications must not combine smaller instructions into a larger
instruction but may convert a larger instruction to some number of
smaller instructions.

- Modified instruction memory must have the coherence PMA.

Other well-defined code-modification strategies exist, but these rules provide
a safe harbor.

Note that the software modifying the code need not know the value of `M`.
Because ILEN must be at least the width of the instruction being modified,
a lower bound on `M` can be inferred from the instruction's width and XLEN.
====

Memory protection and executability PMAs are applied only to bytes that are
not discarded by this algorithm.

[NOTE]
====
For example, if `M`=8, `N`=0, and the PMP granularity is 4 bytes, then
it is valid to fetch a 4-byte instruction at `pc`, even if fetching from
`pc` + 4 would have been disallowed by PMP.

For simplicity, implementations are likely to choose a PMP granularity no
smaller than `M`.
====
