=== Ziccid Extension for Instruction/Data Coherence and Consistency

The Ziccid extension mandates more stringent requirements for consistency
between instruction fetches and other memory accesses than those imposed by
the base ISA.
As described in detail in the next section, Ziccid guarantees that a hart's
instruction fetches appear to occur in program order with respect to each
other, and that stores eventually become visible to all harts' instruction
fetches.

[NOTE]
====
The primary intent of the Ziccid extension is to accelerate JIT
compilation in multiprocessor systems.

In straightforward implementations, maintaining coherence between instruction
caches and the data-memory system suffices to satisfy this extension's
eventuality property.
The Ziccid extension can be viewed as a means to codify the concept of
instruction-cache coherence.

The in-order fetch property, expected by some JIT compilers, is also
provided naturally by most straightforward microarchitectures.
An example of a technique that might violate this property, however, is an
instruction buffer that is populated out of program order, e.g., while fetching
down the predicted path following an instruction-cache miss.
Example solutions include buffering instructions only in program order, or
keeping the buffer coherent by making the coherent instruction cache inclusive
of the buffer.
====

[NOTE]
====
Under Ziccid, stores _eventually_ become visible to instruction fetches, even
without executing a FENCE.I instruction.
As a consequence of this requirement, the consumer thread in the following
litmus test is guaranteed to terminate:

```
Producer:                                       Consumer:

la t0, patch_me                               patch_me:
li t1, 0x4585                                   c.li a1, 0
sh t1, (t0)   # patch_me := c.li a1, 1          beqz a1, patch_me
```

As is the case without the Ziccid extension, software can make a store from
the current hart visible to the hart's instruction fetches immediately by
executing a FENCE.I instruction.
Software can make a store from the current hart visible to another hart's
instruction fetches by executing a FENCE W,O instruction, then sending an
interprocessor interrupt to the remote hart, requesting that it execute
a FENCE.I instruction.
Alternatively, the current hart can execute a FENCE W,W instruction, then
write a flag in memory; upon observing the flag write, the remote hart
executes a FENCE.I instruction.
In neither case is a data FENCE required on the remote hart.
====

The Ziccid extension depends on the Ziccif extension.

NOTE: Although instruction/data consistency and instruction-fetch atomicity
are conceptually independent properties, the former is much more useful in
conjunction with the latter.

==== Operational Model of the Ziccid Extension

An implementation with the Ziccid extension behaves in a manner consistent
with the following operational model.
This model only applies to instruction fetches to memory regions with the
cacheability and coherence PMAs; instruction fetches to other memory regions
proceed as though the Ziccid extension were not implemented.

NOTE: Informally, instructions in incoherent and/or uncacheable memory regions
may be incoherently cached; this cache is flushed upon execution of a FENCE.I
instruction.

Harts have two ordered operational stages: instruction fetch and execution.
Each hart has an instruction buffer of bounded capacity.
Instructions are fetched from memory in program order, then inserted into the
instruction buffer in program order.

An instruction fetch is a memory read operation that appears in the global
memory order, in program order with respect to other instruction fetches
from the same hart.
For each instruction byte fetched from memory, memory
supplies the value written by the most recent store that precedes the read in
global memory order.

NOTE: This property is distinct from than the load-value axiom, in that fetches
do not observe the local hart's stores before other harts' fetches can observe them.

Instruction fetches appear in the global memory order before any explicit memory
accesses to which they give rise.

[NOTE]
====
Absent the execution of a FENCE.I instruction, there is no requirement that
younger instruction fetches appear in the global memory order later than older
explicit memory accesses.
For example, if a program consists of two store instructions X and Y to
distinct addresses AX and AY, then the following global orders are valid:

- fetch X, fetch Y, store AX, store AY
- fetch X, fetch Y, store AY, store AX
- fetch X, store AX, fetch Y, store AY
====

After some amount of time, instructions are dequeued in program order from the
instruction buffer and executed.

NOTE: Therefore, absent the execution of a FENCE.I instruction,
stores do not necessarily become visibile immediately to subsequent instruction fetches,
though they do _eventually_ become visible to subsequent instruction fetches.

Instructions are executed in program order, but instructions' explicit memory
accesses may be reordered in any manner consistent with RVWMO.

NOTE: Executing a `fence w,w` instruction between two store instructions, for
example, suffices to guarantee that the second store will not become visible
to any instruction fetch before the first store does.

The FENCE.I instruction performs the following operations sequentially:

- All of the hart's older explicit memory accesses become globally visible.
- The instruction buffer is flushed.

[NOTE]
====
The FENCE.I instruction in Ziccid is specified such that software written for
non-Ziccid machines is compatible with Ziccid machines.
For cacheable and coherent memory regions, the combination of making older
stores globally visible and flushing the instruction buffer on FENCE.I
suffices to implement FENCE.I's pre-Ziccid semantics for those regions.
====

//
