[[ext:zifencei]]
=== ext:zifencei[] Extension for Instruction-Fetch Fence
This chapter defines the ext:zifencei[] extension, which includes the
insn:fence.i[] instruction that provides explicit synchronization between writes
to instruction memory and instruction fetches on the same hart. Currently, this
instruction is the only standard mechanism to ensure that stores visible to a
hart will also be visible to its instruction fetches.
(((store instruction word, not included)))
[NOTE]
====
We considered but did not include a _store instruction word_ instruction as in
cite:[majc]. JIT compilers may generate a large trace of instructions before a
single insn:fence.i[], and amortize any instruction cache snooping or
invalidation overhead by writing translated instructions to memory regions that
are known not to reside in the instruction cache.
====
'''
[NOTE]
====
insn:fence.i[] was designed to support a wide variety of implementations. A
simple implementation can flush the local instruction cache and the instruction
pipeline when the insn:fence.i[] is executed. A more complex implementation
might snoop the instruction (data) cache on every data (instruction) cache miss,
or use an inclusive unified private L2 cache to invalidate lines from the
primary instruction cache when they are being written by a local store
instruction. If instruction and data caches are kept coherent in this way, or if
the memory system consists of only uncached RAMs, then just the fetch pipeline
needs to be flushed at a insn:fence.i[].

insn:fence.i[] was previously part of the base ext:i[] instruction set. Two main
issues are driving moving this out of the mandatory base, although at time of
writing it is still the only standard method for maintaining instruction-fetch
coherence.

First, it has been recognized that on some systems, insn:fence.i[] will be
expensive to implement and alternate mechanisms are being discussed in the
memory model task group. In particular, for designs that have an incoherent
instruction cache and an incoherent data cache, or where the instruction cache
refill does not snoop a coherent data cache, both caches must be completely
flushed when a insn:fence.i[] instruction is encountered. This problem is
exacerbated when there are multiple levels of instruction and data caches in
front of a unified cache or outer memory system.

Second, the instruction is not powerful enough to make available at user level
in a Unix-like operating system environment. The insn:fence.i[] only
synchronizes the local hart, and the OS can reschedule the user hart to a
different physical hart after the insn:fence.i[]. This would require the OS to
execute an additional insn:fence.i[] as part of every context migration. For
this reason, the standard Linux ABI has removed insn:fence.i[] from user-level
and now requires a system call to maintain instruction-fetch coherence, which
allows the OS to minimize the number of insn:fence.i[] executions required on
current systems and provides forward-compatibility with future improved
instruction-fetch coherence mechanisms.

Future approaches to instruction-fetch coherence under discussion include
providing more restricted versions of insn:fence.i[] that only target a given
address specified in _rs1_, and/or allowing software to use an ABI that relies
on machine-mode cache-maintenance operations.
====

include::images/wavedrom/zifencei-ff.edn[]
[[zifencei-ff]]
//.FENCE.I instruction
(((FENCE.I, synchronization)))
[[insn:fence.i]]
The insn:fence.i[] instruction is used to synchronize the instruction and data
streams. RISC-V does not guarantee that stores to instruction memory will be
made visible to instruction fetches on a RISC-V hart until that hart executes a
insn:fence.i[] instruction. A insn:fence.i[] instruction ensures that a
subsequent instruction fetch on a RISC-V hart will see any previous data stores
already visible to the same RISC-V hart. insn:fence.i[] does _not_ ensure that
other RISC-V harts' instruction fetches will observe the local hart's stores in
a multiprocessor system. To make a store to instruction memory visible to all
RISC-V harts, the writing hart also has to execute a data insnlink:fence[]
before requesting that all remote RISC-V harts execute a insn:fence.i[].

[[norm:fence_i_op]]
A insn:fence.i[] instruction orders all explicit memory accesses that precede
the insn:fence.i[] in program order before all instruction fetches that follow
the insn:fence.i[] in program order.

[NOTE]
====
In the following litmus test, for example, the outcome `a0`=1, `a1`=0 on the
consumer hart is forbidden, assuming little-endian RV32IC harts:

```
Initially, flag = 0.

Producer hart:                                  Consumer hart:

la t0, patch_me                                 la t2, flag
li t1, 0x4585                                   lw a0, (t2)
sh t1, (t0)   # patch_me := c.li a1, 1          fence.i
fence w, w    # order flag write              patch_me:
la t0, flag                                     c.li a1, 0
li t1, 1
sw t1, (t0)   # flag := 1
```

Note that this example is only meant to illustrate the aforementioned ordering
property.
In a realistic producer-consumer code-generation scheme, the consumer would loop
until `flag` becomes 1 before executing the insn:fence.i[] instruction.
====

An instruction fetch is always ordered before any explicit memory accesses that
instruction gives rise to.

[[norm:fence_i_rsv]]
The unused fields in the insn:fence.i[] instruction, _funct12_, _rs1_, and _rd_,
are reserved for finer-grain fences in future extensions. For forward
compatibility, base implementations shall ignore these fields, and standard
software shall zero these fields.
(((FENCE.I, finer-grained)))
(((FENCE.I, forward compatibility)))
[NOTE]
====
Because insn:fence.i[] only orders stores with a hart's own instruction fetches,
application code should only rely upon insn:fence.i[] if the application thread
will not be migrated to a different hart. The EEI can provide mechanisms for
efficient multiprocessor instruction-stream synchronization.
====

//
