[[ext:zihintpause]]
=== ext:zihintpause[] Extension for Pause Hint
[#norm:pause_op]#The insnlink:pause[] instruction is a HINT that indicates the current hart's rate
of instruction retirement should be temporarily reduced or paused. The
duration of its effect must be bounded and may be zero.#
(((PAUSE, HINT)))
(((HINT, PAUSE)))
[NOTE]
====
(((PAUSE, energy consumption)))
Software can use the insnlink:pause[] instruction to reduce energy consumption
while executing spin-wait code sequences. Multithreaded cores might
temporarily relinquish execution resources to other harts when insnlink:pause[] is
executed. It is recommended that a insnlink:pause[] instruction generally be
included in the code sequence for a spin-wait loop.

(((PAUSE, duration)))
The duration of a insnlink:pause[] instruction's effect may vary significantly
within and among implementations. In typical implementations this
duration should be much less than the time to perform a context switch,
probably more on the rough order of an on-chip cache miss latency or a
cacheless access to main memory.

A series of insnlink:pause[] instructions can be used to create a cumulative delay
loosely proportional to the number of insnlink:pause[] instructions. In spin-wait
loops in portable code, however, only one insnlink:pause[] instruction should be
used before re-evaluating loop conditions, else the hart might stall
longer than optimal on some implementations, degrading system
performance.
====

[#norm:pause_enc_fence]#insnlink:pause[] is encoded as a insnlink:fence[] instruction with _pred_=`W`, _succ_=`0`, _fm_=`0`,
_rd_=`x0`, and _rs1_=`x0`.#

[NOTE]
====
(((PAUSE, encoding)))
insnlink:pause[] is encoded as a hint within the insnlink:fence[] opcode because some
implementations are expected to deliberately stall the insnlink:pause[] instruction
until outstanding memory transactions have completed. Because the
successor set is null, however, insnlink:pause[] does not _mandate_ any particular
memory ordering—hence, it truly is a HINT.

(((PAUSE, LR/RC sequences)))
Like other insnlink:fence[] instructions, insnlink:pause[] cannot be used within LR/SC
sequences without voiding the forward-progress guarantee.

The choice of a predecessor set of W is arbitrary, since the successor
set is null. Other HINTs similar to insnlink:pause[] might be encoded with other
predecessor sets.
====
