[[ext:zihintntl]]
=== ext:zihintntl[] Extension for Non-Temporal Locality Hints

The insn:ntl[] instructions are HINTs that indicate that the explicit memory
accesses of the immediately subsequent instruction (henceforth "target
instruction") exhibit poor temporal locality of reference.
[#norm:NTL_target_definition]#The insn:ntl[] instructions do not change architectural state, nor do they alter the
architecturally visible effects of the target instruction.# Four variants
are provided:

[#norm:NTL-P1_op]#The insn:ntl.p1[] instruction indicates that the target instruction does not
exhibit temporal locality within the capacity of the innermost level of
private cache in the memory hierarchy.# [#norm:NTL-P1_enc]#insn:ntl.p1[] is encoded as
insn:add[x0,x0,x2].#

[#norm:NTL-PALL_op]#The insn:ntl.pall[] instruction indicates that the target instruction does not
exhibit temporal locality within the capacity of any level of private
cache in the memory hierarchy.# [#norm:NTL-PALL_enc]#insn:ntl.pall[] is encoded as insn:add[x0,x0,x3].#

[#norm:NTL-S1_op]#The insn:ntl.s1[] instruction indicates that the target instruction does not
exhibit temporal locality within the capacity of the innermost level of
shared cache in the memory hierarchy.# [#norm:NTL-S1_enc]#insn:ntl.s1[] is encoded as
insn:add[x0,x0,x4].#

[#norm:NTL-ALL_op]#The insn:ntl.all[] instruction indicates that the target instruction does not
exhibit temporal locality within the capacity of any level of cache in
the memory hierarchy.# [#norm:NTL-ALL_enc]#insn:ntl.all[] is encoded as insn:add[x0,x0,x5].#

[NOTE]
====
The insn:ntl[] instructions can be used to avoid cache pollution when streaming
data or traversing large data structures, or to reduce latency in
producer-consumer interactions.

A microarchitecture might use the insn:ntl[] instructions to inform the cache
replacement policy, or to decide which cache to allocate into, or to
avoid cache allocation altogether. For example, insn:ntl.p1[] might indicate
that an implementation should not allocate a line in a private L1 cache,
but should allocate in L2 (whether private or shared). In another
implementation, insn:ntl.p1[] might allocate the line in L1, but in the
least-recently used state.

insn:ntl.all[] will typically inform implementations not to allocate anywhere
in the cache hierarchy. Programmers should use insn:ntl.all[] for accesses that
have no exploitable temporal locality.

Like any HINTs, these instructions may be freely ignored. Hence,
although they are described in terms of cache-based memory hierarchies,
they do not mandate the provision of caches.

Some implementations might respect these HINTs for some memory accesses
but not others: e.g., implementations that implement LR/SC by acquiring
a cache line in the exclusive state in L1 might ignore insn:ntl[] instructions
on LR and SC, but might respect insn:ntl[] instructions for AMOs and regular
loads and stores.
====

<<ntl-portable>> lists several software use cases and the recommended insn:ntl[] variant that _portable_ software—i.e., software not tuned for any specific implementation's memory hierarchy—should use in each case.

[[ntl-portable]]
.Recommended insn:ntl[] variant for portable software to employ in various scenarios.
[%autowidth,float="center",align="center",cols="<,<",options="header",]
|===
|Scenario |Recommended insn:ntl[] variant
|Access to a working set between 64 KiB and 256 KiB in size |insn:ntl.p1[]
|Access to a working set between 256 KiB and 1 MiB in size |insn:ntl.pall[]
|Access to a working set greater than 1 MiB in size |insn:ntl.s1[]
|Access with no exploitable temporal locality (e.g., streaming) |insn:ntl.all[]
|Access to a contended synchronization variable |insn:ntl.pall[]
|===

[NOTE]
====
The working-set sizes listed in <<ntl-portable>> are not meant to
constrain implementers' cache-sizing decisions.
Cache sizes will obviously vary between implementations, and so software
writers should only take these working-set sizes as rough guidelines.
====

<<ntl>> lists several sample memory hierarchies and
recommends how each insn:ntl[] variant maps onto each cache level. The table
also recommends which insn:ntl[] variant that implementation-tuned software
should use to avoid allocating in a particular cache level. For example,
for a system with a private L1 and a shared L2, it is recommended that
insn:ntl.p1[] and insn:ntl.pall[] indicate that temporal locality cannot be exploited
by the L1, and that insn:ntl.s1[] and insn:ntl.all[] indicate that temporal locality
cannot be exploited by the L2. Furthermore, software tuned for such a
system should use insn:ntl.p1[] to indicate a lack of temporal locality
exploitable by the L1, or should use insn:ntl.all[] indicate a lack of temporal
locality exploitable by the L2.

[#norm:NTL-compressed_variants]#If the ext:c[] or ext:zca[] extension is provided, compressed variants of these HINTs are
also provided: insn:c.ntl.p1[] is encoded as insn:c.add[x0,x2]; insn:c.ntl.pall[] is
encoded as insn:c.add[x0,x3]; insn:c.ntl.s1[] is encoded as insn:c.add[x0,x4]; and
insn:c.ntl.all[] is encoded as insn:c.add[x0,x5].#

[#norm:NTL_range]#The insn:ntl[] instructions affect all memory-access instructions except the
cache-management instructions in the ext:zicbom[] extension.#

[NOTE]
====
As of this writing, there are no other exceptions to this rule, and so
the insn:ntl[] instructions affect all memory-access instructions defined in
the base ISAs and the ext:a[], ext:f[], ext:d[], ext:q[], ext:c[], and ext:v[] standard extensions, as well
as those defined within the hypervisor extension in <<hypervisor>>.

The insn:ntl[] instructions can affect cache-management operations other than
those in the ext:zicbom[] extension. For example, insn:ntl.pall[] followed by
insn:cbo.zero[] might indicate that the line should be allocated in L3 and
zeroed, but not allocated in L1 or L2.
====

<<<

[[ntl]]
[%autowidth,float="center",align="center",cols="<,^,^,^,^,^,^,^,^",options="header"]
.Mapping of insn:ntl[] variants to various memory hierarchies.
|===
| Memory hierarchy 4+| Recommended mapping of insn:ntl[] +
variant to actual cache level 4+| Recommended insn:ntl[] variant for +
explicit cache management
|
|P1 |PALL |S1 |ALL
|L1 |L2 |L3 |L4/L5
 9+^| Common Scenarios
| No caches 4+|--- 4+|none
|Private L1 only |L1 |L1 |L1 |L1| ALL |--- |--- |---
|Private L1; shared L2 |L1  |L1  |L2  |L2 |P1|ALL|---|---
|Private L1; shared L2/L3 |L1 | L1 | L2 | L3 |P1  |S1   |ALL |---
|Private L1/L2 |L1  |L2  |L2  |L2 | P1  |ALL  |--- |---
|Private L1/L2; shared L3 |L1 | L2 | L3 | L3 | P1 | PALL| ALL |---
|Private L1/L2; shared L3/L4 | L1 | L2|  L3 | L4 | P1 | PALL | S1 | ALL
 9+^| Uncommon Scenarios
|Private L1/L2/L3; shared L4 | L1 | L3 |L4 |L4 |P1 |P1 |PALL |ALL
|Private L1; shared L2/L3/L4 |L1 | L1 |L2 |L4 |P1 |S1 |ALL |ALL
|Private L1/L2; shared L3/L4/L5  |L1 | L2 | L3 | L5 |P1 | PALL |S1 |ALL
|Private L1/L2/L3; shared L4/L5  |L1 |L3 |L4 |L5 |P1 |P1 |PALL |ALL
|===

[#norm:NTL_Zicob_prefetch_outer]#When an insn:ntl[] instruction is applied to a
prefetch hint in the ext:zicbop[] extension, it indicates that a cache line
should be prefetched into a cache that is _outer_ from the level specified by
the insn:ntl[].#

[NOTE]
====
For example, in a system with a private L1 and shared L2, insn:ntl.p1[]
followed by insn:prefetch.r[] might prefetch into L2 with read intent.

To prefetch into the innermost level of cache, do not prefix the
prefetch instruction with an insn:ntl[] instruction.

In some systems, insn:ntl.all[] followed by a prefetch instruction might
prefetch into a cache or prefetch buffer internal to a memory
controller.
====

Software is discouraged from following an insn:ntl[] instruction with an
instruction that does not explicitly access memory. Nonadherence to this
recommendation might reduce performance but otherwise has no
architecturally visible effect.

[#norm:NTL_trap_behavior]#In the event that a trap is taken on the target instruction,
implementations are discouraged from applying the insn:ntl[] to the first
instruction in the trap handler. Instead, implementations are
recommended to ignore the HINT in this case.#

[NOTE]
====
If an interrupt occurs between the execution of an insn:ntl[] instruction and
its target instruction, execution will normally resume at the target
instruction. The insn:ntl[] instruction being not re-executed does not change
the semantics of the program.

Some implementations might prefer not to process the insn:ntl[] instruction
until the target instruction is seen (e.g., so that the insn:ntl[] can be fused
with the memory access it modifies). Such implementations might
preferentially take the interrupt before the insn:ntl[], rather than between
the insn:ntl[] and the memory access.
====

[[norm:NTL-LR_SC_exception]]
[NOTE]
====
Since the insn:ntl[] instructions are encoded as insn:add[]s, they can be used within
LR/SC loops without voiding the forward-progress guarantee.
However, since using other loads and stores within an LR/SC loop _does_ void the
forward-progress guarantee, the only reason to use an insn:ntl[] within such a
loop is to modify the LR or the SC.
====
