[[ext:zijfal]]
=== ext:zijfal[] Extension for Far Jumps and Calls

This extension defines an unconditional control-transfer instruction,
insn:jfal[] ("jump far and link"), which has greater displacement than the
insn:jal[] instruction defined in the base ISAs.

insn:jfal[] writes the address of the instruction following the
jump (`pc` + 4) into register _rd_, which must be either `x0` or `x1`.
Then, insn:jfal[] sets the `pc` to `pc` + `offset`.

insn:jfal[] is encoded in the same major opcode as insn:jalr[], using
`funct3` patterns 1-7.
(Pattern 0 corresponds to insn:jalr[].)
insn:jfal[] can target a range of -12 MiB to +16 MiB from the current `pc`.

include::images/wavedrom/jfal.edn[]

To reduce hardware cost, offset bits 11{endash}1 and 19{endash}15 are in the
same location as for the JAL instruction, and offset bit 12 is in the same
location as for the conditional branch instructions.
Note, the offset's most-significant bit is the complement of instruction
bit 14.

[NOTE]
====
Because insn:jfal[] is encoded in the same major opcode as insn:jalr[], the
latter of which uses ⅛ of the major opcode, only ⅞ of the major opcode remains
to encode insn:jfal[].
Hence, the displacement is not a power of 2.
It would have been possible to make the displacement symmetric about zero at
the cost of additional logic, but we reasoned that it was more important to
avoid exacerbating critical paths in instruction-fetch units.

We also considered an alternate design that provides symmetric {pm}16 MiB
displacement for the variant that links into `x1` but only {pm}8 MiB for
the variant that does not link, but we rejected it to keep the displacement
for tail calls the same as for regular calls.
====
