[[ext:zijf]]
=== ext:zijf[] Extension for Far Jumps and Calls

This extension defines two unconditional control-transfer instructions,
insn:jf[] ("jump far") and insn:jfal[] ("jump far and link"), which have
greater displacement than the insn:jal[] instruction defined in the base ISAs.

insn:jf[] sets the `pc` to `pc` + `offset`.
insn:jf[] can target a range of qty:±8[MiB].

include::images/wavedrom/jf.edn[]

insn:jfal[] writes the address of the instruction following the
jump (`pc` + 4) into register `x1`.
Then, insn:jfal[] sets the `pc` to `pc` + `offset`.
insn:jfal[] can target a range of qty:±16[MiB].

include::images/wavedrom/jfal.edn[]

[NOTE]
====
To reduce hardware cost, offset bits 11{endash}1 and 19{endash}15 are in the
same location as for the JAL instruction.
As with other control-flow instructions, the sign bit is in bit 31.
`rd` is encoded in bit 12, as with insn:c.jr[] and insn:c.jalr[].
====

[NOTE]
====
Because insn:jf[] and insn:jfal[] are encoded in the same major opcode as
insn:jalr[], the latter of which uses ⅛ of the major opcode,
a non-power-of-2-sized encoding space remains to encode
insn:jf[] and insn:jfal[].
Leveraging the observation that tail calls are substantially less common
than regular calls, insn:jf[] is given a smaller fraction (¼) of the major
opcode than insn:jfal[] (½), hence has half the displacement.
====
