[[ext:zisb]]
=== ext:zisb[] Extension for Speculation Barrier Instructions

Modern CPU pipelines are massively parallelized, leveraging techniques such as
control flow speculation, data value speculation, and data dependency
speculation to enhance efficiency and avoid stalls caused by unresolved
instruction dependencies. However, this aggressive speculation introduces
vulnerabilities to transient execution attacks like Spectre, which exploit
speculative execution to leak sensitive data. The ext:zisb[] extension addresses these
vulnerabilities by introducing speculation barriers, enabling developers to
explicitly control speculation boundaries and ensure that transient
execution--arising from control flow, data value, or dependency
speculation--does not expose data through side channels.

Side Channel is defined as a channel is any medium in a computing system that
may transmit or signal information. Legitimate channels are those intended by
system designers for the transmission of information; all other channels are
incidental channels. An incidental channel becomes a covert channel if an
adversary can control both its input and output. It serves as a side channel
if the adversary can only observe its output, without controlling its input.

Processors that predict the outcomes of branches or loads may use a speculative
value before confirming its correctness, allowing execution to proceed
temporarily based on that prediction. If the speculation is correct, dependent
instructions are valid and may retire. If the speculative value is incorrect,
the dependent instructions must be flushed from the pipeline and re-executed
with the correct value. These flushed instructions are known as transient
instructions. Although transient instructions do not commit results to
architectural state, they can affect microarchitectural state (e.g., caches).
This microarchitectural state forms an incidental channel, which can be observed
using side-channel techniques such as Flush+Reload or Prime+Probe, which measure
the timing of accesses to that state.

Transient Execution Attacks are attacks that exploit the side effects of
transient execution. These attacks access a victim’s secrets and transmit them
via a covert channel using a disclosure gadget. A disclosure gadget is an
instruction sequence that can execute transiently and a) access a victim's
secrets, and b) transmit that secret over a covert channel.

Transient execution attacks can be classified into the following categories:

* Domain-bypass attacks bypass hardware access controls such as privilege
  separation or page tables. Example: Rogue Data Cache Load (Meltdown).

* Cross-domain attacks require a disclosure gadget in the victim's domain, which
  can be transiently executed to access and transmit a secret. Example: Branch
  Target Injection (Spectre Variant 2).

* In-domain attacks allow an adversary to access a secret within the same domain
  by circumventing software-based access controls. Example: Bounds Check Bypass
  (Spectre Variant 1).

The domain-bypass attacks can be mitigated through microarchitectural techniques
such as not allowing faulting loads to provide data to dependent instructions.
The cross-domain attacks can be mitigated by tagging predictors with information
such as the privilege mode that identifies the domain in which the prediction was
created and not using predictions learned in one domain to predict outcomes in
another domain. The in-domain attacks primarily bypass software-based access
controls, and these boundaries are typically not visible to hardware.

The ext:zisb[] extension provides mechanisms to control speculation leading to
in-domain attacks through the use of speculation barrier instructions to
explicitly control speculation boundaries and ensure that transient
execution--arising from control flow, data value, or dependency speculation--does
not expose data through cache-based side channels.

The barrier instructions do not flush or clear predictions. They augment
techniques such as tagging predictions with domain information to disallow
use of predictions created in one domain when executing in another domain.
This extension does not address leakage through incidental channels such as power,
thermal, electromagnetic, or other non-cache-based side channels.

The ext:zisb[] extension depends on the Zimop extension.

[NOTE]
====
These instructions are encoded using Zimop code points, enabling programs to
functionally execute on processors that support the Zimop extension, even if
they do not implement the ext:zisb[] instructions. This ensures compatibility with
processors that either lack ext:zisb[] support or do not require it due to the absence
of speculative execution. Unlike HINT instructions, which may or may not be
honored by hardware, ext:zisb[] instructions represent a strict contract between the
program and the hardware. The semantics of this contract must always be honored,
ensuring robust defense against transient execution vulnerabilities.
====
==== Speculation Barrier Instructions

The ext:zisb[] extension provides three barrier instructions to control speculation
that could lead to in-domain attacks. Using these barrier instructions allows
explicit control of speculation boundaries to ensure that transient execution
--arising from control-flow, data-value, or data-dependency speculation--does
not expose data through cache-based side channels.

* TEB (Transient Execution Barrier): mitigates transient execution due
  to control-flow prediction.
* MDB (Memory Disambiguation Barrier): mitigates transient execution due
  to data-dependency prediction.
* DPB (Data-Value Prediction Barrier): mitigates transient execution due
  to data-value prediction.

===== TEB - Transient Execution Barrier

The TEB instruction has the following barrier semantics:

* The TEB instruction cannot be speculatively executed due to control-flow
  speculation by instructions that appear in program order before TEB.
* Execution of instructions that follow TEB in program order cannot be observed
  through cache-based side channels until TEB completes.

[NOTE]
====
These semantics allow execution of instructions that follow TEB, provided their
execution does not cause revelation of the data used by those instructions
through a cache-based side channel.

Processors may speculate the control flow of a program by predicting the
outcome of a branch using data structures such as a pattern history table
(PHT) before the branch is executed. Eventually, the prediction is verified.
If a misprediction is detected, the speculatively executed instructions are
discarded, the architectural state is recovered, and control flow continues
along the correct path. Speculative execution that occurs before the branch
outcome is verified may be used to leak data through cache-based side channels.
The TEB may be used to control such control-flow speculation, as illustrated by the
following code snippet. This example assumes that the shared data cache can
be exploited as a side channel, allowing an attacker to infer sensitive
information by observing cache access patterns resulting from speculative
execution.

[listing]
 1. void bounds_check_bypass_example(uint32_t x,
 2.  uint8_t *array1, uint32_t len1,
 3.  uint8_t *array2, uint32_t len2) {
 4. if (x < len1)) {
 5.     bgeu    a0, a2, L3
 6. // If the branch at line 5 mispredicts then the load at
 7. // line 15 may use an out-of-bound index into array1 and
 8. // disclose its contents using a side channel caused by
 9. // the load at line 19. The TEB at line 12 prevents
10. // execution of the loads at line 15 and 19 until the
11. // branch resolves.
12.     teb
13.     y = array2[array1[x] * 4096];
14.       add    a5, a0, a1
15.       lbu    a5, 0(a1)
16.       sext.w a5, a5
17.       sllw   a5, a5,0xc
18.       add    a5, a5, a3
19.       lbu    a5,0(a5)
20. }
21. L3:

====

===== MDB - Memory Disambiguation Barrier

The MDB instruction has the following barrier semantics:

* An instruction that loads from memory and appears in program order after MDB
  must obtain its data from the last instruction that stores to the same physical
  memory location and appears in program order before MDB. These semantics shall
  be enforced regardless of whether the load and/or the store are speculative
  and regardless of whether the load and/or store eventually complete.

[NOTE]
====
This semantic prevents loads that appear in program order after MDB from
bypassing a store that appears in program order before MDB unless the physical
address to which that store will write has been determined. A load that appears
in program order after MDB must obtain its data either from a preceding store
that has been determined to write to the same physical memory location (e.g.,
through store-to-load forwarding) or from the memory that the store writes to.
Such a load may execute even if it is speculative.
====

* Instructions that load from memory and precede MDB in program order must not
  speculatively obtain their data from any instructions that store to memory and
  appear in program order after MDB.

[NOTE]
====
A load instruction may depend on a preceding store. If the address of the
preceding store is not yet known, an implementation may either block loads
until all preceding store addresses are known or may employ a memory
disambiguation predictor to predict whether a load is dependent on a previous
store. When the disambiguator predicts that a load does not have such a
dependency, the load obtains its data from the data cache or memory.
Eventually, the prediction is verified. If an actual conflict is detected,
the load and all succeeding instructions are re-executed. The speculative
store bypass that occurs when the prediction is wrong may be exploited to
leak data using cache-based side channels. The MDB may be used to control such
data-dependency speculation, as illustrated by the following code snippet.

[listing]
 1. typedef void (*msg_handler)(uint8_t *data, uint32_t size);
 2. extern void proc1(uint8_t *data, uint32_t size);
 3. extern void proc2(uint8_t *data, uint32_t size);
 4. extern uint32_t mode;
 5. msg_handler get_handler(uint32_t mode) {
 6.   return (mode == 0) ? proc1 : proc2;
 7. }
 8. void memory_disambiguation_example(uint8_t *data, uint32_t len) {
 9.       add  sp, sp, -32
10.       sd   ra, 24(sp)
11.       sd   a0, 16(sp)
12.       sd   a1,  8(sp)
13.   msg_handler mh = get_handler(mode);
14.       la   a0, mode
15.       la   ra, get_handler
16.       jalr ra
17. // The address of the handler is stored in the
18. // variable `mh` by the store at line 19.
19.       sd   a0, 0(sp)
20.   mh(data, len);
21. // If the load at line 32 bypasses the store at line 19, it
22. // may read the old contents of the stack and provide that as
23. // the target to JALR at line 33. The old contents may be
24. // controlled by untrusted entities and allow speculative
25. // execution of a disclosure gadget that could leak
26. // information through a cache-based side channel. The MDB at line 29
27. // ensures that the LD at line 32 cannot bypass SD at line 19
28. // thereby ensuring that it gets the data stored by that SD.
29.       mdb
30.       ld   a0, 16(sp)
31.       ld   a1,  8(sp)
32.       ld   ra,  0(sp)
33.       jalr ra
34.       ld   ra, 24(sp)
35.       add  sp, sp, 32
36.       ret
37. }

====

===== DPB - Data-value Prediction Barrier

The DPB instruction has the following barrier semantics:

* Instructions that appear in program order after a DPB must not execute with
  operand values that are the result of data-value speculation by instructions
  in program order before the DPB, until the DPB completes, if such execution
  could be observed through cache-based side channels.

[NOTE]
====
Modern processors may predict the result of computations or load operations
based on previously observed data values. These predictions, when used
speculatively, can be influenced by attackers to access out-of-bounds or
unauthorized memory. Eventually, the prediction is verified. If a
misprediction is detected, all succeeding instructions are re-executed. When
the prediction is wrong, the transient execution may be exploited to leak
data using cache-based side channels. The DPB may be used to control such
data-value speculation, as illustrated by the following code snippet.

[listing]
 1. uint32_t cur_priv;
 2. uint8_t data_value_prediction_example(uint32_t index,
 3.                 uint8_t *priv_array, uint8_t *unpriv_array) {
 4.   uint8_t *array;
 5.   array = (cur_priv == 0) ? priv_array : unpriv_array;
 6.       la         t0, cur_priv
 7.       lw         t0, 0(t0)
 8.       la         a1, priv_array
 9.       la         a2, unpriv_array
10.   // If the data value of cur_priv was predicted by the load
11.   // at line 7 and the prediction was incorrect, then data may
12.   // be loaded from the wrong array speculatively by the load
13.   // at line 22. The DPB at line 16 ensures that the load at
14.   // line 22 will not execute speculatively using a predicted
15.   // data value.
16.       dpb
17.       czero.eqz  a2, a2, t0
18.       czero.nez  a1, a1, t0
19.       or         t0, a1, a2
20.   return array[index];
21.       add        t0, t0, a0
22.       lbu        a0, 0(t0)
23. }

====
