[[ext:zmmul]]
=== ext:zmmul[] Extension for Integer Multiplication

(((MUL, Zmmul)))
The ext:zmmul[] extension implements the multiplication subset of the ext:m[]
extension. It adds the following instructions defined in extlink:m[]:
insn:mul[], insn:mulh[], insn:mulhu[], insn:mulhsu[], and (for RV64 only)
insn:mulw[]. The encodings and semantics are identical to those of the
corresponding instructions in ext:m[]. ext:m[] implies ext:zmmul[].
[NOTE]
====
The ext:zmmul[] extension enables low-cost implementations that require
multiplication operations but not division. For many microcontroller
applications, division operations are too infrequent to justify the cost
of divider hardware. By contrast, multiplication operations are more
frequent, making the cost of multiplier hardware more justifiable.
Simple FPGA soft cores particularly benefit from eliminating division
but retaining multiplication, since many FPGAs provide hardwired
multipliers but require dividers be implemented in soft logic.
====
