[[vector]]
== Vector Extensions

NOTE: This chapter is currently being restructured.
Its contents are normative, but the presentation might appear disjoint.

RISC-V provides several vector extensions that add vector registers of
implementation-defined length and instructions that operate on those
registers, mostly in SIMD fashion.
The extlink:zve32x[] extension is the base vector extension, providing
the architectural state and the operations on 8-, 16-, and 32-bit
integer and fixed-point types.
The extlink:zve64x[] extension includes the ext:zve32x[] functionality
and adds support for 64-bit integers.
The extlink:zve32f[] extension includes the ext:zve32x[] functionality
and adds single-precision floating-point support.
The extlink:zve64f[] extension is the union of
ext:zve64x[] and ext:zve64f[].
The extlink:zve64d[] extension extends ext:zve64f[] by adding
double-precision floating-point support.

The extlink:V[] extension, intended for application processors,
builds on ext:zve64d[] and imposes a minimum vector length of 128 bits.

Several additional ext:Zv*[] extensions that add new arithmetic
and permutation instructions are also defined.

include::vector-common.adoc[]
include::zve32x.adoc[]
include::zve32f.adoc[]
include::zve64x.adoc[]
include::zve64f.adoc[]
include::zve64d.adoc[]
include::v-st-ext.adoc[]
include::zvfhmin.adoc[]
include::zvfh.adoc[]
include::zvfbfmin.adoc[]
include::zvfbfwma.adoc[]

==== Vector Instruction Listing

include::images/wavedrom/v-inst-table.edn[]

//
