[[ext:zve64x]]
=== ext:zve64x[] 64-bit Integer Vector Extension

This section describes ext:zve64x[], the vector extension for 8-, 16-,
32-, and 64-bit integer and fixed-point types.
It is compatible with all currently defined base ISAs.

[#norm:Zve32f_Zve64x_dependent_Zve32x]#ext:zve64x[] depends upon the ext:zve32x[] extension.#

ext:zve64x[] provides support for EEW of 8, 16, 32, and 64.

ext:zve64x[] supports the vector configuration instructions
(<<sec-vector-config>>).

[#norm:Zve_nsupport_eew64_xlen32]#ext:zve64x[] supports all vector load and store instructions
(<<sec-vector-memory>>),
except EEW=64 for index values is not supported when XLEN=32.#

[#norm:Zve64_eew64_nsupport_vmulh]#ext:zve64x[] supports all vector integer instructions
(<<sec-vector-integer>>), except that
the insn:vmulh[] integer multiply
variants that return the high half of the product (insn:vmulh.vv[],
insn:vmulh.vx[], insn:vmulhu.vv[], insn:vmulhu.vx[], insn:vmulhsu.vv[],
insn:vmulhsu.vx[]) are not included for EEW=64.#

NOTE: Producing the high-word of a product can take substantial
additional gates for large EEW.

[#norm:Zve64_eew64_nsupport_vsmul]#ext:zve64x[] supports all vector fixed-point arithmetic
instructions (<<sec-vector-fixed-point>>), except that insn:vsmul.vv[] and
insn:vsmul.vx[] are not included for EEW=64.#

NOTE: As with insn:vmulh[], insn:vsmul[] requires a large amount of additional
logic, and 64-bit fixed-point multiplies are relatively rare.

ext:zve64x[] supports all vector integer single-width and
widening reduction operations (<<sec-vector-integer-reduce>>,
<<sec-vector-integer-reduce-widen>>).

ext:zve64x[] supports all vector mask instructions
(<<sec-vector-mask>>).

ext:zve64x[] supports all vector integer permutation instructions
(<<sec-vector-integer-permute>>).

//
