[[ext:zvfbfa]]
=== ext:zvfbfa[] Vector Extension for Additional BF16 Computation

The Zvfbfa extension adds more complete BF16 vector compute support.

The Zvfbfa extension requires the Zve32f and Zfbfmin extensions.

NOTE: Zvfbfa is compatible with, but does not require, Zvfbfwma and
Zvfbfmin.

Zvfbfa adds a 1-bit field, csr::[altfmt], to the csr:vtype[] CSR in bit position 8.
Attempting to set csr::[altfmt]=1 and SEW >= 32 is reserved.

NOTE: The recommended assembly syntax to set csr::[altfmt]=1 is to append the token
`alt` to the SEW setting, e.g. insn:vsetvli[a0,a1,e16alt,m1,ta,ma].

NOTE: Implementations should set csr:vtype[vill] when a reserved combination
of csr::[altfmt] and SEW is selected.

When csr::[altfmt]=0, the hart behaves as though Zvfbfa were not implemented.

When csr::[altfmt]=1 and SEW=8, all vector floating-point instructions become
reserved, except for the following, which are redefined to use the BF16
format for any operand that would otherwise have used the FP16 format:

- insn:vfwcvt.f.x.v[], insn:vfwcvt.f.xu.v[]
- insn:vfncvt.x.f.w[], insn:vfncvt.xu.f.w[]
- insn:vfncvt.rtz.x.f.w[], insn:vfncvt.rtz.xu.f.w[]

When csr::[altfmt]=1 and SEW=16, all vector floating-point instructions become
reserved, except for the following, which are redefined to use the BF16
format for any operand that would otherwise have used the FP16 format:

- insn:vfadd.vv[], insn:vfadd.vf[]
- insn:vfsub.vv[], insn:vfsub.vf[]
- insn:vfmin.vv[], insn:vfmin.vf[]
- insn:vfmax.vv[], insn:vfmax.vf[]
- insn:vfsgnj.vv[], insn:vfsgnj.vf[] ††
- insn:vfsgnjn.vv[], insn:vfsgnjn.vf[] ††
- insn:vfsgnjx.vv[], insn:vfsgnjx.vf[] ††
- insn:vfslide1up.vf[] ††
- insn:vfslide1down.vf[] ††
- insn:vfmv.v.f[] ††
- insn:vfmerge.vfm[] ††
- insn:vmfeq.vv[], insn:vmfeq.vf[]
- insn:vmfle.vv[], insn:vmfle.vf[]
- insn:vmflt.vv[], insn:vmflt.vf[]
- insn:vmfne.vv[], insn:vmfne.vf[]
- insn:vmfgt.vf[]
- insn:vmfge.vf[]
- insn:vfmul.vv[], insn:vfmul.vf[]
- insn:vfrsub.vf[]
- insn:vfmadd.vv[], insn:vfmadd.vf[]
- insn:vfnmadd.vv[], insn:vfnmadd.vf[]
- insn:vfmsub.vv[], insn:vfmsub.vf[]
- insn:vfnmsub.vv[], insn:vfnmsub.vf[]
- insn:vfmacc.vv[], insn:vfmacc.vf[]
- insn:vfnmacc.vv[], insn:vfnmacc.vf[]
- insn:vfmsac.vv[], insn:vfmsac.vf[]
- insn:vfnmsac.vv[], insn:vfnmsac.vf[]
- insn:vfwadd.vv[], insn:vfwadd.vf[]
- insn:vfwsub.vv[], insn:vfwsub.vf[]
- insn:vfwadd.wv[], insn:vfwadd.wf[]
- insn:vfwsub.wv[], insn:vfwsub.wf[]
- insn:vfwmul.vv[], insn:vfwmul.vf[]
- insn:vfwmacc.vv[], insn:vfwmacc.vf[]
- insn:vfwnmacc.vv[], insn:vfwnmacc.vf[]
- insn:vfwmsac.vv[], insn:vfwmsac.vf[]
- insn:vfwnmsac.vv[], insn:vfwnmsac.vf[]
- insn:vfmv.s.f[] ††
- insn:vfmv.f.s[] †
- insn:vfwcvt.f.f.v[]
- insn:vfncvt.f.f.w[]
- insn:vfncvt.rod.f.f.w[]
- insn:vfrsqrt7.v[]
- insn:vfrec7.v[] †††
- insn:vfclass.v[]
- insn:vfwmaccbf16.vv[], insn:vfwmaccbf16.vf[] † (only if Zvfbfwma is implemented)
- insn:vfwcvtbf16.f.f.v[] † (only if Zvfbfmin is implemented)
- insn:vfncvtbf16.f.f.w[] † (only if Zvfbfmin is implemented)


† These instructions have the same semantics regardless of csr::[altfmt].

†† These instructions differ only in that improperly NaN-boxed
`f`-register operands must substitute the BF16 canonical NaN instead of the
FP16 canonical NaN.

††† For insn:vfrec7.v[], some inputs greater than 2^126^ produce subnormal results that
cannot be exactly represented in BF16's limited precision.
These results are rounded towards zero.

NOTE: The operations from ext:zve32f[] that are excluded from ext:zvfbfa[] are
division, square root, reductions, and conversions to/from integers wider than
8 bits.
These operations can be performed by converting to and from FP32.
