[[ext:zvfbfwma]]
=== ext:zvfbfwma[] Extension for Vector BF16 Widening Multiply-Accumulation

This extension adds vector instructions that multiply BF16 numbers and
accumulate into FP32.

[[norm:zvfbfwma_depends]]
This extension depends upon the ext:zvfbfmin[] and ext:zfbfmin[] extensions.

==== insn:vfwmaccbf16[]

Synopsis::
Vector BF16 widening multiply-accumulate

Mnemonic::
insn:vfwmaccbf16.vv[vd,vs1,vs2,vm]
insn:vfwmaccbf16.vf[vd,rs1,vs2,vm]

Encoding (Vector-Vector)::
[[norm:vfwmaccbf16_encoding_vv]]
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '001', attr:['OPFVV']},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '111011', attr:['vfwmaccbf16']},
]}
....

Encoding (Vector-Scalar)::
[[norm:vfwmaccbf16_encoding_vf]]
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '101', attr:['OPFVF']},
{bits: 5, name: 'rs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '111011', attr:['vfwmaccbf16']},
]}
....

Reserved Encodings::
[[norm:vfwmaccbf16_sew_rsv]]
* `SEW` is any value other than 16

Arguments::
[%autowidth]
[%header,cols="4,2,2,2"]
|===
|Register
|Direction
|EEW
|Definition

| Vd      | input  | 32  | FP32 Accumulate
| Vs1/rs1 | input  | 16  | BF16 Source
| Vs2     | input  | 16  | BF16 Source
| Vd      | output | 32  | FP32 Result
|===

Description::

[[norm:vfwmaccbf16_op]]
This instruction performs a widening fused multiply-accumulate
operation, where each pair of BF16 values are multiplied and their
unrounded product is added to the corresponding FP32 accumulate value.
The sum is rounded according to the _frm_ register.

[[norm:vfwmaccbf16_vv]]
In the vector-vector version, the BF16 elements are read from `vs1`
and `vs2` and FP32 accumulate value is read from `vd`. The FP32 result
is written to the destination register `vd`.

[[norm:vfwmaccbf16_vf]]
The vector-scalar version is similar, but instead of reading elements
from `vs1`, a scalar BF16 value is read from the FPU register `rs1`.


Exceptions: Overflow, Underflow, Inexact, Invalid

Operation::

This insn:vfwmaccbf16.vv[] instruction is equivalent to widening each of the BF16 inputs to
FP32 and then performing an FMACC as shown in the following
instruction sequence:

[source,asm]
--
vfwcvtbf16.f.f.v T1, vs1, vm
vfwcvtbf16.f.f.v T2, vs2, vm
vfmacc.vv        vd, T1, T2, vm
--

Likewise, insn:vfwmaccbf16.vf[] is equivalent to the following instruction sequence:

[source,asm]
--
fcvt.s.bf16      T1, rs1
vfwcvtbf16.f.f.v T2, vs2, vm
vfmacc.vf        vd, T1, T2, vm
--

//
