[[ext:zvfh]]
=== ext:zvfh[]: Vector Extension for Half-Precision Floating-Point

The ext:zvfh[] extension provides support for vectors of IEEE 754-2008
binary16 values.
[#norm:Zvfh_instr]#When the ext:zvfh[] extension is implemented, all instructions in
<<sec-vector-float>>, <<sec-vector-float-reduce>>,
<<sec-vector-float-reduce-widen>>, <<sec-vector-float-move>>,
<<sec-vfslide1up>>, and <<sec-vfslide1down>>
become defined when SEW=16.#
[#norm:Zvfh_eew16]#The EEW=16 floating-point operands of these instructions use the binary16
format.#

[#norm:Zvfh_instr_cvt]#Additionally, conversions between 8-bit integers and binary16 values are
provided.  The floating-point-to-integer narrowing conversions
(insn:vfncvt.x.f.w[], insn:vfncvt.xu.f.w[], insn:vfncvt.rtz.x.f.w[], and insn:vfncvt.rtz.xu.f.w[]) and integer-to-floating-point
widening conversions (insn:vfwcvt.f.x.v[] and insn:vfwcvt.f.xu.v[]) become defined when SEW=8.#

[#norm:Zvfh_dependent_Zve32f_Zfhmin]#The ext:zvfh[] extension depends on the extlink:zve32f[] and extlink:zfhmin[] extensions.#
NOTE: Requiring basic scalar half-precision support makes ext:zvfh[]'s
vector-scalar instructions substantially more useful.
We considered requiring more complete scalar half-precision support, but we
reasoned that, for many half-precision vector workloads, performing the scalar
computation in single-precision will suffice.
