[[encap-intro]]
== Introduction

The Efficient Trace for RISC-V (E-Trace) standard in <<chap:trace>> defines packet payloads for instruction and data trace but does not fully define how this should be encapsulated into fully formed packets for transport, nor how instruction and data trace should be differentiated.  <<packets>> gives some illustrative examples but this is insufficiently detailed and informative only.

Although the primary motivation for developing this standard was to define an encapsulation format for E-Trace packets that allows tools to parse and decode them in a standard manner, the encapsulation format defined in this chapter is agnostic to the packet payload structure and meaning and so can be used for any kind of unformatted data.  In addition to E-trace, it could also be used for a wide variety of other uses, for example: performance counter metrics, trace or other diagnostic data from a bus fabric monitor or on-chip logic analyser. 

It is not suitable for data that has already been formatted into packets, such as N-Trace, which inserts a 2-bit MSEO formatting code into each byte.

This chapter defines an encapsulation format suitable for use with a variety of transport mechanisms, including but not limited to AMBA Advanced Trace Bus (ATB) and Siemens' Messaging Infrastructure.

Examples of how trace packets can be routed for transport is given in the 'Trace Components' subsection of the https://github.com/riscv-non-isa/tg-nexus-trace/blob/master/docs/RISC-V-Trace-Control-Interface.adoc[RISC-V Trace Control Interface Specification].

=== Glossary

* *ATB* - Advanced Trace Bus, a protocol described in ARM document IHI0032B;
* *E-Trace* - Abbreviation for Efficient Trace for RISC-V, <<chap:trace>>;
* *PIB* - Pin Interface Block, a parallel or serial off-chip trace port feeding into a trace probe, as defined in the https://github.com/riscv-non-isa/tg-nexus-trace/blob/master/docs/RISC-V-Trace-Control-Interface.adoc[RISC-V Trace Control Interface Specification];
* *N-Trace* - Abbreviation for https://github.com/riscv-non-isa/tg-nexus-trace/blob/master/docs/RISC-V-N-Trace.adoc[RISC-V N-Trace (Nexus-based trace) Specification]
* *Trace Encoder* - Hardware module that accepts execution information from a hart and generates a stream of trace packets;
* *TFP* - Trace Formatter protocol, a trace framing protocol described in ARM document IHI0029E.  Also adopted by MIPI as Trace Wrapper Protocol (TWP);
* *TWP* - See *TFP*.

