[colophon]
== Preface

This document describes the RISC-V debug and trace architecture.
It contains the following versions of the RISC-V debug and trace modules,
all of which have been ratified:

[%autowidth,float="center",align="center",cols="^,<",options="header",]
|===
|Module |Version
|Debug |1.0
|Efficient Trace (E-Trace) |2.0.2

h|Extension h|Version

|Sdext |1.0
|Sdtrig |1.0
|===

Contributors to all versions of the debug specification in alphabetical order
(please contact the editors to suggest corrections): Bruce Ableidinger, Krste
Asanović, Peter Ashenden, Allen Baum, Mark Beal, Alex Bradbury, Chuanhua
Chang, Yen Hao Chen, Zhong-Ho Chen, Monte Dalrymple, Paul Donahue,
Vyacheslav Dyachenko, Ernie Edgar, Peter Egold, Marc Gauthier, Markus
Goehrle, Robert Golla, John Hauser, Richard Herveille, Yung-ching Hsiao,
Po-wei Huang, Scott Johnson, L. J. Madar, Grigorios Magklis, Daniel
Mangum, Alexis Marquet, Jan Matyas, Kai Meinhard, Jean-Luc Nagel, Aram
Nahidipour, Rishiyur Nikhil, Gajinder Panesar, Deepak Panwar, Antony
Pavlov, Klaus Kruse Pedersen, Ken Pettit, Darius Rad, Joe Rahmeh, Josh
Scheid, Vedvyas Shanbhogue, Gavin Stark, Ben Staveley, Wesley Terpstra,
Tommy Thorn, Megan Wachs, Jan-Willem van de Waerdt, Philipp Wagner,
Stefan Wallentowitz, Ray Van De Walker, Andrew Waterman, Thomas Wicki,
Andy Wright, Bryan Wyatt, and Florian Zaruba.

The Efficient Trace for RISC-V specification was authored by Gajinder
Panesar and Iain Robertson.

//
