= Preamble

_This document is released under a Creative Commons Attribution 4.0 International License._

_This document is a derivative of the RISC-V
privileged specification version 1.9.1 released under following license: ©2010-2017 Andrew Waterman, Yunsup Lee, Rimas Avižienis, David Patterson, Krste Asanović. Creative Commons Attribution 4.0 International License._


== Contributors

_Contributors to all versions of the spec in alphabetical order (please contact editors to suggest corrections):
Krste Asanović,
Peter Ashenden,
Rimas Avižienis,
Jacob Bachmeyer,
Allen J. Baum,
Jonathan Behrens,
Paolo Bonzini,
Ruslan Bukin,
Christopher Celio,
Chuanhua Chang,
David Chisnall,
Anthony Coulter,
Palmer Dabbelt,
Monte Dalrymple,
Paul Donahue,
Greg Favor,
Dennis Ferguson,
Marc Gauthier,
Andy Glew,
Gary Guo,
Mike Frysinger,
John Hauser,
David Horner,
Olof Johansson,
David Kruckemyer,
Yunsup Lee,
Daniel Lustig,
Andrew Lutomirski,
Martin Maas,
Prashanth Mundkur,
Jonathan Neuschäfer,
Rishiyur Nikhil,
Stefan O'Rear,
Albert Ou,
John Ousterhout,
David Patterson,
Dmitri Pavlov,
Kade Phillips,
Josh Scheid,
Colin Schmidt,
Michael Taylor,
Wesley Terpstra,
Matt Thomas,
Tommy Thorn,
Ray VanDeWalker,
Megan Wachs,
Steve Wallach,
Andrew Waterman,
Claire Wolf,
Adam Zabrocki,
and Reinoud Zandijk._

Please contact RISC-V International to suggest corrections.
