== RVA23 Profiles

The RVA23 profiles are intended to align implementations of RISC-V
64-bit application processors to allow binary software ecosystems to
rely on a large set of guaranteed extensions and a small number of
discoverable coarse-grain options.  It is explicitly a non-goal of
RVA23 to allow more hardware implementation flexibility by supporting
only a minimal set of features and a large number of fine-grain
extensions.

Only user-mode (RVA23U64) and supervisor-mode (RVA23S64) profiles are
specified in this family.

=== RVA23U64 Profile

The RVA23U64 profile specifies the ISA features available to user-mode
execution environments in 64-bit applications processors.  This is the
most important profile within the application processor family in
terms of the amount of software that targets this profile.

==== RVA23U64 Mandatory Base

RV64I is the mandatory base ISA for RVA23U64 and is little-endian.  As
per the unprivileged architecture specification, the `ECALL`
instruction causes a requested trap to the execution environment.

==== RVA23U64 Mandatory Extensions

The following mandatory extensions were present in RVA22U64.

- <<mstandard,**M**>> Integer multiplication and division.
- <<chap:a,**A**>> Atomic instructions.
- <<single-float,**F**>> Single-precision floating-point instructions.
- <<chap:d,**D**>> Double-precision floating-point instructions.
- <<compressed,**C**>> Compressed instructions.
- <<bits,**B**>> Bit-manipulation instructions.
- <<csrinsts,**Zicsr**>>  CSR instructions.  These are implied by presence of F.
- <<counters,**Zicntr**>> Base counters and timers.
- <<counters,**Zihpm**>> Hardware performance counters.
- <<ziccif,**Ziccif**>> Main memory regions with both the cacheability and
  coherence PMAs must support instruction fetch, and any instruction
  fetches of naturally aligned power-of-2 sizes up to min(ILEN,XLEN)
  (i.e., 32 bits for RVA23) are atomic.
- <<ziccrse,**Ziccrse**>> Main memory regions with both the cacheability and coherence PMAs must support RsrvEventual.
- <<ziccamoa,**Ziccamoa**>> Main memory regions with both the cacheability and coherence PMAs must support all atomics in the Zaamo extension.
- <<zicclsm,**Zicclsm**>> Misaligned loads and stores to main memory regions with both the
  cacheability and coherence PMAs must be supported.
- <<za64rs,**Za64rs**>> Reservation sets are contiguous, naturally aligned, and a
   maximum of 64 bytes.
- <<zihintpause,**Zihintpause**>> Pause hint.
- <<zic64b,**Zic64b**>> Cache blocks must be 64 bytes in size, naturally aligned in the
address space.
- <<cmo,**Zicbom**>> Cache-block management instructions.
- <<cmo,**Zicbop**>> Cache-block prefetch instructions.
- <<cmo,**Zicboz**>> Cache-Block Zero Instructions.
- <<zfhmin,**Zfhmin**>> Half-precision floating-point.
- <<zkt,**Zkt**>> Data-independent execution latency.

The following mandatory extensions are new in RVA23U64:

- <<vector,**V**>> Vector extension.

NOTE: V was optional in RVA22U64.

- *Zvfhmin* Vector minimal half-precision floating-point.

- *Zvbb* Vector basic bit-manipulation instructions.

- *Zvkt* Vector data-independent execution latency.

- *Zihintntl* Non-temporal locality hints.

- *Zicond* Integer conditional operations.

- *Zimop* may-be-operations.

- *Zcmop* Compressed may-be-operations.

- *Zcb* Additional compressed instructions.

- *Zfa* Additional floating-Point instructions.

- *Zawrs* Wait-on-reservation-set instructions.

- *Supm* Pointer masking, with the execution environment providing a means to
   select PMLEN=0 and PMLEN=7 at minimum.

==== RVA23U64 Optional Extensions

===== Localized Options

The following localized options are new in RVA23U64:

- *Zvkng* Vector crypto NIST algorithms with GCM.
- *Zvksg* Vector crypto ShangMi algorithms with GCM.

NOTE: The scalar crypto extensions Zkn and Zks that were options in
RVA22 are not options in RVA23.  The goal is for both hardware and
software vendors to move to use vector crypto, as vectors are now
mandatory and vector crypto is substantially faster than scalar
crypto.

NOTE: We have included only the Zvkng/Zvksg options with GCM to
standardize on a higher performance crypto alternative. Zvbc is listed
as a development option for use in other algorithms, and will become
mandatory.  Scalar Zbc is now listed as an expansion option, i.e., it
will probably not become mandatory.

===== Development Options

The following are new development options intended to become mandatory in a future RVA profile.

- *Zabha* Byte and halfword atomic memory operations.
- *Zacas* Compare-and-Swap instructions.
- *Ziccamoc* Main memory regions with both the cacheability and coherence PMAs
  must provide `AMOCASQ` level PMA support.

NOTE: Ziccamoc is a new profile-defined extension that ensures
Compare and Swap instructions are properly supported in main memory
regions.  The extension will be added to the PMA section of the
privileged architecture manual.

- *Zvbc* Vector carryless multiplication.
- *Zama16b* Misaligned loads, stores, and AMOs to main memory regions that do not cross a naturally aligned 16-byte boundary are atomic.

NOTE: Zama16b is a new profile-defined extension that represents
the presence of the new Misaligned Atomicity Granule feature added in
Sm1p13.  The extension will be added to the PMA section of the
privileged architecture manual.

===== Expansion Options

The following expansion options were also present in RVA22U64:

- <<chap:zfh,**Zfh**>> Scalar half-precision floating-point.

The following are new expansion options in RVA23U64:

- *Zbc* Scalar carryless multiply.
- *Zicfilp* Landing Pads.
- *Zicfiss* Shadow Stack.
- *Zvfh* Vector half-precision floating-point.
- *Zfbfmin* Scalar BF16 converts.
- *Zvfbfmin* Vector BF16 converts.
- *Zvfbfwma* Vector BF16 widening mul-add.

===== Transitory Options

There are no transitory options in RVA23U64.

NOTE: Scalar crypto is no longer an option in RVA23U64, though the Zbc
extension has now been exposed as an expansion option.

==== RVA23U64 Recommendations

Implementations are strongly recommended to raise illegal-instruction
exceptions on attempts to execute unimplemented opcodes.

=== RVA23S64 Profile

The RVA23S64 profile specifies the ISA features available to a
supervisor-mode execution environment in 64-bit applications
processors.  RVA23S64 is based on privileged architecture version
1.13.

==== RVA23S64 Mandatory Base

RV64I is the mandatory base ISA for RVA23S64 and is little-endian.
The `ECALL` instruction operates as per the unprivileged architecture
specification.  An `ECALL` in user mode causes a contained trap to
supervisor mode.  An `ECALL` in supervisor mode causes a requested
trap to the execution environment.

==== RVA23S64 Mandatory Extensions

The following unprivileged extensions are mandatory:

- The RVA23S64 mandatory unprivileged extensions include all the
mandatory unprivileged extensions in RVA23U64.

- <<zifencei,*Zifencei*>>  Instruction-Fetch Fence.

NOTE: Zifencei is mandated as it is the only standard way to support
instruction-cache coherence in RVA23 application processors.  A new
instruction-cache coherence mechanism is under development
(tentatively named Zjid) which might be added as an option in the
future.

The following privileged extensions are mandatory:

- *Ss1p13*  Supervisor architecture version 1.13.

NOTE: Ss1p13 supersedes Ss1p12.

The following privileged extensions were also mandatory in RVA22S64:

- <<svbare,**Svbare**>> The `satp` mode Bare must be supported.

- <<sv39,**Sv39**>> Page-based 39-bit virtual-Memory system.

- <<svade,**Svade**>> Page-fault exceptions are raised when a page is accessed
   when A bit is clear, or written when D bit is clear.

- <<ssccptr,**Ssccptr**>> Main memory regions with both the cacheability and
   coherence PMAs must support hardware page-table reads.

- <<sstvecd,**Sstvecd**>> `stvec.MODE` must be capable of holding the value 0
  (Direct).  When `stvec.MODE=Direct`, `stvec.BASE` must be capable of
  holding any valid four-byte-aligned address.

- <<sstvala,**Sstvala**>> `stval` must be written with the faulting virtual address
  for load, store, and instruction page-fault, access-fault, and
  misaligned exceptions, and for breakpoint exceptions that are defined to write
  an address to stval, other than those caused by execution of the `EBREAK` or
  `C.EBREAK` instructions.
  For virtual-instruction and illegal-instruction exceptions, `stval` must be written with the
  faulting instruction.

- <<sscounterenw,**Sscounterenw**>> For any `hpmcounter` that is not read-only zero, the
  corresponding bit in `scounteren` must be writable.

- <<svpbmt,**Svpbmt**>> Page-based memory types

- <<svinval,**Svinval**>> Fine-grained address-translation cache invalidation.

The following are new mandatory extensions:

- <<svnapot,**Svnapot**>> NAPOT translation contiguity.

NOTE: Svnapot was optional in RVA22.

- <<Sstc,**Sstc**>> supervisor-mode timer interrupts.

NOTE: Sstc was optional in RVA22.

- <<Sscofpmf,**Sscofpmf**>> count overflow and mode-based filtering.

- <<sec:pm-exts,**Ssnpm**>> Pointer masking, with `senvcfg.PMM` and `henvcfg.PMM` supporting,
at minimum, settings PMLEN=0 and PMLEN=7.

- <<ssu64xl,**Ssu64xl**>> `sstatus.UXL` must be capable of holding the value 2
(i.e., UXLEN=64 must be supported).

NOTE: Ssu64xl was optional in RVA22.


- *Sha* The augmented hypervisor extension.

NOTE: Sha is a new profile-defined extension that captures the
full set of features that are mandated to be supported along with the
H extension.  There is no change to the features added by including
the hypervisor extension in a profile--the new name is solely to
simplify the text of the profiles.  The definition has been added to
the RVA22 profile text, where the hypervisor extension was first
added, but will be added to the hypervisor section of the combined ISA
manual.

*Sha* comprises the following extensions:

** <<hypervisor,**H**>> The hypervisor extension.

** <<smstateen,**Ssstateen**>> Supervisor-mode view of the state-enable extension.  The
   supervisor-mode (`sstateen0-3`) and hypervisor-mode (`hstateen0-3`)
   state-enable registers must be provided.

** <<shcounterenw,**Shcounterenw**>> For any `hpmcounter` that is not read-only zero, the corresponding bit in `hcounteren` must be writable.

** <<shvstvala,**Shvstvala**>> `vstval` must be written in all cases described above for `stval`.

** *Shtvala* `htval` must be written with the faulting guest physical
   address in all circumstances permitted by the ISA.

** <<shvstvecd,**Shvstvecd**>> `vstvec.MODE` must be capable of holding the value 0 (Direct).
  When `vstvec.MODE`=Direct, `vstvec.BASE` must be capable of holding
  any valid four-byte-aligned address.

** *Shvsatpa* All translation modes supported in `satp` must be supported in `vsatp`.

** *Shgatpa* For each supported virtual memory scheme SvNN supported in
  `satp`, the corresponding hgatp SvNNx4 mode must be supported.  The
  `hgatp` mode Bare must also be supported.

NOTE: The augmented hypervisor extension (exactly equivalent to Sha) was optional in RVA22.

==== RVA23S64 Optional Extensions

RVA23S64 has the same unprivileged options as RVA23U64.

The privileged options in RVA23S64 are listed in the following
sections.

===== Localized Options

There are no privileged localized options in RVA23S64.

===== Development Options

There are no privileged development options in RVA23S64.

===== Expansion Options

The following privileged expansion options were present in RVA22S64:

- <<sv48,**Sv48**>> Page-based 48-bit virtual-memory system.

- <<sv57,**Sv57**>> Page-based 57-bit virtual-memory system.

- <<zkr,**Zkr**>>  Entropy CSR.

The following are new privileged expansion options in RVA23S64

- <<sec:svadu,**Svadu**>> Hardware A/D bit updates.

- *Sdtrig* Debug triggers.

- *Ssstrict* No non-conforming extensions are present.  Attempts to
   execute unimplemented opcodes or access unimplemented CSRs in the
   standard or reserved encoding spaces raises an illegal instruction
   exception that results in a contained trap to the supervisor-mode
   trap handler.

NOTE: Ssstrict is a new profile-defined extension that restricts the
behavior of reserved encoding spaces.  The extension will be added to
the supervisor chapter of the privileged architecture.

NOTE: Ssstrict does not prescribe behavior for the custom encoding
spaces or CSRs.

NOTE: Ssstrict definition applies to the execution environment
claiming to be RVA23-compatible, which must have the hypervisor
extension. That execution environment will take a contained trap to
supervisor-mode (however that trap is implemented, including, but not
limited to, emulation/delegation in the outer execution
environment). Ssstrict (and all the other RVA23 mandates and options)
do not apply to any guest VMs run by a hypervisor. An RVA23 hypervisor
can provide guest VMs that are also RVA23-compatible but with an
expanded set of emulated standard instructions. An RVA23 hypervisor
can also choose to implement guest VMs that are not RVA23 compatible
(e.g., lacking H, or only RVA20).


- <<sec:svvptc,**Svvptc**>> Transitions from invalid to valid PTEs will be visible in
   bounded time without an explicit memory-management fence.

- <<sec:pm-exts,**Sspm**>> Supervisor-mode pointer masking, with the supervisor execution
   environment providing a means to select PMLEN=0 and PMLEN=7 at minimum.

===== Transitory Options

There are no privileged transitory options in RVA23S64.

==== RVA23S64 Recommendations

- Implementations are strongly recommended to raise
  illegal-instruction exceptions when attempting to execute
  unimplemented opcodes or access unimplemented CSRs.

//
