== RVA22 Profiles

The RVA22 profiles are intended to be used for 64-bit application
processors running rich OS stacks.  Only user-mode (RVA22U64) and
supervisor-mode (RVA22S64) profiles are specified in this family.

=== RVA22U64 Profile

The RVA22U64 profile specifies the ISA features available to user-mode
execution environments in 64-bit applications processors.  This is the
most important profile within the application processor family in
terms of the amount of software that targets this profile.

==== RVA22U64 Mandatory Base

RV64I is the mandatory base ISA for RVA22U64, including mandatory `fence.tso`, and is little-endian.

NOTE: Later versions of the RV64I unprivileged ISA specification
ratified in 2021 made clear that `fence.tso` is mandatory.

As per the unprivileged architecture specification, the `ecall`
instruction causes a requested trap to the execution environment.

==== RVA22U64 Mandatory Extensions

The following mandatory extensions were present in RVA20U64.

- <<mstandard,**M**>> Integer multiplication and division.
- <<chap:a,**A**>> Atomic instructions.
- <<single-float,**F**>> Single-precision floating-point instructions.
- <<chap:d,**D**>> Double-precision floating-point instructions.
- <<compressed,**C**>> Compressed Instructions.
- <<csrinsts,**Zicsr**>>  CSR instructions.  These are implied by presence of F.
- <<counters,**Zicntr**>> Base counters and timers.

- <<ziccif,**Ziccif**>> Main memory regions with both the cacheability and
  coherence PMAs must support instruction fetch, and any instruction
  fetches of naturally aligned power-of-2 sizes up to min(ILEN,XLEN)
  (i.e., 32 bits for RVA22) are atomic.

- <<ziccrse,**Ziccrse**>> Main memory regions with both the cacheability and coherence PMAs must support RsrvEventual.

NOTE: Ziccrse is a new extension name capturing this feature.

- <<ziccamoa,**Ziccamoa**>> Main memory regions with both the cacheability and coherence PMAs must support AMOArithmetic.

NOTE: Ziccamoa is a new extension name capturing this feature.

- <<zicclsm,**Zicclsm**>> Misaligned loads and stores to main memory regions with both the
  cacheability and coherence PMAs must be supported.

NOTE: This is a new extension name for this feature. Even though
mandated, misaligned loads and stores might execute extremely slowly.
Standard software distributions should assume their existence only for
correctness, not for performance.

The following mandatory feature was further restricted in RVA22U64:

- <<za64rs,**Za64rs**>> Reservation sets are contiguous, naturally aligned, and a
   maximum of 64 bytes.

NOTE: This is a new extension name capturing this feature.  The
maximum reservation size has been reduced to match the required cache
block size.  The minimum reservation size is effectively set by the
instructions in the mandatory A extension.

The following mandatory extensions are new for RVA22U64.

- <<bits,**B**>> Bit-manipulation instructions.

NOTE: The B extension comprises the Zba, Zbb, and Zbs extensions.
At the time of RVA22U64's ratification, the B extension had not yet been
defined, and so RVA22U64 explicitly mandated Zba, Zbb, and Zbs instead.
Mandating B is equivalent.

- <<counters,**Zihpm**>> Hardware performance counters.

NOTE: Zihpm was optional in RVA20U64.

- <<zihintpause,**Zihintpause**>> Pause instruction.

NOTE: While the `pause` instruction is a HINT can be implemented as a
NOP and hence trivially supported by hardware implementers, its
inclusion in the mandatory extension list signifies that software
should use the instruction whenever it would make sense and that
implementors are expected to exploit this information to optimize
hardware execution.

- <<zic64b,**Zic64b**>> Cache blocks must be 64 bytes in size, naturally aligned in the
address space.

NOTE: This is a new extension name for this feature. While the general
RISC-V specifications are agnostic to cache block size, selecting a
common cache block size simplifies the specification and use of the
following cache-block extensions within the application processor
profile. Software does not have to query a discovery mechanism and/or
provide dynamic dispatch to the appropriate code. We choose 64 bytes
at it is effectively an industry standard. Implementations may use
longer cache blocks to reduce tag cost provided they use 64-byte
sub-blocks to remain compatible. Implementations may use shorter cache
blocks provided they sequence cache operations across the multiple
cache blocks comprising a 64-byte block to remain compatible.

- <<cmo,**Zicbom**>> Cache-Block Management Operations.
- <<cmo,**Zicbop**>> Cache-Block Prefetch Operations.

NOTE: As with other HINTS, the inclusion of prefetches in the
mandatory set of extensions indicates that software should generate
these instructions where they are expected to be useful, and hardware
is expected to exploit that information.

- <<cmo,**Zicboz**>> Cache-Block Zero Operations.

- <<zfhmin,**Zfhmin**>> Half-Precision Floating-point transfer and convert.

NOTE: Zfhmin is a small extension that adds support to load/store and convert
IEEE 754 half-precision numbers to and from the IEEE 754 single-precision
format.  The hardware cost for this extension is low, and mandating the
extension avoids adding an option to the profile.

- <<zkt,**Zkt**>> Data-independent execution time.

NOTE: Zkt requires a certain subset of integer instructions execute
with data-independent latency.  Mandating this feature enables
portable libraries for safe basic cryptographic operations. It is
expected that application processors will naturally have this property
and so implementation cost is low, if not zero, in most systems that
would support RVA22.

==== RVA22U64 Optional Extensions

RVA22U64 has four profile options (Zfh, V, Zkn, Zks):

- <<chap:zfh,**Zfh**>> Half-Precision Floating-Point.

NOTE: A future profile might mandate Zfh.

- <<vector,**V**>> Vector Extension.

NOTE: The smaller vector extensions (Zve32f, Zve32x, Zve64d, Zve64f,
Zve64x) are not provided as separately supported profile options. The
full V extension is specified as the only supported profile option.

NOTE: A future profile might mandate V.

- <<zkn,**Zkn**>> Scalar Crypto NIST Algorithms.
- <<zks,**Zks**>> Scalar Crypto ShangMi Algorithms.

NOTE: The scalar crypto extensions are expected to be superseded by
vector crypto standards in future profiles, and the scalar extensions
may be removed as supported options once vector crypto is present.

NOTE: The smaller component scalar crypto extensions (Zbc, Zbkb, Zbkc,
Zbkx, Zknd, Zkne, Zknh, Zksed, Zksh) are not provided as separate
options in the profile.  Profile implementers should provide all of
the instructions in a given algorithm suite as part of the Zkn or Zks
supported options.

NOTE: Access to the entropy source (Zkr) in a system is usually
carefully controlled.  While the design supports unprivileged access
to the entropy source, this is unlikely to be commonly used in an
application processor, and so Zkr was not added as a profile option.
This also means the roll-up Zk was not added as a profile option.

NOTE: The Zfinx, Zdinx, Zhinx, Zhinxmin extensions are incompatible
with the profile mandates to support the F and D extensions.

==== RVA22U64 Recommendations

Recommendations are not strictly mandated but are included to guide
implementers making design choices.

Implementations are strongly recommended to raise illegal-instruction
exceptions on attempts to execute unimplemented opcodes.

=== RVA22S64 Profile

The RVA22S64 profile specifies the ISA features available to a
supervisor-mode execution environment in 64-bit applications
processors.  RVA22S64 is based on privileged architecture version
1.12.

==== RVA22S64 Mandatory Base

RV64I is the mandatory base ISA for RVA22S64, including mandatory
`fence.tso`, and is little-endian.

NOTE: Later versions of the RV64I unprivileged ISA specification
ratified in 2021 made clear that `fence.tso` is mandatory.

The `ecall` instruction operates as per the unprivileged architecture
specification.  An `ecall` in user mode causes a contained trap to
supervisor mode.  An `ecall` in supervisor mode causes a requested
trap to the execution environment.

==== RVA22S64 Mandatory Extensions

The following unprivileged extensions are mandatory:

- The RVA22S64 mandatory unprivileged extensions include all the
mandatory unprivileged extensions in RVA22U64.

- <<zifencei,*Zifencei*>>  Instruction-Fetch Fence.

NOTE: Zifencei is mandated as it is the only standard way to support
instruction-cache coherence in RVA22 application processors.  A new
instruction-cache coherence mechanism is under development which might
be added as an option in the future.

The following privileged extensions are mandatory:

- *Ss1p12*  Privileged Architecture version 1.12.

NOTE: Ss1p12 supersedes Ss1p11.

- <<svbare,**Svbare**>> The `satp` mode Bare must be supported.

NOTE: This is a new extension name for this feature.

- <<sv39,**Sv39**>> Page-Based 39-bit Virtual-Memory System.

- <<svade,**Svade**>> Page-fault exceptions are raised when a page is accessed
   when A bit is clear, or written when D bit is clear.

- <<ssccptr,**Ssccptr**>> Main memory regions with both the cacheability and
   coherence PMAs must support hardware page-table reads.

- <<sstvecd,**Sstvecd**>> `stvec.MODE` must be capable of holding the value 0
  (Direct).  When `stvec.MODE=Direct`, `stvec.BASE` must be capable of
  holding any valid four-byte-aligned address.

- <<sstvala,**Sstvala**>> stval must be written with the faulting virtual address
  for load, store, and instruction page-fault, access-fault, and
  misaligned exceptions, and for breakpoint exceptions other than
  those caused by execution of the EBREAK or C.EBREAK instructions.
  For virtual-instruction and illegal-instruction exceptions, stval must be written with the
  faulting instruction.

- <<sscounterenw,**Sscounterenw**>> For any hpmcounter that is not read-only zero, the corresponding bit in scounteren must be writable.

NOTE: This is new extension name capturing this feature.

- <<svpbmt,**Svpbmt**>> Page-Based Memory Types

- <<svinval,**Svinval**>> Fine-Grained Address-Translation Cache Invalidation

==== RVA22S64 Optional Extensions

RVA22S64 has four unprivileged options (Zfh, V, Zkn, Zks) from
RVA22U64, and eight privileged options (Sv48, Sv57, Svnapot, Ssu64xl,
Sstc, Sscofpmf, Zkr, H).

The privileged optional extensions are:

- <<sv48,**Sv48**>> Page-Based 48-bit Virtual-Memory System.

- <<sv57,**Sv57**>> Page-Based 57-bit Virtual-Memory System.

- <<svnapot,**Svnapot**>> NAPOT Translation Contiguity

NOTE: It is expected that Svnapot will be mandatory in the next
profile release.

- <<ssu64xl,**Ssu64xl**>> `sstatus.UXL` must be capable of holding the value 2
(i.e., UXLEN=64 must be supported).

NOTE: This is a new extension name for this feature.

- <<Sstc,**Sstc**>> supervisor-mode timer interrupts.

NOTE: Sstc was not made mandatory in RVA22S64 as it is a more
disruptive change affecting system-level architecture, and will take
longer for implementations to adopt.  It is expected to be made
mandatory in the next profile release.

- <<Sscofpmf,**Sscofpmf**>> Count Overflow and Mode-Based Filtering.

NOTE: Platforms may choose to mandate the presence of Sscofpmf.

- <<zkr,**Zkr**>>  Entropy CSR.

NOTE: Technically, Zk is also a privileged-mode option capturing that
Zkr, Zkn, and Zkt are all implemented.  However, the Zk rollup is less
descriptive than specifying the individual extensions explicitly.

- *Sha* The augmented hypervisor extension.
  Sha comprises the following extensions:

** <<hypervisor,**H**>> The hypervisor extension.

** <<smstateen,**Ssstateen**>> Supervisor-mode view of the state-enable extension.  The
   supervisor-mode (`sstateen0-3`) and hypervisor-mode (`hstateen0-3`)
   state-enable registers must be provided.

** <<shcounterenw,**Shcounterenw**>> For any `hpmcounter` that is not read-only zero, the corresponding bit in `hcounteren` must be writable.

** *Shvstvala* `vstval` must be written in all cases described above for `stval`.

** *Shtvala* `htval` must be written with the faulting guest physical
   address in all circumstances permitted by the ISA.

** <<shvstvecd,**Shvstvecd**>> `vstvec.MODE` must be capable of holding the value 0 (Direct).
  When `vstvec.MODE`=Direct, `vstvec.BASE` must be capable of holding
  any valid four-byte-aligned address.

** *Shvsatpa* All translation modes supported in `satp` must be supported in `vsatp`.

** *Shgatpa* For each supported virtual memory scheme SvNN supported in
  `satp`, the corresponding hgatp SvNNx4 mode must be supported.  The
  `hgatp` mode Bare must also be supported.

NOTE: Sha, Shcounterenw, Shvstvala, Shtvala, Shvstvecd, Shvsatpa, and Shgatpa
are new extension names.  Sha was introduced after RVA22S64 was ratified, but
the ratified text required all of Sha's constituent extensions if the optional
H extension was included.  Hence, offering the Sha option is equivalent.

NOTE: The Smstateen extension specification is an M-mode extension as
it includes M-mode features, but the supervisor-mode visible
components of the extension are named as the Ssstateen extension.  Only
Ssstateen is mandated in the RVA22S64 profile when the hypervisor
extension is implemented.  These registers are not mandated or
supported options without the hypervisor extension, as there are no
RVA22S64 supported options with relevant state to control in the
absence of the hypervisor extension.

==== RVA22S64 Recommendations

- Implementations are strongly recommended to raise illegal-instruction
  exceptions when attempting to execute unimplemented opcodes.

== New ISA Extensions

This profile specification introduces the following new extension
names for existing features, but none require new features:

- <<ziccif,**Ziccif**>>: Main memory supports instruction fetch with atomicity requirement
- <<ziccrse,**Ziccrse**>>: Main memory supports forward progress on LR/SC sequences
- <<ziccamoa,**Ziccamoa**>>: Main memory supports all atomics in Zaamo
- <<zicclsm,**Zicclsm**>>: Main memory supports misaligned loads/stores
- <<za64rs,**Za64rs**>>: Reservation set size of at most 64 bytes
- <<za128rs,**Za128rs**>>: Reservation set size of at most 128 bytes
- <<zic64b,**Zic64b**>>: Cache block size is 64 bytes
- <<svbare,**Svbare**>>: Bare mode virtual-memory translation supported
- <<svade,**Svade**>>: Raise exceptions on improper A/D bits
- <<ssccptr,**Ssccptr**>>: Main memory supports page table reads
- <<sscounterenw,**Sscounterenw**>>: Support writeable enables for any supported counter
- <<sstvecd,**Sstvecd**>>: `stvec` supports Direct mode
- <<sstvala,**Sstvala**>>: `stval` provides all needed values
- <<ssu64xl,**Ssu64xl**>>: UXLEN=64 must be supported
- <<smstateen,**Ssstateen**>>: Supervisor-mode view of the state-enable extension
- <<shcounterenw,**Shcounterenw**>>: Support writeable enables for any supported counter
- *Shvstvala*:  `vstval` provides all needed values
- *Shtvala*:  `htval` provides all needed values
- <<shvstvecd,**Shvstvecd**>>: `vstvec` supports Direct mode
- *Shvsatpa*: `vsatp` supports all modes supported by `satp`
- *Shgatpa*: SvNNx4 mode supported for all modes supported by `satp`, as well as Bare

//
