== RVA23.1 Profiles

The RVA23.1 profiles are intended to expand upon
the RVA23 major release of the RVA Family of RISC-V Application
Processor Profile.

This is a minor release of the RVA23 Profile Family. As such, Minor
Profiles do not contain any new mandatory extensions and are expected to be
built on top of the extensions listed in the RVA23 profiles. For
the sake of simplicity when referring to this profile in code or
use in a command line argument, all instances of the period will
be replaced with the lower case letter 'p', as in `rva23p1s64`.

Only supervisor-mode (`rva23p1s64`) profiles are specified in this
family.

=== The `rva23p1s64` Profile

The `rva23p1s64` profile specifies the ISA features available to a
supervisor-mode execution environment in 64-bit applications
processors.  `rva23p1s64` is based on and requires an `rva23s64`
implementation.

==== Optional Extensions

The `rva23p1s64` profile specifies the ISA features available to a
supervisor-mode execution environment in 64-bit applications
processors.  `rva23p1s64` is designed to be added on to and requires
and implementation of `rva23s64` for Mandatory Base and Mandatory
Extensions. `rva23p1s64` only provides new Development Options and
Expansion Options on top of the `rva23s64`.

===== Localized Options

There are no privileged localized options in `rva23p1s64`.

===== Development Options

The following are new privileged development options in `rva23p1s64`:

- ext:svrsw60t59b[] PTE reserved-for-software bits.

- **Ssdbltrap** Double Trap.

- **Sscfg** Supervisor Counter Delegation.

===== Expansion Options

The following are new privileged expansion options in RVA23.1S64:

- ext:ssctr[] Control Transfer Records, CTR.

NOTE: *Ssctr* also implies inclusion of *Sscsrind* (indirect CSR access)

- <<ssqosid,**Ssqosid**>> QoS identifiers.

===== Transitory Options

There are no privileged transitory options in `rva23p1s64`.

//
