== RVA23.1 Profile Family

The RVA23.1 profile family is intended to expand upon
the RVA23 family of RISC-V Application Processor Profiles.

This is a minor release of the RVA23 profile family. As such, it
contains only optional extensions. The minor release number is part
of the profile name, with the period replaced by the lowercase
letter 'p', as in `rva23p1s64`.

Only a supervisor-mode (`rva23p1s64`) profile is specified in this
family.

=== The `rva23p1s64` Profile

The `rva23p1s64` profile specifies the ISA features available to a
supervisor-mode execution environment in 64-bit applications
processors.  `rva23p1s64` is based on and requires an `rva23s64`
implementation.

==== Optional Extensions

`rva23p1s64` is designed as an add-on and requires an implementation
of `rva23s64` for its Mandatory Base and Mandatory Extensions.
`rva23p1s64` only provides new Development Options and Expansion
Options on top of the `rva23s64`.

===== Localized Options

There are no privileged localized options in `rva23p1s64`.

===== Development Options

The following are new privileged development options in `rva23p1s64`:

- ext:svrsw60t59b[] PTE reserved-for-software bits.

- **Ssdbltrp** Double Trap.

- **Ssccfg** Supervisor Counter Delegation.

===== Expansion Options

The following are new privileged expansion options in `rva23p1s64`:

- ext:ssctr[] Control Transfer Records, CTR.

NOTE: *Ssctr* also implies inclusion of *Sscsrind* (indirect CSR access)

- <<ssqosid,**Ssqosid**>> QoS identifiers.

===== Transitory Options

There are no privileged transitory options in `rva23p1s64`.

//
