== RVB23.1 Profile Family

The RVB23.1 profile family is intended to expand upon
the RVB23 family of RISC-V Application Processor Profiles.

This is a minor release of the RVB23 profile family. As such, it
contains only optional extensions. The minor release number is part
of the profile name, with the period replaced by the lowercase
letter 'p', as in `rvb23p1s64`.

Only a supervisor-mode (`rvb23p1s64`) profile is
specified in this family.

=== The `rvb23p1s64` Profile

The `rvb23p1s64` profile specifies the ISA features available to a
supervisor-mode execution environment in 64-bit applications
processors.  `rvb23p1s64` is based on and requires an `rvb23s64`
implementation.

==== Optional Extensions

`rvb23p1s64` has the same unprivileged options as `rvb23u64`.

The privileged options in `rvb23p1s64` are listed in the following
sections and are additional options to the `rvb23s64` Profile.

===== Localized Options

There are no privileged localized options in `rvb23p1s64`.

===== Development Options

The following are new privileged development options in `rvb23p1s64`:

- ext:svrsw60t59b[] PTE reserved-for-software bits.

NOTE: *Svrsw60t59b* is used to avoid optionality in Linux kernel page tables

- **Ssdbltrp** Double Trap, which is included to make trap handling more robust

===== Expansion Options

The following are new privileged expansion options in `rvb23p1s64`:

- **Ssccfg** Supervisor Counter Delegation.

- ext:ssctr[] Control Transfer Records, CTR.

NOTE: *Ssctr* also implies inclusion of *Sscsrind* (indirect CSR access)

- <<ssqosid,**Ssqosid**>> QoS identifiers.

//
