== RVB23 Profiles

This chapter specifies the RVB23 profile
family. RVB23 is the first major release of the RVB
series of RISC-V Application Processor Profile.

RVB profiles are intended to be used for customized 64-bit application
processors that will run rich OS stacks, but usually as a custom build
of standard OS source-code distributions.  The approach is to provide
a large guaranteed set of relatively inexpensive and/or widely
beneficial features but allow optionality for more expensive and/or
more targeted extensions.

Unlike the RVA profiles, it is explicitly a non-goal of RVB profiles
to provide a single standard ISA interface supporting a wide variety
of binary kernel and binary application software distributions.
However, individual software ecosystems may build upon RVB profiles to
produce a more targeted standard interface for a certain market.

Only user-mode (RVB23U64) and supervisor-mode (RVB23S64) profiles are
specified in this family.

=== RVB23U64 Profile

The RVB23U64 profile specifies the ISA features available to user-mode
execution environments in 64-bit RVB applications processors.

==== RVB23U64 Mandatory Base

RV64I is the mandatory base ISA for RVB23U64 and is little-endian.  As
per the unprivileged architecture specification, the `ECALL`
instruction causes a requested trap to the execution environment.

==== RVB23U64 Mandatory Extensions

The following mandatory extensions in RVB23U64 were also mandatory in
RVA22U64.

- extlink:m[] Integer multiplication and division.
- extlink:a[] Atomic instructions.
- extlink:f[] Single-precision floating-point instructions.
- extlink:d[] Double-precision floating-point instructions.
- extlink:c[] Compressed instructions.
- <<bits,**B**>> Bit-manipulation instructions.
- extlink:zicsr[]  CSR instructions.  These are implied by presence of F.
- extlink:zicntr[] Base counters and timers.
- extlink:zihpm[] Hardware performance counters.
- extlink:ziccif[] Main memory regions with both the coherence and
  cacheability PMAs must support instruction fetch, and any instruction
  fetches of naturally aligned power-of-2 sizes up to min(ILEN,XLEN)
  (i.e., 32 bits for RVB23) are atomic.
- extlink:ziccrse[] Main memory regions with both the coherence and cacheability
  PMAs must support RsrvEventual.
- extlink:ziccamoa[] Main memory regions with both the coherence and
  cacheability PMAs must support AMOArithmetic.
- extlink:zicclsm[] Misaligned loads and stores to main memory regions with both
  the coherence and cacheability PMAs must be supported.
- extlink:za64rs[] Reservation sets must be contiguous, naturally aligned, and a
  maximum of 64 bytes.
- extlink:zihintpause[] Pause hint.
- extlink:zic64b[] Cache blocks must be 64 bytes in size, naturally aligned
  in the address space.
- extlink:zicbom[] Cache-Block Management Operations.
- extlink:zicbop[] Cache-Block Prefetch Operations.
- extlink:zicboz[] Cache-Block Zero Operations.
- <<zkt,**Zkt**>> Data-independent execution latency.

The following mandatory extensions are also present in RVA23U64:

- extlink:zihintntl[] Non-temporal locality hints.
- extlink:zicond[] Integer conditional operations.
- ext:zimop[] May-be-operations.
- ext:zcmop[] Compressed may-be-operations.
- ext:zcb[] Additional compressed instructions.
- extlink:zfa[] Additional floating-Point instructions.
- extlink:zawrs[] Wait-on-reservation-set instructions.

==== RVB23U64 Optional Extensions

RVB23U64 has 18 profile options listed below.

===== Localized Options

The following extensions are localized options in both RVA23U64 and RVB23U64:

- <<zvkng,**Zvkng**>> Vector crypto NIST Algorithms with GCM.
- <<zvksg,**Zvksg**>> Vector crypto ShangMi Algorithms with GCM.

The following extensions options are localized options in RVB23U64 but
are not present in RVA23U64:

- <<zvkg,**Zvkg**>> Vector GCM/GMAC instructions.
- <<zvknc,**Zvknc**>> Vector crypto NIST algorithms with carryless multiply.
- <<zvksc,**Zvksc**>> Vector crypto ShangMi algorithms with carryless multiply.

NOTE: RVA profiles mandate the higher-performing but more expensive GHASH
options when adding vector crypto.  To reduce implementation cost, RVB profiles
also allow these carryless multiply options (Zvknc and Zvksc) to implement GCM
efficiently, with GHASH available as a separate option.

- <<zkn,**Zkn**>> Scalar crypto NIST algorithms.
- <<zks,**Zks**>> Scalar crypto ShangMi algorithms.

NOTE: RVA23 profiles drop support for scalar crypto as an option, as the vector
extension is now mandatory in RVA23.  RVB23 profiles support scalar crypto, as
the vector extension is optional in RVB23.

===== Development Options

The following are new development options intended to become mandatory in a
later RVB profile:

- extlink:zabha[] Byte and halfword atomic memory operations.
- extlink:zacas[] Compare-and-swap instructions.
- extlink:ziccamoc[] Main memory regions with both the coherence and
  cacheability PMAs must provide AMOCASQ-level PMA support.
- extlink:zama16b[] Misaligned loads, stores and AMOs to main memory regions
  with both the coherence and cacheability PMAs that do not cross a naturally
  aligned 16-byte boundary are atomic.

===== Expansion Options

The following are expansion options in RVB23U64, but are mandatory in RVA23U64.

- ext:zfhmin[] Half-precision floating-point.

- <<vector,**V**>> Vector extension.

NOTE: Unclear if other Zve* extensions should also be supported in RVB.

- <<zvfhmin,**Zvfhmin**>> Vector minimal half-precision floating-point.
- <<zvbb,**Zvbb**>> Vector basic bit-manipulation instructions.
- <<zvkt,**Zvkt**>> Vector data-independent execution latency.
- <<sec:pm-exts,**Supm**>> Pointer masking, with the execution environment
  providing a means to select PMLEN=0 and PMLEN=7 at minimum.

The following extensions are expansion options in both RVA23U64 and RVB23U64:

- <<chap:zfh,**Zfh**>> Scalar half-precision floating-point.
- <<zbc,**Zbc**>> Scalar carryless multiplication.
- extlink:zicfilp[] Landing Pads.
- extlink:zicfiss[] Shadow Stack.
- <<zvfh,**Zvfh**>> Vector half-precision floating-point.
- <<zfbfmin,**Zfbfmin**>> Scalar BF16 converts.
- <<zvfbfmin,**Zvfbfmin**>> Vector BF16 converts.
- <<zvfbfwma,**Zvfbfwma**>> Vector BF16 widening mul-add.

The following are expansion options for RVB23U64 as they are not intended to be
made mandatory in future RVB profiles, but are listed as RVA23U64 development
options as they are intended to become mandatory in future RVA profiles.

- <<zvbc,**Zvbc**>> Vector carryless multiplication.

===== Transitory Options

There are no transitory options in RVB23U64.

==== RVB23U64 Recommendations

Implementations are strongly recommended to raise illegal-instruction exceptions
on attempts to execute unimplemented opcodes.

=== RVB23S64 Profile

The RVB23S64 profile specifies the ISA features available to a supervisor-mode
execution environment in 64-bit applications processors.  RVB23S64 is based on
privileged architecture version 1.13.

==== RVB23S64 Mandatory Base

RV64I is the mandatory base ISA for RVB23S64 and is little-endian.
The `ECALL` instruction operates as per the unprivileged architecture
specification.  An `ECALL` in user mode causes a contained trap to
supervisor mode.  An `ECALL` in supervisor mode causes a requested
trap to the execution environment.

==== RVB23S64 Mandatory Extensions

The following unprivileged extensions are mandatory:

- The RVB23S64 mandatory unprivileged extensions include all the
mandatory unprivileged extensions in RVB23U64.

- extlink:zifencei[] Instruction-fetch fence.

NOTE: ext:zifencei[] is mandated as it is the only standard way to support
instruction-cache coherence in RVB23 application processors.  A new
instruction-cache coherence mechanism is under development
(tentatively named Zjid) which might be added as an option in the
future.

The following privileged extensions are mandatory, and are also
mandatory in RVA23S64.

- *Ss1p13*  Supervisor architecture version 1.13.

NOTE: Ss1p13 supersedes Ss1p12.

- <<svnapot,**Svnapot**>> NAPOT translation contiguity.

NOTE: Svnapot is very low cost to provide, so is made mandatory even
in RVB.

- <<svbare,**Svbare**>> The `satp` mode Bare must be supported.

- <<sv39,**Sv39**>> Page-Based 39-bit Virtual-Memory System.

- <<svade,**Svade**>> Page-fault exceptions are raised when a page is accessed
  when A bit is clear, or written when D bit is clear.

- <<ssccptr,**Ssccptr**>> Main memory regions with both the cacheability and
  coherence PMAs must support hardware page-table reads.

- <<sstvecd,**Sstvecd**>> `stvec.MODE` must be capable of holding the value 0
  (Direct).  When `stvec.MODE=Direct`, `stvec.BASE` must be capable of holding
  any valid four-byte-aligned address.

- <<sstvala,**Sstvala**>> `stval` must be written with the faulting virtual
  address for load, store, and instruction page-fault, access-fault, and
  misaligned exceptions, and for breakpoint exceptions that are defined to write
  an address to stval, other than those caused by execution of the `EBREAK` or
  `C.EBREAK` instructions.
  For virtual-instruction and illegal-instruction exceptions, `stval` must be
  written with the faulting instruction.

- <<sscounterenw,**Sscounterenw**>> For any `hpmcounter` that is not read-only
  zero, the corresponding bit in `scounteren` must be writable.

- <<svpbmt,**Svpbmt**>> Page-based memory types.

- <<svinval,**Svinval**>> Fine-grained address-translation cache invalidation.

- <<Sstc,**Sstc**>> supervisor-mode timer interrupts.

- <<Sscofpmf,**Sscofpmf**>> Count overflow and mode-based filtering.

- <<ssu64xl,**Ssu64xl**>> `sstatus.UXL` must be capable of holding the value 2
  (i.e., UXLEN=64 must be supported).

==== RVB23S64 Optional Extensions

RVB23S64 has the same unprivileged options as RVB23U64.

The privileged options in RVB23S64 are listed in the following sections.

===== Localized Options

There are no privileged localized options in RVB23S64.

===== Development Options

There are no privileged development options in RVB23S64.

===== Expansion Options

The following are privileged expansion options in RVB23S64, but are mandatory in
RVA23S64:

- <<sec:pm-exts,**Ssnpm**>> Pointer masking, with `senvcfg.PMM` supporting at
  minimum, settings PMLEN=0 and PMLEN=7.

- <<sha,**Sha**>> The augmented hypervisor extension.

When the hypervisor extension is implemented, the following are also mandatory:

- If the hypervisor extension is implemented and pointer masking (Ssnpm) is
  supported then `henvcfg.PMM` must support at minimum, settings PMLEN=0 and
  PMLEN=7.

The following are privileged expansion options in RVB23S64 that are also
privileged expansion options in RVA23S64:

- <<sv48,**Sv48**>> Page-based 48-bit virtual-memory system.

- <<sv57,**Sv57**>> Page-based 57-bit virtual-memory system.

- <<svadu,**Svadu**>> Hardware A/D bit updates.

- <<zkr,**Zkr**>>  Entropy CSR.

- *Sdtrig* Debug triggers.

- <<ssstrict,**Ssstrict**>> No non-conforming extensions are present.  Attempts
  to execute unimplemented opcodes or access unimplemented CSRs in the standard
  or reserved encoding spaces raises an illegal instruction exception that
  results in a contained trap to the supervisor-mode trap handler.

NOTE: Ssstrict does not prescribe behavior for the custom encoding spaces or
CSRs.

NOTE: Ssstrict definition applies to the execution environment claiming to be
RVB23S64-compatible.
That execution environment will take a contained trap to supervisor-mode
(however that trap is implemented, including, but not limited to,
emulation/delegation in the outer execution environment).
Ssstrict (and all the other RVB23S64 mandates and options) does not apply to
any guest VMs run by a hypervisor.
An RVB23S64 hypervisor can provide guest VMs that are also RVB23S64-compatible
but with an expanded set of emulated standard instructions.
An RVB23S64 hypervisor can also choose to implement guest VMs that are not
RVB23S64 compatible (e.g., only RVA20S64).

- <<svvptc,**Svvptc**>> Transitions from invalid to valid PTEs will be visible
  in bounded time without an explicit memory-management fence.

- <<sec:pm-exts,**Sspm**>> Supervisor-mode pointer masking, with the supervisor
  execution environment providing a means to select PMLEN=0 and PMLEN=7 at
  minimum.

==== RVB23S64 Recommendations

- Implementations are strongly recommended to raise illegal-instruction
  exceptions when attempting to execute unimplemented opcodes.

//
