[[plic-thresholds]]

== Priority Thresholds

PLIC provides context based `threshold register` for the settings of a interrupt priority 
threshold of each context. The `threshold register` is a WARL field. The PLIC will mask all 
PLIC interrupts of a priority less than or equal to `threshold`.  For example,
a `threshold` value of zero permits all interrupts with non-zero priority. +
 +
The base address of Priority Thresholds register block is located at 4K alignment starts
from offset 0x200000.

[cols="15%,20%,20%,45%"]
|===
| *PLIC Register Block Name* | *Function*|*Register Block Size in Byte*| *Description*
|Priority Threshold
|Priority Threshold for 15872 contexts
|4096 * 15872 = 65011712(0x3e00000) bytes
|This is the register of Priority Thresholds setting for each context
|===

*PLIC Interrupt Priority Thresholds Memory Map* +

	0x200000: Priority threshold for context 0
	0x201000: Priority threshold for context 1
	0x202000: Priority threshold for context 2
	0x203000: Priority threshold for context 3
	...
	...
	...
	0x3FFF000: Priority threshold for context 15871
	
