[[plic-priority]]

== Interrupt Priorities

Interrupt priorities are small unsigned integers, with a platform-specific maximum
number of supported levels. The priority value 0 is reserved to mean "never
interrupt", and interrupt priority increases with increasing integer values.
Each global interrupt source has an associated interrupt priority held in a
memory-mapped register. Different interrupt sources need not support the same set
of priority values. A valid implementation can hardwire all input priority levels.
Interrupt source priority registers should be WARL fields to allow software to
determine the number and position of read-write bits in each priority
specification, if any. To simplify discovery of supported priority values, each
priority register must support any combination of values in the bits that are
variable within the register, i.e., if there are two variable bits in the
register, all four combinations of values in those bits must operate as valid priority levels.

If PLIC supports Interrupt Priorities, then each PLIC interrupt source can be
assigned a priority by writing to its 32-bit memory-mapped `priority` register.  A
priority value of 0 is reserved to mean "never interrupt" and effectively disables
the interrupt. Priority 1 is the lowest active priority while the maximum level of priority depends on PLIC implementation. Ties between global interrupts of the
same priority are broken by the Interrupt ID; interrupts with the lowest ID have
the highest effective priority. +
 +
The base address of Interrupt Source Priority block within PLIC Memory Map region is fixed at 0x000000.

[cols="15%,20%,20%,45%"]
|===
| *PLIC Register Block Name*| *Function*|*Register Block Size in Byte*| *Description*
|Interrupt Source Priority
|Interrupt Source Priority #0 to #1023
|1024 * 4 = 4096(0x1000) bytes
|This is a continuously memory block which contains PLIC Interrupt Source Priority. Total 1024 Interrupt Source Priority 
in this memory block. Interrupt Source Priority #0 is reserved which indicates it does not exist.
|===

*PLIC Interrupt Source Priority Memory Map* +

	0x000000: Reserved (interrupt source 0 does not exist)
	0x000004: Interrupt source 1 priority
	0x000008: Interrupt source 2 priority
	...
	0x000FFC: Interrupt source 1023 priority

