[[plic-interrupts]]

== Interrupt Pending Bits

The current status of the interrupt source pending bits in the PLIC core can be
read from the pending array, organized as 32-bit register.  The pending bit
for interrupt ID N is stored in bit (N mod 32) of word (N/32).  Bit 0
of word 0, which represents the non-existent interrupt source 0, is hardwired
to zero.

A pending bit in the PLIC core can be cleared by setting the associated enable
bit then performing a claim. +
 +
The base address of Interrupt Pending Bits block within PLIC Memory Map region is fixed at 0x001000.

[cols="15%,20%,20%,45%"]
|===
| *PLIC Register Block Name* | *Function*|*Register Block Size in Byte*| *Description*
|Interrupt Pending Bits
|Interrupt Pending Bit of Interrupt Source #0 to #N
|1024 / 8 = 128(0x80) bytes
|This is a continuously memory block contains PLIC Interrupt Pending Bits. Each
Interrupt Pending Bit occupies 1-bit from this register block.
|===

*PLIC Interrupt Pending Bits Memory Map* +

	0x001000: Interrupt Source #0 to #31 Pending Bits
	...
	0x00107C: Interrupt Source #992 to #1023 Pending Bits

