[[plic-memory-map]]

== Memory Map

The `base address of PLIC Memory Map` is platform implementation-specific. The memory-mapped
registers specified in this chapter have a width of 32-bits. The bits are accessed atomically with LW and SW instructions.

*PLIC Memory Map*

	base + 0x000000: Reserved (interrupt source 0 does not exist)
	base + 0x000004: Interrupt source 1 priority
	base + 0x000008: Interrupt source 2 priority
	...
	base + 0x000FFC: Interrupt source 1023 priority
	base + 0x001000: Interrupt Pending bit 0-31
	base + 0x00107C: Interrupt Pending bit 992-1023
	...	
	base + 0x002000: Enable bits for sources 0-31 on context 0
	base + 0x002004: Enable bits for sources 32-63 on context 0
	...
	base + 0x00207C: Enable bits for sources 992-1023 on context 0
	base + 0x002080: Enable bits for sources 0-31 on context 1
	base + 0x002084: Enable bits for sources 32-63 on context 1	
	...
	base + 0x0020FC: Enable bits for sources 992-1023 on context 1
	base + 0x002100: Enable bits for sources 0-31 on context 2
	base + 0x002104: Enable bits for sources 32-63 on context 2	
	...
	base + 0x00217C: Enable bits for sources 992-1023 on context 2
	...
	base + 0x1F1F80: Enable bits for sources 0-31 on context 15871
	base + 0x1F1F84: Enable bits for sources 32-63 on context 15871		
	base + 0x1F1FFC: Enable bits for sources 992-1023 on context 15871
	...	
	base + 0x1FFFFC: Reserved
	base + 0x200000: Priority threshold for context 0
	base + 0x200004: Claim/complete for context 0
	base + 0x200008: Reserved
	...
	base + 0x200FFC: Reserved
	base + 0x201000: Priority threshold for context 1
	base + 0x201004: Claim/complete for context 1
	...
	base + 0x3FFF000: Priority threshold for context 15871
	base + 0x3FFF004: Claim/complete for context 15871
	base + 0x3FFF008: Reserved
	...	
	base + 0x3FFFFFC: Reserved
	
Sections below describe the control register blocks of PLIC operation parameters.

