== Privileged RV32 Instructions
:doctype: book
// Now the document header is complete and the wavedrom attribute is active.


[#udb:doc:inst:rv32:dret]
== dret

Synopsis::
No synopsis available

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
dret

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x7b200073,"type":2}]}
....

Description::
No description available.


Decode Variables::
dret has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Sdext*
| any
|===




[#udb:doc:inst:rv32:hfence_gvma]
== hfence.gvma

Synopsis::
Hypervisor fence guest-physical address

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hfence.gvma xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x73,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x31,"type":2}]}
....

Description::
Invalidates any address-translation cache entries that a subsequent
implicit memory access to guest physical memory may use. The instruction
applies to any guest physical addresses within the range specified by
`xs1` and `xs2`, for all address spaces if `xs2`=0, or for the address
space identified by the VMID in `xs2` otherwise.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hfence_vvma]
== hfence.vvma

Synopsis::
Hypervisor fence guest virtual address

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hfence.vvma xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x73,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x11,"type":2}]}
....

Description::
Invalidates any address-translation cache entries that a subsequent
implicit memory access to guest virtual memory may use. The instruction
applies to guest virtual addresses within the range specified by `xs1`
and `xs2`, for all address spaces if `xs2`=0, or for the address space
identified by the ASID in `xs2` otherwise. Only entries for the current
virtual machine (as identified by hgatp.VMID) are affected.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hinval_gvma]
== hinval.gvma

Synopsis::
Invalidate cached address translations

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hinval.gvma xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x73,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x33,"type":2}]}
....

Description::
xref:insts:hinval_gvma.adoc#udb:doc:inst:hinval_gvma[hinval.gvma] has the same semantics as xref:insts:sinval_vma.adoc#udb:doc:inst:sinval_vma[sinval.vma] except that it combines with
xref:insts:sfence_w_inval.adoc#udb:doc:inst:sfence_w_inval[sfence.w.inval] and xref:insts:sfence_inval_ir.adoc#udb:doc:inst:sfence_inval_ir[sfence.inval.ir] to replace xref:insts:hfence_gvma.adoc#udb:doc:inst:hfence_gvma[hfence.gvma] and uses VMID instead of ASID.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Svinval*
| any
| *H*
| any
|===




[#udb:doc:inst:rv32:hinval_vvma]
== hinval.vvma

Synopsis::
Invalidate cached address translations

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hinval.vvma xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x73,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x13,"type":2}]}
....

Description::
xref:insts:hinval_vvma.adoc#udb:doc:inst:hinval_vvma[hinval.vvma] has the same semantics as xref:insts:sinval_vma.adoc#udb:doc:inst:sinval_vma[sinval.vma] except that it combines with
xref:insts:sfence_w_inval.adoc#udb:doc:inst:sfence_w_inval[sfence.w.inval] and xref:insts:sfence_inval_ir.adoc#udb:doc:inst:sfence_inval_ir[sfence.inval.ir] to replace xref:insts:hfence_vvma.adoc#udb:doc:inst:hfence_vvma[hfence.vvma].


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Svinval*
| any
| *H*
| any
|===




[#udb:doc:inst:rv32:hlv_b]
== hlv.b

Synopsis::
Hypervisor load byte

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hlv.b xd, xs1

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":7,"name": 0x73,"type":2},{"bits":5,"name": "xd","type":4},{"bits":3,"name": 0x4,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":12,"name": 0x600,"type":2}]}
....

Description::
Load 8 bits of data into register `xd` from guest physical memory at the
address in `xs1`, as though V=1. Sign-extend the result to XLEN bits.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs1 |$encoding[19:15]
|xd |$encoding[11:7]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hlv_bu]
== hlv.bu

Synopsis::
Hypervisor load byte unsigned

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hlv.bu xd, xs1

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":7,"name": 0x73,"type":2},{"bits":5,"name": "xd","type":4},{"bits":3,"name": 0x4,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":12,"name": 0x601,"type":2}]}
....

Description::
Load 8 bits of data into register `xd` from guest physical memory at the
address in `xs1`, as though V=1. Zero-extend the result to XLEN bits.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs1 |$encoding[19:15]
|xd |$encoding[11:7]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hlv_h]
== hlv.h

Synopsis::
Hypervisor load halfword

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hlv.h xd, xs1

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":7,"name": 0x73,"type":2},{"bits":5,"name": "xd","type":4},{"bits":3,"name": 0x4,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":12,"name": 0x640,"type":2}]}
....

Description::
Load 16 bits of data into register `xd` from guest physical memory at the
address in `xs1`, as though V=1. Sign-extend the result to XLEN bits.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs1 |$encoding[19:15]
|xd |$encoding[11:7]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hlv_hu]
== hlv.hu

Synopsis::
Hypervisor load halfword unsigned

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hlv.hu xd, xs1

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":7,"name": 0x73,"type":2},{"bits":5,"name": "xd","type":4},{"bits":3,"name": 0x4,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":12,"name": 0x641,"type":2}]}
....

Description::
Load 16 bits of data into register `xd` from guest physical memory at the
address in `xs1`, as though V=1. Zero-extend the result to XLEN bits.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs1 |$encoding[19:15]
|xd |$encoding[11:7]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hlv_w]
== hlv.w

Synopsis::
Hypervisor load word

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hlv.w xd, xs1

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":7,"name": 0x73,"type":2},{"bits":5,"name": "xd","type":4},{"bits":3,"name": 0x4,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":12,"name": 0x680,"type":2}]}
....

Description::
Load 32 bits of data into register `xd` from guest physical memory at the
address in `xs1`, as though V=1. Sign-extend the result to XLEN bits.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs1 |$encoding[19:15]
|xd |$encoding[11:7]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hlvx_hu]
== hlvx.hu

Synopsis::
Hypervisor load halfword unsigned, executable

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hlvx.hu xd, xs1

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":7,"name": 0x73,"type":2},{"bits":5,"name": "xd","type":4},{"bits":3,"name": 0x4,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":12,"name": 0x643,"type":2}]}
....

Description::
Load 16 bits of data into register `xd` from guest physical memory at the
address in `xs1`, as though V=1, with execute permission check instead of
read permission. Zero-extend the result to XLEN bits. This instruction is
used to fetch instructions from guest memory for emulation purposes.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs1 |$encoding[19:15]
|xd |$encoding[11:7]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hlvx_wu]
== hlvx.wu

Synopsis::
Hypervisor load word unsigned, executable

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hlvx.wu xd, xs1

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":7,"name": 0x73,"type":2},{"bits":5,"name": "xd","type":4},{"bits":3,"name": 0x4,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":12,"name": 0x683,"type":2}]}
....

Description::
Load 32 bits of data into register `xd` from guest physical memory at the
address in `xs1`, as though V=1, with execute permission check instead of
read permission. Zero-extend the result to XLEN bits. This instruction is
used to fetch instructions from guest memory for emulation purposes.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs1 |$encoding[19:15]
|xd |$encoding[11:7]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hsv_b]
== hsv.b

Synopsis::
Hypervisor store byte

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hsv.b xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x4073,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x31,"type":2}]}
....

Description::
Store 8 bits of data from register `xs2` to guest physical memory at the
address in `xs1`, as though V=1.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hsv_h]
== hsv.h

Synopsis::
Hypervisor store halfword

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hsv.h xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x4073,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x33,"type":2}]}
....

Description::
Store 16 bits of data from register `xs2` to guest physical memory at the
address in `xs1`, as though V=1.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:hsv_w]
== hsv.w

Synopsis::
Hypervisor store word

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
hsv.w xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x4073,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x35,"type":2}]}
....

Description::
Store 32 bits of data from register `xs2` to guest physical memory at the
address in `xs1`, as though V=1.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *H*
| any
|===




[#udb:doc:inst:rv32:mnret]
== mnret

Synopsis::
Machine mode resume from the RNMI or Double Trap handler

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
mnret

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x70200073,"type":2}]}
....

Description::
MNRET is an M-mode-only instruction that uses the values in mnepc and mnstatus to return to the
program counter, privilege mode, and virtualization mode of the interrupted context. This instruction
also sets mnstatus.NMIE. If MNRET changes the privilege mode to a mode less privileged than M, it
also sets mstatus.MPRV to 0. If the Zicfilp extension is implemented, then if the new privileged mode is
y, MNRET sets ELP to the logical AND of yLPE (see Section 22.1.1) and mnstatus.MNPELP.


Decode Variables::
mnret has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Smrnmi*
| any
|===




[#udb:doc:inst:rv32:mret]
== mret

Synopsis::
Machine-mode Return from Trap

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
mret

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x30200073,"type":2}]}
....

Description::
Return from machine mode after handling a trap.


Decode Variables::
mret has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Sm*
| any
|===




[#udb:doc:inst:rv32:sctrclr]
== sctrclr

Synopsis::
Supervisor Control Transfer Record (CTR) clear

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
sctrclr

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x10400073,"type":2}]}
....

Description::
When xref:csrs:mstateen0.adoc#udb:doc:csr_field:mstateen0:CTR[mstateen0.CTR]=1, the SCTRCLR instruction performs the following operations:

* Zeroes all CTR Entry Registers, for all DEPTH values
* Reset to Zero the optional CTR cycle counter where implemented
** `ctrdata.CC` and `ctrdata.CCV` bit fields.

Any read of `ctrsource`, `ctrtarget`, or `ctrdata` that follows SCTRCLR, such that it precedes the next
qualified control transfer, will return the value 0.

Further, the first recorded transfer following SCTRCLR will have `ctrdata.CCV`=0.

SCTRCLR execution causes an `IllegalInstruction` exception if:

* xref:exts:Smctr.adoc#udb:doc:ext:Smctr[Smctr] is not implemented
* The instruction is executed in S/VS/VU-mode and xref:exts:Ssctr.adoc#udb:doc:ext:Ssctr[Ssctr] is not implemented, or xref:csrs:mstateen0.adoc#udb:doc:csr_field:mstateen0:CTR[mstateen0.CTR]=0
* The instruction is executed in U-mode

SCTRCLR execution  causes a `VirtualInstruciton` exception if xref:csrs:mstateen0.adoc#udb:doc:csr_field:mstateen0:CTR[mstateen0.CTR]=1 and:

* The instruction is executed in VS-mode and xref:csrs:hstateen0.adoc#udb:doc:csr_field:hstateen0:CTR[hstateen0.CTR]=0
* The instruction is executed in VU-mode


Decode Variables::
sctrclr has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Ssctr*
| any
|===




[#udb:doc:inst:rv32:sfence_inval_ir]
== sfence.inval.ir

Synopsis::
Order implicit page table reads after invalidation

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
sfence.inval.ir

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x18100073,"type":2}]}
....

Description::
The xref:insts:sfence_inval_ir.adoc#udb:doc:inst:sfence_inval_ir[sfence.inval.ir] instruction guarantees that any previous xref:insts:sinval_vma.adoc#udb:doc:inst:sinval_vma[sinval.vma]
instructions executed by the current hart are ordered before subsequent implicit references by
that hart to the memory-management data structures.


Decode Variables::
sfence.inval.ir has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Svinval*
| any
|===




[#udb:doc:inst:rv32:sfence_vma]
== sfence.vma

Synopsis::
Supervisor memory-management fence

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
sfence.vma xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x73,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0x9,"type":2}]}
....

Description::
The supervisor memory-management fence instruction `SFENCE.VMA` is used to
synchronize updates to in-memory memory-management data structures with
current execution. Instruction execution causes implicit reads and
writes to these data structures; however, these implicit references are
ordinarily not ordered with respect to explicit loads and stores.
Executing an SFENCE.VMA instruction guarantees that any previous stores
already visible to the current RISC-V hart are ordered before certain
implicit references by subsequent instructions in that hart to the
memory-management data structures. The specific set of operations
ordered by SFENCE.VMA is determined by _xs1_ and _xs2_, as described
below. SFENCE.VMA is also used to invalidate entries in the
address-translation cache associated with a hart (see <<sv32algorithm>>). Further details on the behavior of this instruction are described in <<virt-control>> and <<pmp-vmem>>.

[NOTE]
====
The SFENCE.VMA is used to flush any local hardware caches related to
address translation. It is specified as a fence rather than a TLB flush
to provide cleaner semantics with respect to which instructions are
affected by the flush operation and to support a wider variety of
dynamic caching structures and memory-management schemes. SFENCE.VMA is
also used by higher privilege levels to synchronize page table writes
and the address translation hardware.
====

SFENCE.VMA orders only the local hart's implicit references to the
memory-management data structures.

[NOTE]
====
Consequently, other harts must be notified separately when the
memory-management data structures have been modified. One approach is to
use 1) a local data fence to ensure local writes are visible globally,
then 2) an interprocessor interrupt to the other thread, then 3) a local
SFENCE.VMA in the interrupt handler of the remote thread, and finally 4)
signal back to originating thread that operation is complete. This is,
of course, the RISC-V analog to a TLB shootdown.
====

For the common case that the translation data structures have only been
modified for a single address mapping (i.e., one page or superpage),
_xs1_ can specify a virtual address within that mapping to effect a
translation fence for that mapping only. Furthermore, for the common
case that the translation data structures have only been modified for a
single address-space identifier, _xs2_ can specify the address space.
The behavior of SFENCE.VMA depends on _xs1_ and _xs2_ as follows:

* If __xs1__=`x0` and __xs2__=`x0`, the fence orders all reads and writes
made to any level of the page tables, for all address spaces. The fence
also invalidates all address-translation cache entries, for all address
spaces.
* If __xs1__=`x0` and __xs2__&#8800;``x0``, the fence orders all
reads and writes made to any level of the page tables, but only for the
address space identified by integer register _xs2_. Accesses to _global_
mappings (see <<translation>>) are not ordered. The
fence also invalidates all address-translation cache entries matching
the address space identified by integer register _xs2_, except for
entries containing global mappings.
* If __xs1__&#8800;``x0`` and __xs2__=`x0`, the fence orders only
reads and writes made to leaf page table entries corresponding to the
virtual address in __xs1__, for all address spaces. The fence also
invalidates all address-translation cache entries that contain leaf page
table entries corresponding to the virtual address in _xs1_, for all
address spaces.
* If __xs1__&#8800;``x0`` and __xs2__&#8800;``x0``, the
fence orders only reads and writes made to leaf page table entries
corresponding to the virtual address in _xs1_, for the address space
identified by integer register _xs2_. Accesses to global mappings are
not ordered. The fence also invalidates all address-translation cache
entries that contain leaf page table entries corresponding to the
virtual address in _xs1_ and that match the address space identified by
integer register _xs2_, except for entries containing global mappings.

If the value held in _xs1_ is not a valid virtual address, then the
SFENCE.VMA instruction has no effect. No exception is raised in this
case.

When __xs2__&#8800;``x0``, bits SXLEN-1:ASIDMAX of the value held
in _xs2_ are reserved for future standard use. Until their use is
defined by a standard extension, they should be zeroed by software and
ignored by current implementations. Furthermore, if
ASIDLEN<ASIDMAX, the implementation shall ignore bits
ASIDMAX-1:ASIDLEN of the value held in _xs2_.

[NOTE]
====
It is always legal to over-fence, e.g., by fencing only based on a
subset of the bits in _xs1_ and/or _xs2_, and/or by simply treating all
SFENCE.VMA instructions as having _xs1_=`x0` and/or _xs2_=`x0`. For
example, simpler implementations can ignore the virtual address in _xs1_
and the ASID value in _xs2_ and always perform a global fence. The
choice not to raise an exception when an invalid virtual address is held
in _xs1_ facilitates this type of simplification.
====

An implicit read of the memory-management data structures may return any
translation for an address that was valid at any time since the most
recent SFENCE.VMA that subsumes that address. The ordering implied by
SFENCE.VMA does not place implicit reads and writes to the
memory-management data structures into the global memory order in a way
that interacts cleanly with the standard RVWMO ordering rules. In
particular, even though an SFENCE.VMA orders prior explicit accesses
before subsequent implicit accesses, and those implicit accesses are
ordered before their associated explicit accesses, SFENCE.VMA does not
necessarily place prior explicit accesses before subsequent explicit
accesses in the global memory order. These implicit loads also need not
otherwise obey normal program order semantics with respect to prior
loads or stores to the same address.

[NOTE]
====
A consequence of this specification is that an implementation may use
any translation for an address that was valid at any time since the most
recent SFENCE.VMA that subsumes that address. In particular, if a leaf
PTE is modified but a subsuming SFENCE.VMA is not executed, either the
old translation or the new translation will be used, but the choice is
unpredictable. The behavior is otherwise well-defined.

In a conventional TLB design, it is possible for multiple entries to
match a single address if, for example, a page is upgraded to a
superpage without first clearing the original non-leaf PTE's valid bit
and executing an SFENCE.VMA with __xs1__=`x0`. In this case, a similar
remark applies: it is unpredictable whether the old non-leaf PTE or the
new leaf PTE is used, but the behavior is otherwise well defined.

Another consequence of this specification is that it is generally unsafe
to update a PTE using a set of stores of a width less than the width of
the PTE, as it is legal for the implementation to read the PTE at any
time, including when only some of the partial stores have taken effect.

***

This specification permits the caching of PTEs whose V (Valid) bit is
clear. Operating systems must be written to cope with this possibility,
but implementers are reminded that eagerly caching invalid PTEs will
reduce performance by causing additional page faults.
====

Implementations must only perform implicit reads of the translation data
structures pointed to by the current contents of the xref:csrs:satp.adoc#udb:doc:csr:satp[satp] register or
a subsequent valid (V=1) translation data structure entry, and must only
raise exceptions for implicit accesses that are generated as a result of
instruction execution, not those that are performed speculatively.

Changes to the xref:csrs:sstatus.adoc#udb:doc:csr:sstatus[sstatus] fields SUM and MXR take effect immediately,
without the need to execute an SFENCE.VMA instruction. Changing
xref:csrs:satp.adoc#udb:doc:csr:satp[satp].MODE from Bare to other modes and vice versa also takes effect
immediately, without the need to execute an SFENCE.VMA instruction.
Likewise, changes to xref:csrs:satp.adoc#udb:doc:csr:satp[satp].ASID take effect immediately.

[TIP]
====
The following common situations typically require executing an
SFENCE.VMA instruction:

* When software recycles an ASID (i.e., reassociates it with a different
page table), it should _first_ change xref:csrs:satp.adoc#udb:doc:csr:satp[satp] to point to the new page
table using the recycled ASID, _then_ execute SFENCE.VMA with __xs1__=`x0`
and _xs2_ set to the recycled ASID. Alternatively, software can execute
the same SFENCE.VMA instruction while a different ASID is loaded into
xref:csrs:satp.adoc#udb:doc:csr:satp[satp], provided the next time xref:csrs:satp.adoc#udb:doc:csr:satp[satp] is loaded with the recycled ASID,
it is simultaneously loaded with the new page table.
* If the implementation does not provide ASIDs, or software chooses to
always use ASID 0, then after every xref:csrs:satp.adoc#udb:doc:csr:satp[satp] write, software should
execute SFENCE.VMA with __xs1__=`x0`. In the common case that no global
translations have been modified, _xs2_ should be set to a register other
than `x0` but which contains the value zero, so that global translations
are not flushed.
* If software modifies a non-leaf PTE, it should execute SFENCE.VMA with
__xs1__=`x0`. If any PTE along the traversal path had its G bit set, _xs2_
must be `x0`; otherwise, _xs2_ should be set to the ASID for which the
translation is being modified.
* If software modifies a leaf PTE, it should execute SFENCE.VMA with
_xs1_ set to a virtual address within the page. If any PTE along the
traversal path had its G bit set, _xs2_ must be `x0`; otherwise, _xs2_
should be set to the ASID for which the translation is being modified.
* For the special cases of increasing the permissions on a leaf PTE and
changing an invalid PTE to a valid leaf, software may choose to execute
the SFENCE.VMA lazily. After modifying the PTE but before executing
SFENCE.VMA, either the new or old permissions will be used. In the
latter case, a page-fault exception might occur, at which point software
should execute SFENCE.VMA in accordance with the previous bullet point.
====

If a hart employs an address-translation cache, that cache must appear
to be private to that hart. In particular, the meaning of an ASID is
local to a hart; software may choose to use the same ASID to refer to
different address spaces on different harts.

[NOTE]
====
A future extension could redefine ASIDs to be global across the SEE,
enabling such options as shared translation caches and hardware support
for broadcast TLB shootdown. However, as OSes have evolved to
significantly reduce the scope of TLB shootdowns using novel
ASID-management techniques, we expect the local-ASID scheme to remain
attractive for its simplicity and possibly better scalability.
====

For implementations that make xref:csrs:satp.adoc#udb:doc:csr:satp[satp].MODE read-only zero (always Bare),
attempts to execute an SFENCE.VMA instruction might raise an
illegal-instruction exception.


Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *S*
| any
|===




[#udb:doc:inst:rv32:sfence_w_inval]
== sfence.w.inval

Synopsis::
Order writes before sfence

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
sfence.w.inval

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x18000073,"type":2}]}
....

Description::
The xref:insts:sfence_w_inval.adoc#udb:doc:inst:sfence_w_inval[sfence.w.inval] instruction guarantees that any previous stores already visible to the
current RISC-V hart are ordered before subsequent xref:insts:sinval_vma.adoc#udb:doc:inst:sinval_vma[sinval.vma] instructions executed by the
same hart.


Decode Variables::
sfence.w.inval has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Svinval*
| any
|===




[#udb:doc:inst:rv32:sinval_vma]
== sinval.vma

Synopsis::
Invalidate cached address translations

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
sinval.vma xs1, xs2

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":15,"name": 0x73,"type":2},{"bits":5,"name": "xs1","type":4},{"bits":5,"name": "xs2","type":4},{"bits":7,"name": 0xb,"type":2}]}
....

Description::
The xref:insts:sinval_vma.adoc#udb:doc:inst:sinval_vma[sinval.vma] instruction invalidates any address-translation cache entries that an xref:insts:sfence_vma.adoc#udb:doc:inst:sfence_vma[sfence.vma] instruction with the same values of xs1 and xs2 would invalidate. However, unlike xref:insts:sfence_vma.adoc#udb:doc:inst:sfence_vma[sfence.vma], xref:insts:sinval_vma.adoc#udb:doc:inst:sinval_vma[sinval.vma] instructions are only ordered with respect to xref:insts:sfence_vma.adoc#udb:doc:inst:sfence_vma[sfence.vma], xref:insts:sfence_w_inval.adoc#udb:doc:inst:sfence_w_inval[sfence.w.inval], and xref:insts:sfence_inval_ir.adoc#udb:doc:inst:sfence_inval_ir[sfence.inval.ir] instructions as defined below.

Decode Variables::
[width="100%", cols="1,2", options="header"]
|===
|Variable Name |Location
|xs2 |$encoding[24:20]
|xs1 |$encoding[19:15]
|===

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Svinval*
| any
|===




[#udb:doc:inst:rv32:sret]
== sret

Synopsis::
Supervisor Mode Return from Trap

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
sret

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x10200073,"type":2}]}
....

Description::
Returns from supervisor mode after handling a trap.

When xref:insts:sret.adoc#udb:doc:inst:sret[sret] is allowed to execute, its behavior depends on whether or not the current privilege
mode is virtualized.

*When the current privilege mode is (H)S-mode or M-mode*

xref:insts:sret.adoc#udb:doc:inst:sret[sret] sets  xref:csrs:hstatus.adoc#udb:doc:csr:hstatus[hstatus] = 0, xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:SPP[mstatus.SPP] = 0,
xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:SIE[mstatus.SIE] = xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:SPIE[mstatus.SPIE], and xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:SPIE[mstatus.SPIE] = 1,
changes the privilege mode according to the table below,
and then jumps to the address in xref:csrs:sepc.adoc#udb:doc:csr:sepc[sepc].

.Next privilege mode following an xref:insts:sret.adoc#udb:doc:inst:sret[sret] in (H)S-mode or M-mode
[%autowidth]
|===
| [.rotate]#xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:SPP[mstatus.SPP]# | [.rotate]#xref:csrs:hstatus.adoc#udb:doc:csr_field:hstatus:SPV[hstatus.SPV]# .>| Mode after xref:insts:sret.adoc#udb:doc:inst:sret[sret]

| 0 | 0 | U-mode
| 0 | 1 | VU-mode
| 1 | 0 | (H)S-mode
| 1 | 1 | VS-mode
|===

*When the current privilege mode is VS-mode*

xref:insts:sret.adoc#udb:doc:inst:sret[sret] sets
xref:csrs:vsstatus.adoc#udb:doc:csr_field:vsstatus:SPP[vsstatus.SPP] = 0, xref:csrs:vsstatus.adoc#udb:doc:csr_field:vsstatus:SIE[vsstatus.SIE] = `vstatus.SPIE`, and xref:csrs:vsstatus.adoc#udb:doc:csr_field:vsstatus:SPIE[vsstatus.SPIE] = 1,
changes the privilege mode according to the table below,
and then jumps to the address in xref:csrs:vsepc.adoc#udb:doc:csr:vsepc[vsepc].

.Next privilege mode following an xref:insts:sret.adoc#udb:doc:inst:sret[sret] in (H)S-mode or M-mode
[%autowidth]
|===
| [.rotate]#xref:csrs:vsstatus.adoc#udb:doc:csr_field:vsstatus:SPP[vsstatus.SPP]# .>| Mode after xref:insts:sret.adoc#udb:doc:inst:sret[sret]

| 0 | VU-mode
| 1 | VS-mode
|===


Decode Variables::
sret has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *S*
| any
|===




[#udb:doc:inst:rv32:wfi]
== wfi

Synopsis::
Wait for interrupt

Base::

[cols="1,1"]
|===
| RV32 | RV64

| &#x2713;
| &#x2713;
|===

Assembly::
wfi

Encoding::
[wavedrom, ,svg,subs='attributes',width="100%"]
....
{"reg":[{"bits":32,"name": 0x10500073,"type":2}]}
....

Description::
Can causes the processor to enter a low-power state until the next interrupt occurs.

<%- if ext?(:H) -%>
The behavior of xref:insts:wfi.adoc#udb:doc:inst:wfi[wfi] is affected by the xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:TW[mstatus.TW]
and xref:csrs:hstatus.adoc#udb:doc:csr_field:hstatus:VTW[hstatus.VTW] bits, as summarized below.

[%autowidth,%footer]
|===
.2+| [.rotate]#xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:TW[mstatus.TW]# .2+| [.rotate]#xref:csrs:hstatus.adoc#udb:doc:csr_field:hstatus:VTW[hstatus.VTW]# 4+^.>| xref:insts:wfi.adoc#udb:doc:inst:wfi[wfi] behavior
h| HS-mode h| U-mode h| VS-mode h| in VU-mode

| 0 | 0 | Wait | Trap (I) | Wait | Trap (V)
| 0 | 1 | Wait | Trap (I) | Trap (V) | Trap (V)
| 1 | - | Trap (I) | Trap (I) | Trap (I) | Trap (I)

6+| Trap (I) - Trap with `Illegal Instruction` code +
Trap (V) - Trap with `Virtual Instruction` code
|===

<%- else -%>
The xref:insts:wfi.adoc#udb:doc:inst:wfi[wfi] instruction is also affected by xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:TW[mstatus.TW], as shown below:

[%autowidth,%footer]
|===
.2+| [.rotate]#xref:csrs:mstatus.adoc#udb:doc:csr_field:mstatus:TW[mstatus.TW]# 2+^.>| xref:insts:wfi.adoc#udb:doc:inst:wfi[wfi] behavior
h| S-mode h| U-mode

| 0 | Wait | Trap (I)
| 1 | Trap (I) | Trap (I)

3+| Trap (I) - Trap with `Illegal Instruction` code
|===

<%- end -%>

When xref:insts:wfi.adoc#udb:doc:inst:wfi[wfi] is marked as causing a trap above, the implementation is allowed to wait
for an unspecified period of time to see if an interrupt occurs before raising the trap.
That period of time can be zero (_i.e._, xref:insts:wfi.adoc#udb:doc:inst:wfi[wfi] always causes a trap in the cases identified
above).


Decode Variables::
wfi has no decode variables.

Included in::


[width="100%",cols="1,2",options="header"]
|===
| Extension | Version

| *Sm*
| any
|===




