[[sec:svvptc]]
=== "Svvptc" Extension for Obviating Memory-Management Instructions after Marking PTEs Valid, Version 1.0

[#norm:Svvptc_explicit_stores_update_valid_bit]#When the Svvptc extension is implemented, explicit stores by a hart that update
the Valid bit of leaf and/or non-leaf PTEs from 0 to 1 and are visible to a hart
will eventually become visible within a bounded timeframe to subsequent implicit
accesses by that hart to such PTEs.#

[NOTE]
====
Svvptc relieves an operating system from executing certain memory-management
instructions, such as `SFENCE.VMA` or `SINVAL.VMA`, which would normally be used
to synchronize the hart's address-translation caches when a memory-resident PTE
is changed from Invalid to Valid. Synchronizing the hart's address-translation
caches with other forms of updates to a memory-resident PTE, including when a
PTE is changed from Valid to Invalid, requires the use of suitable
memory-management instructions. Svvptc guarantees that a change to a PTE from
Invalid to Valid is made visible within a bounded time, thereby making the
execution of these memory-management instructions redundant. The performance
benefit of eliding these instructions outweighs the cost of an occasional
gratuitous additional page fault that may occur.

Depending on the microarchitecture, some possible ways to facilitate
implementation of Svvptc include: not having any address-translation caches, not
storing Invalid PTEs in the address-translation caches, automatically evicting
Invalid PTEs using a bounded timer, or making address-translation caches
coherent with store instructions that modify PTEs.
====

[[sec:svrsw60t59b]]
=== "Svrsw60t59b" Extension for PTE Reserved-for-Software Bits 60-59, Version 1.0

[#norm:Svrsw60t59b_reserved_bits_60_59]#If the Svrsw60t59b extension is implemented, then bits 60-59 of the page table
entries (PTEs) are reserved for use by supervisor software and are ignored by
the implementation.#

[#norm:Svrsw60t59b_h_g_stage_reserved_bits]#If the Hypervisor (H) extension is also implemented, then bits 60-59 of the
G-stage PTEs are reserved for use by supervisor software and are ignored by
the implementation.#

[#norm:Svrsw60t59b_depends_on_sv39]#The Svrsw60t59b extension depends on Sv39.#

[NOTE]
====
Operating systems frequently use reserved bits within PTEs to store metadata for
advanced memory management features. Embedding these metadata bits directly within
the PTEs allows for fast access with minimal overhead, avoiding costly lookups in
auxiliary data structures. By default, Sv39 and Sv39x4 require a page fault and
a guest-page fault exception, respectively, to be raised if bits 60–59 are not
zero.
====
