// Frozen from the RISC-V Debug Specification v1.0 (Ratified, 2025-02-21),
// generated from xml/dm_registers.xml in riscv/riscv-debug-spec. Do not regenerate;
// edit this file directly if an erratum requires a change.

[[tab:None]]
.Debug Module Debug Bus Registers
[cols="1,6,2",options="header"]
|===
|Address |Name |Section
|0x04 |Abstract Data 0 ({dm-data0})| xref:dm-data0[]
|0x05 |Abstract Data 1 ({dm-data1})| 
|0x06 |Abstract Data 2 ({dm-data2})| 
|0x07 |Abstract Data 3 ({dm-data3})| 
|0x08 |Abstract Data 4 ({dm-data4})| 
|0x09 |Abstract Data 5 ({dm-data5})| 
|0x0a |Abstract Data 6 ({dm-data6})| 
|0x0b |Abstract Data 7 ({dm-data7})| 
|0x0c |Abstract Data 8 ({dm-data8})| 
|0x0d |Abstract Data 9 ({dm-data9})| 
|0x0e |Abstract Data 10 ({dm-data10})| 
|0x0f |Abstract Data 11 ({dm-data11})| 
|0x10 |Debug Module Control ({dm-dmcontrol})| xref:dm-dmcontrol[]
|0x11 |Debug Module Status ({dm-dmstatus})| xref:dm-dmstatus[]
|0x12 |Hart Info ({dm-hartinfo})| xref:dm-hartinfo[]
|0x13 |Halt Summary 1 ({dm-haltsum1})| xref:dm-haltsum1[]
|0x14 |Hart Array Window Select ({dm-hawindowsel})| xref:dm-hawindowsel[]
|0x15 |Hart Array Window  ({dm-hawindow})| xref:dm-hawindow[]
|0x16 |Abstract Control and Status ({dm-abstractcs})| xref:dm-abstractcs[]
|0x17 |Abstract Command ({dm-command})| xref:dm-command[]
|0x18 |Abstract Command Autoexec ({dm-abstractauto})| xref:dm-abstractauto[]
|0x19 |Configuration Structure Pointer 0 ({dm-confstrptr0})| xref:dm-confstrptr0[]
|0x1a |Configuration Structure Pointer 1 ({dm-confstrptr1})| xref:dm-confstrptr1[]
|0x1b |Configuration Structure Pointer 2 ({dm-confstrptr2})| xref:dm-confstrptr2[]
|0x1c |Configuration Structure Pointer 3 ({dm-confstrptr3})| xref:dm-confstrptr3[]
|0x1d |Next Debug Module ({dm-nextdm})| xref:dm-nextdm[]
|0x1f |Custom Features ({dm-custom})| xref:dm-custom[]
|0x20 |Program Buffer 0 ({dm-progbuf0})| xref:dm-progbuf0[]
|0x21 |Program Buffer 1 ({dm-progbuf1})| 
|0x22 |Program Buffer 2 ({dm-progbuf2})| 
|0x23 |Program Buffer 3 ({dm-progbuf3})| 
|0x24 |Program Buffer 4 ({dm-progbuf4})| 
|0x25 |Program Buffer 5 ({dm-progbuf5})| 
|0x26 |Program Buffer 6 ({dm-progbuf6})| 
|0x27 |Program Buffer 7 ({dm-progbuf7})| 
|0x28 |Program Buffer 8 ({dm-progbuf8})| 
|0x29 |Program Buffer 9 ({dm-progbuf9})| 
|0x2a |Program Buffer 10 ({dm-progbuf10})| 
|0x2b |Program Buffer 11 ({dm-progbuf11})| 
|0x2c |Program Buffer 12 ({dm-progbuf12})| 
|0x2d |Program Buffer 13 ({dm-progbuf13})| 
|0x2e |Program Buffer 14 ({dm-progbuf14})| 
|0x2f |Program Buffer 15 ({dm-progbuf15})| 
|0x30 |Authentication Data ({dm-authdata})| xref:dm-authdata[]
|0x32 |Debug Module Control and Status 2 ({dm-dmcs2})| xref:dm-dmcs2[]
|0x34 |Halt Summary 2 ({dm-haltsum2})| xref:dm-haltsum2[]
|0x35 |Halt Summary 3 ({dm-haltsum3})| xref:dm-haltsum3[]
|0x37 |System Bus Address 127:96 ({dm-sbaddress3})| xref:dm-sbaddress3[]
|0x38 |System Bus Access Control and Status ({dm-sbcs})| xref:dm-sbcs[]
|0x39 |System Bus Address 31:0 ({dm-sbaddress0})| xref:dm-sbaddress0[]
|0x3a |System Bus Address 63:32 ({dm-sbaddress1})| xref:dm-sbaddress1[]
|0x3b |System Bus Address 95:64 ({dm-sbaddress2})| xref:dm-sbaddress2[]
|0x3c |System Bus Data 31:0 ({dm-sbdata0})| xref:dm-sbdata0[]
|0x3d |System Bus Data 63:32 ({dm-sbdata1})| xref:dm-sbdata1[]
|0x3e |System Bus Data 95:64 ({dm-sbdata2})| xref:dm-sbdata2[]
|0x3f |System Bus Data 127:96 ({dm-sbdata3})| xref:dm-sbdata3[]
|0x40 |Halt Summary 0 ({dm-haltsum0})| xref:dm-haltsum0[]
|0x70 |Custom Features 0 ({dm-custom0})| xref:dm-custom0[]
|0x71 |Custom Features 1 ({dm-custom1})| 
|0x72 |Custom Features 2 ({dm-custom2})| 
|0x73 |Custom Features 3 ({dm-custom3})| 
|0x74 |Custom Features 4 ({dm-custom4})| 
|0x75 |Custom Features 5 ({dm-custom5})| 
|0x76 |Custom Features 6 ({dm-custom6})| 
|0x77 |Custom Features 7 ({dm-custom7})| 
|0x78 |Custom Features 8 ({dm-custom8})| 
|0x79 |Custom Features 9 ({dm-custom9})| 
|0x7a |Custom Features 10 ({dm-custom10})| 
|0x7b |Custom Features 11 ({dm-custom11})| 
|0x7c |Custom Features 12 ({dm-custom12})| 
|0x7d |Custom Features 13 ({dm-custom13})| 
|0x7e |Custom Features 14 ({dm-custom14})| 
|0x7f |Custom Features 15 ({dm-custom15})| 
|===
[[dm-dmstatus]]
==== Debug Module Status (((dmstatus)), at 0x11)

This register reports status for the overall Debug Module as well as
the currently selected harts, as defined in {dmcontrol-hasel}.  Its address will
not change in the future, because it contains {dmstatus-version}.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 31)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "25" "" "" "24" "" "" "" "" "23" "" "" "" "22" "" "21" "" "20" "" "" "19" "" "" "" "" "18" "" ""]})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "ndmresetpending" {:font-size 20}) {:span 5})
(draw-box (text "stickyunavail" {:font-size 20}) {:span 5})
(draw-box (text "impebreak" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 3})
(draw-box (text "allhavereset" {:font-size 20}) {:span 5})
(draw-box (text "anyhavereset" {:font-size 20}) {:span 5})
(draw-box "7" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "2" {:span 3 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
----
[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 35)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "" "17" "" "" "" "" "16" "" "" "" "" "15" "" "" "" "" "14" "" "" "" "" "13" "" "" "" "" "12" "" "" "" "" "11" "" ""]})
(draw-box (text "allresumeack" {:font-size 20}) {:span 5})
(draw-box (text "anyresumeack" {:font-size 20}) {:span 5})
(draw-box (text "allnonexistent" {:font-size 20}) {:span 5})
(draw-box (text "anynonexistent" {:font-size 20}) {:span 5})
(draw-box (text "allunavail" {:font-size 20}) {:span 5})
(draw-box (text "anyunavail" {:font-size 20}) {:span 5})
(draw-box (text "allrunning" {:font-size 20}) {:span 5})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
----
[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 34)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "" "10" "" "" "" "9" "" "" "8" "" "" "" "7" "" "" "" "6" "" "" "" "5" "" "" "" "" "4" "" "" "3" "" "" "" "0"]})
(draw-box (text "anyrunning" {:font-size 20}) {:span 5})
(draw-box (text "allhalted" {:font-size 20}) {:span 3})
(draw-box (text "anyhalted" {:font-size 20}) {:span 3})
(draw-box (text "authenticated" {:font-size 20}) {:span 5})
(draw-box (text "authbusy" {:font-size 20}) {:span 3})
(draw-box (text "hasresethaltreq" {:font-size 20}) {:span 5})
(draw-box (text "confstrptrvalid" {:font-size 20}) {:span 5})
(draw-box (text "version" {:font-size 20}) {:span 5})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "4" {:span 5 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[dmstatus-ndmresetpending]] `((ndmresetpending))`
a|

0 (false): Unimplemented, or {dmcontrol-ndmreset} is zero and no ndmreset is currently
in progress.


1 (true): {dmcontrol-ndmreset} is currently nonzero, or there is an ndmreset in progress.
a|*R*
a|-
|[[dmstatus-stickyunavail]] `((stickyunavail))`
a|

0 (current): The per-hart `unavail` bits reflect the current state of the hart.


1 (sticky): The per-hart `unavail` bits are sticky. Once they are set, they will
not clear until the debugger acknowledges them using {dmcontrol-ackunavail}.
a|*R*
a|Preset
|[[dmstatus-impebreak]] `((impebreak))`
a|If 1, then there is an implicit `ebreak` instruction at the
non-existent word immediately after the Program Buffer. This saves
the debugger from having to write the `ebreak` itself, and
allows the Program Buffer to be one word smaller.

This must be 1 when {abstractcs-progbufsize} is 1.
a|*R*
a|Preset
|[[dmstatus-allhavereset]] `((allhavereset))`
a|This field is 1 when all currently selected harts have been reset
and reset has not been acknowledged for any of them.
a|*R*
a|-
|[[dmstatus-anyhavereset]] `((anyhavereset))`
a|This field is 1 when at least one currently selected hart has been
reset and reset has not been acknowledged for that hart.
a|*R*
a|-
|[[dmstatus-allresumeack]] `((allresumeack))`
a|This field is 1 when all currently selected harts have their
((resume ack bit)) set.
a|*R*
a|-
|[[dmstatus-anyresumeack]] `((anyresumeack))`
a|This field is 1 when any currently selected hart has its
((resume ack bit)) set.
a|*R*
a|-
|[[dmstatus-allnonexistent]] `((allnonexistent))`
a|This field is 1 when all currently selected harts do not exist in
this hardware platform.
a|*R*
a|-
|[[dmstatus-anynonexistent]] `((anynonexistent))`
a|This field is 1 when any currently selected hart does not exist in
this hardware platform.
a|*R*
a|-
|[[dmstatus-allunavail]] `((allunavail))`
a|This field is 1 when all currently selected harts are
unavailable, or (if {dmstatus-stickyunavail} is 1) were
unavailable without that being acknowledged.
a|*R*
a|-
|[[dmstatus-anyunavail]] `((anyunavail))`
a|This field is 1 when any currently selected hart is unavailable,
or (if {dmstatus-stickyunavail} is 1) was unavailable without
that being acknowledged.
a|*R*
a|-
|[[dmstatus-allrunning]] `((allrunning))`
a|This field is 1 when all currently selected harts are running.
a|*R*
a|-
|[[dmstatus-anyrunning]] `((anyrunning))`
a|This field is 1 when any currently selected hart is running.
a|*R*
a|-
|[[dmstatus-allhalted]] `((allhalted))`
a|This field is 1 when all currently selected harts are halted.
a|*R*
a|-
|[[dmstatus-anyhalted]] `((anyhalted))`
a|This field is 1 when any currently selected hart is halted.
a|*R*
a|-
|[[dmstatus-authenticated]] `((authenticated))`
a|

0 (false): Authentication is required before using the DM.


1 (true): The authentication check has passed.

On components that don't implement authentication, this bit must be
preset as 1.
a|*R*
a|Preset
|[[dmstatus-authbusy]] `((authbusy))`
a|

0 (ready): The authentication module is ready to process the next
read/write to {dm-authdata}.


1 (busy): The authentication module is busy. Accessing {dm-authdata} results
in unspecified behavior.

{dmstatus-authbusy} only becomes set in immediate response to an access to
{dm-authdata}.
a|*R*
a|0
|[[dmstatus-hasresethaltreq]] `((hasresethaltreq))`
a|1 if this Debug Module supports halt-on-reset functionality
controllable by the {dmcontrol-setresethaltreq} and {dmcontrol-clrresethaltreq} bits.
0 otherwise.
a|*R*
a|Preset
|[[dmstatus-confstrptrvalid]] `((confstrptrvalid))`
a|

0 (invalid): {dm-confstrptr0}--{dm-confstrptr3} hold information which
is not relevant to the configuration structure.


1 (valid): {dm-confstrptr0}--{dm-confstrptr3} hold the address of the
configuration structure.
a|*R*
a|Preset
|[[dmstatus-version]] `((version))`
a|

0 (none): There is no Debug Module present.


1 (0.11): There is a Debug Module and it conforms to version 0.11 of this
specification.


2 (0.13): There is a Debug Module and it conforms to version 0.13 of this
specification.


3 (1.0): There is a Debug Module and it conforms to version 1.0 of this
specification.


15 (custom): There is a Debug Module but it does not conform to any
available version of this spec.
a|*R*
a|3
|===

[[dm-dmcontrol]]
==== Debug Module Control (((dmcontrol)), at 0x10)

This register controls the overall Debug Module
as well as the currently selected harts, as defined in {dmcontrol-hasel}.

[[hartsel]]
(((hartsel)))
Throughout this document we refer to {hartsel}, which is {dmcontrol-hartselhi}
combined with {dmcontrol-hartsello}. While the spec allows for 20 {hartsel} bits,
an implementation may choose to implement fewer than that. The actual
width of {hartsel} is called `HARTSELLEN`. It must be at least 0
and at most 20. A debugger should discover `HARTSELLEN` by writing
all ones to {hartsel} (assuming the maximum size) and reading back the
value to see which bits were actually set. Debuggers must not change
{hartsel} while an abstract command is executing. Hardware should enforce
this by ignoring changes to {hartsel} while {abstractcs-busy} is set.

[NOTE]
====
There are separate {dmcontrol-setresethaltreq} and {dmcontrol-clrresethaltreq} bits so that
it is possible to write {dm-dmcontrol} without changing the halt-on-reset
request bit for each selected hart, when not all selected harts have
the same configuration.
====

On any given write, a debugger may only write 1 to at most one of the
following bits: {dmcontrol-resumereq}, {dmcontrol-hartreset}, {dmcontrol-ackhavereset},
{dmcontrol-setresethaltreq}, and {dmcontrol-clrresethaltreq}. The others must be written 0.

[[resethaltreq]]
(((resethaltreq)))
{resethaltreq} is an optional internal bit of per-hart state that cannot be
read, but can be written with {dmcontrol-setresethaltreq} and {dmcontrol-clrresethaltreq}.

[[keepalive]]
(((keepalive)))
{keepalive} is an optional internal bit of per-hart state. When it is
set, it suggests that the hardware should attempt to keep the hart
available for the debugger, e.g. by keeping it from entering a
low-power state once powered on. Even if the bit is implemented,
hardware might not be able to keep a hart available. The bit is
written through {dmcontrol-setkeepalive} and
{dmcontrol-clrkeepalive}.

For forward compatibility, {dmstatus-version} will always be readable when bit 1
({dmcontrol-ndmreset}) is 0 and bit 0 ({dmcontrol-dmactive}) is 1.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 29)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "31" "" "" "30" "" "" "29" "" "" "" "28" "" "" "" "" "27" "" "" "" "26" "" "25" "" "" "" "" "" "16"]})
(draw-box (text "haltreq" {:font-size 20}) {:span 3})
(draw-box (text "resumereq" {:font-size 20}) {:span 3})
(draw-box (text "hartreset" {:font-size 20}) {:span 3})
(draw-box (text "ackhavereset" {:font-size 20}) {:span 5})
(draw-box (text "ackunavail" {:font-size 20}) {:span 5})
(draw-box (text "hasel" {:font-size 20}) {:span 3})
(draw-box (text "hartsello" {:font-size 20}) {:span 7})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "10" {:span 7 :borders {}})
----
[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 33)
(draw-column-headers {:font-size 15 :height 17 :labels ["15" "" "" "" "" "" "6" "" "" "5" "" "" "" "" "4" "" "" "" "" "3" "" "" "" "" "2" "" "" "" "1" "" "" "0" ""]})
(draw-box (text "hartselhi" {:font-size 20}) {:span 7})
(draw-box (text "setkeepalive" {:font-size 20}) {:span 5})
(draw-box (text "clrkeepalive" {:font-size 20}) {:span 5})
(draw-box (text "setresethaltreq" {:font-size 20}) {:span 5})
(draw-box (text "clrresethaltreq" {:font-size 20}) {:span 5})
(draw-box (text "ndmreset" {:font-size 20}) {:span 3})
(draw-box (text "dmactive" {:font-size 20}) {:span 3})
(draw-box "10" {:span 7 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[dmcontrol-haltreq]] `((haltreq))`
a|Writing 0 clears the halt request bit for all currently selected
harts. This may cancel outstanding halt requests for those harts.

Writing 1 sets the halt request bit for all currently selected
harts. Running harts will halt whenever their halt request bit is
set.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.

Writes to this bit should be ignored while an abstract command is
executing.
a|*WARZ*
a|-
|[[dmcontrol-resumereq]] `((resumereq))`
a|Writing 1 causes the currently selected harts to resume once, if
they are halted when the write occurs. It also clears the resume
ack bit for those harts.

{dmcontrol-resumereq} is ignored if {dmcontrol-haltreq} is set.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.

Writes to this bit should be ignored while an abstract command is
executing.
a|*W1*
a|-
|[[dmcontrol-hartreset]] `((hartreset))`
a|This optional field writes the reset bit for all the currently
selected harts.  To perform a reset the debugger writes 1, and then
writes 0 to deassert the reset signal.

While this bit is 1, the debugger must not change which harts are
selected.

If this feature is not implemented, the bit always stays 0, so
after writing 1 the debugger can read the register back to see if
the feature is supported.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.
a|*WARL*
a|0
|[[dmcontrol-ackhavereset]] `((ackhavereset))`
a|

0 (nop): No effect.


1 (ack): Clears `havereset` for any selected harts.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.

Writes to this bit should be ignored while an abstract command is
executing.
a|*W1*
a|-
|[[dmcontrol-ackunavail]] `((ackunavail))`
a|

0 (nop): No effect.


1 (ack): Clears `unavail` for any selected harts that are currently available.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.
a|*W1*
a|-
|[[dmcontrol-hasel]] `((hasel))`
a|Selects the definition of currently selected harts.

0 (single): There is a single currently selected hart, that is selected by {hartsel}.


1 (multiple): There may be multiple currently selected harts -- the hart
selected by {hartsel}, plus those selected by the hart array mask
register.

An implementation which does not implement the hart array mask register
must tie this field to 0. A debugger which wishes to use the hart array
mask register feature should set this bit and read back to see if the functionality
is supported.
a|*WARL*
a|0
|[[dmcontrol-hartsello]] `((hartsello))`
a|The low 10 bits of {hartsel}: the DM-specific index of the hart to
select. This hart is always part of the currently selected harts.
a|*WARL*
a|0
|[[dmcontrol-hartselhi]] `((hartselhi))`
a|The high 10 bits of {hartsel}: the DM-specific index of the hart to
select. This hart is always part of the currently selected harts.
a|*WARL*
a|0
|[[dmcontrol-setkeepalive]] `((setkeepalive))`
a|This optional field sets {keepalive} for all currently selected
harts, unless {dmcontrol-clrkeepalive} is simultaneously set to
1.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.
a|*W1*
a|-
|[[dmcontrol-clrkeepalive]] `((clrkeepalive))`
a|This optional field clears {keepalive} for all currently selected
harts.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.
a|*W1*
a|-
|[[dmcontrol-setresethaltreq]] `((setresethaltreq))`
a|This optional field writes the halt-on-reset request bit for all
currently selected harts, unless {dmcontrol-clrresethaltreq} is
simultaneously set to 1.
When set to 1, each selected hart will halt upon the next deassertion
of its reset. The halt-on-reset request bit is not automatically
cleared. The debugger must write to {dmcontrol-clrresethaltreq} to clear it.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.

If {dmstatus-hasresethaltreq} is 0, this field is not implemented.

Writes to this bit should be ignored while an abstract command is
executing.
a|*W1*
a|-
|[[dmcontrol-clrresethaltreq]] `((clrresethaltreq))`
a|This optional field clears the halt-on-reset request bit for all
currently selected harts.

Writes apply to the new value of {hartsel} and {dmcontrol-hasel}.

Writes to this bit should be ignored while an abstract command is
executing.
a|*W1*
a|-
|[[dmcontrol-ndmreset]] `((ndmreset))`
a|This bit controls the reset signal from the DM to the rest of the
hardware platform. The signal should reset every part of the hardware platform, including
every hart, except for the DM and any logic required to access the
DM.
To perform a hardware platform reset the debugger writes 1,
and then writes 0
to deassert the reset.
a|*R/W*
a|0
|[[dmcontrol-dmactive]] `((dmactive))`
a|This bit serves as a reset signal for the Debug Module itself.
After changing the value of this bit, the debugger must poll
{dm-dmcontrol} until {dmcontrol-dmactive} has taken the requested value
before performing any action that assumes the requested {dmcontrol-dmactive}
state change has completed.  Hardware may
take an arbitrarily long time to complete activation or deactivation and will
indicate completion by setting {dmcontrol-dmactive} to the requested value.
During this time, the DM may ignore any register writes.

0 (inactive): The module's state, including authentication mechanism,
takes its reset values (the {dmcontrol-dmactive} bit is the only bit which can
be written to something other than its reset value). Any accesses
to the module may fail. Specifically, {dmstatus-version} might not return
correct data.

When this value is written, the DM may ignore any other bits written
to {dmcontrol} in the same write.


1 (active): The module functions normally.

No other mechanism should exist that may result in resetting the
Debug Module after power up.

To place the Debug Module into a known state, a debugger should write 0 to {dmcontrol-dmactive},
poll until {dmcontrol-dmactive} is observed 0, write 1 to {dmcontrol-dmactive}, and
poll until {dmcontrol-dmactive} is observed 1.

Implementations may pay attention to this bit to further aid
debugging, for example by preventing the Debug Module from being
power gated while debugging is active.
a|*R/W*
a|0
|===

[[dm-hartinfo]]
==== Hart Info (((hartinfo)), at 0x12)

This register gives information about the hart currently
selected by {hartsel}.

This register is optional. If it is not present it should
read all-zero.

If this register is included, the debugger can do more with
the Program Buffer by writing programs which
explicitly access the `data` and/or `dscratch`
registers.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 32)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "24" "23" "" "" "" "20" "19" "" "" "" "17" "" "" "16" "" "" "15" "" "" "" "12" "11" "" "" "" "" "" "0"]})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "nscratch" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "dataaccess" {:font-size 20}) {:span 5})
(draw-box (text "datasize" {:font-size 20}) {:span 5})
(draw-box (text "dataaddr" {:font-size 20}) {:span 7})
(draw-box "8" {:span 5 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "12" {:span 7 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[hartinfo-nscratch]] `((nscratch))`
a|Number of `dscratch` registers available for the debugger
to use during program buffer execution, starting from {csr-dscratch0}.
The debugger can make no assumptions about the contents of these
registers between commands.
a|*R*
a|Preset
|[[hartinfo-dataaccess]] `((dataaccess))`
a|

0 (csr): The `data` registers are shadowed in the hart by CSRs.
Each CSR is DXLEN bits in size, and corresponds
to a single argument, per <<tab:datareg>>.


1 (memory): The `data` registers are shadowed in the hart's memory map.
Each register takes up 4 bytes in the memory map.
a|*R*
a|Preset
|[[hartinfo-datasize]] `((datasize))`
a|If {hartinfo-dataaccess} is 0: Number of CSRs dedicated to
shadowing the `data` registers.

If {hartinfo-dataaccess} is 1: Number of 32-bit words in the memory map
dedicated to shadowing the `data` registers.

Since there are at most 12 `data` registers, the value in this
register must be 12 or smaller.
a|*R*
a|Preset
|[[hartinfo-dataaddr]] `((dataaddr))`
a|If {hartinfo-dataaccess} is 0: The number of the first CSR dedicated to
shadowing the `data` registers.

If {hartinfo-dataaccess} is 1: Address of RAM where the data
registers are shadowed. This address is sign extended giving a
range of -2048 to 2047, easily addressed with a load or store using
`x0` as the address register.
a|*R*
a|Preset
|===

[[dm-hawindowsel]]
==== Hart Array Window Select (((hawindowsel)), at 0x14)

This register selects which of the 32-bit portion of the hart array mask
register (see xref:hartarraymask[]) is accessible in {dm-hawindow}.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "15" "14" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "0" {:font-size 20}) {:span 7})
(draw-box (text "hawindowsel" {:font-size 20}) {:span 7})
(draw-box "" {:span 10 :borders {}})
(draw-box "17" {:span 7 :borders {}})
(draw-box "15" {:span 7 :borders {}})
(draw-box "" {:span 10 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[hawindowsel-hawindowsel]] `((hawindowsel))`
a|The high bits of this field may be tied to 0, depending on how large
the array mask register is.  E.g. on a hardware platform with 48 harts only bit 0
of this field may actually be writable.
a|*WARL*
a|0
|===

[[dm-hawindow]]
==== Hart Array Window  (((hawindow)), at 0x15)

This register provides R/W access to a 32-bit portion of the
hart array mask register (see xref:hartarraymask[]).
The position of the window is determined by {dm-hawindowsel}. I.e. bit 0
refers to hart {dm-hawindowsel} latexmath:[$* 32$], while bit 31 refers to hart
{dm-hawindowsel} latexmath:[$* 32 + 31$].

Since some bits in the hart array mask register may be constant 0, some
bits in this register may be constant 0, depending on the current value
of {dm-hawindowsel}.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "maskdata" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-abstractcs]]
==== Abstract Control and Status (((abstractcs)), at 0x16)

Writing this register while an abstract command is executing causes
{abstractcs-cmderr} to become 1 (busy) once the command completes
({abstractcs-busy} becomes 0).

[NOTE]
====
{abstractcs-datacount} must be at least 1 to support RV32 harts, 2 to support
RV64 harts, or 4 to support RV128 harts.
====


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 40)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "29" "28" "" "" "" "24" "23" "" "" "" "" "" "13" "" "12" "" "" "" "11" "" "" "10" "" "" "" "8" "7" "" "" "" "4" "3" "" "" "" "0"]})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "progbufsize" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 7})
(draw-box (text "busy" {:font-size 20}) {:span 3})
(draw-box (text "relaxedpriv" {:font-size 20}) {:span 5})
(draw-box (text "cmderr" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "datacount" {:font-size 20}) {:span 5})
(draw-box "3" {:span 5 :borders {}})
(draw-box "5" {:span 5 :borders {}})
(draw-box "11" {:span 7 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "4" {:span 5 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[abstractcs-progbufsize]] `((progbufsize))`
a|Size of the Program Buffer, in 32-bit words. Valid sizes are 0 - 16.
a|*R*
a|Preset
|[[abstractcs-busy]] `((busy))`
a|

0 (ready): There is no abstract command currently being executed.


1 (busy): An abstract command is currently being executed.

This bit is set as soon as {dm-command} is written, and is
not cleared until that command has completed.
a|*R*
a|0
|[[abstractcs-relaxedpriv]] `((relaxedpriv))`
a|This optional bit controls whether program buffer and abstract
memory accesses are performed with the exact and full set of
permission checks that apply based on the current architectural
state of the hart performing the access, or with a relaxed set of
permission checks (e.g. PMP restrictions are ignored).  The
details of the latter are implementation-specific.

0 (full checks): Full permission checks apply.


1 (relaxed checks): Relaxed permission checks apply.
a|*WARL*
a|Preset
|[[abstractcs-cmderr]] `((cmderr))`
a|Gets set if an abstract command fails. The bits in this field remain set until
they are cleared by writing 1 to them. No abstract command is
started until the value is reset to 0.

This field only contains a valid value if {abstractcs-busy} is 0.

0 (none): No error.


1 (busy): An abstract command was executing while {dm-command},
{dm-abstractcs}, or {dm-abstractauto} was written, or when one
of the `data` or `progbuf` registers was read or written.
This status is only written if {abstractcs-cmderr} contains 0.


2 (not supported): The command in {dm-command} is not supported.  It
may be supported with different options set, but it will not be
supported at a later time when the hart or system state are
different.


3 (exception): An exception occurred while executing the command
(e.g. while executing the Program Buffer).


4 (halt/resume): The abstract command couldn't execute because the
hart wasn't in the required state (running/halted), or unavailable.


5 (bus): The abstract command failed due to a bus error (e.g.
alignment, access size, or timeout).


6 (reserved): Reserved for future use.


7 (other): The command failed for another reason.
a|*R/W1C*
a|0
|[[abstractcs-datacount]] `((datacount))`
a|Number of `data` registers that are implemented as part of the
abstract command interface. Valid sizes are 1 -- 12.
a|*R*
a|Preset
|===

[[dm-command]]
==== Abstract Command (((command)), at 0x17)

Writes to this register cause the corresponding abstract command to be
executed.

Writing this register while an abstract command is executing causes
{abstractcs-cmderr} to become 1 (busy) once the command completes
(busy becomes 0).

If {abstractcs-cmderr} is non-zero, writes to this register are ignored.

[NOTE]
====
{abstractcs-cmderr} inhibits starting a new command to accommodate debuggers
that, for performance reasons, send several commands to be executed
in a row without checking {abstractcs-cmderr} in between. They can safely do
so and check {abstractcs-cmderr} at the end without worrying that one command
failed but then a later command (which might have depended on the
previous one succeeding) passed.
====


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "24" "23" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "cmdtype" {:font-size 20}) {:span 5})
(draw-box (text "control" {:font-size 20}) {:span 7})
(draw-box "" {:span 12 :borders {}})
(draw-box "8" {:span 5 :borders {}})
(draw-box "24" {:span 7 :borders {}})
(draw-box "" {:span 12 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[command-cmdtype]] `((cmdtype))`
a|The type determines the overall functionality of this
abstract command.
a|*WARZ*
a|0
|[[command-control]] `((control))`
a|This field is interpreted in a command-specific manner,
described for each abstract command.
a|*WARZ*
a|0
|===

[[dm-abstractauto]]
==== Abstract Command Autoexec (((abstractauto)), at 0x18)

This register is optional. Including it allows more efficient burst
accesses.  A debugger can detect whether it is supported by setting bits
and reading them back.

If this register is implemented then bits corresponding to implemented
progbuf and data registers must be writable.  Other bits must be
hard-wired to 0.

If this register is written while an abstract command is executing
then the write is ignored and
{abstractcs-cmderr} becomes 1 (busy) once the command completes
(busy becomes 0).


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "16" "15" "" "" "" "12" "11" "" "" "" "" "" "0" "" "" "" "" ""]})
(draw-box (text "autoexecprogbuf" {:font-size 20}) {:span 7})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "autoexecdata" {:font-size 20}) {:span 7})
(draw-box "" {:span 5 :borders {}})
(draw-box "16" {:span 7 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "12" {:span 7 :borders {}})
(draw-box "" {:span 5 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[abstractauto-autoexecprogbuf]] `((autoexecprogbuf))`
a|When a bit in this field is 1, read or write accesses to the
corresponding `progbuf` word cause the DM to act as if the
current value in {dm-command} was written there again after the
access to `progbuf` completes.
a|*WARL*
a|0
|[[abstractauto-autoexecdata]] `((autoexecdata))`
a|When a bit in this field is 1, read or write accesses to the
corresponding `data` word cause the DM to act as if the current
value in {dm-command} was written there again after the
access to `data` completes.
a|*WARL*
a|0
|===

[[dm-confstrptr0]]
==== Configuration Structure Pointer 0 (((confstrptr0)), at 0x19)

When {dmstatus-confstrptrvalid} is set, reading this register returns bits 31:0
of the configuration structure pointer. Reading the other `confstrptr`
registers returns the upper bits of the address.

When system bus access is implemented, this must be an
address that can be used with the System Bus Access module. Otherwise,
this must be an address that can be used to access the
configuration structure from the hart with ID 0.

If {dmstatus-confstrptrvalid} is 0, then the `confstrptr` registers
hold identifier information which is not
further specified in this document.

The configuration structure itself is a data structure of the same format
as the data structure pointed to by `mconfigptr` as described in the
Privileged Spec.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "addr" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-confstrptr1]]
==== Configuration Structure Pointer 1 (((confstrptr1)), at 0x1a)

When {dmstatus-confstrptrvalid} is set, reading this register returns bits 63:32
of the configuration structure pointer. See {dm-confstrptr0} for more details.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "addr" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-confstrptr2]]
==== Configuration Structure Pointer 2 (((confstrptr2)), at 0x1b)

When {dmstatus-confstrptrvalid} is set, reading this register returns bits 95:64
of the configuration structure pointer. See {dm-confstrptr0} for more details.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "addr" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-confstrptr3]]
==== Configuration Structure Pointer 3 (((confstrptr3)), at 0x1c)

When {dmstatus-confstrptrvalid} is set, reading this register returns bits 127:96
of the configuration structure pointer. See {dm-confstrptr0} for more details.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "addr" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-nextdm]]
==== Next Debug Module (((nextdm)), at 0x1d)

If there is more than one DM accessible on this DMI, this register
contains the base address of the next one in the chain, or 0 if this is
the last one in the chain.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "addr" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-data0]]
==== Abstract Data 0 (((data0)), at 0x04)

{dm-data0} through {dm-data11} are registers that may
be read or changed by abstract commands. {abstractcs-datacount} indicates how many
of them are implemented, starting at {dm-data0}, counting up.
<<tab:datareg>> shows how abstract commands use these
registers.

Accessing these registers while an abstract command is executing causes
{abstractcs-cmderr} to be set to 1 (busy) if it is 0.

Attempts to write them while {abstractcs-busy} is set does not change their value.

The values in these registers might not be preserved after an abstract
command is executed. The only guarantees on their contents are the ones
offered by the command in question. If the command fails, no
assumptions can be made about the contents of these registers.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-progbuf0]]
==== Program Buffer 0 (((progbuf0)), at 0x20)

{dm-progbuf0} through {dm-progbuf15} must provide write access to the
optional program buffer. It may also be possible for the debugger to
read from the program buffer through these registers. If reading
is not supported, then all reads return 0.

{abstractcs-progbufsize} indicates how many `progbuf` registers are
implemented starting at {dm-progbuf0}, counting up.

Accessing these registers while an abstract command is executing causes
{abstractcs-cmderr} to be set to 1 (busy) if it is 0.

Attempts to write them while {abstractcs-busy} is set does not change their value.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-authdata]]
==== Authentication Data (((authdata)), at 0x30)

This register serves as a 32-bit serial port to/from the authentication
module.

When {dmstatus-authbusy} is clear, the debugger can communicate with the
authentication module by reading or writing this register. There is no
separate mechanism to signal overflow/underflow.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-dmcs2]]
==== Debug Module Control and Status 2 (((dmcs2)), at 0x32)

This register contains DM control and status bits that didn't easily
fit in {dm-dmcontrol} and {dm-dmstatus}. All are optional.

If halt groups are not implemented, then {dmcs2-group} will always
be 0 when {dmcs2-grouptype} is 0.

If resume groups are not implemented, then {dmcs2-grouptype} will
remain 0 even after 1 is written there.

The DM external triggers available to add to halt groups may be the same as
or distinct from the DM external triggers available to add to resume groups.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 26)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "12" "" "11" "" "10" "" "" "" "7" "6" "" "" "" "2" "" "1" "" "" "0" ""]})
(draw-box (text "0" {:font-size 20}) {:span 7})
(draw-box (text "grouptype" {:font-size 20}) {:span 3})
(draw-box (text "dmexttrigger" {:font-size 20}) {:span 5})
(draw-box (text "group" {:font-size 20}) {:span 5})
(draw-box (text "hgwrite" {:font-size 20}) {:span 3})
(draw-box (text "hgselect" {:font-size 20}) {:span 3})
(draw-box "20" {:span 7 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "5" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[dmcs2-grouptype]] `((grouptype))`
a|

0 (halt): The remaining fields in this register configure halt groups.


1 (resume): The remaining fields in this register configure resume groups.
a|*WARL*
a|0
|[[dmcs2-dmexttrigger]] `((dmexttrigger))`
a|This field contains the currently selected DM external trigger.

If a non-existent trigger value is written here, the hardware will
change it to a valid one or 0 if no DM external triggers exist.
a|*WARL*
a|0
|[[dmcs2-group]] `((group))`
a|When {dmcs2-hgselect} is 0, contains the group of the hart
specified by {hartsel}.

When {dmcs2-hgselect} is 1, contains the group of the DM external
trigger selected by {dmcs2-dmexttrigger}.

The value written to this field is ignored unless {dmcs2-hgwrite}
is also written 1.

Group numbers are contiguous starting at 0, with the highest number
being implementation-dependent, and possibly different between
different group types. Debuggers should read back this field after
writing to confirm they are using a hart group that is supported.

If groups aren't implemented, then this entire field is 0.
a|*WARL*
a|preset
|[[dmcs2-hgwrite]] `((hgwrite))`
a|When 1 is written and {dmcs2-hgselect} is 0, for every selected
hart the DM will change its group to the value written to {dmcs2-group},
if the hardware supports that group for that hart.
Implementations may also change the group of a minimal set of
unselected harts in the same way, if that is necessary due to
a hardware limitation.

When 1 is written and {dmcs2-hgselect} is 1, the DM will change
the group of the DM external trigger selected by {dmcs2-dmexttrigger}
to the value written to {dmcs2-group}, if the hardware supports
that group for that trigger.

Writing 0 has no effect.
a|*W1*
a|-
|[[dmcs2-hgselect]] `((hgselect))`
a|

0 (harts): Operate on harts.


1 (triggers): Operate on DM external triggers.

If there are no DM external triggers, this field must be tied to 0.
a|*WARL*
a|0
|===

[[dm-haltsum0]]
==== Halt Summary 0 (((haltsum0)), at 0x40)

Each bit in this read-only register indicates whether one specific hart
is halted or not. Unavailable/nonexistent harts are not considered to
be halted.

This register might not be present if fewer than 2 harts are connected
to this DM.

The LSB reflects the halt status of hart {hartsel[19:5],5'h0}, and the
MSB reflects halt status of hart {hartsel[19:5],5'h1f}.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "haltsum0" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-haltsum1]]
==== Halt Summary 1 (((haltsum1)), at 0x13)

Each bit in this read-only register indicates whether any of a group of
harts is halted or not. Unavailable/nonexistent harts are not considered to
be halted.

This register might not be present if fewer than 33 harts are connected
to this DM.

The LSB reflects the halt status of harts {hartsel[19:10],10'h0}
through {hartsel[19:10],10'h1f}.
The MSB reflects the halt status of harts {hartsel[19:10],10'h3e0}
through {hartsel[19:10],10'h3ff}.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "haltsum1" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-haltsum2]]
==== Halt Summary 2 (((haltsum2)), at 0x34)

Each bit in this read-only register indicates whether any of a group of
harts is halted or not. Unavailable/nonexistent harts are not considered to
be halted.

This register might not be present if fewer than 1025 harts are connected
to this DM.

The LSB reflects the halt status of harts {hartsel[19:15],15'h0}
through {hartsel[19:15],15'h3ff}.
The MSB reflects the halt status of harts {hartsel[19:15],15'h7c00}
through {hartsel[19:15],15'h7fff}.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "haltsum2" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-haltsum3]]
==== Halt Summary 3 (((haltsum3)), at 0x35)

Each bit in this read-only register indicates whether any of a group of
harts is halted or not. Unavailable/nonexistent harts are not considered to
be halted.

This register might not be present if fewer than 32769 harts are connected
to this DM.

The LSB reflects the halt status of harts 20'h0 through 20'h7fff.
The MSB reflects the halt status of harts 20'hf8000 through 20'hfffff.

This entire register is read-only.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "haltsum3" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[dm-sbcs]]
==== System Bus Access Control and Status (((sbcs)), at 0x38)




[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 33)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "29" "28" "" "" "" "23" "" "" "22" "" "" "" "21" "" "" "" "20" "" "" "19" "" "" "" "17" "" "" "16" "" ""]})
(draw-box (text "sbversion" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "sbbusyerror" {:font-size 20}) {:span 5})
(draw-box (text "sbbusy" {:font-size 20}) {:span 3})
(draw-box (text "sbreadonaddr" {:font-size 20}) {:span 5})
(draw-box (text "sbaccess" {:font-size 20}) {:span 5})
(draw-box (text "sbautoincrement" {:font-size 20}) {:span 5})
(draw-box "3" {:span 5 :borders {}})
(draw-box "6" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
----
[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 38)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "" "15" "" "" "14" "" "" "" "12" "11" "" "" "" "5" "" "" "4" "" "" "" "" "3" "" "" "" "" "2" "" "" "" "" "1" "" "" "" "0" ""]})
(draw-box (text "sbreadondata" {:font-size 20}) {:span 5})
(draw-box (text "sberror" {:font-size 20}) {:span 5})
(draw-box (text "sbasize" {:font-size 20}) {:span 5})
(draw-box (text "sbaccess128" {:font-size 20}) {:span 5})
(draw-box (text "sbaccess64" {:font-size 20}) {:span 5})
(draw-box (text "sbaccess32" {:font-size 20}) {:span 5})
(draw-box (text "sbaccess16" {:font-size 20}) {:span 5})
(draw-box (text "sbaccess8" {:font-size 20}) {:span 3})
(draw-box "1" {:span 5 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "7" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbcs-sbversion]] `((sbversion))`
a|

0 (legacy): The System Bus interface conforms to mainline drafts of this
spec older than 1 January, 2018.


1 (1.0): The System Bus interface conforms to this version of the spec.

Other values are reserved for future versions.
a|*R*
a|1
|[[sbcs-sbbusyerror]] `((sbbusyerror))`
a|Set when the debugger attempts to read data while a read is in
progress, or when the debugger initiates a new access while one is
already in progress (while {sbcs-sbbusy} is set). It remains set until
it's explicitly cleared by the debugger.

While this field is set, no more system bus accesses can be
initiated by the Debug Module.
a|*R/W1C*
a|0
|[[sbcs-sbbusy]] `((sbbusy))`
a|When 1, indicates the system bus manager is busy. (Whether the
system bus itself is busy is related, but not the same thing.) This
bit goes high immediately when a read or write is requested for any
reason, and does not go low until the access is fully completed.

Writes to {dm-sbcs} while {sbcs-sbbusy} is high result in undefined
behavior.  A debugger must not write to {dm-sbcs} until it reads
{sbcs-sbbusy} as 0.
a|*R*
a|0
|[[sbcs-sbreadonaddr]] `((sbreadonaddr))`
a|When 1, every write to {dm-sbaddress0} automatically triggers a
system bus read at the new address.
a|*R/W*
a|0
|[[sbcs-sbaccess]] `((sbaccess))`
a|Select the access size to use for system bus accesses.

0 (8bit): 8-bit


1 (16bit): 16-bit


2 (32bit): 32-bit


3 (64bit): 64-bit


4 (128bit): 128-bit

If {sbcs-sbaccess} has an unsupported value when the DM starts a bus
access, the access is not performed and {sbcs-sberror} is set to 4.
a|*R/W*
a|2
|[[sbcs-sbautoincrement]] `((sbautoincrement))`
a|When 1, `sbaddress` is incremented by the access size (in
bytes) selected in {sbcs-sbaccess} after every system bus access.
a|*R/W*
a|0
|[[sbcs-sbreadondata]] `((sbreadondata))`
a|When 1, every read from {dm-sbdata0} automatically triggers a
system bus read at the (possibly auto-incremented) address.
a|*R/W*
a|0
|[[sbcs-sberror]] `((sberror))`
a|When the Debug Module's system bus
manager encounters an error, this field gets set. The bits in this
field remain set until they are cleared by writing 1 to them.
While this field is non-zero, no more system bus accesses can be
initiated by the Debug Module.

An implementation may report ``Other'' (7) for any error condition.

0 (none): There was no bus error.


1 (timeout): There was a timeout.


2 (address): A bad address was accessed.


3 (alignment): There was an alignment error.


4 (size): An access of unsupported size was requested.


7 (other): Other.
a|*R/W1C*
a|0
|[[sbcs-sbasize]] `((sbasize))`
a|Width of system bus addresses in bits. (0 indicates there is no bus
access support.)
a|*R*
a|Preset
|[[sbcs-sbaccess128]] `((sbaccess128))`
a|1 when 128-bit system bus accesses are supported.
a|*R*
a|Preset
|[[sbcs-sbaccess64]] `((sbaccess64))`
a|1 when 64-bit system bus accesses are supported.
a|*R*
a|Preset
|[[sbcs-sbaccess32]] `((sbaccess32))`
a|1 when 32-bit system bus accesses are supported.
a|*R*
a|Preset
|[[sbcs-sbaccess16]] `((sbaccess16))`
a|1 when 16-bit system bus accesses are supported.
a|*R*
a|Preset
|[[sbcs-sbaccess8]] `((sbaccess8))`
a|1 when 8-bit system bus accesses are supported.
a|*R*
a|Preset
|===

[[dm-sbaddress0]]
==== System Bus Address 31:0 (((sbaddress0)), at 0x39)

If {sbcs-sbasize} is 0, then this register is not present.

When the system bus manager is busy, writes to this register will set
{sbcs-sbbusyerror} and don't do anything else.

If {sbcs-sberror} is 0, {sbcs-sbbusyerror} is 0, and {sbcs-sbreadonaddr} is set then writes to this register start the following:

. Set {sbcs-sbbusy}.
. Perform a bus read from the new value of `sbaddress`.
. If the read succeeded and {sbcs-sbautoincrement} is set, increment `sbaddress`.
. Clear {sbcs-sbbusy}.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "address" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbaddress0-address]] `((address))`
a|Accesses bits 31:0 of the physical address in `sbaddress`.
a|*R/W*
a|0
|===

[[dm-sbaddress1]]
==== System Bus Address 63:32 (((sbaddress1)), at 0x3a)

If {sbcs-sbasize} is less than 33, then this register is not present.

When the system bus manager is busy, writes to this register will set
{sbcs-sbbusyerror} and don't do anything else.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "address" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbaddress1-address]] `((address))`
a|Accesses bits 63:32 of the physical address in `sbaddress` (if
the system address bus is that wide).
a|*R/W*
a|0
|===

[[dm-sbaddress2]]
==== System Bus Address 95:64 (((sbaddress2)), at 0x3b)

If {sbcs-sbasize} is less than 65, then this register is not present.

When the system bus manager is busy, writes to this register will set
{sbcs-sbbusyerror} and don't do anything else.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "address" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbaddress2-address]] `((address))`
a|Accesses bits 95:64 of the physical address in `sbaddress` (if
the system address bus is that wide).
a|*R/W*
a|0
|===

[[dm-sbaddress3]]
==== System Bus Address 127:96 (((sbaddress3)), at 0x37)

If {sbcs-sbasize} is less than 97, then this register is not present.

When the system bus manager is busy, writes to this register will set
{sbcs-sbbusyerror} and don't do anything else.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "address" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbaddress3-address]] `((address))`
a|Accesses bits 127:96 of the physical address in `sbaddress` (if
the system address bus is that wide).
a|*R/W*
a|0
|===

[[dm-sbdata0]]
==== System Bus Data 31:0 (((sbdata0)), at 0x3c)

If all of the `sbaccess` bits in {dm-sbcs} are 0, then this register
is not present.

Any successful system bus read updates `sbdata`. If the width of
the read access is less than the width of `sbdata`, the contents of
the remaining high bits may take on any value.

If either {sbcs-sberror} or {sbcs-sbbusyerror} isn't 0 then accesses do nothing.

If the bus manager is busy then accesses set {sbcs-sbbusyerror}, and don't do
anything else.

Writes to this register start the following:

. Set {sbcs-sbbusy}.
. Perform a bus write of the new value of `sbdata` to `sbaddress`.
. If the write succeeded and {sbcs-sbautoincrement} is set,
increment `sbaddress`.
. Clear {sbcs-sbbusy}.

Reads from this register start the following:

. "Return" the data.
. Set {sbcs-sbbusy}.
. If {sbcs-sbreadondata} is set:
// TODO: This doesn't work right, but it does work in asiidoclive
.. Perform a system bus read from the address contained in
`sbaddress`, placing the result in `sbdata`.
.. If {sbcs-sbautoincrement} is set and the read was
successful, increment `sbaddress`.
. Clear {sbcs-sbbusy}.

Only {dm-sbdata0} has this behavior. The other `sbdata` registers
have no side effects. On systems that have buses wider than 32 bits, a
debugger should access {dm-sbdata0} after accessing the other `sbdata`
registers.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbdata0-data]] `((data))`
a|Accesses bits 31:0 of `sbdata`.
a|*R/W*
a|0
|===

[[dm-sbdata1]]
==== System Bus Data 63:32 (((sbdata1)), at 0x3d)

If {sbcs-sbaccess64} and {sbcs-sbaccess128} are 0, then this
register is not present.

If the bus manager is busy then accesses set {sbcs-sbbusyerror}, and don't do
anything else.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbdata1-data]] `((data))`
a|Accesses bits 63:32 of `sbdata` (if the system bus is that
wide).
a|*R/W*
a|0
|===

[[dm-sbdata2]]
==== System Bus Data 95:64 (((sbdata2)), at 0x3e)

This register only exists if {sbcs-sbaccess128} is 1.

If the bus manager is busy then accesses set {sbcs-sbbusyerror}, and don't do
anything else.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbdata2-data]] `((data))`
a|Accesses bits 95:64 of `sbdata` (if the system bus is that
wide).
a|*R/W*
a|0
|===

[[dm-sbdata3]]
==== System Bus Data 127:96 (((sbdata3)), at 0x3f)

This register only exists if {sbcs-sbaccess128} is 1.

If the bus manager is busy then accesses set {sbcs-sbbusyerror}, and don't do
anything else.


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[sbdata3-data]] `((data))`
a|Accesses bits 127:96 of `sbdata` (if the system bus is that
wide).
a|*R/W*
a|0
|===

[[dm-custom]]
==== Custom Features (((custom)), at 0x1f)

This optional register may be used for non-standard features. Future
version of the debug spec will not use this address.


[[dm-custom0]]
==== Custom Features 0 (((custom0)), at 0x70)

The optional {dm-custom0} through {dm-custom15} registers may
be used for non-standard features. Future versions of the debug spec
will not use these addresses.


