// Frozen from the RISC-V Debug Specification v1.0 (Ratified, 2025-02-21),
// generated from xml/hwbp_registers.xml in riscv/riscv-debug-spec. Do not regenerate;
// edit this file directly if an erratum requires a change.
[#norm:Sdtrig_trigger_modes]#The Trigger Module registers, except {csr-mscontext}, {csr-scontext}, and {csr-hcontext}, are only accessible in machine
and Debug Mode to prevent untrusted user code from causing entry into Debug
Mode without the OS's permission.#

In this section XLEN refers to the effective XLEN in the current execution
mode. [#norm:Sdtrig_xlen_handling]#On systems where XLEN values can differ between modes, this is handled
as follows.#
[#norm:Sdtrig_fields]#Fields retain their values regardless of XLEN, which only affects where
in the register these fields appear# (e.g. {tdata1-type}). [#norm:Sdtrig_fields_high]#Some fields
are wider when XLEN is 64 than when it is 32 (e.g.
{textra32-svalue}). The high bits in such fields retain their
value but are not readable when XLEN is 32.#
[#norm:Sdtrig_xlen_modification]#A modification of a register when XLEN is 32 clears any inaccessible bits
in that register.#
[[tab:trigger]]
.Trigger Module Registers
[cols="1,6,2",options="header"]
|===
|Address |Name |Section
|0x5a8 |Supervisor Context ({csr-scontext})| xref:csr-scontext[]
|0x6a8 |Hypervisor Context ({csr-hcontext})| xref:csr-hcontext[]
|0x7a0 |Trigger Select ({csr-tselect})| xref:csr-tselect[]
|0x7a1 |Trigger Data 1 ({csr-tdata1})| xref:csr-tdata1[]
|0x7a1 |Match Control ({csr-mcontrol})| xref:csr-mcontrol[]
|0x7a1 |Match Control Type 6 ({csr-mcontrol6})| xref:csr-mcontrol6[]
|0x7a1 |Instruction Count ({csr-icount})| xref:csr-icount[]
|0x7a1 |Interrupt Trigger ({csr-itrigger})| xref:csr-itrigger[]
|0x7a1 |Exception Trigger ({csr-etrigger})| xref:csr-etrigger[]
|0x7a1 |External Trigger ({csr-tmexttrigger})| xref:csr-tmexttrigger[]
|0x7a2 |Trigger Data 2 ({csr-tdata2})| xref:csr-tdata2[]
|0x7a3 |Trigger Data 3 ({csr-tdata3})| xref:csr-tdata3[]
|0x7a3 |Trigger Extra (RV32) ({csr-textra32})| xref:csr-textra32[]
|0x7a3 |Trigger Extra (RV64) ({csr-textra64})| xref:csr-textra64[]
|0x7a4 |Trigger Info ({csr-tinfo})| xref:csr-tinfo[]
|0x7a5 |Trigger Control ({csr-tcontrol})| xref:csr-tcontrol[]
|0x7a8 |Machine Context ({csr-mcontext})| xref:csr-mcontext[]
|0x7aa |Machine Supervisor Context ({csr-mscontext})| xref:csr-mscontext[]
|===
[[csr-tselect]]
==== Trigger Select (((tselect)), at 0x7a0)

[#norm:Sdtrig_tselect]#This register determines which trigger is accessible through the other
Trigger Module registers.# It is optional if no triggers are implemented.  [#norm:Sdtrig_tselect_access]#The
set of accessible triggers must start at 0, and be contiguous.#

[#norm:Sdtrig_tselect_warl]#This register is *WARL*.#
Writes of values greater than or equal to the number of supported
triggers may result in a different value in this register than what was
written or may point to a trigger where {tdata1-type}=0.
To verify that what they wrote is a valid index, debuggers can
read back the value and check that {csr-tselect} holds what they wrote
and read {csr-tdata1} to see that {tdata1-type} is non-zero.

Since triggers can be used both by Debug Mode and M-mode, the external
debugger must restore this register if it modifies it.

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "index" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "XLEN" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[csr-tdata1]]
==== Trigger Data 1 (((tdata1)), at 0x7a1)

[#norm:Sdtrig_tdata1]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_tdata1_reset]#The reset values listed here apply to every underlying trigger.#

This register is optional if no triggers are implemented.

[#norm:Sdtrig_tdata1_write0]#Writing 0 to this register must result in a trigger that is disabled.#
[#norm:Sdtrig_tdata1_multiple_types]#If this trigger supports multiple types, then the hardware should
disable it by changing {tdata1-type} to 15.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "XLEN-4" "" "" "XLEN-5" "" "" "XLEN-6" "" "" "" "" "" "" "0" "" "" "" "" "" "" ""]})
(draw-box (text "type" {:font-size 20}) {:span 5})
(draw-box (text "dmode" {:font-size 20}) {:span 3})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 7 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "XLEN - 5" {:span 9 :borders {}})
(draw-box "" {:span 7 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[tdata1-type]] `((type))`
a|

0 (none): There is no trigger at this {csr-tselect}.


1 (legacy): The trigger is a legacy SiFive address match trigger. These
should not be implemented and aren't further documented here.


2 (mcontrol): The trigger is an address/data match trigger. The remaining bits
in this register act as described in {csr-mcontrol}.


3 (icount): The trigger is an instruction count trigger. The remaining bits
in this register act as described in {csr-icount}.


4 (itrigger): The trigger is an interrupt trigger. The remaining bits
in this register act as described in {csr-itrigger}.


5 (etrigger): The trigger is an exception trigger. The remaining bits
in this register act as described in {csr-etrigger}.


6 (mcontrol6): The trigger is an address/data match trigger. The remaining bits
in this register act as described in {csr-mcontrol6}. This is similar
to a type 2 trigger, but provides additional functionality and
should be used instead of type 2 in newer implementations.


7 (tmexttrigger): The trigger is a trigger source external to the TM.  The
remaining bits in this register act as described in {csr-tmexttrigger}.


12--14 (custom): These trigger types are available for non-standard use.


15 (disabled): [#norm:Sdtrig_tdata1_type_disabled]#This trigger is disabled. In this state, {csr-tdata2} and
{csr-tdata3} can be written with any value that is supported for
any of the types this trigger implements.
The remaining bits in this register, except for {tdata1-dmode},
are ignored.#

[#norm:Sdtrig_tdata1_type_rsv]#Other values are reserved for future use.#
a|*WARL*
a|Preset
|[[tdata1-dmode]] `((dmode))`
a|[#norm:Sdtrig_tdata1_dmode_type_0]#If {tdata1-type} is 0, then this bit is hard-wired to 0.#

0 (both): [#norm:Sdtrig_tdata1_dmode_0]#Both Debug and M-mode can write the `tdata` registers at the
selected {csr-tselect}.#


1 (dmode): [#norm:Sdtrig_tdata1_dmode_1]#Only Debug Mode can write the `tdata` registers at the
selected {csr-tselect}.  Writes from other modes are ignored.#

[#norm:Sdtrig_tdata1_dmode_writable]#This bit is only writable from Debug Mode.#
In ordinary use, external debuggers will always set this bit when
configuring a trigger.
When clearing this bit, debuggers should also set the action field
(whose location depends on {tdata1-type}) to something other
than 1.
a|*WARL*
a|0
|[[tdata1-data]] `((data))`
a|[#norm:Sdtrig_tdata1_data]#If {tdata1-type} is 0, then this field is hard-wired to 0.#

Trigger-specific data.
a|*WARL*
a|Preset
|===

[[csr-tdata2]]
==== Trigger Data 2 (((tdata2)), at 0x7a2)

[#norm:Sdtrig_tdata2]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_tdata2_reset]#The reset values listed here apply to every underlying trigger.#

Trigger-specific data. It is optional if no implemented triggers use
it.

[#norm:Sdtrig_tdata2_disabled]#If the trigger is disabled, then this register can be written with any
value supported by any of the trigger types supported by this trigger.#

[#norm:Sdtrig_tdata2_sign_extend]#If XLEN is less than DXLEN, writes to this register are sign-extended.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "XLEN" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[csr-tdata3]]
==== Trigger Data 3 (((tdata3)), at 0x7a3)

[#norm:Sdtrig_tdata3]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_tdata3_reset]#The reset values listed here apply to every underlying trigger.#

Trigger-specific data. It is optional if no implemented triggers use
it.

[#norm:Sdtrig_tdata3_disabled]#If the trigger is disabled, then this register can be written with any
value supported by any of the trigger types supported by this trigger.#

[#norm:Sdtrig_tdata3_sign_extend]#If XLEN is less than DXLEN, writes to this register are sign-extended.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 15 :borders {}})
(draw-box "XLEN" {:span 9 :borders {}})
(draw-box "" {:span 15 :borders {}})
----

[[csr-tinfo]]
==== Trigger Info (((tinfo)), at 0x7a4)

[#norm:Sdtrig_tinfo]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_tinfo_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_tinfo_optional]#This register is optional if no triggers are implemented, or if
{tdata1-type} is not writable and {tinfo-version} would be 0. In
this case the debugger can read the only supported type from
{csr-tdata1}.#

Writing this read/write CSR has no effect.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "32" "31" "" "" "" "24" "23" "" "" "" "16" "15" "" "" "" "" "" "0" "" "" "" ""]})
(draw-box (text "0" {:font-size 20}) {:span 3})
(draw-box (text "version" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "info" {:font-size 20}) {:span 7})
(draw-box "" {:span 4 :borders {}})
(draw-box "XLEN - 32" {:span 3 :borders {}})
(draw-box "8" {:span 5 :borders {}})
(draw-box "8" {:span 5 :borders {}})
(draw-box "16" {:span 7 :borders {}})
(draw-box "" {:span 4 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[tinfo-version]] `((version))`
a|[#norm:Sdtrig_tinfo_version]#Contains the version of the Sdtrig extension implemented.#

0 (0): [#norm:Sdtrig_tinfo_version_0]#Supports triggers as described in this spec at commit 5a5c078,
made on February 2, 2023.#

In these older versions:

. {csr-mcontrol6} has a timing bit identical to {mcontrol-timing}
. {mcontrol6-hit0} behaves just as {mcontrol-hit}.
. {mcontrol6-hit1} is read-only 0.
. Encodings for {mcontrol6-size} for access sizes larger than 64 bits are different.


1 (1): [#norm:Sdtrig_tinfo_version_1]#Supports triggers as described in the ratified version 1.0 of
this document.#
a|*R*
a|Preset
|[[tinfo-info]] `((info))`
a|[#norm:Sdtrig_tinfo_support]#One bit for each possible {tdata1-type} enumerated in {csr-tdata1}. Bit N
corresponds to type N. If the bit is set, then that type is
supported by the currently selected trigger.#

[#norm:Sdtrig_tinfo_no_trigger]#If the currently selected trigger doesn't exist, this field
contains 1.#
a|*R*
a|Preset
|===

[[csr-tcontrol]]
==== Trigger Control (((tcontrol)), at 0x7a5)

[#norm:Sdtrig_trigger_modes_1]#This optional register is only accessible in M-mode and Debug Mode and
provides various control bits related to triggers.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "" "" "" "8" "" "7" "" "6" "" "" "" "4" "3" "2" "" "" "" "0" "" "" ""]})
(draw-box (text "0" {:font-size 20}) {:span 7})
(draw-box (text "mpte" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "mte" {:font-size 20}) {:span 1})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box "" {:span 3 :borders {}})
(draw-box "XLEN - 8" {:span 7 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[tcontrol-mpte]] `((mpte))`
a|M-mode previous trigger enable field.

{tcontrol-mpte} and {tcontrol-mte} provide one solution to a problem
regarding triggers with action=0 firing in M-mode trap handlers. See
xref:nativetrigger[] for more details.

[#norm:Sdtrig_tcontrol_mpte]#When any trap into M-mode is taken, {tcontrol-mpte} is set to the value of
{tcontrol-mte}.#
a|*WARL*
a|0
|[[tcontrol-mte]] `((mte))`
a|M-mode trigger enable field.

0 (disabled): [#norm:Sdtrig_tcontrol_mte_disabled]#Triggers with action=0 do not match/fire while the hart is in M-mode.#


1 (enabled): [#norm:Sdtrig_tcontrol_mte_enabled]#Triggers do match/fire while the hart is in M-mode.#

[#norm:Sdtrig_tcontrol_mte]#When any trap into M-mode is taken, {tcontrol-mte} is set to 0.# [#norm:Sdtrig_tcontrol_mte_mret]#When `mret` is executed, {tcontrol-mte} is set to the value of {tcontrol-mpte}.#
a|*WARL*
a|0
|===

[[csr-hcontext]]
==== Hypervisor Context (((hcontext)), at 0x6a8)

[#norm:Sdtrig_hcontext_implemented]#This optional register may be implemented only if the H extension is
implemented. If it is implemented, {csr-mcontext} must also be implemented.#

[#norm:Sdtrig_hcontext_access]#This register is only accessible in HS-Mode, M-mode and Debug Mode.# [#norm:Sdtrig_hcontext_smstateen]#If
Smstateen is implemented, then accessibility of in HS-Mode is
controlled by `mstateenzero[57]`.#

[#norm:Sdtrig_hcontext]#This register is an alias of the {csr-mcontext} register, providing
access to the {mcontext-hcontext} field from HS-Mode.#


[[csr-scontext]]
==== Supervisor Context (((scontext)), at 0x5a8)

[#norm:Sdtrig_scontext_access]#This optional register is only accessible in S/HS-mode, VS-mode,
M-mode and Debug Mode.#

[#norm:Sdtrig_scontext_accessibility]#Accessibility of this CSR is controlled by `mstateenzero[57]` and
`hstateenzero[57]` in the Smstateen extension.#  Enabling {csr-scontext}
can be a security risk in a virtualized system with a hypervisor that
does not swap {csr-scontext}.

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "32" "31" "" "" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "0" {:font-size 20}) {:span 3})
(draw-box (text "data" {:font-size 20}) {:span 9})
(draw-box "" {:span 12 :borders {}})
(draw-box "XLEN - 32" {:span 3 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "" {:span 12 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[scontext-data]] `((data))`
a|[#norm:Sdtrig_scontext_data]#Supervisor mode software can write a context number to this
register, which can be used to set triggers that only fire in that
specific context.#

An implementation may tie any number of high bits in this field to
0. It's recommended to implement 16 bits on RV32 and 32 bits on
RV64.
a|*WARL*
a|0
|===

[[csr-mcontext]]
==== Machine Context (((mcontext)), at 0x7a8)

[#norm:Sdtrig_mcontext_implementation]#This register must be implemented if {csr-hcontext} is implemented, and
is optional otherwise.#  [#norm:Sdtrig_mcontext_access]#It is only accessible in M-mode and Debug mode.#

[NOTE]
====
{mcontext-hcontext} is primarily useful to set triggers on
hypervisor systems that only fire when a given VM is executing. It
is also useful in systems where M-Mode implements something like a
hypervisor directly.
====

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "" "" "" "14" "13" "" "" "" "" "" "0" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "0" {:font-size 20}) {:span 7})
(draw-box (text "hcontext" {:font-size 20}) {:span 7})
(draw-box "" {:span 10 :borders {}})
(draw-box "XLEN - 14" {:span 7 :borders {}})
(draw-box "14" {:span 7 :borders {}})
(draw-box "" {:span 10 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[mcontext-hcontext]] `((hcontext))`
a|[#norm:Sdtrig_mcontext_hcontext_data]#M-Mode or HS-Mode (using {csr-hcontext}) software can write a context
number to this register, which can be used to set triggers that only
fire in that specific context.#

An implementation may tie any number of upper bits in this field to
0. If the H extension is not implemented, it's recommended to implement
6 bits on RV32 and 13 bits on RV64 (as visible through the
{csr-mcontext} register).  If the H extension is implemented,
it's recommended to implement 7 bits on RV32
and 14 bits on RV64.
a|*WARL*
a|0
|===

[[csr-mscontext]]
==== Machine Supervisor Context (((mscontext)), at 0x7aa)

[#norm:Sdtrig_mscontext]#This optional register is an alias for {csr-scontext}.#  [#norm:Sdtrig_mscontext_access]#It is only
accessible in S/HS-mode, M-mode and Debug Mode.#  It is included
for backward compatibility with version 0.13.

[NOTE]
====
The encoding of this CSR does not conform to the CSR Address Mapping
Convention in the Privileged Spec.  It is expected that new
implementations will not support this encoding and that new
debuggers will not use this CSR if {csr-scontext} is available.
====


[[csr-mcontrol]]
==== Match Control (((mcontrol)), at 0x7a1)

[#norm:Sdtrig_mcontrol]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_mcontrol_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_mcontrol_access]#This register is accessible as {csr-tdata1} when {tdata1-type} is 2.#
This trigger type is deprecated.  It is included for backward compatibility
with version 0.13.

[NOTE]
====
This trigger type only supports a subset of features of the newer
{csr-mcontrol6}.  It is expected that new implementations will not
support this trigger type and that new debuggers will not use it if
{csr-mcontrol6} is available.
====

Address and data trigger implementation are heavily dependent on how
the processor core is implemented. To accommodate various
implementations, execute, load, and store address/data triggers may fire at
whatever point in time is most convenient for the implementation.
The debugger may request specific timings as described in {mcontrol-timing}.
<<tab:hwbp_timing>> suggests timings for the best user experience.

A chain of triggers that don't all have the same {mcontrol-timing}
value will never fire. That means to implement the suggestions in
<<tab:hwbp_timing>>, both timings should be supported on load
address triggers that can be chained with a load data trigger.

The Privileged Spec says that breakpoint exceptions that occur on
instruction fetches, loads, or stores update the `tval` CSR
with either zero or the faulting virtual address.  The faulting
virtual address for an mcontrol trigger with {mcontrol-action}=0 is the
address being accessed and which caused that trigger to fire.
If multiple mcontrol triggers are chained then the faulting
virtual address is the address which caused any of the chained
triggers to fire.

If {csr-textra32} or {csr-textra64} are implemented for this
trigger, it only matches when the conditions set there are satisfied.

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 28)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "XLEN-4" "" "" "XLEN-5" "" "" "XLEN-6" "" "XLEN-11" "" "" "XLEN-12" "" "" "23" "22" "" "21" "20" "" "19" "" "" "18" ""]})
(draw-box (text "type" {:font-size 20}) {:span 5})
(draw-box (text "dmode" {:font-size 20}) {:span 3})
(draw-box (text "maskmax" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "sizehi" {:font-size 20}) {:span 3})
(draw-box (text "hit" {:font-size 20}) {:span 1})
(draw-box (text "select" {:font-size 20}) {:span 3})
(draw-box (text "timing" {:font-size 20}) {:span 3})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "6" {:span 5 :borders {}})
(draw-box "XLEN - 34" {:span 5 :borders {}})
(draw-box "2" {:span 3 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
----
[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 29)
(draw-column-headers {:font-size 15 :height 17 :labels ["17" "" "16" "15" "" "" "" "12" "" "11" "" "10" "" "" "" "7" "6" "5" "4" "3" "" "2" "" "" "1" "" "" "0" ""]})
(draw-box (text "sizelo" {:font-size 20}) {:span 3})
(draw-box (text "action" {:font-size 20}) {:span 5})
(draw-box (text "chain" {:font-size 20}) {:span 3})
(draw-box (text "match" {:font-size 20}) {:span 5})
(draw-box (text "m" {:font-size 20}) {:span 1})
(draw-box (text "0" {:font-size 20}) {:span 1})
(draw-box (text "s" {:font-size 20}) {:span 1})
(draw-box (text "u" {:font-size 20}) {:span 1})
(draw-box (text "execute" {:font-size 20}) {:span 3})
(draw-box (text "store" {:font-size 20}) {:span 3})
(draw-box (text "load" {:font-size 20}) {:span 3})
(draw-box "2" {:span 3 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[mcontrol-maskmax]] `((maskmax))`
a|[#norm:Sdtrig_mcontrol_maskmax]#Specifies the largest naturally aligned powers-of-two (NAPOT) range
supported by the hardware when {mcontrol-match} is 1. The value is the
logarithm base 2 of the number of bytes in that range.
A value of 0 indicates {mcontrol-match} 1 is not supported.
A value of 63 corresponds to the maximum NAPOT range, which is
2^63^ bytes in size.#
a|*R*
a|Preset
|[[mcontrol-sizehi]] `((sizehi))`
a|[#norm:Sdtrig_mcontrol_sizehi]#This field only exists when XLEN is at least 64.
It contains the 2 high bits of the access size. The low bits
come from {mcontrol-sizelo}.# See {mcontrol-sizelo} for how this
is used.
a|*WARL*
a|0
|[[mcontrol-hit]] `((hit))`
a|[#norm:Sdtrig_mcontrol_hit]#If this bit is implemented then it must become set when this
trigger fires and may become set when this trigger matches.
The trigger's user can set or clear it at any
time. It is used to determine which
trigger(s) matched.  If the bit is not implemented, it is always 0
and writing it has no effect.#
a|*WARL*
a|0
|[[mcontrol-select]] `((select))`
a|This bit determines the contents of the XLEN-bit compare values.

0 (address): [#norm:Sdtrig_mcontrol_select_address]#There is at least one compare value and it contains the lowest
virtual address of the access.#
It is recommended that there are additional compare values for
the other accessed virtual addresses.
(E.g. on a 32-bit read from 0x4000, the lowest address is 0x4000
and the other addresses are 0x4001, 0x4002, and 0x4003.)


1 (data): [#norm:Sdtrig_mcontrol_select_data]#There is exactly one compare value and it contains the data
value loaded or stored, or the instruction executed.
Any bits beyond the size of the data access will contain 0.#
a|*WARL*
a|0
|[[mcontrol-timing]] `((timing))`
a|

0 (before): [#norm:Sdtrig_mcontrol_timing_before]#The action for this trigger will be taken just before the
instruction that triggered it is retired, but after all preceding
instructions are retired. `xepc` or {csr-dpc} (depending
on {mcontrol-action}) must be set to the virtual address of the
instruction that matched.#

If this is combined with {mcontrol-load} and
{mcontrol-select}=1 then a memory access will be
performed (including any side effects of performing such an access) even
though the load will not update its destination register. Debuggers
should consider this when setting such breakpoints on, for example,
memory-mapped I/O addresses.

[#norm:Sdtrig_mcontrol_timing_multi]#If an instruction matches this trigger and the instruction performs
multiple memory accesses, it is UNSPECIFIED which memory accesses
have completed before the trigger fires.#


1 (after): [#norm:Sdtrig_mcontrol_timing_after]#The action for this trigger will be taken after the instruction
that triggered it is retired. It should be taken before the next
instruction is retired, but it is better to implement triggers imprecisely
than to not implement them at all.  `xepc` or
{csr-dpc} (depending on {mcontrol-action}) must be set to
the virtual address of the next instruction that must be executed to
preserve the program flow.#

Most hardware will only implement one timing or the other, possibly
dependent on {mcontrol-select}, {mcontrol-execute},
{mcontrol-load}, and {mcontrol-store}. This bit
primarily exists for the hardware to communicate to the debugger
what will happen. Hardware may implement the bit fully writable, in
which case the debugger has a little more control.

Data load triggers with {mcontrol-timing} of 0 will result in the same load
happening again when the debugger lets the hart run. For data load
triggers, debuggers must first attempt to set the breakpoint with
{mcontrol-timing} of 1.

[#norm:Sdtrig_mcontrol_timing_overlap]#If a trigger with {mcontrol-timing} of 0 matches, it is
implementation-dependent whether that prevents a trigger with
{mcontrol-timing} of 1 matching as well.#
a|*WARL*
a|0
|[[mcontrol-sizelo]] `((sizelo))`
a|This field contains the 2 low bits of the access size. The high bits come
from {mcontrol-sizehi}. The combined value is interpreted as follows:

0 (any): [#norm:Sdtrig_mcontrol_size_any]#The trigger will attempt to match against an access of any size.
The behavior is only well-defined if {mcontrol-select}=0, or if the access
size is XLEN.#


1 (8bit): [#norm:Sdtrig_mcontrol_size_8bit]#The trigger will only match against 8-bit memory accesses.#


2 (16bit): [#norm:Sdtrig_mcontrol_size_16bit]#The trigger will only match against 16-bit memory accesses or
execution of 16-bit instructions.#


3 (32bit): [#norm:Sdtrig_mcontrol_size_32bit]#The trigger will only match against 32-bit memory accesses or
execution of 32-bit instructions.#


4 (48bit): [#norm:Sdtrig_mcontrol_size_48bit]#The trigger will only match against execution of 48-bit instructions.#


5 (64bit): [#norm:Sdtrig_mcontrol_size_64bit]#The trigger will only match against 64-bit memory accesses or
execution of 64-bit instructions.#


6 (80bit): [#norm:Sdtrig_mcontrol_size_80bit]#The trigger will only match against execution of 80-bit instructions.#


7 (96bit): [#norm:Sdtrig_mcontrol_size_96bit]#The trigger will only match against execution of 96-bit instructions.#


8 (112bit): [#norm:Sdtrig_mcontrol_size_112bit]#The trigger will only match against execution of 112-bit instructions.#


9 (128bit): [#norm:Sdtrig_mcontrol_size_128bit]#The trigger will only match against 128-bit memory accesses or
execution of 128-bit instructions.#

[#norm:Sdtrig_mcontrol_size_support]#An implementation must support the value of 0, but all other values
are optional.# When an implementation supports address triggers
({mcontrol-select}=0), it is recommended that those triggers
support every access size that the hart supports, as well as for
every instruction size that the hart supports.

Implementations such as RV32D or RV64V are able to perform loads
and stores that are wider than XLEN. Custom extensions may also
support instructions that are wider than XLEN. Because
{csr-tdata2} is of size XLEN, there is a known limitation that
data value triggers ({mcontrol-select}=1) can only be supported
for access sizes up to XLEN bits.  When an implementation supports
data value triggers ({mcontrol-select}=1), it is recommended
that those triggers support every access size up to XLEN that the
hart supports, as well as for every instruction length up to XLEN
that the hart supports.
a|*WARL*
a|0
|[[mcontrol-action]] `((action))`
a|The action to take when the trigger fires. The values are explained
in xref:tab:action[].
a|*WARL*
a|0
|[[mcontrol-chain]] `((chain))`
a|

0 (disabled): [#norm:Sdtrig_mcontrol_chain_disabled]#When this trigger matches, the configured action is taken.#


1 (enabled): [#norm:Sdtrig_mcontrol_chain_enabled]#While this trigger does not match, it prevents the trigger with
the next index from matching.#

[#norm:Sdtrig_mcontrol_chain_start]#A trigger chain starts on the first trigger with `chain`=1 after
a trigger with `chain`=0, or simply on the first trigger if that
has `chain`=1. It ends on the first trigger after that which has
`chain`=0. This final trigger is part of the chain. The action
on all but the final trigger is ignored.  The action on that final
trigger will be taken if and only if all the triggers in the chain
match at the same time.#

Debuggers should not terminate a chain with a trigger with a
different type. It is undefined when exactly such a chain fires.

[#norm:Sdtrig_mcontrol_chain_next]#Because {mcontrol-chain} affects the next trigger, hardware must zero it in
writes to {csr-mcontrol} that set {tdata1-dmode} to 0 if the next trigger has
{tdata1-dmode} of 1.#
[#norm:Sdtrig_mcontrol_chain_ignore]#In addition hardware should ignore writes to {csr-mcontrol} that set
{tdata1-dmode} to 1 if the previous trigger has both {tdata1-dmode} of 0 and
{mcontrol-chain} of 1.# Debuggers must avoid the latter case by checking
{mcontrol-chain} on the previous trigger if they're writing {csr-mcontrol}.

Implementations that wish to limit the maximum length of a trigger
chain (eg. to meet timing requirements) may do so by zeroing
{mcontrol-chain} in writes to {csr-mcontrol} that would make the chain too long.
a|*WARL*
a|0
|[[mcontrol-match]] `((match))`
a|

0 (equal): [#norm:Sdtrig_mcontrol_match_equal]#Matches when any compare value equals {csr-tdata2}.#


1 (napot): [#norm:Sdtrig_mcontrol_match_napot]#Matches when the top `M` bits of any compare value match the top
`M` bits of {csr-tdata2}.
`M` is `XLEN-1` minus the index of the least-significant
bit containing 0 in {csr-tdata2}.# Debuggers should only write values
to {csr-tdata2} such that `M` + {mcontrol-maskmax} ≥ `XLEN`
and `M` > 0, otherwise it's undefined on what conditions the
trigger will match.


2 (ge): [#norm:Sdtrig_mcontrol_match_ge]#Matches when any compare value is greater than (unsigned) or
equal to {csr-tdata2}.#


3 (lt): [#norm:Sdtrig_mcontrol_match_lt]#Matches when any compare value is less than (unsigned)
{csr-tdata2}.#


4 (mask low): [#norm:Sdtrig_mcontrol_match_mask_low]#Matches when latexmath:[$\frac{XLEN}{2}-{1:0}] of any compare value
equals latexmath:[$\frac{XLEN}{2}-{1:0}] of {csr-tdata2} after
latexmath:[$\frac{XLEN}{2}-{1:0}] of the compare value is ANDed with
`XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of {csr-tdata2}.#


5 (mask high): [#norm:Sdtrig_mcontrol_match_mask_high]#Matches when `XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of any compare
value equals latexmath:[$\frac{XLEN}{2}-{1:0}] of {csr-tdata2} after
`XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of the compare value is ANDed with
`XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of {csr-tdata2}.#


8 (not equal): [#norm:Sdtrig_mcontrol_match_not_equal]#Matches when {mcontrol-match}=0 would not match.#


9 (not napot): [#norm:Sdtrig_mcontrol_match_not_napot]#Matches when {mcontrol-match}=1 would not match.#


12 (not mask low): [#norm:Sdtrig_mcontrol_match_not_mask_low]#Matches when {mcontrol-match}=4 would not match.#


13 (not mask high): [#norm:Sdtrig_mcontrol_match_not_mask_high]#Matches when {mcontrol-match}=5 would not match.#

[#norm:Sdtrig_mcontrol_match_rsv]#Other values are reserved for future use.#

[#norm:Sdtrig_mcontrol_comparisons]#All comparisons only look at the lower XLEN (in the current mode)
bits of the compare values and of {csr-tdata2}.
When {mcontrol-select}=1 and access size is N, this is further
reduced, and comparisons only look at the lower N bits of the
compare values and of {csr-tdata2}.#
a|*WARL*
a|0
|[[mcontrol-m]] `((m))`
a|[#norm:Sdtrig_mcontrol_m]#When set, enable this trigger in M-mode.#
a|*WARL*
a|0
|[[mcontrol-s]] `((s))`
a|[#norm:Sdtrig_mcontrol_s]#When set, enable this trigger in S/HS-mode.
This bit is hard-wired to 0 if the hart does not support
S-mode.#
a|*WARL*
a|0
|[[mcontrol-u]] `((u))`
a|[#norm:Sdtrig_mcontrol_u]#When set, enable this trigger in U-mode.
This bit is hard-wired to 0 if the hart does not support
U-mode.#
a|*WARL*
a|0
|[[mcontrol-execute]] `((execute))`
a|[#norm:Sdtrig_mcontrol_execute]#When set, the trigger fires on the virtual address or opcode of an
instruction that is executed.#
a|*WARL*
a|0
|[[mcontrol-store]] `((store))`
a|[#norm:Sdtrig_mcontrol_store]#When set, the trigger fires on the virtual address or data of any
store.#
a|*WARL*
a|0
|[[mcontrol-load]] `((load))`
a|[#norm:Sdtrig_mcontrol_load]#When set, the trigger fires on the virtual address or data of any
load.#
a|*WARL*
a|0
|===

[[csr-mcontrol6]]
==== Match Control Type 6 (((mcontrol6)), at 0x7a1)

[#norm:Sdtrig_mcontrol6]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_mcontrol6_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_mcontrol6_access]#This register is accessible as {csr-tdata1} when {tdata1-type} is 6.#

[#norm:Sdtrig_mcontrol6_dependence]#Implementing this trigger as described here requires that
{tinfo-version} is 1 or higher, which in turn means {csr-tinfo} must
be implemented.#

This replaces mcontrol in newer implementations and serves to provide additional
functionality.

Address and data trigger implementation are heavily dependent on how
the processor core is implemented. To accommodate various
implementations, execute, load, and store address/data triggers may fire at
whatever point in time is most convenient for the implementation.

<<tab:hwbp_timing>> suggests timings for the best user experience.
The underlying principle is that firing just before the instruction
gives a user more insight, so is preferable. However, depending on the
instruction and conditions, it might not be possible to evaluate the
trigger until the instruction has partially executed. In that case it is
better to let the instruction retire before the trigger fires, to avoid
extra memory accesses which might affect the state of the system.

[[tab:hwbp_timing]]
.Suggested Trigger Timings
[%autowidth,align="center",float="center",cols=">,<",options="header"]
|===
| Match Type | Suggested Trigger Timing
| Execute Address             | Before
| Execute Instruction         | Before
| Execute Address+Instruction | Before
| Load Address                | Before
| Load Data                   | After
| Load Address+Data           | After
| Store Address               | Before
| Store Data                  | Before
| Store Address+Data          | Before
|===

[#norm:Sdtrig_mcontrol6_chain]#A chain of triggers must only fire if every trigger in the chain was
matched by the same instruction.#

[#norm:Sdtrig_mcontrol6_breakpoint]#The Privileged Spec says that breakpoint exceptions that occur on
instruction fetches, loads, or stores update the `tval` CSR
with either zero or the faulting virtual address.#  [#norm:Sdtrig_mcontrol6_faulting_address]#The faulting
virtual address for an mcontrol6 trigger with {mcontrol6-action}=0 is the
address being accessed and which caused that trigger to fire.#
[#norm:Sdtrig_mcontrol6_chained_faulting]#If multiple mcontrol6 triggers are chained then the faulting
virtual address is the address which caused any of the chained
triggers to fire.#

In implementations that support {mcontrol6-match} mode 1 (NAPOT), not all
NAPOT ranges may be supported.  [#norm:Sdtrig_mcontrol6_napot_range]#All NAPOT ranges between stem:[2^1] and stem:[2^{maskmax6}]
are supported where stem:[{maskmax6} ≥ 1].#  The value of maskmax6 can be determined
by the debugger via the following sequence:

. Write {csr-tdata1}=0, in case the current {csr-tdata2} value is not supported with mcontrol6 triggers.
. Write {csr-tdata2}=0, which is always supported with mcontrol6 triggers.
. Write {csr-tdata1} with {tdata1-type}=mcontrol6 and {mcontrol6-match}=1.
. Read {mcontrol6-match}. If it is not 1 then NAPOT matching is not supported.
. Write all ones to {csr-tdata2}.
. Read {csr-tdata2}. The value of maskmax6 is the index of the most significant 0 bit plus 1.

[#norm:Sdtrig_mcontrol6_textra]#If {csr-textra32} or {csr-textra64} are implemented for this
trigger, it only matches when the conditions set there are satisfied.#

[NOTE]
====
{mcontrol6-uncertain} and {mcontrol6-uncertainen} exist to
accommodate systems where not every memory access is fully observed by
the Trigger Module. Possible examples include data values in far AMOs,
and the address/data/size of accesses by instructions that perform
multiple memory accesses, such as vector, push, and pop instructions.

While the uncertain mechanism exists to deal with these situations, it
can lead to an unusable number of false positives. Users will get a much
better debug experience if the TM does have perfect visibility into the
details of every memory access.
====

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 33)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "XLEN-4" "" "" "XLEN-5" "" "" "XLEN-6" "27" "" "26" "" "" "25" "" "24" "23" "" "22" "" "" "21" "" "20" "" "19" "18" "" "" "" "16"]})
(draw-box (text "type" {:font-size 20}) {:span 5})
(draw-box (text "dmode" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 3})
(draw-box (text "uncertain" {:font-size 20}) {:span 3})
(draw-box (text "hit1" {:font-size 20}) {:span 3})
(draw-box (text "vs" {:font-size 20}) {:span 1})
(draw-box (text "vu" {:font-size 20}) {:span 1})
(draw-box (text "hit0" {:font-size 20}) {:span 3})
(draw-box (text "select" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 3})
(draw-box (text "size" {:font-size 20}) {:span 5})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "XLEN - 32" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "2" {:span 3 :borders {}})
(draw-box "3" {:span 5 :borders {}})
----
[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 30)
(draw-column-headers {:font-size 15 :height 17 :labels ["15" "" "" "" "12" "" "11" "" "10" "" "" "" "7" "6" "" "" "5" "" "" "4" "3" "" "2" "" "" "1" "" "" "0" ""]})
(draw-box (text "action" {:font-size 20}) {:span 5})
(draw-box (text "chain" {:font-size 20}) {:span 3})
(draw-box (text "match" {:font-size 20}) {:span 5})
(draw-box (text "m" {:font-size 20}) {:span 1})
(draw-box (text "uncertainen" {:font-size 20}) {:span 5})
(draw-box (text "s" {:font-size 20}) {:span 1})
(draw-box (text "u" {:font-size 20}) {:span 1})
(draw-box (text "execute" {:font-size 20}) {:span 3})
(draw-box (text "store" {:font-size 20}) {:span 3})
(draw-box (text "load" {:font-size 20}) {:span 3})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 5 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[mcontrol6-uncertain]] `((uncertain))`
a|[#norm:Sdtrig_mcontrol6_uncertain]#If implemented, the TM updates this field every time the trigger
fires.#

0 (certain): [#norm:Sdtrig_mcontrol6_uncertain_0]#The trigger that fired satisfied the configured conditions, or
this bit is not implemented.#


1 (uncertain): [#norm:Sdtrig_mcontrol6_uncertain_1]#The trigger that fired might not have perfectly satisfied the
configured conditions.# Due to the implementation the hardware
cannot be certain.
a|*WARL*
a|0
|[[mcontrol6-vs]] `((vs))`
a|[#norm:Sdtrig_mcontrol6_vs]#When set, enable this trigger in VS-mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[mcontrol6-vu]] `((vu))`
a|[#norm:Sdtrig_mcontrol6_vu]#When set, enable this trigger in VU-mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[mcontrol6-hit0]] `((hit0))`
a|[#norm:Sdtrig_mcontrol6_hit0]#If they are implemented, {mcontrol6-hit1} (MSB) and
{mcontrol6-hit0} (LSB) combine into a single 2-bit field.
The TM updates this field when the trigger fires.# After the debugger
has seen the update, it will normally write 0 to this field to so it
can see future changes.

[#norm:Sdtrig_mcontrol6_hit0_unimplemented]#If either of the bits is not implemented, the unimplemented bits
will be read-only 0.#

0 (false): The trigger did not fire.


1 (before): The trigger fired before the instruction that matched it was
retired, but after all preceding instructions are retired. This
explicitly allows for instructions to be partially executed, as
described in xref:multistate[].

[#norm:Sdtrig_mcontrol6_hit0_1]#`xepc` or {csr-dpc} (depending on {mcontrol6-action}) must be set
to the virtual address of the instruction that matched.#


2 (after): The trigger fired after the instruction that triggered and at least
one additional instruction were retired.
[#norm:Sdtrig_mcontrol6_hit0_2]#`xepc` or {csr-dpc} (depending on {mcontrol6-action}) must be set
to the virtual address of the next instruction that must be executed
to preserve the program flow.#


3 (immediately after): The trigger fired just after the instruction that triggered it was
retired, but before any subsequent instructions were executed.
[#norm:Sdtrig_mcontrol6_hit0_3]#`xepc` or {csr-dpc} (depending on {mcontrol6-action}) must be set
to the virtual address of the next instruction that must be executed
to preserve the program flow.#

[#norm:Sdtrig_mcontrol6_hit0_multiple_accesses]#If the instruction performed multiple memory accesses, all of them
have been completed.#
a|*WARL*
a|0
|[[mcontrol6-select]] `((select))`
a|This bit determines the contents of the XLEN-bit compare values.

0 (address): [#norm:Sdtrig_mcontrol6_select_address]#There is at least one compare value and it contains the lowest
virtual address of the access.#
In addition, it is recommended that there are additional compare
values for the other accessed virtual addresses match.
(E.g. on a 32-bit read from 0x4000, the lowest address is 0x4000
and the other addresses are 0x4001, 0x4002, and 0x4003.)


1 (data): [#norm:Sdtrig_mcontrol6_select_data]#There is exactly one compare value and it contains the data
value loaded or stored, or the instruction executed.
Any bits beyond the size of the data access will contain 0.#
a|*WARL*
a|0
|[[mcontrol6-size]] `((size))`
a|

0 (any): [#norm:Sdtrig_mcontrol6_size_any]#The trigger will attempt to match against an access of any size.
The behavior is only well-defined if {mcontrol6-select}=0, or if the
access size is XLEN.#


1 (8bit): [#norm:Sdtrig_mcontrol6_size_8bit]#The trigger will only match against 8-bit memory accesses.#


2 (16bit): [#norm:Sdtrig_mcontrol6_size_16bit]#The trigger will only match against 16-bit memory accesses or
execution of 16-bit instructions.#


3 (32bit): [#norm:Sdtrig_mcontrol6_size_32bit]#The trigger will only match against 32-bit memory accesses or
execution of 32-bit instructions.#


4 (48bit): [#norm:Sdtrig_mcontrol6_size_48bit]#The trigger will only match against execution of 48-bit instructions.#


5 (64bit): [#norm:Sdtrig_mcontrol6_size_64bit]#The trigger will only match against 64-bit memory accesses or
execution of 64-bit instructions.#


6 (128bit): [#norm:Sdtrig_mcontrol6_size_128bit]#The trigger will only match against 128-bit memory accesses or
execution of 128-bit instructions.#

[#norm:Sdtrig_mcontrol6_size_support]#An implementation must support the value of 0, but all other values
are optional.# When an implementation supports address triggers
({mcontrol6-select}=0), it is recommended that those triggers
support every access size that the hart supports, as well as for
every instruction size that the hart supports.

Implementations such as RV32D or RV64V are able to perform loads
and stores that are wider than XLEN. Custom extensions may also
support instructions that are wider than XLEN. Because
{csr-tdata2} is of size XLEN, there is a known limitation that
data value triggers ({mcontrol6-select}=1) can only be supported
for access sizes up to XLEN bits.  When an implementation supports
data value triggers ({mcontrol6-select}=1), it is recommended
that those triggers support every access size up to XLEN that the
hart supports, as well as for every instruction length up to XLEN
that the hart supports.
a|*WARL*
a|0
|[[mcontrol6-action]] `((action))`
a|The action to take when the trigger fires. The values are explained
in xref:tab:action[].
a|*WARL*
a|0
|[[mcontrol6-chain]] `((chain))`
a|

0 (disabled): [#norm:Sdtrig_mcontrol6_chain_disabled]#When this trigger matches, the configured action is taken.#


1 (enabled): [#norm:Sdtrig_mcontrol6_chain_enabled]#While this trigger does not match, it prevents the trigger with
the next index from matching.#

[#norm:Sdtrig_mcontrol6_chain_start]#A trigger chain starts on the first trigger with `chain`=1 after
a trigger with `chain`=0, or simply on the first trigger if that
has `chain`=1. It ends on the first trigger after that which has
`chain`=0. This final trigger is part of the chain. The action
on all but the final trigger is ignored.  The action on that final
trigger will be taken if and only if all the triggers in the chain
match at the same time.#

Debuggers should not terminate a chain with a trigger with a
different type. It is undefined when exactly such a chain fires.

[#norm:Sdtrig_mcontrol6_chain_next]#Because {mcontrol6-chain} affects the next trigger, hardware must zero it in
writes to {csr-mcontrol6} that set {tdata1-dmode} to 0 if the next trigger has
{tdata1-dmode} of 1.#
[#norm:Sdtrig_mcontrol6_chain_ignore]#In addition hardware should ignore writes to {csr-mcontrol6} that set
{tdata1-dmode} to 1 if the previous trigger has both {tdata1-dmode} of 0 and
{mcontrol6-chain} of 1.# Debuggers must avoid the latter case by checking
{mcontrol6-chain} on the previous trigger if they're writing {csr-mcontrol6}.

Implementations that wish to limit the maximum length of a trigger
chain (eg. to meet timing requirements) may do so by zeroing
{mcontrol6-chain} in writes to {csr-mcontrol6} that would make the chain too long.
a|*WARL*
a|0
|[[mcontrol6-match]] `((match))`
a|

0 (equal): [#norm:Sdtrig_mcontrol6_match_equal]#Matches when any compare value equals {csr-tdata2}.#


1 (napot): [#norm:Sdtrig_mcontrol6_match_napot]#Matches when the top `M` bits of any compare value match the top
`M` bits of {csr-tdata2}.
`M` is `XLEN-1` minus the index of the least-significant bit
containing 0 in {csr-tdata2}.#
{csr-tdata2} is *WARL* and [#norm:Sdtrig_mcontrol6_match_napot_mask]#if bits `maskmax6-1:0` are written with all
ones then bit `maskmax6-1` will be set to 0 while the values of bits `maskmax6-2:0`
are UNSPECIFIED.#
[#norm:Sdtrig_mcontrol6_match_napot_legal]#Legal values for {csr-tdata2} require M + `maskmax6` ≥ `XLEN` and `M` > 0.
See above for how to determine maskmax6.#


2 (ge): [#norm:Sdtrig_mcontrol6_match_ge]#Matches when any compare value is greater than (unsigned) or
equal to {csr-tdata2}.#


3 (lt): [#norm:Sdtrig_mcontrol6_match_lt]#Matches when any compare value is less than (unsigned)
{csr-tdata2}.#


4 (mask low): [#norm:Sdtrig_mcontrol6_match_mask_low]#Matches when latexmath:[$\frac{XLEN}{2}-{1:0}] of any compare value
equals latexmath:[$\frac{XLEN}{2}-{1:0}] of {csr-tdata2} after
latexmath:[$\frac{XLEN}{2}-{1:0}] of the compare value is ANDed with
`XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of {csr-tdata2}.#


5 (mask high): [#norm:Sdtrig_mcontrol6_match_mask_high]#Matches when `XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of any compare
value equals latexmath:[$\frac{XLEN}{2}-{1:0}] of {csr-tdata2} after
`XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of the compare value is ANDed with
`XLEN-1`:latexmath:[$\frac{XLEN}{2}$] of {csr-tdata2}.#


8 (not equal): [#norm:Sdtrig_mcontrol6_match_not_equal]#Matches when {mcontrol6-match} `=0` would not match.#


9 (not napot): [#norm:Sdtrig_mcontrol6_match_not_napot]#Matches when {mcontrol6-match} `=1` would not match.#


12 (not mask low): [#norm:Sdtrig_mcontrol6_match_not_mask_low]#Matches when {mcontrol6-match} `=4` would not match.#


13 (not mask high): [#norm:Sdtrig_mcontrol6_match_not_mask_high]#Matches when {mcontrol6-match} `=5` would not match.#

[#norm:Sdtrig_mcontrol6_match_rsv]#Other values are reserved for future use.#

[#norm:Sdtrig_mcontrol6_comparisons]#All comparisons only look at the lower XLEN (in the current mode)
bits of the compare values and of {csr-tdata2}.
When {mcontrol-select}=1 and access size is N, this is further
reduced, and comparisons only look at the lower N bits of the
compare values and of {csr-tdata2}.#
a|*WARL*
a|0
|[[mcontrol6-m]] `((m))`
a|[#norm:Sdtrig_mcontrol6_m]#When set, enable this trigger in M-mode.#
a|*WARL*
a|0
|[[mcontrol6-uncertainen]] `((uncertainen))`
a|

0 (disabled): [#norm:Sdtrig_mcontrol6_uncertainen_disabled]#This trigger will only match if the hardware can perfectly
evaluate it.#


1 (enabled): [#norm:Sdtrig_mcontrol6_uncertainen_enabled]#This trigger will match if it's possible that it would match if
the Trigger Module had perfect information about the operations
being performed.#
a|*WARL*
a|0
|[[mcontrol6-s]] `((s))`
a|[#norm:Sdtrig_mcontrol6_s]#When set, enable this trigger in S/HS-mode.
This bit is hard-wired to 0 if the hart does not support
S-mode.#
a|*WARL*
a|0
|[[mcontrol6-u]] `((u))`
a|[#norm:Sdtrig_mcontrol6_u]#When set, enable this trigger in U-mode.
This bit is hard-wired to 0 if the hart does not support
U-mode.#
a|*WARL*
a|0
|[[mcontrol6-execute]] `((execute))`
a|[#norm:Sdtrig_mcontrol6_execute]#When set, the trigger fires on the virtual address or opcode of an
instruction that is executed.#
a|*WARL*
a|0
|[[mcontrol6-store]] `((store))`
a|[#norm:Sdtrig_mcontrol6_store]#When set, the trigger fires on the virtual address or data of any
store.#
a|*WARL*
a|0
|[[mcontrol6-load]] `((load))`
a|[#norm:Sdtrig_mcontrol6_load]#When set, the trigger fires on the virtual address or data of any
load.#
a|*WARL*
a|0
|===

[[csr-icount]]
==== Instruction Count (((icount)), at 0x7a1)

[#norm:Sdtrig_icount]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_icount_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_icount_access]#This register is accessible as {csr-tdata1} when {tdata1-type} is 3.#

This trigger matches when:

.  [#norm:Sdtrig_icount_match1]#An instruction retires after having been fetched in a privilege
mode where the trigger is enabled.
This explicitly includes all RET instructions from various modes.#
. [#norm:Sdtrig_icount_match2]#A trap is taken from a privilege mode where the trigger is enabled.
This explicitly includes traps taken due to interrupts.#

[#norm:Sdtrig_icount_multiple_match]#If more than one of the above events occur during a single instruction
execution, the trigger still only matches once for that instruction.#

[NOTE]
====
[#norm:Sdtrig_icount_match_non_reexecuted]#For use in single step, icount must match for traps where the
instruction will not be reexecuted after the handler, such as
illegal instructions that are emulated by privileged software and
the instruction being emulated never retires.# Ideally, icount would
not match for traps where the instruction will later be retried by
the handler, such as page faults where privileged software modifies
the page tables and returns to the faulting instruction which
ultimately retires. Trying to distinguish the two cases leads to
complex rules, so instead [#norm:Sdtrig_icount_all_traps_match]#the rule is simply that all traps match.#
See also xref:stepicount[].
====

[#norm:Sdtrig_icount_match_gt1]#When {icount-count} is greater than 1 and the trigger matches, then
{icount-count} is decremented by 1.#

[#norm:Sdtrig_icount_match_eq1]#When {icount-count} is 1 and the trigger matches, then {icount-pending}
becomes set. In addition {icount-count} will become 0 unless it is
hard-wired to 1.#

[#norm:Sdtrig_icount_exception]#The only exception to the above is when the instruction the trigger matched on is a
write to the icount trigger. In that case {icount-pending} might or might
not become set if {icount-count} was 1. Afterwards {icount-count}
contains the newly written value.#

[#norm:Sdtrig_icount_count_zero]#When {icount-count} is 0 it stays at 0 until explicitly written.#

[#norm:Sdtrig_icount_pending]#When {icount-pending} is set, the trigger fires just
before any further instructions are executed in a mode where the
trigger is enabled. As the trigger fires, {icount-pending} is
cleared. In addition, if {icount-count} is hard-wired to 1 then {icount-m},
{icount-s}, {icount-u}, {icount-vs}, and {icount-vu} are all
cleared.#

[#norm:Sdtrig_icount_action0]#If the trigger fires with {icount-action}=0 then zero is written to the
`tval` CSR on the breakpoint trap.#

[NOTE]
====
[#norm:Sdtrig_icount_case]#The intent of {icount-pending} is to cleanly handle the case where
{icount-action} is 0, {icount-m} is 0, {icount-u} is 1,
{icount-count} is 1, and the U-mode instruction being executed
causes a trap into M-mode. In that case we want the entire M-mode
handler to be executed, and the debug trap to be taken before the
next U-mode instruction.#
====

[NOTE]
====
This trigger type is intended to be used as a single step for software
monitor programs or native debug.  Systems that support multiple
privilege modes that want to debug software running in lower privilege
modes don't need to support {icount-count} greater than 1.
====

[#norm:Sdtrig_icount_textra]#If {csr-textra32} or {csr-textra64} are implemented for this
trigger, it only matches when the conditions set there are satisfied.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 32)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "XLEN-4" "" "" "XLEN-5" "" "" "XLEN-6" "27" "26" "25" "24" "23" "" "" "" "" "" "10" "9" "" "8" "" "7" "6" "5" "" "" "" "0"]})
(draw-box (text "type" {:font-size 20}) {:span 5})
(draw-box (text "dmode" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 3})
(draw-box (text "vs" {:font-size 20}) {:span 1})
(draw-box (text "vu" {:font-size 20}) {:span 1})
(draw-box (text "hit" {:font-size 20}) {:span 1})
(draw-box (text "count" {:font-size 20}) {:span 7})
(draw-box (text "m" {:font-size 20}) {:span 1})
(draw-box (text "pending" {:font-size 20}) {:span 3})
(draw-box (text "s" {:font-size 20}) {:span 1})
(draw-box (text "u" {:font-size 20}) {:span 1})
(draw-box (text "action" {:font-size 20}) {:span 5})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "XLEN - 32" {:span 3 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "14" {:span 7 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "6" {:span 5 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[icount-vs]] `((vs))`
a|[#norm:Sdtrig_icount_vs]#When set, enable this trigger in VS-mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[icount-vu]] `((vu))`
a|[#norm:Sdtrig_icount_vu]#When set, enable this trigger in VU-mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[icount-hit]] `((hit))`
a|[#norm:Sdtrig_icount_hit]#If this bit is implemented, the hardware sets it when this
trigger fires. The trigger's user can set or clear it at any
time. It is used to determine which
trigger(s) fires.  If the bit is not implemented, it is always 0
and writing it has no effect.#
a|*WARL*
a|0
|[[icount-count]] `((count))`
a|The trigger will generally fire after {icount-count} instructions
in enabled modes have been executed. See above for the precise behavior.
a|*WARL*
a|1
|[[icount-m]] `((m))`
a|[#norm:Sdtrig_icount_m]#When set, enable this trigger in M-mode.#
a|*WARL*
a|0
|[[icount-pending]] `((pending))`
a|[#norm:Sdtrig_icount_pending_set]#This bit becomes set when {icount-count} is decremented from 1
to 0. It is cleared when the trigger fires, which will happen just
before executing the next instruction in one of the enabled modes.#
a|*R/W*
a|0
|[[icount-s]] `((s))`
a|[#norm:Sdtrig_icount_s]#When set, enable this trigger in S/HS-mode.
This bit is hard-wired to 0 if the hart does not support
S-mode.#
a|*WARL*
a|0
|[[icount-u]] `((u))`
a|[#norm:Sdtrig_icount_u]#When set, enable this trigger in U-mode.
This bit is hard-wired to 0 if the hart does not support
U-mode.#
a|*WARL*
a|0
|[[icount-action]] `((action))`
a|The action to take when the trigger fires. The values are explained
in xref:tab:action[].
a|*WARL*
a|0
|===

[[csr-itrigger]]
==== Interrupt Trigger (((itrigger)), at 0x7a1)

[#norm:Sdtrig_itrigger]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_itrigger_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_itrigger_access]#This register is accessible as {csr-tdata1} when {tdata1-type} is 4.#

[#norm:Sdtrig_itrigger_fire]#This trigger can fire when an interrupt trap is taken.#

[#norm:Sdtrig_itrigger_enable_num]#It can be enabled for individual interrupt numbers by setting the bit
corresponding to the interrupt number in {csr-tdata2}. The interrupt
number is interpreted in the mode that the trap handler executes in.#
(E.g. virtualized interrupt numbers are not the same in every mode.)
[#norm:Sdtrig_itrigger_enable_nmi]#In addition the trigger can be enabled for non-maskable interrupts using
{itrigger-nmi}.#

[NOTE]
====
[#norm:Sdtrig_itrigger_xlen32]#If XLEN is 32, then it is not possible to set a trigger for interrupts
with Exception Code larger than 31.# A future version of the RISC-V
Privileged Spec will likely define interrupt Exception Codes 32 through
47. Some of those numbers are already being used by the RISC-V Advanced
Interrupt Architecture.
====

Hardware may only support a subset of interrupts for this trigger.  A
debugger must read back {csr-tdata2} after writing it to confirm the
requested functionality is actually supported.

[#norm:Sdtrig_itrigger_timing]#When the trigger matches, it fires after the trap occurs, just before
the first instruction of the trap handler is executed.#  [#norm:Sdtrig_itrigger_action0]#If
{itrigger-action}=0, the standard CSRs are updated for taking the
breakpoint trap, and zero is written to the relevant `tval` CSR.# If
the breakpoint trap does not go to a higher privilege mode, this will
lose CSR information for the original trap.  See
xref:nativetrigger[] for more information about this case.

[#norm:Sdtrig_itrigger_textra]#If {csr-textra32} or {csr-textra64} are implemented for this
trigger, it only matches when the conditions set there are satisfied.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 30)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "XLEN-4" "" "" "XLEN-5" "" "" "XLEN-6" "" "" "XLEN-7" "" "" "" "" "13" "12" "11" "10" "9" "8" "7" "6" "5" "" "" "" "0"]})
(draw-box (text "type" {:font-size 20}) {:span 5})
(draw-box (text "dmode" {:font-size 20}) {:span 3})
(draw-box (text "hit" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 7})
(draw-box (text "vs" {:font-size 20}) {:span 1})
(draw-box (text "vu" {:font-size 20}) {:span 1})
(draw-box (text "nmi" {:font-size 20}) {:span 1})
(draw-box (text "m" {:font-size 20}) {:span 1})
(draw-box (text "0" {:font-size 20}) {:span 1})
(draw-box (text "s" {:font-size 20}) {:span 1})
(draw-box (text "u" {:font-size 20}) {:span 1})
(draw-box (text "action" {:font-size 20}) {:span 5})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "XLEN - 19" {:span 7 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "6" {:span 5 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[itrigger-hit]] `((hit))`
a|[#norm:Sdtrig_itrigger_hit]#If this bit is implemented, the hardware sets it when this
trigger matches. The trigger's user can set or clear it at any
time. It is used to determine which
trigger(s) matched.  If the bit is not implemented, it is always 0
and writing it has no effect.#
a|*WARL*
a|0
|[[itrigger-vs]] `((vs))`
a|[#norm:Sdtrig_itrigger_vs]#When set, enable this trigger for interrupts that are taken from VS
mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[itrigger-vu]] `((vu))`
a|[#norm:Sdtrig_itrigger_vu]#When set, enable this trigger for interrupts that are taken from VU
mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[itrigger-nmi]] `((nmi))`
a|[#norm:Sdtrig_itrigger_nmi]#When set, non-maskable interrupts cause this
trigger to fire if the trigger is enabled for the current mode.#
a|*WARL*
a|0
|[[itrigger-m]] `((m))`
a|[#norm:Sdtrig_itrigger_m]#When set, enable this trigger for interrupts that are taken from M
mode.#
a|*WARL*
a|0
|[[itrigger-s]] `((s))`
a|[#norm:Sdtrig_itrigger_s]#When set, enable this trigger for interrupts that are taken from S/HS
mode.
This bit is hard-wired to 0 if the hart does not support
S-mode.#
a|*WARL*
a|0
|[[itrigger-u]] `((u))`
a|[#norm:Sdtrig_itrigger_u]#When set, enable this trigger for interrupts that are taken from U
mode.
This bit is hard-wired to 0 if the hart does not support
U-mode.#
a|*WARL*
a|0
|[[itrigger-action]] `((action))`
a|The action to take when the trigger fires. The values are explained
in xref:tab:action[].
a|*WARL*
a|0
|===

[[csr-etrigger]]
==== Exception Trigger (((etrigger)), at 0x7a1)

[#norm:Sdtrig_etrigger]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_etrigger_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_etrigger_access]#This register is accessible as {csr-tdata1} when {tdata1-type} is 5.#

[#norm:Sdtrig_etrigger_fire]#This trigger may fire on up to XLEN of the Exception Codes defined in
`mcause` (described in the Privileged Spec, with Interrupt=0).# [#norm:Sdtrig_etrigger_config]#Those
causes are configured by writing the corresponding bit in {csr-tdata2}.#
(E.g.  to trap on an illegal instruction, the debugger sets bit 2 in
{csr-tdata2}.)

[NOTE]
====
[#norm:Sdtrig_etrigger_xlen32]#If XLEN is 32, then it is not possible to set a trigger on Exception
Codes higher than 31.# A future version of the RISC-V Privileged Spec
will likely define Exception Codes 32 through 47.

====

Hardware may support only a subset of exceptions. A debugger must read
back {csr-tdata2} after writing it to confirm the requested functionality
is actually supported.

[#norm:Sdtrig_etrigger_timing]#When the trigger matches, it fires after the trap occurs, just before
the first instruction of the trap handler is executed.#  [#norm:Sdtrig_etrigger_action0]#If
{etrigger-action}=0, the standard CSRs are updated for taking the
breakpoint trap, and zero is written to the relevant `tval` CSR.# If
the breakpoint trap does not go to a higher privilege mode, this will
lose CSR information for the original trap.  See
xref:nativetrigger[] for more information about this case.

[#norm:Sdtrig_etrigger_textra]#If {csr-textra32} or {csr-textra64} are implemented for this
trigger, it only matches when the conditions set there are satisfied.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 30)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "XLEN-4" "" "" "XLEN-5" "" "" "XLEN-6" "" "" "XLEN-7" "" "" "" "" "13" "12" "11" "10" "9" "8" "7" "6" "5" "" "" "" "0"]})
(draw-box (text "type" {:font-size 20}) {:span 5})
(draw-box (text "dmode" {:font-size 20}) {:span 3})
(draw-box (text "hit" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 7})
(draw-box (text "vs" {:font-size 20}) {:span 1})
(draw-box (text "vu" {:font-size 20}) {:span 1})
(draw-box (text "0" {:font-size 20}) {:span 1})
(draw-box (text "m" {:font-size 20}) {:span 1})
(draw-box (text "0" {:font-size 20}) {:span 1})
(draw-box (text "s" {:font-size 20}) {:span 1})
(draw-box (text "u" {:font-size 20}) {:span 1})
(draw-box (text "action" {:font-size 20}) {:span 5})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "XLEN - 19" {:span 7 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "6" {:span 5 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[etrigger-hit]] `((hit))`
a|[#norm:Sdtrig_etrigger_hit]#If this bit is implemented, the hardware sets it when this
trigger matches. The trigger's user can set or clear it at any
time. It is used to determine which
trigger(s) matched.  If the bit is not implemented, it is always 0
and writing it has no effect.#
a|*WARL*
a|0
|[[etrigger-vs]] `((vs))`
a|[#norm:Sdtrig_etrigger_vs]#When set, enable this trigger for exceptions that are taken from VS
mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[etrigger-vu]] `((vu))`
a|[#norm:Sdtrig_etrigger_vu]#When set, enable this trigger for exceptions that are taken from VU
mode.
This bit is hard-wired to 0 if the hart does not support
virtualization mode.#
a|*WARL*
a|0
|[[etrigger-m]] `((m))`
a|[#norm:Sdtrig_etrigger_m]#When set, enable this trigger for exceptions that are taken from M
mode.#
a|*WARL*
a|0
|[[etrigger-s]] `((s))`
a|[#norm:Sdtrig_etrigger_s]#When set, enable this trigger for exceptions that are taken from S/HS
mode.
This bit is hard-wired to 0 if the hart does not support
S-mode.#
a|*WARL*
a|0
|[[etrigger-u]] `((u))`
a|[#norm:Sdtrig_etrigger_u]#When set, enable this trigger for exceptions that are taken from U
mode.
This bit is hard-wired to 0 if the hart does not support
U-mode.#
a|*WARL*
a|0
|[[etrigger-action]] `((action))`
a|The action to take when the trigger fires. The values are explained
in xref:tab:action[].
a|*WARL*
a|0
|===

[[csr-tmexttrigger]]
==== External Trigger (((tmexttrigger)), at 0x7a1)

[#norm:Sdtrig_tmexttrigger]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_tmexttrigger_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_tmexttrigger_access]#This register is accessible as {csr-tdata1} when {tdata1-type} is 7.#

[#norm:Sdtrig_tmexttrigger_fire]#This trigger fires when any selected TM external trigger input
signals.#  [#norm:Sdtrig_tmexttrigger_inputs]#Up to 16 TM external
trigger inputs coming from other blocks outside the TM,
(e.g. signaling an hpmcounter overflow) can be selected.#  [#norm:Sdtrig_tmexttrigger_subset]#Hardware
may support none or just a few TM external trigger inputs
(starting with TM external trigger input 0 and continuing
sequentially).#  [#norm:Sdtrig_tmexttrigger_unsupported]#Unsupported inputs are hardwired to be inactive.#

[#norm:Sdtrig_tmexttrigger_action0]#If the trigger fires with {tmexttrigger-action}=0 then zero is written to the
`tval` CSR on the breakpoint trap.#  [#norm:Sdtrig_tmexttrigger_async]#This trigger fires
asynchronously but it is subject to delegation by medeleg[3] like
the other triggers.#

[#norm:Sdtrig_tmexttrigger_prevented]#The TM external trigger input can signal when the trigger is prevented
from firing due to one of the mechanisms in xref:nativetrigger[].#
[#norm:Sdtrig_tmexttrigger_pending]#An implementation may either ignore the signal altogether when it cannot
fire (dropping the trigger event) or it may hold the action as pending
and fire the trigger once it is legal to do so.#

[NOTE]
====
{tmexttrigger-intctl} is intended to be used by the `clicinttrig`
mechanism from the Core-Local Interrupt Controller (CLIC) RISC-V
Privileged Architecture Extensions.
====

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 31)
(draw-column-headers {:font-size 15 :height 17 :labels ["" "XLEN-1" "" "XLEN-4" "" "" "XLEN-5" "" "" "XLEN-6" "" "" "XLEN-7" "" "" "23" "" "22" "" "21" "" "" "" "" "" "6" "5" "" "" "" "0"]})
(draw-box (text "type" {:font-size 20}) {:span 5})
(draw-box (text "dmode" {:font-size 20}) {:span 3})
(draw-box (text "hit" {:font-size 20}) {:span 3})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "intctl" {:font-size 20}) {:span 3})
(draw-box (text "select" {:font-size 20}) {:span 7})
(draw-box (text "action" {:font-size 20}) {:span 5})
(draw-box "4" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "XLEN - 29" {:span 5 :borders {}})
(draw-box "1" {:span 3 :borders {}})
(draw-box "16" {:span 7 :borders {}})
(draw-box "6" {:span 5 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[tmexttrigger-hit]] `((hit))`
a|[#norm:Sdtrig_tmexttrigger_hit]#If this bit is implemented, the hardware sets it when this
trigger matches. The trigger's user can set or clear it at any
time. It is used to determine which
trigger(s) matched.  If the bit is not implemented, it is always 0
and writing it has no effect.#
a|*WARL*
a|0
|[[tmexttrigger-intctl]] `((intctl))`
a|[#norm:Sdtrig_tmexttrigger_intctl]#This optional bit, when set, causes this trigger to fire whenever an attached
interrupt controller signals a trigger.#
a|*WARL*
a|0
|[[tmexttrigger-select]] `((select))`
a|[#norm:Sdtrig_tmexttrigger_select]#Selects any combination of up to 16 TM external trigger inputs
that cause this trigger to fire.#
a|*WARL*
a|0
|[[tmexttrigger-action]] `((action))`
a|The action to take when the trigger fires. The values are explained
in xref:tab:action[].
a|*WARL*
a|0
|===

[[csr-textra32]]
==== Trigger Extra (RV32) (((textra32)), at 0x7a3)

[#norm:Sdtrig_textra32]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_textra32_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_textra32_access]#This register is accessible as {csr-tdata3} when {tdata1-type} is 2, 3, 4,
5, or 6 and XLEN=32.#

[#norm:Sdtrig_textra32_dxlen64]#If DXLEN >= 64, then this register provides access to the low bits of
each field defined in {csr-textra64}. Writes to this register will clear
the high bits of the corresponding fields in {csr-textra64}.#

All functionality in this register is optional.  Any number of upper
bits of {textra32-mhvalue} and {textra32-svalue} may be tied to 0.
{textra32-mhselect} and {textra32-sselect} may only support 0 (ignore).

[#norm:Sdtrig_textra32_byte_granular]#Byte-granular comparison of {csr-scontext} to {textra32-svalue}
allows {csr-scontext} to be defined to include more than one element of comparison.#
For example, software instrumentation can program the {csr-scontext} value to be
the concatenation of different ID contexts such as process ID and thread ID.
The user can then program byte compares based on {textra32-sbytemask}
to include one or more of the contexts in the compare.

[#norm:Sdtrig_textra32_byte_mask_applies]#Byte masking only applies to {csr-scontext} comparison; i.e when {textra32-sselect} is 1.#

[NOTE]
====
[#norm:Sdtrig_textra32_filter_modes]#Note that sselect and mhselect filtering apply in all modes, including M-mode
and S-mode.#  If desired, debuggers can use a trigger's mode filtering bits to
restrict the matching to modes where it considers ASID/VMID/scontext/hcontext
to be active.
====

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 28)
(draw-column-headers {:font-size 15 :height 17 :labels ["31" "" "" "" "26" "25" "" "" "" "23" "22" "" "" "" "20" "19" "" "18" "17" "" "" "" "" "" "2" "1" "" "0"]})
(draw-box (text "mhvalue" {:font-size 20}) {:span 5})
(draw-box (text "mhselect" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "sbytemask" {:font-size 20}) {:span 3})
(draw-box (text "svalue" {:font-size 20}) {:span 7})
(draw-box (text "sselect" {:font-size 20}) {:span 3})
(draw-box "6" {:span 5 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "2" {:span 3 :borders {}})
(draw-box "16" {:span 7 :borders {}})
(draw-box "2" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[textra32-mhvalue]] `((mhvalue))`
a|Data used together with {textra32-mhselect}.
a|*WARL*
a|0
|[[textra32-mhselect]] `((mhselect))`
a|

0 (ignore): [#norm:Sdtrig_textra32_mhselect_ignore]#Ignore {textra32-mhvalue}.#


4 (mcontext): [#norm:Sdtrig_textra32_mhselect_mcontext]#This trigger will only match or fire if the low bits of
{csr-mcontext}/{csr-hcontext} equal {textra32-mhvalue}.#

[#norm:Sdtrig_textra32_mhselect_mctx_sel]#1, 5 (mcontext_select): This trigger will only match or fire if the
low bits of
{csr-mcontext}/{csr-hcontext} equal {{textra32-mhvalue}, mhselect[2]}.#

[#norm:Sdtrig_textra32_mhselect_vmid_sel]#2, 6 (vmid_select): This trigger will only match or fire if VMID in
hgatp equals the lower VMIDMAX
(defined in the Privileged Spec) bits of {{textra32-mhvalue}, mhselect[2]}.#

[#norm:Sdtrig_textra32_mhselect_rsv]#3, 7 (reserved): Reserved.#

[#norm:Sdtrig_textra32_mhselect_no_h]#If the H extension is not supported, the only legal values are 0 and 4.#
a|*WARL*
a|0
|[[textra32-sbytemask]] `((sbytemask))`
a|[#norm:Sdtrig_textra32_sbytemask]#When the least significant bit of this field is 1, it causes bits 7:0
in the comparison to be ignored, when {textra32-sselect}=1.
When the next most significant bit of this field is 1, it causes bits 15:8
to be ignored in the comparison, when {textra32-sselect}=1.#
a|*WARL*
a|0
|[[textra32-svalue]] `((svalue))`
a|Data used together with {textra32-sselect}.

[#norm:Sdtrig_textra32_svalue_no_s]#This field should be tied to 0 when S-mode is not supported.#
a|*WARL*
a|0
|[[textra32-sselect]] `((sselect))`
a|

0 (ignore): [#norm:Sdtrig_textra32_sselect_ignore]#Ignore {textra32-svalue}.#


1 (scontext): [#norm:Sdtrig_textra32_sselect_scontext]#This trigger will only match or fire if the low bits of
{csr-scontext} equal {textra32-svalue}.#


2 (asid): [#norm:Sdtrig_textra32_sselect_asid1]#This trigger will only match or fire if:#

* [#norm:Sdtrig_textra32_sselect_asid2]#the mode is VS-mode or VU-mode and ASID in `vsatp`
equals the lower ASIDMAX (defined in the Privileged Spec) bits
of {textra32-svalue}.#

* [#norm:Sdtrig_textra32_sselect_asid3]#in all other modes, ASID in `satp` equals the lower
ASIDMAX (defined in the Privileged Spec) bits of
{textra32-svalue}.#

[#norm:Sdtrig_textra32_sselect_no_s]#This field should be tied to 0 when S-mode is not supported.#
a|*WARL*
a|0
|===

[[csr-textra64]]
==== Trigger Extra (RV64) (((textra64)), at 0x7a3)

[#norm:Sdtrig_textra64]#This register provides access to the trigger selected by {csr-tselect}.#
[#norm:Sdtrig_textra64_reset]#The reset values listed here apply to every underlying trigger.#

[#norm:Sdtrig_textra64_access]#This register is accessible as {csr-tdata3} when {tdata1-type} is 2, 3, 4,
5, or 6 and XLEN=64.# The function of the fields are defined
above, in {csr-textra32}. [#norm:Sdtrig_textra64_retain]#This register retains its value when XLEN
changes.# [#norm:Sdtrig_textra64_xlen32]#When XLEN=32 some of the bits can be accessed through {csr-textra32}.#

[#norm:Sdtrig_textra64_byte_granular]#Byte-granular comparison of {csr-scontext} to {textra64-svalue} in
{csr-textra64} allows {csr-scontext} to be defined to include
more than one element of comparison.#  For example, software instrumentation
can program the {csr-scontext} value to be the concatenation of different ID contexts
such as process ID and thread ID.  The user can then program byte compares based on
{textra64-sbytemask} to include one or more of the contexts in the compare.

[#norm:Sdtrig_textra64_byte_mask_applies]#Byte masking only applies to {csr-scontext} comparison; i.e when {textra64-sselect} is 1.#

This CSR is read/write.

[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 37)
(draw-column-headers {:font-size 15 :height 17 :labels ["63" "" "" "" "" "" "51" "50" "" "" "" "48" "47" "" "" "" "40" "39" "" "" "" "36" "35" "" "34" "33" "" "" "" "" "" "" "" "2" "1" "" "0"]})
(draw-box (text "mhvalue" {:font-size 20}) {:span 7})
(draw-box (text "mhselect" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 5})
(draw-box (text "sbytemask" {:font-size 20}) {:span 5})
(draw-box (text "0" {:font-size 20}) {:span 3})
(draw-box (text "svalue" {:font-size 20}) {:span 9})
(draw-box (text "sselect" {:font-size 20}) {:span 3})
(draw-box "13" {:span 7 :borders {}})
(draw-box "3" {:span 5 :borders {}})
(draw-box "8" {:span 5 :borders {}})
(draw-box "4" {:span 5 :borders {}})
(draw-box "2" {:span 3 :borders {}})
(draw-box "32" {:span 9 :borders {}})
(draw-box "2" {:span 3 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[textra64-sbytemask]] `((sbytemask))`
a|[#norm:Sdtrig_textra64_sbytemask]#When the least significant bit of this field is 1, it causes bits 7:0
in the comparison to be ignored, when {textra64-sselect}=1.
Likewise, the second bit controls the comparison of bits 15:8,
third bit controls the comparison of bits 23:16,
and fourth bit controls the comparison of bits 31:24.#
a|*WARL*
a|0
|===
