// Frozen from the RISC-V Debug Specification v1.0 (Ratified, 2025-02-21),
// generated from xml/sw_registers.xml in riscv/riscv-debug-spec. Do not regenerate;
// edit this file directly if an erratum requires a change.
A virtual register is one that doesn't exist directly in the hardware, but
that the debugger exposes as if it does. Debug software should implement
them, but hardware can skip this section. Virtual registers exist to give
users access to functionality that's not part of standard debuggers without
requiring them to carefully modify debug registers while the debugger is
also accessing those same registers.
[[tab:virtual]]
.Virtual Core Debug Registers
[cols="1,6,2",options="header"]
|===
|Address |Name |Section
|virtual |Privilege Mode ({virt-priv})| xref:virt-priv[]
|===
[[virt-priv]]
==== Privilege Mode (((priv)), at virtual)

Users can read this register to inspect the privilege mode that
the hart was running in when the hart halted.
Users can write this register to change the privilege mode that
the hart will run in when it resumes.

This register contains {dcsr-prv} and {dcsr-v} from {csr-dcsr}, but in a place that the user
is expected to access. The user should not access {csr-dcsr} directly,
because doing so might interfere with the debugger.

[[tab:privmode]]
.Privilege Mode and Virtualization Mode Encoding
[%autowidth,align="center",float="center",cols="^,^,^,<,<",options="header"]
|===
| H extension supported |v |prv |Abbreviation |Name
| No | 0 | 0 | U-mode | User mode
| No | 0 | 1 | S-mode | Supervisor mode
| No | 0 | 3 | M-mode | Machine mode
| Yes | 0 | 0 | U-mode | User mode
| Yes | 0 | 1 | HS-mode | Hypervisor-enabled supervisor mode
| Yes | 0 | 3 | M-mode | Machine mode
| Yes | 1 | 0 | VU-mode | Virtual user mode
| Yes | 1 | 1 | VS-mode | Virtual supervisor mode
|===


[bytefield]
----
(def row-height 45)
(def row-header-fn nil)
(def boxes-per-row 24)
(draw-column-headers {:font-size 15 :height 17 :labels ["2" "1" "" "0" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""]})
(draw-box (text "v" {:font-size 20}) {:span 1})
(draw-box (text "prv" {:font-size 20}) {:span 3})
(draw-box "" {:span 20 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "2" {:span 3 :borders {}})
(draw-box "" {:span 20 :borders {}})
----
[float="center",align="center",cols="<23,<61,^10,^10",options="header"]
|===
|Field |Description |Access |Reset
|[[priv-v]] `((v))`
a|Contains the virtualization mode the hart was operating in when Debug
Mode was entered. The encoding is described in <<tab:privmode>>,
and matches the virtualization mode encoding from the Privileged Spec.
A user can write this value to change the hart's virtualization mode
when exiting Debug Mode.
a|*WARL*
a|0
|[[priv-prv]] `((prv))`
a|Contains the privilege mode the hart was operating in when Debug
Mode was entered. The encoding is described in <<tab:privmode>>, and matches the privilege mode encoding from
the Privileged Spec. A user can write this
value to change the hart's privilege mode when exiting Debug Mode.
a|*R/W*
a|0
|===

