[bytefield]
----
(defattrs :plain [:plain {:font-size 14 :font-family "M+ 1p Fallback" :vertical-align "middle"}])
(def row-height 45 )
(def row-header-fn nil)
(def left-margin 0)
(def right-margin 0)
(def boxes-per-row 32)
(draw-column-headers {:height 20 :font-size 18 :labels (reverse ["0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "20" "21" "22" "23" "" "" "" "" "" "" "30" "31"])})

(draw-box "SD" {:span 1})
(draw-box (text "WPRI" {:font-weight "bold"}) {:span 8})
(draw-box "TSR" {:span 1})
(draw-box "TW" {:span 1})
(draw-box "TVM" {:span 1})
(draw-box "MXR" {:span 1})
(draw-box "SUM" {:span 1})
(draw-box "MPRV" {:span 1})
(draw-box "XS[1:0]" {:span 2})
(draw-box "FS[1:0]" {:span 2})
(draw-box "MPP[1:0]" {:span 2})
(draw-box "VS[1:0]" {:span 2})
(draw-box "SPP" {:span 1})
(draw-box "MPIE" {:span 1})
(draw-box "UBE" {:span 1})
(draw-box "SPIE" {:span 1})
(draw-box (text "WPRI" {:font-weight "bold"}) {:span 1})
(draw-box "MIE" {:span 1})
(draw-box (text "WPRI" {:font-weight "bold"}) {:span 1})
(draw-box "SIE" {:span 1})
(draw-box (text "WPRI" {:font-weight "bold"}) {:span 1})

(draw-box "1" {:span 1 :borders {}})
(draw-box "8" {:span 8 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "2" {:span 2 :borders {}})
(draw-box "2" {:span 2 :borders {}})
(draw-box "2" {:span 2 :borders {}})
(draw-box "2" {:span 2 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
(draw-box "1" {:span 1 :borders {}})
----