[[bits]]
== "B" Standard Extension for Bit Manipulation, Version 0.0

[[preface]]
=== Bit-manipulation a, b, c and s extensions grouped for public review and ratification

The bit-manipulation (bitmanip) extension collection is comprised of several component extensions to the base RISC-V architecture that are intended to provide some combination of code size reduction, performance improvement, and energy reduction.
While the instructions are intended to have general use, some instructions are more useful in some domains than others.
Hence, several smaller bitmanip extensions are provided, rather than one large extension.
Each of these smaller extensions is grouped by common function and use case, and each has its own Zb*-extension name.

Each bitmanip extension includes a group of several bitmanip instructions that have similar purposes and that can often share the same logic. Some instructions are available in only one extension while others are available in several.
The instructions have mnemonics and encodings that are independent of the extensions in which they appear.
Thus, when implementing extensions with overlapping instructions, there is no redundancy in logic or encoding.

The bitmanip extensions are defined for RV32 and RV64.
Most of the instructions are expected to be forward compatible with RV128.
While the shift-immediate instructions are defined to have at most a 6-bit immediate field, a 7th bit is available in the encoding space should this be needed for RV128.

=== Word Instructions

The bitmanip extension follows the convention in RV64 that _w_-suffixed instructions (without a dot before the _w_) ignore the upper 32 bits of their inputs, operate on the least-significant 32-bits as signed values and produce a 32-bit signed result that is sign-extended to XLEN.

Bitmanip instructions with the suffix _.uw_ have one operand that is an unsigned 32-bit value that is extracted from the least significant 32 bits of the specified register.  Other than that, these perform full XLEN operations.

Bitmanip instructions with the suffix _.b_, _.h_ and _.w_ only look at the least significant 8-bits, 16-bits and 32-bits of the input (respectively) and produce an XLEN-wide result that is sign-extended or zero-extended, based on the specific instruction.

=== Pseudocode for instruction semantics

The semantics of each instruction in <<#insns>> is expressed in a SAIL-like syntax.

=== Extensions

The first group of bitmanip extensions to be released for Public Review are:

* <<#zba>>
* <<#zbb>>
* <<#zbc>>
* <<#zbs>>

Below is a list of all of the instructions (and pseudoinstructions) that are included in these extensions
along with their specific mapping:

[%header,cols="^3,^3,10,16,^2,^2,^2,^2"]
|====
|RV32
|RV64
|Mnemonic
|Instruction
|Zba
|Zbb
|Zbc
|Zbs

|
|&#10003;
|add.uw _rd_, _rs1_, _rs2_
|<<#insns-add_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|andn _rd_, _rs1_, _rs2_
|<<#insns-andn>>
|
|&#10003;
|
|


|&#10003;
|&#10003;
|clmul _rd_, _rs1_, _rs2_
|<<#insns-clmul>>
|
|
|&#10003;
|

|&#10003;
|&#10003;
|clmulh _rd_, _rs1_, _rs2_
|<<#insns-clmulh>>
|
|
|&#10003;
|

|&#10003;
|&#10003;
|clmulr _rd_, _rs1_, _rs2_
|<<#insns-clmulr>>
|
|
|&#10003;
|

|&#10003;
|&#10003;
|clz _rd_, _rs_
|<<#insns-clz>>
|
|&#10003;
|
|

|
|&#10003;
|clzw _rd_, _rs_
|<<#insns-clzw>>
|
|&#10003;
|
|
|&#10003;
|&#10003;
|cpop _rd_, _rs_
|<<#insns-cpop>>
|
|&#10003;
|
|

|
|&#10003;
|cpopw _rd_, _rs_
|<<#insns-cpopw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|ctz _rd_, _rs_
|<<#insns-ctz>>
|
|&#10003;
|
|

|
|&#10003;
|ctzw _rd_, _rs_
|<<#insns-ctzw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|max _rd_, _rs1_, _rs2_
|<<#insns-max>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|maxu _rd_, _rs1_, _rs2_
|<<#insns-maxu>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|min _rd_, _rs1_, _rs2_
|<<#insns-min>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|minu _rd_, _rs1_, _rs2_
|<<#insns-minu>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|orc.b _rd_, _rs1_, _rs2_
|<<#insns-orc_b>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|orn _rd_, _rs1_, _rs2_
|<<#insns-orn>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|rev8 _rd_, _rs_
|<<#insns-rev8>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|rol _rd_, _rs1_, _rs2_
|<<#insns-rol>>
|
|&#10003;
|
|

|
|&#10003;
|rolw _rd_, _rs1_, _rs2_
|<<#insns-rolw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|ror _rd_, _rs1_, _rs2_
|<<#insns-ror>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|rori _rd_, _rs1_, _shamt_
|<<#insns-rori>>
|
|&#10003;
|
|

|
|&#10003;
|roriw _rd_, _rs1_, _shamt_
|<<#insns-roriw>>
|
|&#10003;
|
|

|
|&#10003;
|rorw _rd_, _rs1_, _rs2_
|<<#insns-rorw>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|bclr _rd_, _rs1_, _rs2_
|<<#insns-bclr>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bclri _rd_, _rs1_, _imm_
|<<#insns-bclri>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bext _rd_, _rs1_, _rs2_
|<<#insns-bext>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bexti _rd_, _rs1_, _imm_
|<<#insns-bexti>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|binv _rd_, _rs1_, _rs2_
|<<#insns-binv>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|binvi _rd_, _rs1_, _imm_
|<<#insns-binvi>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bset _rd_, _rs1_, _rs2_
|<<#insns-bset>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|bseti _rd_, _rs1_, _imm_
|<<#insns-bseti>>
|
|
|
|&#10003;

|&#10003;
|&#10003;
|sext.b _rd_, _rs_
|<<#insns-sext_b>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|sext.h _rd_, _rs_
|<<#insns-sext_h>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|sh1add _rd_, _rs1_, _rs2_
|<<#insns-sh1add>>
|&#10003;
|
|
|

|
|&#10003;
|sh1add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh1add_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|sh2add _rd_, _rs1_, _rs2_
|<<#insns-sh2add>>
|&#10003;
|
|
|

|
|&#10003;
|sh2add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh2add_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|sh3add _rd_, _rs1_, _rs2_
|<<#insns-sh3add>>
|&#10003;
|
|
|

|
|&#10003;
|sh3add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh3add_uw>>
|&#10003;
|
|
|

|
|&#10003;
|slli.uw _rd_, _rs1_, _imm_
|<<#insns-slli_uw>>
|&#10003;
|
|
|

|&#10003;
|&#10003;
|xnor _rd_, _rs1_, _rs2_
|<<#insns-xnor>>
|
|&#10003;
|
|

|&#10003;
|&#10003;
|zext.h _rd_, _rs_
|<<#insns-zext_h>>
|
|&#10003;
|
|

|
|&#10003;
|zext.w _rd_, _rs_
|<<#insns-add_uw>>
|&#10003;
|
|
|

|====

[#zba,reftext=Address generation instructions]
==== Zba extension

[NOTE,caption=Frozen]
====
The Zba extension is frozen.
====

The Zba instructions can be used to accelerate the generation of addresses that index into arrays of basic types (halfword, word, doubleword) using both unsigned word-sized and XLEN-sized indices: a shifted index is added to a base address.

The shift and add instructions do a left shift of 1, 2, or 3 because these are commonly found in real-world code and because they can be implemented with a minimal amount of additional hardware beyond that of the simple adder. This avoids lengthening the critical path in implementations.

While the shift and add instructions are limited to a maximum left shift of 3, the slli instruction (from the base ISA) can be used to perform similar shifts for indexing into arrays of wider elements. The slli.uw -- added in this extension -- can be used when the index is to be interpreted as an unsigned word.

The following instructions (and pseudoinstructions) comprise the Zba extension:

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|
|&#10003;
|add.uw _rd_, _rs1_, _rs2_
|<<#insns-add_uw>>

|&#10003;
|&#10003;
|sh1add _rd_, _rs1_, _rs2_
|<<#insns-sh1add>>

|
|&#10003;
|sh1add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh1add_uw>>

|&#10003;
|&#10003;
|sh2add _rd_, _rs1_, _rs2_
|<<#insns-sh2add>>

|
|&#10003;
|sh2add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh2add_uw>>

|&#10003;
|&#10003;
|sh3add _rd_, _rs1_, _rs2_
|<<#insns-sh3add>>

|
|&#10003;
|sh3add.uw _rd_, _rs1_, _rs2_
|<<#insns-sh3add_uw>>

|
|&#10003;
|slli.uw _rd_, _rs1_, _imm_
|<<#insns-slli_uw>>

|
|&#10003;
|zext.w _rd_, _rs_
|<<#insns-add_uw>>

|===

[#zbb,reftext="Basic bit-manipulation"]
==== Zbb: Basic bit-manipulation

[NOTE,caption=Frozen]
====
The Zbb extension is frozen.
====
===== Logical with negate

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|andn _rd_, _rs1_, _rs2_
|<<#insns-andn>>

|&#10003;
|&#10003;
|orn _rd_, _rs1_, _rs2_
|<<#insns-orn>>

|&#10003;
|&#10003;
|xnor _rd_, _rs1_, _rs2_
|<<#insns-xnor>>
|===

.Implementation Hint
[NOTE, caption="Imp" ]
===============================================================
The Logical with Negate instructions can be implemented by inverting the _rs2_ inputs to the base-required AND, OR, and XOR logic instructions.
In some implementations, the inverter on rs2 used for subtraction can be reused for this purpose.
===============================================================

===== Count leading/trailing zero bits

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|clz _rd_, _rs_
|<<#insns-clz>>

|
|&#10003;
|clzw _rd_, _rs_
|<<#insns-clzw>>

|&#10003;
|&#10003;
|ctz _rd_, _rs_
|<<#insns-ctz>>

|
|&#10003;
|ctzw _rd_, _rs_
|<<#insns-ctzw>>
|===

===== Count population

These instructions count the number of set bits (1-bits). This is also
commonly referred to as population count.

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|cpop _rd_, _rs_
|<<#insns-cpop>>

|
|&#10003;
|cpopw _rd_, _rs_
|<<#insns-cpopw>>
|===

===== Integer minimum/maximum

The integer minimum/maximum instructions are arithmetic R-type
instructions that return the smaller/larger of two operands.

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|max _rd_, _rs1_, _rs2_
|<<#insns-max>>

|&#10003;
|&#10003;
|maxu _rd_, _rs1_, _rs2_
|<<#insns-maxu>>

|&#10003;
|&#10003;
|min _rd_, _rs1_, _rs2_
|<<#insns-min>>

|&#10003;
|&#10003;
|minu _rd_, _rs1_, _rs2_
|<<#insns-minu>>
|===

===== Sign- and zero-extension

These instructions perform the sign-extension or zero-extension of the least significant 8 bits, 16 bits or 32 bits of the source register.

These instructions replace the generalized idioms `slli rD,rS,(XLEN-<size>) + srli` (for zero-extension) or `slli + srai` (for sign-extension) for the sign-extension of 8-bit and 16-bit quantities, and for the zero-extension of 16-bit and 32-bit quantities.

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|sext.b _rd_, _rs_
|<<#insns-sext_b>>

|&#10003;
|&#10003;
|sext.h _rd_, _rs_
|<<#insns-sext_h>>

|&#10003;
|&#10003;
|zext.h _rd_, _rs_
|<<#insns-zext_h>>
|===

===== Bitwise rotation

Bitwise rotation instructions are similar to the shift-logical operations from the base spec. However, where the shift-logical 
instructions shift in zeros, the rotate instructions shift in the bits that were shifted out of the other side of the value.
Such operations are also referred to as ‘circular shifts’.



[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|rol _rd_, _rs1_, _rs2_
|<<#insns-rol>>

|
|&#10003;
|rolw _rd_, _rs1_, _rs2_
|<<#insns-rolw>>

|&#10003;
|&#10003;
|ror _rd_, _rs1_, _rs2_
|<<#insns-ror>>

|&#10003;
|&#10003;
|rori _rd_, _rs1_, _shamt_
|<<#insns-rori>>

|
|&#10003;
|roriw _rd_, _rs1_, _shamt_
|<<#insns-roriw>>

|
|&#10003;
|rorw _rd_, _rs1_, _rs2_
|<<#insns-rorw>>
|===

.Architecture Explanation
[NOTE, caption="AE" ]
===============================================================
The rotate instructions were included to replace a common
four-instruction sequence to achieve the same effect (neg; sll/srl; srl/sll; or)
===============================================================

===== OR Combine

*orc.b* sets the bits of each byte in the result _rd_ to all zeros if no bit within the respective byte of _rs_ is set, or to all ones if any bit within the respective byte of _rs_ is set.

One use-case is string-processing functions, such as *strlen* and *strcpy*, which can use *orc.b* to test for the terminating zero byte by counting the set bits in leading non-zero bytes in a word.

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|&#10003;
|&#10003;
|orc.b _rd_, _rs_
|<<#insns-orc_b>>
|===
