[appendix]
== Historical Rationale for Extensions
[[chap:rationale]]

This appendix contains the rationale for RISC-V ISA extensions at the time they
were ratified.
Unlike the ISA specification, this appendix is ordered chronologically, so as
to convey the motivation and architectural reasoning underpinning each
extension at the time of ratification.
For extensions ratified prior to the conception of this appendix (ca. 2025),
the rationale will be added over time.
In cases where the rationale was not recorded, the authors and editors will
synthesize it from the historical record.

=== "Zicond" Extension for Integer Conditional Operations

Replacing unpredictable branches with conditional-select or conditional-move
instructions can mitigate a class of costly branch mispredictions.
Unfortunately, conditional-select instructions require three source operands.
These instructions are a logical addition to ISAs that include three-source
integer instructions for other reasons, but are too costly otherwise.

Some ISAs have instead furnished conditional-move instructions, which consume
less encoding space and avoid the extra register read in simple
microarchitectures.
Unfortunately, in register-renamed microarchitectures, these instructions incur
costs simlar to conditional select, or require additional microarchitectural
structures and micro-op-issue constraints.

The Zicond extension was defined to solve the same problem as conditional
select and conditional move, but with very little incremental cost for complex
microarchitectures.
It provides conditional-zero instructions, which read two source operands and,
based upon the zeroness of the second operand, produce either the first operand
or zero.
These instructions can be used as part of a three-instruction sequence to
synthesize conditional select.
Several common conditional-execution idioms require only two instructions,
including conditional addition, can be synthesized with two instructions, as
would be the case with conditional select or move.
