[[sh]]
== "Sh" Hypervisor Extensions

NOTE: This chapter is currently being restructured.
Its contents are normative, but the presentation might appear disjoint.

[[shvstvecd]]
=== Shvstvecd Extension for Direct Trap Vectoring, Version 1.0

If the Shvstvecd extension is implemented, then `vstvec.MODE` must be capable
of holding the value 0 (Direct).
Furthermore, when `vstvec.MODE`=Direct, `vstvec.BASE` must be capable of
holding any valid four-byte-aligned address.

[[shcounterenw]]
=== Shcounterenw Extension for Counter-Enable Writability, Version 1.0

If the Shcounterenw extension is implemented, then for any `hpmcounter` that
is not read-only zero, the corresponding bit in `hcounteren` must be writable.

[[shvstvala]]
=== Shvstvala Extension for Trap Value Reporting, Version 1.0
If the Shvstvala extension is implemented, `vstval` must be written in all
cases described in <<sstvala>> for `stval`.

[[shtvala]]
=== Shtvala Extension for Trap Value Reporting, Version 1.0
If the Shtvala extension is implemented, `htval` must be written with the
faulting guest physical address in all circumstances permitted by the ISA.

[[shvsatpa]]
=== Shvsatpa Extension for Translation Mode Support, Version 1.0
If the Shvsatpa extension is implemented, all translation modes supported in
`satp` must be supported in `vsatp`.

[[shgatpa]]
=== Shgatpa Extension for Translation Mode Support, Version 1.0
If the Shgatpa extension is implemented, then for each supported virtual
memory scheme Sv__NN__ supported in `satp`, the corresponding hgatp Sv__NN__x4
mode must be supported.
Furthermore, the `hgatp` mode Bare must also be supported.

[[sha]]
=== Sha Augmented Hypervisor Extension

The Augmented Hypervisor Extension, Sha, adds several minor features to the
hypervisor extension.  It depends on the following extensions:

- <<hypervisor,H>>
- <<smstateen,Ssstateen>>
- <<shcounterenw,Shcounterenw>>
- <<shvstvala,Shvstvala>>
- <<shtvala,Shtvala>>
- <<shvstvecd,Shvstvecd>>
- <<shvsatpa,Shvsatpa>>
- <<shgatpa,Shgatpa>>

//
