[[ss]]
== "Ss" Supervisor Extensions

NOTE: This chapter is currently being restructured.
Its contents are normative, but the presentation might appear disjoint.

[[ssu64xl]]
=== Ssu64xl Extension for UXLEN=64 Support, Version 1.0

If the Ssu64xl extension is implemented, then `sstatus.UXL` must be capable of
holding the value 2 (i.e., UXLEN=64 must be supported).

[[ssccptr]]
=== Ssccptr Extension for Main Memory Page-Table Reads, Version 1.0

If the Ssccptr extension is implemented, then main memory regions with both
the cacheability and coherence PMAs must support hardware page-table reads.

[[sstvecd]]
=== Sstvecd Extension for Direct Trap Vectoring, Version 1.0

If the Sstvecd extension is implemented, then `stvec.MODE` must be capable of
holding the value 0 (Direct).
Furthermore, when `stvec.MODE=Direct`, `stvec.BASE` must be capable of holding
any valid four-byte-aligned address.

[[sstvala]]
=== Sstvala Extension for Trap Value Reporting, Version 1.0

If the Sstvala extension is implemented, then `stval` must be written with the
faulting virtual address for load, store, and instruction page-fault,
access-fault, and misaligned exceptions, and for breakpoint exceptions that
are defined to write an address to stval, other than those caused by execution
of the `EBREAK` or `C.EBREAK` instructions.
For virtual-instruction and illegal-instruction exceptions, `stval` must be
written with the faulting instruction.

[[sscounterenw]]
=== Sscounterenw Extension for Counter-Enable Writability, Version 1.0

If the Sscounterenw extension is implemented, then for any `hpmcounter` that
is not read-only zero, the corresponding bit in `scounteren` must be writable.
