[[ssdbltrp]]
== "Ssdbltrp" Double Trap Extension, Version 1.0

The Ssdbltrp extension addresses a double trap (See xref:machine.adoc#machine-double-trap[Double Trap Control in `mstatus` Register])
privilege modes lower than M. [#norm:HS-mode_invoke_error]#It enables HS-mode to invoke a critical error
handler in a virtual machine on a double trap in VS-mode.# [#norm:M-mode_invoke_error]#It also allows M-mode
to invoke a critical error handler in the OS/Hypervisor on a double trap in
S/HS-mode.#

[#norm:menvcfg_DTE]#The Ssdbltrp extension adds the `menvcfg`.DTE (See xref:machine.adoc#sec:menvcfg[Machine Environment Configuration (`menvcfg`) Register])# [#norm:sstatus_SDT]#and the
`sstatus`.SDT fields (See xref:supervisor.adoc#sstatus[Supervisor Status (`sstatus`) Register]).# [#norm:henvcfg_DTE]#If the hypervisor extension is
additionally implemented, then the extension adds the `henvcfg`.DTE (See
xref:hypervisor.adoc#sec:henvcfg[Hypervisor Environment Configuration Register (`henvcfg`)])# [#norm:vsstatus_SDT]#and the `vsstatus`.SDT fields (See xref:hypervisor.adoc#vsstatus[Virtual Supervisor Status (`vsstatus`) Register]).#

See xref:supervisor.adoc#supv-double-trap[Double Trap Control in `sstatus` Register] for the operational details.
