== "Zabhlrsc" Extension for Byte and Halfword Load Reserved/Store Conditional, Version 0.9

The Zalrsc extension offers LR/SC (load reserved/store conditional) instructions
for _words_ and_doublewords. The absence of LR/SC operations for subword data types
is problematic for CHERI software (futureRV64CH, RV32CH base architectures).
Non-CHERI RISC-V software can use LR/SC on larger data types than are strictly
required for the memory access to register the reservation set.
RV64CH/RV32CH check memory bounds and so it not possible to round a subword
access up to a word or larger to gain the reservation set.

The Zabhlrsc extension addresses this by adding support for _byte_ and
_halfword_ LR/SC memory operations to the RISC-V Unprivileged ISA. The Zabhlrsc
extension depends upon the Zalrsc standard extension.

=== Byte and Halfword Atomic Load Reserved/Store Conditional Instructions

The Zabhlrsc extension provides the `LR.[B|H]` and `SC.[B|H]` instructions.

[wavedrom, zabhlrsc-lr-ext-wavedrom-reg,svg]
....
{reg: [
  {bits: 7,  name: 'opcode',   attr: ['7', 'AMO=0101111'], type: 8},
  {bits: 5,  name: 'rd',       attr: ['5', 'rdest[4:0]'], type: 3},
  {bits: 3,  name: 'funct3',   attr: ['3', '.B=000', '.H=001', '.W=010', 'rv64: .D=011'], type: 8},
  {bits: 5,  name: 'rs1',      attr: ['5', 'base'], type: 4},
  {bits: 5,  name: 'rs2',      attr: ['5', 'LR.*=00000'],  type: 4},
  {bits: 1,  name: 'rl',       attr: ['1', 'rl'],  type: 4},
  {bits: 1,  name: 'aq',       attr: ['1', 'aq'],  type: 4},
  {bits: 5,  name: 'funct5',   attr: ['5', 'op', 'LR.*=00010'], type: 3},
]}
....

[wavedrom, zabhlrsc-sc-ext-wavedrom-reg,svg]
....
{reg: [
  {bits: 7,  name: 'opcode',   attr: ['7', 'AMO=0101111'], type: 8},
  {bits: 5,  name: 'rd',       attr: ['5', 'rdest[4:0]'], type: 3},
  {bits: 3,  name: 'funct3',   attr: ['3', 'width', '.B=000','.H=001','.W=010', 'rv64: .D=011'], type: 8},
  {bits: 5,  name: 'rs1',      attr: ['5', 'base'], type: 4},
  {bits: 5,  name: 'rs2',      attr: ['5', 'src'],  type: 4},
  {bits: 1,  name: 'rl',       attr: ['1', 'rl'],  type: 4},
  {bits: 1,  name: 'aq',       attr: ['1', 'aq'],  type: 4},
  {bits: 5,  name: 'funct5',   attr: ['5', 'op', 'SC=00011'], type: 3},
]}
....

LR.[B|H] behave analogously to LR.[W|D].
SC.[B|H] behave analogously to SC.[W|D].

All Zabhlrsc instructions sign extend the result and write it to _rd_.
