:le: &#8804;

== Ziccif Extension for Instruction-Fetch Atomicity, Version 1.0

NOTE: This extension was ratified alongside the RVA20U64 profile.
This chapter supplies an operational definition for the extension
and adds expository material.

If the Ziccif extension is implemented, main memory regions with both the
cacheability and coherence PMAs must support instruction fetch, and any
instruction fetches of naturally aligned power-of-2 sizes up to
`min(ILEN,XLEN)` are atomic.

An implementation with the Ziccif extension fetches instructions in a manner
equivalent to the following state machine.

. Let `M` be `min(ILEN,XLEN)/8`, rounded up to the next power of 2.
Let `N` be the `pc` modulo `M`.
Atomically fetch `M` - `N` bytes from memory at address `pc`.
Let `T` be the running total of bytes fetched, initially `M` - `N`.

. If the `T` bytes fetched begin with a complete instruction of length `L` {le}
`T`, then execute that instruction, discard the remaining `T` - `L` bytes
fetched, and go back to step 1, using the updated `pc`.

. Otherwise, atomically fetch M bytes from memory at address `pc` + `T`,
increment `T` by `M`, and go back to step 2.

[NOTE]
====
The instruction-fetch atomicity rule supports concurrent code modification.
If a hart modifies instruction memory that it, or other, harts might
execute without first having executed a FENCE.I instruction, it should
adhere to the following rules:

- Modification stores must be single-copy atomic, hence must be naturally
aligned.

- The modified instruction must not span an `M`-byte boundary,
unless it is replaced with a shorter unconditional control transfer
(e.g. `c.ebreak` or `c.j`) that does not itself span an `M`-byte
boundary.

- Modification stores must alter a complete instruction or complete
instructions that do not collectively span an `M`-byte boundary,
modulo the exception above that the first part of an instruction may be
replaced with an unconditional control transfer instruction.

- Modifications may not combine smaller instructions into a larger
instruction but may convert a larger instruction to some number of
smaller instructions.

- Modified instruction memory must have the coherence PMA.

Other well-defined code-modification strategies exist, but these rules provide
a safe harbor.
====
