== `Zvdota` and `Zvbdota` Families of Dot-Product Extensions, Version 1.0

This document describes several extensions that accelerate the computation
of Euclidean inner products, a.k.a. dot products.
The extensions fall into two classes: dot products between two vectors,
producing a scalar result; and _batched_ dot products, wherein one vector is
broadcast to eight vectors to perform eight dot products, producing a vector of
eight results.
Both classes support a variety of data formats, including widening
accumulations.

NOTE: Some instructions in this proposal use the `vtype`.`altfmt` field,
originally proposed as part of the Zvfbfa extension, to select the format
of one or more of the operands.
This approach helps conserve the limited 32-bit encoding space available
to vector instructions.
Because `altfmt` is written as a consequence of executing the `vsetvli`
instruction needed for stripmine loop control, there is often no performance
overhead to this approach.

=== `Zvdota` Family of Dot-Product Extensions, Version 1.0

Each extension in the `Zvdota` family adds one or more instructions that
compute a dot product between two vector register groups, identified by
`vs2` and `vs1`, producing a scalar result that is accumulated into element
0 of vector register `vd`.

The other elements in `vd` (0 < index < VLEN/SEW) are considered the tail and
are managed with the current tail agnostic/undisturbed policy.

The `vs2` and `vs1` register groups have EMUL=LMUL and EEW=SEW.
The `vd` register always has EMUL=1; its EEW depends on the instruction.

These instructions are maskable.

These instructions always report exceptions with a `vstart` of 0;
executing one with a nonzero `vstart` is reserved.

The destination vector register cannot overlap with the source vector register
groups, otherwise the instruction encoding is reserved.

NOTE: Non-accumulating variants are not provided; `vd[0]` can be initialized
to zero to effect this operation.

==== `Zvqwdota8i` 8-bit Integer Dot-Product Extension, Version 1.0

The Zvqwdota8i extension adds two instructions, each of which computes a dot
product between two 8-bit integer vectors, accumulating into a 32-bit scalar.
The `vqwdotau.vv` instruction treats the `vs2` operand as unsigned 8-bit
integers, whereas the `vqwdotas.vv` instruction treats the `vs2` operand
as signed 8-bit integers.
The `vtype`.`altfmt` field selects the signedness of the `vs1` operand,
with 0 indicating unsigned and 1 indicating signed.
These instructions are reserved unless SEW=8.
The `vd` operand has EEW=4*SEW.

----
# Zvqwdota8i 8-bit integer dot-product instructions
# signedness of vs1 supplied by altfmt (0 unsigned, 1 signed)
vqwdotau.vv vd, vs2, vs1, vm   # vd[0] += unsigned(vs2) dot vs1
vqwdotas.vv vd, vs2, vs1, vm   # vd[0] += signed(vs2) dot vs1
----

These dot products are computed modulo 2^32^.

The instructions are encoded in major opcode 0x77 with funct3=0,
and with funct6=0x26 for `vqwdotau.vv` and funct6=0x27 for
`vqwdotas.vv`.

The Zvqwdota8i extension depends on the Zve32x extension.

==== `Zvqwdota16i` 16-bit Integer Dot-Product Extension, Version 1.0

The Zvqwdota16i extension adds two instructions, each of which computes a dot
product between two 16-bit integer vectors, accumulating into a 64-bit scalar.
The `vqwdotau.vv` instruction treats the `vs2` operand as unsigned 16-bit
integers, whereas the `vqwdotas.vv` instruction treats the `vs2` operand
as signed 16-bit integers.
The `vtype`.`altfmt` field selects the signedness of the `vs1` operand,
with 0 indicating unsigned and 1 indicating signed.
These instructions use the same encodings as those defined in the Zvqwdota8i
extension.
These instructions are reserved unless SEW=16.
The `vd` operand has EEW=4*SEW.

These dot products are computed modulo 2^64^.

The Zvqwdota16i extension depends on the Zve64x extension.

==== `Zvfwdota16bf` BF16 Dot-Product Extension, Version 1.0

The Zvfwdota16bf extension adds one instruction, `vfwdota.vv`, which computes
a dot product between two BF16 vectors, accumulating into an FP32 scalar.
The instruction is reserved unless `vtype`.`altfmt`=1 and SEW=16.
The `vd` operand has EEW=2*SEW.

----
# Zvfwdota16bf BF16 dot-product instruction
# altfmt=1
vfwdota.vv vd, vs2, vs1, vm   # vd[0] += vs2 dot vs1
----

These dot products are computed using the bulk-normalization scheme defined in
Section <<#DPBulkNorm>>.

The `vfwdota.vv` instruction is encoded in major opcode 0x77 with funct3=1 and funct6=0x24.

NOTE: A future extension could define an instruction that uses the same code
points with `vtype`.`altfmt`=0 to compute IEEE 754 FP16 dot products.

[NOTE]
====
Ordered variants of the floating-point dot-product instructions are not
provided because they can be emulated efficiently using existing instruction
sequences.

An unordered FP32 dot-product instruction is not provided for the same
reason.
====

The Zvfwdota16bf extension depends on the Zve32f extension.

==== `Zvfqwdota8f` OFP8 Dot-Product Extension, Version 1.0

The Zvfqwdota8f extension adds two instructions, each of which computes a dot
product between two OFP8 vectors, accumulating into an FP32 scalar.
The `vfqwdota.vv` instruction treats the `vs2` operand as E4M3 numbers,
whereas the `vfqwdota.alt.vv` instruction treats the `vs2` operand
as E5M2 numbers.
The `vtype`.`altfmt` field selects the datatype of the `vs1` operand,
with 0 indicating E4M3 and 1 indicating E5M2.
These instructions are reserved unless SEW=8.
The `vd` operand has EEW=4*SEW.

----
# Zvfqwdota8f OFP8 dot-product instructions
# format of vs1 supplied by altfmt (0 E4M3, 1 E5M2)
vfqwdota.vv     vd, vs2, vs1, vm   # vd[0] += E4M3(vs2) dot vs1
vfqwdota.alt.vv vd, vs2, vs1, vm   # vd[0] += E5M2(vs2) dot vs1
----

These dot products are computed using the bulk-normalization scheme defined in
Section <<#DPBulkNorm>>.

The instructions are encoded in major opcode 0x77 with funct3=1,
and with funct6=0x26 for `vfqwdota.vv` and funct6=0x27 for
`vfqwdota.alt.vv`.

The Zvfqwdota8f extension depends on the Zve32f extension.

=== `Zvbdota` Family of Batched Dot-Product Extensions, Version 1.0

Batched dot-product instructions compute up to eight dot products at a time.
Each instruction in these extensions treats `vs1` as an EMUL=1 vector register
group and `vs2` as an EMUL=8 vector register group, computing eight independent
dot products between `vs1` and each of the eight vector registers within `vs2`.
The vector of eight results is accumulated into `vd`, an EMUL=`ceil(8*EEW/VLEN)`
vector register group.

The vector-length register `vl` sets the length of each of the eight dot
products.
Tail elements are substituted with the bit pattern of all zeros, then the
computation is performed as though `vl`=VLMAX.

image::bdota-simple.svg[Static, pdfwidth=4in, title="Zvbdota operation, VLEN &#8804; 8*EEW"]

For long-vector implementations with VLEN > 8*EEW, each instruction also has
a 3-bit scaled-by-8 immediate `ci` indicating which eight elements of `vd`
destination vector are read and written.
The `ci` field is encoded in `vs2[2:0]`; these bits are not needed for the
register address since `vs2` addresses an EMUL=8 register group for these
instructions.
The instruction is reserved if `ci` {ge} `VLEN/(8*EEW)`.

NOTE: The ability to use all of `vd` improves the efficiency of register-tiled
matrix multiplication.

image::bdota-ci.svg[Static, pdfwidth=7in, title="Zvbdota operation, VLEN > 8*EEW"]

Destination elements with index {ge} `ci + 8` are tail elements and are
managed with the current tail agnostic/undisturbed policy.
Destination elements with index < `ci` are prestart elements and are left
undisturbed.
The remaining destination elements are the body elements.

Each instruction is optionally masked by the `v0` mask register.
If masked and the mask bit corresponding to the destination element in `vd` is clear,
the corresponding dot product is not performed, and the destination element is updated
in accordance with the current mask agnostic/undisturbed policy.

The following pseudocode describes the instructions' operation:

```
for n in [0, 7]
  if (unmasked or mask[ci + n])
    for k in [0, vl-1]
      v[vd][ci + n] += v[vs2 + n][k] * v[vs1][k]
```

The destination vector register group cannot overlap with the source vector
register groups, otherwise the instruction encoding is reserved.

These instructions always report exceptions with a `vstart` of 0;
executing one with a nonzero `vstart` is reserved.

[NOTE]
====
Batched dot-product instructions can be thought of as performing 1x``vl``x8
matrix multiplication.
For `C += A*B`, `vs1` holds one row of A, `vs2` holds eight columns of B, and
`vd` holds one row of C.

These instructions have been architected to minimize the amount of code needed
to handle the various matrix-multiplication fringe cases.
The ability to dynamically control `vl` avoids the need to specially handle
the K-dimension fringe cases when K is not a multiple of VLMAX.
Similarly, the `v0` mask handles the N-dimension fringe cases when N is not
a multiple of 8.
The M dimension has no fringe cases, since these instructions only process one
row of the A matrix at a time.
====

==== `Zvqwbdota8i` 8-bit Integer Batched Dot-Product Extension

The Zvqwbdota8i extension adds instructions that perform batched dot-product
operations on 8-bit integer vectors, accumulating into 32-bit integers.
The `vqwbdotau.vv` instruction treats the `vs2` operand as unsigned 8-bit
integers, whereas the `vqwbdotas.vv` instruction treats the `vs2` operand
as signed 8-bit integers.
The `vtype`.`altfmt` field selects the signedness of the `vs1` operand,
with 0 indicating unsigned and 1 indicating signed.
These instructions are reserved unless SEW=8 and LMUL=1.
The `vs1` and `vs2` operands have EEW=SEW, and the `vd` operand has
EEW=4*SEW.

----
# Zvqwbdota8i 8-bit integer batched dot-product instructions
# signedness of vs1 supplied by altfmt (0 unsigned, 1 signed)
vqwbdotau.vv vd, vs2, vs1, ci, vm   # vs2 unsigned
vqwbdotas.vv vd, vs2, vs1, ci, vm   # vs2 signed
----

Each dot product is computed modulo 2^32^.

The instructions are encoded in major opcode 0x77 with funct3=0,
and with funct6=0x2e for `vqwbdotau.vv` and funct6=0x2f for
`vqwbdotas.vv`.

The Zvqwbdota8i extension depends on the Zve32x extension.

==== `Zvqwbdota16i` 16-bit Integer Batched Dot-Product Extension

The Zvqwbdota16i extension adds instructions that perform batched dot-product
operations on 16-bit integer vectors, accumulating into 64-bit integers.
The `vqwbdotau.vv` instruction treats the `vs2` operand as unsigned 16-bit
integers, whereas the `vqwbdotas.vv` instruction treats the `vs2` operand
as signed 16-bit integers.
The `vtype`.`altfmt` field selects the signedness of the `vs1` operand,
with 0 indicating unsigned and 1 indicating signed.
These instructions use the same encodings as those defined in the Zvqwbdota8i
extension.
These instructions are reserved unless SEW=16 and LMUL=1.
The `vs1` and `vs2` operands have EEW=SEW, and the `vd` operand has
EEW=4*SEW.

Each dot product is computed modulo 2^64^.

The Zvqwbdota16i extension depends on the Zve64x extension.

==== `Zvfwbdota16bf` BF16 Batched Dot-Product Extension

The Zvfwbdota16bf extension adds one instruction, `vfwbdota.vv`, which performs
a batched dot-product operation on BF16 vectors, accumulating into FP32.
The instruction is reserved unless SEW=16, LMUL=1, and `vtype`.`altfmt`=1.
The `vs1` and `vs2` operands have EEW=SEW, and the `vd` operand has
EEW=2*SEW.

----
# Zvfwbdota16bf BF16 batched dot-product instruction
# altfmt=1
vfwbdota.vv vd, vs2, vs1, ci, vm
----

Each dot product is computed using the bulk-normalization scheme defined in
Section <<#DPBulkNorm>>.

The `vfwbdota.vv` instruction is encoded in major opcode 0x77 with funct3=1 and funct6=0x2c.

The Zvfwbdota16bf extension depends on the Zve32f extension.

==== `Zvfqwbdota8f` OFP8 Batched Dot-Product Extension

The Zvfqwbdota8f extension adds instructions that perform batched dot-product
operations on 8-bit OFP8 vectors, accumulating into FP32.
The `vfqwbdota.vv` instruction treats the `vs2` operand as E4M3 numbers,
whereas the `vfqwbdota.alt.vv` instruction treats the `vs2` operand
as E5M2 numbers.
The `vtype`.`altfmt` field selects the datatype of the `vs1` operand,
with 0 indicating E4M3 and 1 indicating E5M2.
These instructions are reserved unless SEW=8 and LMUL=1.
The `vs1` and `vs2` operands have EEW=SEW, and the `vd` operand has
EEW=4*SEW.

----
# Zvfqwbdota8f OFP8 batched dot-product instructions
# format of vs1 supplied by altfmt (0 E4M3, 1 E5M2)
vfqwbdota.vv     vd, vs2, vs1, ci, vm   # vs2 E4M3
vfqwbdota.alt.vv vd, vs2, vs1, ci, vm   # vs2 E5M2
----

Each dot product is computed using the bulk-normalization scheme defined in
Section <<#DPBulkNorm>>.

The instructions are encoded in major opcode 0x77 with funct3=1,
and with funct6=0x2e for `vfqwbdota.vv` and funct6=0x2f for
`vfqwbdota.alt.vv`.

The Zvfqwbdota8f extension depends on the Zve32f extension.

==== `Zvfbdota32f` FP32 Batched Dot-Product Extension

The Zvfbdota32f extension adds one instruction, `vfbdota.vv`, which performs
a batched dot-product operation on FP32 vectors, accumulating into FP32.
The instruction is reserved unless SEW=32 and LMUL=1.
The `vs1`, `vs2`, and `vd` operands all have EEW=SEW.

----
# Zvfbdota32f FP32 batched dot-product instruction
vfbdota.vv vd, vs2, vs1, ci, vm
----

The FP32 products are first computed to full precision, setting the invalid operation
exception flag as appropriate.
The products are then optionally rounded to FP32 according to the dynamic rounding mode,
setting the inexact, overflow, and underflow exception flags as appropriate.
The sum of these products and the accumulator are then computed as though by the
`vfredusum.vs` instruction with SEW=32, including the setting of exception flags.

NOTE: This formulation allows significant implementation flexibility while being sufficiently
precise to implement SGEMM.

NOTE: The algorithm used by the `vfredusum.vs` offers several implementation
choices.
Implementations are not required to use the same algorithm configuration for
the `vfbdota.vv` instruction as for the `vfredusum.vs` instruction.

The `vfbdota.vv` instruction is encoded in major opcode 0x77 with funct3=1 and funct6=0x2b.

The Zvfbdota32f extension depends on the Zve32f extension.

==== Sample matrix-multiplication code

Following is an optimized inner loop for 8-bit signed integer matrix
multiplication, accumulating into 32-bit integers, for row-major A and C and
column-major B.
To demonstrate use of the `ci` immediate, we assume VLEN {ge} 512, hence `vd`
can hold at least 16 elements of C.
Each loop iteration processes one 15xVLx16 tile, performing 31 unit-stride loads
of length VL, for 7.7 MACCs per loaded element.
For clarity, the loop is not scheduled.

```
loop:
  vsetvli t3, a0, e8alt, m1, ta, ma

  # Load 16 columns of B into v0-v15
  add a6, a3, t1
  vle8.v v0, (a6)
  add a6, a6, a4
  vle8.v v1, (a6)
  add a6, a6, a4
  vle8.v v2, (a6)
  add a6, a6, a4
  vle8.v v3, (a6)
  add a6, a6, a4
  vle8.v v4, (a6)
  add a6, a6, a4
  vle8.v v5, (a6)
  add a6, a6, a4
  vle8.v v6, (a6)
  add a6, a6, a4
  vle8.v v7, (a6)
  add a6, a6, a4
  vle8.v v8, (a6)
  add a6, a6, a4
  vle8.v v9, (a6)
  add a6, a6, a4
  vle8.v v10, (a6)
  add a6, a6, a4
  vle8.v v11, (a6)
  add a6, a6, a4
  vle8.v v12, (a6)
  add a6, a6, a4
  vle8.v v13, (a6)
  add a6, a6, a4
  vle8.v v14, (a6)
  add a6, a6, a4
  vle8.v v15, (a6)

  # Load 1 row of A into v31; macc into v16
  add a6, a1, t1
  vle8.v v31, (a6)
  vqwbdotas.vv v16, v0, v31, 0
  vqwbdotas.vv v16, v8, v31, 8

  # Load 1 row of A into v31; macc into v17
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v17, v0, v31, 0
  vqwbdotas.vv v17, v8, v31, 8

  # etc., total of 15 times
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v18, v0, v31, 0
  vqwbdotas.vv v18, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v19, v0, v31, 0
  vqwbdotas.vv v19, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v20, v0, v31, 0
  vqwbdotas.vv v20, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v21, v0, v31, 0
  vqwbdotas.vv v21, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v22, v0, v31, 0
  vqwbdotas.vv v22, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v23, v0, v31, 0
  vqwbdotas.vv v23, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v24, v0, v31, 0
  vqwbdotas.vv v24, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v25, v0, v31, 0
  vqwbdotas.vv v25, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v26, v0, v31, 0
  vqwbdotas.vv v26, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v27, v0, v31, 0
  vqwbdotas.vv v27, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v28, v0, v31, 0
  vqwbdotas.vv v28, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v29, v0, v31, 0
  vqwbdotas.vv v29, v8, v31, 8
  add a6, a6, a2
  vle8.v v31, (a6)
  vqwbdotas.vv v30, v0, v31, 0
  vqwbdotas.vv v30, v8, v31, 8

  # repeat until K dimension exhausted
  sub a0, a0, t3
  add t1, t1, t3
  bnez a0, loop
```

[#DPBulkNorm]
=== Bulk Normalization of Dot Products

Some of the dot-product instructions allow the intermediate products to be
bulk-normalized to improve efficiency.
This section describes the algorithm and permissible options.

* Substitute any inactive and tail source elements with the bit pattern
of all zeros, and perform the following steps as though `vl`=VLMAX.

* Perform either of the following actions:

** Compute the exact product of each of the VLMAX multiplicand pairs.
** Partition the VLMAX multiplicand pairs into an implementation-defined
number of equal-sized sets; the elements within each set are not necessarily
consecutive.
Process each of these sets using the
https://github.com/riscv/riscv-isa-manual/blob/a38e121306757164cdd664d7ffad158885d8b525/src/unpriv/rvbna.adoc[RVBNA Algorithm],
using an output precision no less than that specified by the instruction.

* Optionally, convert the resulting floating-point numbers to a precision
no less than that specified by the instruction, rounding to odd as described in
https://github.com/riscv/riscv-isa-manual/blob/a38e121306757164cdd664d7ffad158885d8b525/src/unpriv/rvbna.adoc#rounding-to-odd-behavior-in-dot-product-mode[RVBNA Rounding to Odd].

* Sum the resulting floating-point numbers and the accumulator input
in a manner consistent with the algorithm used by the `vfredusum.vs`
instruction, rounding to odd as described in
https://github.com/riscv/riscv-isa-manual/blob/a38e121306757164cdd664d7ffad158885d8b525/src/unpriv/rvbna.adoc#rounding-to-odd-behavior-in-dot-product-mode[RVBNA Rounding to Odd],
in a precision no
less than the output precision specified by the instruction.

* Convert the scalar result to the instruction's output precision,
rounding to odd as described in
https://github.com/riscv/riscv-isa-manual/blob/a38e121306757164cdd664d7ffad158885d8b525/src/unpriv/rvbna.adoc#rounding-to-odd-behavior-in-dot-product-mode[RVBNA Rounding to Odd].

NOTE: The algorithm used by the `vfredusum.vs` offers several implementation
choices.
Implementations are not required to use the same algorithm configuration for
batched dot products as for the `vfredusum.vs` instruction.
